/**
 * Public Russian projection for legacy technology-corpus labels.
 *
 * Machine identifiers remain immutable. Only user-visible labels are localized.
 * The maps are intentionally exact and fail closed: they document every imported
 * English component accepted by the R5 concrete/HVAC generators.
 */

export const CONCRETE_COMPONENT_TITLE_RU_R542: Readonly<Record<string, string>> = Object.freeze({
  "A500C": "арматура класса А500С",
  "A500SP при официальной применимости": "арматура класса А500СП при подтверждённой нормативной применимости",
  "GPR": "георадарное обследование",
  "MEP block-outs": "проёмы для инженерных систем",
  "PVC/rubber waterstops.": "гидроизоляционные шпонки из ПВХ или резины",
  "U-bars": "П-образные арматурные стержни",
  "access stairs": "лестницы доступа",
  "admixtures": "добавки к бетонной смеси",
  "aggregate control": "контроль заполнителей",
  "air content": "содержание воздуха в бетонной смеси",
  "aluminum formwork": "алюминиевая опалубка",
  "anchor bolts": "анкерные болты",
  "anchor groups": "анкерные группы",
  "anchor installation": "установка анкеров",
  "anchoring": "анкерное крепление",
  "anchors": "анкеры",
  "anti-frost admixture": "противоморозная добавка",
  "architectural concrete": "архитектурный бетон",
  "architectural finish": "архитектурная отделка поверхности",
  "back-propping": "повторное подпирание конструкций",
  "bar bending schedules": "ведомости гибки арматуры",
  "bars": "арматурные стержни",
  "base/rebar preheating": "предварительный прогрев основания и арматуры",
  "basement slabs": "плиты подземной части здания",
  "batching plant": "бетоносмесительная установка",
  "blinding": "бетонная подготовка",
  "block-outs": "технологические проёмы",
  "bonded tendons": "канатная арматура со сцеплением",
  "bonding agents": "адгезионные составы",
  "boom pump": "бетононасос со стрелой",
  "braces": "раскосы",
  "breakers": "гидромолоты и отбойные механизмы",
  "broom finish": "шероховатая отделка щёткой",
  "cast-in channels": "закладные монтажные каналы",
  "cementitious additions": "минеральные добавки к цементному вяжущему",
  "cementitious injection": "инъектирование цементным составом",
  "chamfers": "фаски",
  "chilled water/ice as mix-design input": "охлаждённая вода или лёд по проекту состава смеси",
  "chute": "бетонолитный жёлоб",
  "circular forms": "круглая опалубка",
  "cleaning": "очистка",
  "climbing forms": "подъёмно-переставная опалубка",
  "colored concrete": "цветной бетон",
  "column forms": "опалубка колонн",
  "combined NDT": "комбинированный неразрушающий контроль",
  "compressible inserts": "сжимаемые вкладыши",
  "compressive strength": "прочность при сжатии",
  "concrete crushing": "дробление бетона",
  "concrete jacketing": "усиление бетонной обоймой",
  "concrete pump": "бетононасос",
  "conduits/sleeves": "каналы и гильзы",
  "cones/tubes": "конусы и трубки стяжных шпилек",
  "construction joints": "рабочие швы бетонирования",
  "continuity strips": "арматурные выпуски в кассетах",
  "continuous pour": "непрерывное бетонирование",
  "contraction joints": "усадочные швы",
  "controlled cooling": "управляемое охлаждение бетона",
  "controlled dismantling": "контролируемый демонтаж",
  "conveyor": "ленточный транспортёр бетонной смеси",
  "conveyor_foundations": "фундаменты конвейерного оборудования",
  "core sampling": "отбор кернов",
  "corrosion treatment": "антикоррозионная обработка",
  "coupler testing": "испытание механических соединений арматуры",
  "cover-meter": "измерение защитного слоя арматуры",
  "crack classification": "классификация трещин",
  "crack injection epoxy": "инъектирование трещин эпоксидным составом",
  "crack injection polyurethane": "инъектирование трещин полиуретановым составом",
  "crack monitoring": "мониторинг раскрытия трещин",
  "crane and bucket": "подача бетонной смеси краном в бадье",
  "crane removal": "демонтаж краном",
  "crushing": "механическое дробление",
  "cube/cylinder specimens": "образцы-кубы и образцы-цилиндры",
  "curing compound": "плёнкообразующий состав для ухода за бетоном",
  "curing specimens": "образцы для контроля условий твердения",
  "data logging": "регистрация данных контроля",
  "deep beams": "балки-стенки",
  "defect mapping": "картирование дефектов",
  "deflection monitoring": "мониторинг прогибов",
  "demolition acts.": "акты выполненного демонтажа",
  "demolition design input": "проектные исходные данные для демонтажа",
  "density": "плотность",
  "diamond drilling": "алмазное сверление",
  "disposal": "вывоз и утилизация",
  "distribution reinforcement": "распределительная арматура",
  "double-tee": "двутавровые сборные плиты",
  "dowel baskets": "каркасы для штыревых соединений",
  "dowelling": "устройство штыревых соединений",
  "dowels": "штыри",
  "duct grouting": "инъектирование каналов преднапряжения",
  "ducts": "каналы преднапряжения",
  "dust extraction": "аспирация пыли",
  "dust suppression": "пылеподавление",
  "edge preparation": "подготовка кромок",
  "edge profiles": "кромочные профили",
  "edge protection": "защита кромок",
  "elongation control": "контроль удлинения арматуры",
  "embedded plates": "закладные пластины",
  "equipment_foundation": "фундамент под оборудование",
  "evaporation control": "контроль испарения влаги",
  "exclusion zone": "опасная зона производства работ",
  "expansion joints": "деформационные швы",
  "exposed architectural concrete": "видимый архитектурный бетон",
  "exposed rebar cleaning": "очистка оголённой арматуры",
  "external vibration": "наружное вибрирование",
  "fair-faced concrete": "лицевой бетон без отделки",
  "falsework": "временные поддерживающие конструкции",
  "fiber-reinforced concrete": "фибробетон",
  "fibers": "фиброволокно",
  "filigree slabs": "полусборные филигранные плиты",
  "fine-grained concrete": "мелкозернистый бетон",
  "flexural strength": "прочность при изгибе",
  "floor sawing": "алмазная резка перекрытий",
  "flowable grout": "текучий безусадочный раствор",
  "fogging": "увлажнение распылённой водой",
  "force measurement": "измерение усилия натяжения",
  "form liners": "матрицы для опалубки",
  "form ties": "стяжки опалубки",
  "form-retained curing": "выдерживание бетона в опалубке",
  "foundation_slab": "фундаментная плита",
  "frames": "несущие рамы",
  "fresh concrete temperature": "температура свежеуложенного бетона",
  "frost resistance": "морозостойкость",
  "frost-resistant concrete": "морозостойкий бетон",
  "generator_foundation": "фундамент генераторной установки",
  "geometry survey": "геодезический контроль геометрии",
  "geotextile covering": "укрытие геотекстилем",
  "grout bedding": "подливка опорной части раствором",
  "grout tests": "испытания раствора для подливки",
  "grouted sleeves": "муфтовые соединения с заполнением раствором",
  "grouting protocols": "протоколы инъектирования",
  "grouting tests": "испытания инъекционного раствора",
  "haulage": "внутриплощадочная перевозка",
  "hazardous coating route": "маршрут обращения с опасным покрытием",
  "heat-resistant concrete": "жаростойкий бетон",
  "heated enclosure": "обогреваемое укрытие",
  "high-performance concrete": "высокофункциональный бетон",
  "high-strength concrete": "высокопрочный бетон",
  "hollow-core slabs": "многопустотные плиты",
  "hot-weather concreting": "бетонирование в жаркую погоду",
  "hydraulic bursting": "гидравлическое разрушение бетона",
  "hydrodemolition": "гидродемонтаж",
  "hydrophilic waterstops": "гидрофильные шпонки",
  "incoming cement control": "входной контроль цемента",
  "injection hose systems": "системы инъекционных шлангов",
  "injection hoses": "инъекционные шланги",
  "inserts": "закладные вставки",
  "insulation mats": "теплоизоляционные маты",
  "internal vibration": "глубинное вибрирование",
  "isolation joints": "изоляционные швы",
  "jack calibration": "калибровка домкратов",
  "joint fillers": "заполнители швов",
  "joint grouting": "заполнение швов раствором",
  "joint sealants": "герметики для швов",
  "keyed joints": "шпоночные швы",
  "laboratory mix design": "лабораторный подбор состава бетона",
  "lean concrete": "тощий бетон",
  "lift-by-lift placement": "послойная укладка бетона",
  "lifting anchors": "монтажные анкеры",
  "lifting points": "точки строповки",
  "lightweight concrete": "лёгкий бетон",
  "line pump": "стационарный бетононасос",
  "links/ties": "хомуты и поперечные связи",
  "loading": "погрузка",
  "loading/unloading": "погрузка и разгрузка",
  "locks/wedges": "замки и клинья опалубки",
  "lost formwork": "несъёмная опалубка",
  "lot release": "приёмка и разрешение партии",
  "low-heat concrete": "бетон с низким тепловыделением",
  "manual placement": "ручная укладка бетонной смеси",
  "mass-concrete thermal monitoring": "температурный мониторинг массивного бетона",
  "maturity monitoring": "контроль зрелости бетона",
  "mechanical couplers": "механические муфты арматуры",
  "mechanical removal": "механизированное удаление бетона",
  "membrane curing": "мембранный уход за бетоном",
  "micro-concrete": "мелкозернистый ремонтный бетон",
  "mix cooling": "охлаждение бетонной смеси",
  "mock-up acceptance": "приёмка опытного образца",
  "mock-up pour.": "бетонирование опытного участка",
  "modular wall forms": "модульная стеновая опалубка",
  "monolithic_frame": "монолитный каркас",
  "movement joints": "деформационные швы перемещения",
  "mud slab": "подготовительный бетонный слой",
  "no-fines concrete": "крупнопористый бетон",
  "noise/vibration monitoring": "мониторинг шума и вибрации",
  "nonconformance/repair records.": "реестр несоответствий и ремонтов",
  "one-sided forms": "односторонняя опалубка",
  "ore_processing_foundations": "фундаменты обогатительного оборудования",
  "overhead repair": "ремонт нижней поверхности конструкций",
  "parapets": "парапеты",
  "patch repair": "локальный ремонт ремонтным составом",
  "patterned concrete surfaces.": "фактурные бетонные поверхности",
  "pile caps": "ростверки",
  "pipeline cleaning": "очистка бетоновода",
  "pipeline setup": "сборка бетоновода",
  "placing boom": "распределительная стрела для бетона",
  "plant QC": "производственный контроль бетонного завода",
  "plywood formwork": "фанерная опалубка",
  "polyethylene covering": "укрытие полиэтиленовой плёнкой",
  "polymer-modified concrete": "полимермодифицированный бетон",
  "post-tensioning": "натяжение арматуры на бетон",
  "pour sequencing": "последовательность бетонирования",
  "power floating": "механизированное заглаживание",
  "pre-tensioning": "натяжение арматуры до бетонирования",
  "precast passports": "паспорта сборных изделий",
  "precast_concrete_frame": "сборный железобетонный каркас",
  "pressed couplers": "опрессованные муфты арматуры",
  "prestress force/elongation": "усилие и удлинение при натяжении",
  "primary/secondary beams": "главные и второстепенные балки",
  "props": "телескопические стойки",
  "protection of anchor zones": "защита анкерных зон",
  "protection removal criteria.": "критерии снятия защитного укрытия",
  "protective coatings": "защитные покрытия",
  "puddle flanges": "герметизирующие фланцы проходок",
  "pull-off testing": "испытание прочности сцепления методом отрыва",
  "pull-out/pull-off": "испытания методом вырыва и отрыва",
  "pump priming": "пусковая смазка бетоновода",
  "raft foundations": "плитные фундаменты",
  "raft_foundation": "плитный фундамент",
  "re-shoring": "повторная установка временных стоек",
  "ready-mix": "товарная бетонная смесь",
  "rebar certificates": "сертификаты на арматурную сталь",
  "rebar scanning": "сканирование расположения арматуры",
  "rebar separation": "раздельный сбор арматурного лома",
  "rebound hammer": "контроль прочности склерометром",
  "recycled aggregate concrete if identity exists": "бетон на вторичном заполнителе при наличии отдельной идентичности",
  "recycling": "переработка бетонного лома",
  "refractory concrete": "огнеупорный бетон",
  "refrigeration_equipment_foundation": "фундамент холодильного оборудования",
  "release agents": "смазка для опалубки",
  "rental/use-cycle pricing": "стоимость аренды и циклов использования",
  "repair": "ремонт бетонной конструкции",
  "repair acceptance.": "приёмка ремонта",
  "repair curing": "уход за ремонтным составом",
  "repair mortar": "ремонтный раствор",
  "replacement/supplementary rebar": "замена и дополнительное армирование",
  "reposition cycles": "циклы перестановки опалубки",
  "retained-edge preparation": "подготовка сохраняемой кромки",
  "rigging": "такелажные работы",
  "roller-compacted concrete": "укатанный бетон",
  "roughening": "шерохование поверхности",
  "sampling": "отбор проб",
  "sandwich concrete panels": "трёхслойные железобетонные панели",
  "saw cutting": "алмазная резка",
  "saw-cut joints": "нарезные усадочные швы",
  "scanning": "инструментальное сканирование",
  "screeding": "выравнивание бетонной смеси",
  "sealing tapes": "герметизирующие ленты",
  "section enlargement": "усиление увеличением сечения",
  "segment planning": "планирование последовательности сегментов",
  "self-climbing forms": "самоподъёмная опалубка",
  "self-compacting concrete": "самоуплотняющийся бетон",
  "sensor installation": "установка датчиков",
  "septic structures": "очистные септические сооружения",
  "shade/wind protection": "защита от солнца и ветра",
  "shoring towers": "опорные башни",
  "shotcrete mix": "торкрет-бетонная смесь",
  "shotcrete repair": "ремонт торкретированием",
  "shrinkage reinforcement": "противоусадочное армирование",
  "silo_foundation": "фундамент силоса",
  "silos": "силосные сооружения",
  "site acceptance.": "приёмка на строительной площадке",
  "site-mix": "бетонная смесь площадочного приготовления",
  "skip": "скиповый подъёмник",
  "slab forms": "опалубка плит",
  "slab_column_frame": "безбалочный каркас",
  "sleeves": "гильзы",
  "slipform": "скользящая опалубка",
  "slipform placement": "бетонирование в скользящей опалубке",
  "slump": "осадка конуса",
  "slump flow": "расплыв конуса",
  "snow/ice removal": "удаление снега и наледи",
  "sorting": "сортировка отходов",
  "sounding": "простукивание поверхности",
  "spalled concrete removal": "удаление отслоившегося бетона",
  "spillways": "водосбросные сооружения",
  "splitting tensile strength": "прочность на растяжение при раскалывании",
  "stability monitoring": "мониторинг устойчивости",
  "standard heavy concrete": "обычный тяжёлый бетон",
  "standby plant": "резервный комплект оборудования",
  "starter bars": "арматурные выпуски",
  "stay-in-place forms": "остающаяся опалубка",
  "steam heating": "паропрогрев бетона",
  "steel formwork": "стальная опалубка",
  "steel-fiber concrete": "сталефибробетон",
  "stop ends": "торцевые щиты рабочего шва",
  "strands": "арматурные канаты",
  "stressing": "натяжение арматуры",
  "stressing protocols": "протоколы натяжения арматуры",
  "strip_foundation": "ленточный фундамент",
  "structural survey": "обследование несущих конструкций",
  "sulfate-resistant concrete": "сульфатостойкий бетон",
  "support frames": "опорные рамы",
  "surface finish acceptance": "приёмка качества поверхности",
  "surface sealing": "герметизация поверхности",
  "surface vibration": "поверхностное вибрирование",
  "survey": "инструментальное обследование",
  "synthetic-fiber concrete": "бетон с синтетической фиброй",
  "table forms": "столовая опалубка перекрытий",
  "tail cutting": "обрезка концов арматурных канатов",
  "tank_foundation": "фундамент резервуара",
  "tank_foundation_ring": "кольцевой фундамент резервуара",
  "temperature monitoring": "температурный мониторинг",
  "temporary support": "временное поддерживание",
  "temporary works design.": "проект временных конструкций",
  "tendon supports": "опоры каналов преднапряжения",
  "thermal cracking prevention": "предотвращение температурного трещинообразования",
  "thermomats": "термоизоляционные маты",
  "thin shells": "тонкостенные оболочки",
  "threaded couplers": "резьбовые муфты арматуры",
  "timber formwork": "деревянная опалубка",
  "top/bottom mats": "верхняя и нижняя арматурные сетки",
  "transfer beams": "передаточные балки",
  "transfer slabs": "передаточные плиты",
  "transformer_foundation": "фундамент трансформатора",
  "transit mixer delivery": "доставка автобетоносмесителем",
  "tremie": "бетонолитная труба",
  "tremie concrete": "бетонирование методом вертикально перемещаемой трубы",
  "trial batches": "пробные замесы",
  "trowelling": "затирка поверхности",
  "trumpets": "анкерные раструбы",
  "tunnel forms": "туннельная опалубка",
  "turbine_foundation": "фундамент турбоагрегата",
  "ultrasonic testing": "ультразвуковой контроль",
  "unbonded tendons": "канатная арматура без сцепления",
  "underwater concrete": "подводный бетон",
  "vacuum dewatering": "вакуумирование бетонной смеси",
  "vacuum-assisted grouting": "вакуумное инъектирование каналов",
  "vents": "вентиляционные отверстия каналов",
  "vertical placement windows": "окна для послойной укладки бетона",
  "void grouting": "инъектирование пустот",
  "walers": "ригели опалубки",
  "wall sawing": "алмазная резка стен",
  "wall-beam systems.": "стенобалочные системы",
  "water/admixture certificates": "сертификаты на воду и добавки",
  "waterstops": "гидроизоляционные шпонки",
  "watertight basements.": "водонепроницаемые подземные части здания",
  "watertight concrete": "водонепроницаемый бетон",
  "watertightness": "водонепроницаемость",
  "watertightness test": "испытание на водонепроницаемость",
  "wedges": "клинья анкерных устройств",
  "weld inspection": "контроль сварных соединений",
  "wet curing": "влажностный уход за бетоном",
  "white concrete": "белый бетон",
  "winter concreting": "зимнее бетонирование",
  "wire sawing": "канатная алмазная резка",
  "working platforms": "рабочие площадки",
  "морские/береговые concrete elements при наличии": "морские и береговые бетонные элементы при наличии",
});

export const HVAC_COMPONENT_TITLE_RU_R542: Readonly<Record<string, string>> = Object.freeze({
  "BMS points list": "перечень точек системы диспетчеризации и автоматизации",
  "cooling distribution unit": "распределительный блок охлаждения",
  "in-row охладитель при применимости": "внутрирядный охладитель при применимости",
  "point-to-point проверка автоматики": "проверка соединений автоматики по каждой точке",
  "rear-door heat exchanger при наличии проекта": "теплообменник задней двери шкафа при наличии проекта",
  "site acceptance test": "приёмочные испытания на объекте",
  "systems manual": "руководство по эксплуатации систем",
  "внутренний блок split-системы": "внутренний блок сплит-системы",
  "вход пожарного сценария Fire owner": "вход пожарного сценария от смежной системы пожарной автоматики",
  "вход тепловыделений от Electrical/UPS owner": "данные о тепловыделениях от смежных систем электроснабжения и бесперебойного питания",
  "граница BMS points и общесистемной автоматики": "граница точек диспетчеризации и общесистемной автоматики",
  "граница MCC и силовых feeders Electrical owner": "граница шкафа управления электродвигателями и силовых линий смежной системы электроснабжения",
  "граница cause-and-effect Fire owner": "граница матрицы причинно-следственных связей смежной пожарной автоматики",
  "граница аварийного дренажа Water owner": "граница аварийного дренажа смежной системы водоотведения",
  "граница аварийного питания Electrical owner": "граница аварийного питания смежной системы электроснабжения",
  "граница ведомости электрических нагрузок Electrical owner": "граница ведомости нагрузок смежной системы электроснабжения",
  "граница водоподготовки Water owner": "граница смежной системы водоподготовки",
  "граница восстановления покрытия Road owner": "граница восстановления дорожного покрытия смежным разделом",
  "граница газоснабжения котельной Gas owner": "граница смежной системы газоснабжения котельной",
  "граница закладных и конструкций Structural owner": "граница закладных деталей и смежных строительных конструкций",
  "граница исполнительной геодезии Survey owner": "граница исполнительной геодезии смежного раздела",
  "граница кабельного подключения термостата Electrical owner": "граница кабельного подключения термостата смежной системой электроснабжения",
  "граница общесистемных тревог BMS": "граница общесистемных тревог диспетчеризации",
  "граница подпитки Water owner": "граница подпитки смежной системой водоснабжения",
  "граница подпитки и дренажа Water owner": "граница подпитки и дренажа смежных систем водоснабжения и водоотведения",
  "граница подпитки и продувки Water owner": "граница подпитки и продувки смежной системой водоснабжения",
  "граница пожарного отключения Fire owner": "граница сигнала пожарного отключения смежной пожарной автоматики",
  "граница пожарного сценария Fire owner": "граница пожарного сценария смежной пожарной автоматики",
  "граница пожарного сценария клапана Fire owner": "граница пожарного сценария клапана смежной пожарной автоматики",
  "граница пожарных сигналов и сценариев Fire owner": "граница пожарных сигналов и сценариев смежной пожарной автоматики",
  "граница пожаротушения Fire owner": "граница смежной системы пожаротушения",
  "граница помещений и зон обслуживания Architecture owner": "граница помещений и зон обслуживания смежного архитектурного раздела",
  "граница проёмов и усилений Structural owner": "граница проёмов и усилений смежного конструктивного раздела",
  "граница сети автоматики BMS/Electrical owner": "граница сети автоматики и смежной системы электроснабжения",
  "граница сигнализатора газа Gas/Fire owner": "граница сигнализатора газа смежных систем газоснабжения и пожарной автоматики",
  "граница силового электроснабжения Electrical owner": "граница силового электроснабжения смежного электротехнического раздела",
  "граница стяжки и напольной конструкции Interior owner": "граница стяжки и напольной конструкции смежного раздела отделки",
  "граница топливного хозяйства Fuel owner": "граница смежной системы топливного хозяйства",
  "граница траншеи и обратной засыпки Earthworks owner": "граница траншеи и обратной засыпки смежного раздела земляных работ",
  "граница тяжёлых рам и фундаментов Structural owner": "граница тяжёлых рам и фундаментов смежного конструктивного раздела",
  "граница учёта топлива Fuel owner": "граница учёта топлива смежной системы топливного хозяйства",
  "граница фальшпола Structural/Interior owner": "граница фальшпола смежных конструктивного и отделочного разделов",
  "граница фундамента дымовой трубы Structural owner": "граница фундамента дымовой трубы смежного конструктивного раздела",
  "граница фундаментов котлов Structural owner": "граница фундаментов котлов смежного конструктивного раздела",
  "граница химических стоков Water/Environmental owner": "граница химических стоков смежных разделов водоотведения и охраны окружающей среды",
  "граница электропитания и защит Electrical owner": "граница электропитания и защит смежного электротехнического раздела",
  "датчик CO при проектной применимости": "датчик угарного газа при проектной применимости",
  "датчик NO2 при проектной применимости": "датчик диоксида азота при проектной применимости",
  "заморозка project basis и revision": "фиксация исходных проектных данных и редакции",
  "изоляция, дренирование или recovery перед заменой": "изоляция, дренирование или сбор рабочего вещества перед заменой",
  "интегрированный технологический комплекс HVAC машинного помещения": "интегрированный технологический комплекс ОВиК машинного помещения",
  "интерфейс оптимизации BMS": "интерфейс оптимизации системы диспетчеризации и автоматизации",
  "испытание lead-lag последовательности": "испытание последовательности основного и резервного агрегатов",
  "испытание резервирования N+1": "испытание резервирования по схеме один резервный агрегат",
  "комплексное испытание пожарного interface": "комплексное испытание интерфейса пожарной автоматики",
  "локальный контроллер HVAC": "локальный контроллер ОВиК",
  "локальный термостат HVAC": "локальный термостат ОВиК",
  "маршрут баллонов и recovered refrigerant": "маршрут баллонов и собранного хладагента",
  "матрица cause-and-effect": "матрица причинно-следственных связей",
  "модуль free cooling": "модуль свободного охлаждения",
  "наружный блок split-системы": "наружный блок сплит-системы",
  "освидетельствование witness и hold points": "освидетельствование контрольных точек присутствия и остановки работ",
  "отчёт TAB": "отчёт наладки и балансировки системы",
  "отчёт design basis": "отчёт об исходных проектных данных",
  "отчёт испытания failover": "отчёт об испытании автоматического переключения на резерв",
  "передача нагрузок на основания Structural owner": "передача нагрузок на основания смежному конструктивному разделу",
  "план инспекций и испытаний ITP": "план инспекций и испытаний",
  "правила измерения предварительной BOQ": "правила измерения предварительной ведомости объёмов работ",
  "прецизионный CRAC агрегат": "прецизионный кондиционер прямого испарения",
  "прецизионный CRAH агрегат": "прецизионный кондиционер с водяным теплообменником",
  "проверка trend logs": "проверка журналов изменения параметров",
  "проверка аварий и fail-safe состояний": "проверка аварий и безопасных состояний при отказе",
  "проверка программы factory acceptance": "проверка программы заводских приёмочных испытаний",
  "проверка стабильности по trend logs": "проверка стабильности по журналам изменения параметров",
  "реестр hold points монтажа": "реестр точек остановки монтажных работ",
  "реестр недостающих входов preliminary BOQ": "реестр недостающих исходных данных предварительной ведомости объёмов работ",
  "реестр согласованных submittals": "реестр согласованных технических представлений",
  "суточный топливный бак на Fuel owner boundary": "суточный топливный бак на границе смежной системы топливного хозяйства",
  "теплообменник ГВС на Water boundary": "теплообменник горячего водоснабжения на границе смежной системы водоснабжения",
  "финальное handover dossier": "итоговый комплект документации для передачи в эксплуатацию",
  "функциональное испытание последовательности AHU": "функциональное испытание последовательности приточно-вытяжной установки",
});

export const CONCRETE_PARAMETER_TITLE_RU_R542: Readonly<Record<string, string>> = Object.freeze({
  access_congestion: "Стеснённость доступа к месту работ",
  bar_class_diameters: "Классы и диаметры арматурных стержней",
  concrete_class: "Проектный класс бетона",
  coupler_locations: "Расположение механических соединений арматуры",
  cover: "Проектный защитный слой бетона",
  curing_method_duration: "Способ и продолжительность ухода за бетоном",
  currency: "Валюта расчёта",
  defect_map: "Карта дефектов",
  delivery_distance_km: "Расстояние доставки",
  demolition_sequence: "Последовательность демонтажа",
  design_loads: "Проектные нагрузки",
  diameter_radius: "Диаметр или радиус элемента",
  element_count: "Количество элементов",
  embedment_schedule: "Ведомость закладных деталей",
  exposure_class: "Класс условий эксплуатации",
  fire_resistance: "Требуемый предел огнестойкости",
  formwork_pressure: "Расчётное давление бетонной смеси на опалубку",
  frost_resistance: "Требуемая морозостойкость",
  height: "Высота",
  joint_layout: "Схема рабочих и деформационных швов",
  lap_anchorage: "Длины нахлёста и анкеровки арматуры",
  length: "Длина",
  manufacturer_data: "Данные изготовителя",
  mix_design: "Проект состава бетонной смеси",
  openings_recesses: "Проёмы, ниши и углубления",
  operation_type: "Вид технологической операции",
  placement_method: "Способ укладки бетонной смеси",
  pour_lift_count: "Количество ярусов бетонирования",
  pour_sequence: "Последовательность бетонирования",
  precast_mass_route: "Масса и маршрут монтажа сборного элемента",
  prestressing_design: "Проект предварительного напряжения",
  price_date: "Дата уровня цен",
  quantity: "Проектное количество",
  region: "Регион расчёта",
  reinforcement_schedule: "Ведомость армирования",
  repair_depth: "Глубина ремонта",
  seismic_requirements: "Сейсмические требования",
  shoring_sequence: "Последовательность установки и снятия временных опор",
  striking_strength: "Прочность бетона к моменту распалубки",
  structure_type: "Тип конструкции",
  surface_class: "Требуемый класс поверхности",
  tax_mode: "Налоговый режим",
  temporary_works: "Проект временных конструкций",
  test_lot_plan: "План контрольных партий и испытаний",
  thermal_control: "План температурного контроля",
  thickness: "Толщина",
  tolerances: "Проектные допуски",
  vertical_transport: "Вертикальная подача материалов",
  waste_route: "Маршрут обращения с отходами",
  watertightness: "Требуемая водонепроницаемость",
  width: "Ширина",
  work_included: "Работа включена в смету",
});

export const COMPONENT_PARAMETER_PREFIX_RU_R542: Readonly<Record<string, string>> = Object.freeze({
  quantity: "Проектное количество",
  labor_norm: "Норма трудозатрат",
  machine_norm: "Норма машинного времени",
  mass_kg_per_unit: "Масса на единицу",
  test_interval: "Интервал испытаний",
  waste_factor: "Коэффициент технологических отходов",
  document_lot: "Размер документируемой партии",
});

export const WATER_MATERIAL_VARIANT_LABEL_RU_R542: Readonly<Record<string, string>> = Object.freeze({
  PVC_SN8: "канализационная труба ПВХ класса SN8",
  PP_CORRUGATED: "гофрированная полипропиленовая труба",
  RC_PIPE: "железобетонная труба",
  PROJECT_APPROVED_METAL: "металлическое изделие по проектной спецификации",
  PROJECT_APPROVED_POLYMER: "полимерное изделие по проектной спецификации",
  FACTORY_ASSEMBLY: "узел заводской сборки",
  SIPHONIC_HDPE: "сифонный трубопровод из полиэтилена низкого давления",
  FACTORY_OUTLET_SYSTEM: "водоприёмная система заводского изготовления",
  PRECAST_CONCRETE: "сборный железобетон",
  POLYMER_CONCRETE: "полимербетон",
  GEOCOMPOSITE: "геокомпозитная система",
  PE100_SDR17: "полиэтиленовая труба ПЭ100 SDR17",
  PE100_SDR11: "полиэтиленовая труба ПЭ100 SDR11",
  DUCTILE_IRON: "труба из высокопрочного чугуна",
  STEEL_COATED: "стальная труба с защитным покрытием",
  PRECAST_RC: "сборная железобетонная конструкция",
  CAST_IN_SITU_RC: "монолитная железобетонная конструкция",
  POLYMER_CHAMBER: "полимерная камера",
  DRY_INSTALLED_PUMP: "насос сухой установки",
  SUBMERSIBLE_PUMP: "погружной насос",
  VERTICAL_TURBINE_PUMP: "вертикальный турбинный насос",
  FACTORY_PACKAGE: "комплектная установка заводского изготовления",
  SITE_ASSEMBLED_STEEL: "стальная установка площадочной сборки",
  REINFORCED_CONCRETE_PROCESS_UNIT: "железобетонное технологическое сооружение",
  REINFORCED_CONCRETE: "железобетон",
  COATED_STEEL: "сталь с защитным покрытием",
  FACTORY_POLYMER: "полимерная ёмкость заводского изготовления",
  INSTALLED_NETWORK: "смонтированная трубопроводная сеть",
  PROJECT_FIXTURE_STANDARD: "санитарно-технический прибор стандартного исполнения по проекту",
  PROJECT_FIXTURE_ACCESSIBLE: "санитарно-технический прибор доступного исполнения по проекту",
  PROJECT_FIXTURE_HEAVY_DUTY: "санитарно-технический прибор усиленного исполнения по проекту",
  PVC_INTERNAL: "внутренняя канализационная труба из ПВХ",
  PP_LOW_NOISE: "малошумная полипропиленовая канализационная труба",
  CAST_IRON_SML: "безраструбная чугунная канализационная труба",
  PPR_PN20: "полипропиленовая труба ППР PN20",
  PPR_FIBER_REINFORCED: "полипропиленовая труба, армированная волокном",
  PPR_ALUMINIUM_REINFORCED: "полипропиленовая труба, армированная алюминием",
  PE_RT: "термостойкая полиэтиленовая труба PE-RT",
  GALVANIZED_STEEL: "стальная оцинкованная труба",
  COPPER: "медная труба",
  MULTILAYER_PEX_AL_PEX: "многослойная металлополимерная труба PEX-AL-PEX",
});

const WATER_DYNAMIC_SYSTEM_RU: Readonly<Record<string, string>> = Object.freeze({
  BOILER: "водонагреватель",
  COLLECTOR: "коллектор",
  FILTER: "фильтр",
  METER: "прибор учёта",
  PUMP: "насос",
  INSTALLATION: "комплектная установка",
});

const WATER_DYNAMIC_DUTY_RU: Readonly<Record<string, string>> = Object.freeze({
  PROJECT_DUTY: "по проектной рабочей точке",
  DUTY_STANDBY: "основной и резервный агрегаты",
  HIGH_EFFICIENCY: "повышенной энергоэффективности",
});

export function waterMaterialVariantLabelRuR542(value: string): string {
  const exact = WATER_MATERIAL_VARIANT_LABEL_RU_R542[value];
  if (exact) return exact;
  const match = value.match(/^(BOILER|COLLECTOR|FILTER|METER|PUMP|INSTALLATION)_(PROJECT_DUTY|DUTY_STANDBY|HIGH_EFFICIENCY)$/u);
  return match ? `${WATER_DYNAMIC_SYSTEM_RU[match[1]!]} — ${WATER_DYNAMIC_DUTY_RU[match[2]!]}` : value;
}

const EXACT_PUBLIC_LABEL_RU: Readonly<Record<string, string>> = Object.freeze({
  ...CONCRETE_PARAMETER_TITLE_RU_R542,
  "Работа включена в проектный scope": "Работа включена в проектный состав",
  "equipment selection reference": "Основание выбора оборудования",
  "design airflow m3 h": "Проектный расход воздуха, м³/ч",
  "design flow m3 h": "Проектный расход, м³/ч",
  "heat load kw": "Тепловая нагрузка, кВт",
  "heating load kw": "Нагрузка отопления, кВт",
  "cooling load kw": "Холодильная нагрузка, кВт",
  "return temperature c": "Температура обратного теплоносителя, °C",
  "supply temperature c": "Температура подающего теплоносителя, °C",
  "external static pressure pa": "Внешнее статическое давление, Па",
  "acoustic limit db": "Предельный уровень звука, дБ",
  "route length m": "Длина трассы, м",
  "filter class": "Класс фильтра",
  "pump head kpa": "Напор насоса, кПа",
  "redundancy class": "Класс резервирования",
  "pipe material": "Материал трубопровода",
  "nominal diameter mm": "Номинальный диаметр, мм",
  "working pressure mpa": "Рабочее давление, МПа",
  "soil and route profile": "Характеристики грунта и профиль трассы",
  "terminal selection reference": "Основание выбора конечного устройства",
  "component count": "Количество компонентов",
  "zone area m2": "Площадь зоны, м²",
  "circuit layout reference": "Проектная схема контуров",
  "floor construction reference": "Проектная конструкция пола",
  "duct dimensions reference": "Проектные размеры воздуховода",
  "duct material": "Материал воздуховода",
  "duct leakage class": "Класс герметичности воздуховода",
  "fire smoke class": "Класс пожарной и дымовой защиты",
  "refrigerant type": "Тип хладагента",
  "manufacturer charge kg": "Заправочная масса по данным изготовителя, кг",
  "liquid line length m": "Длина жидкостной линии, м",
  "gas line length m": "Длина газовой линии, м",
  "elevation difference m": "Перепад высот, м",
  "flue gas flow input": "Проектный расход дымовых газов",
  "flue temperature c": "Температура дымовых газов, °C",
  "flue material": "Материал газохода",
  "flue size reference": "Проектное сечение газохода",
  "structural stack input": "Проектные данные несущего ствола",
  "surface area m2": "Площадь изолируемой поверхности, м²",
  "service temperature c": "Рабочая температура, °C",
  "insulation material": "Материал теплоизоляции",
  "insulation thickness mm": "Толщина теплоизоляции, мм",
  "environment class": "Класс окружающей среды",
  "commissioning scope reference": "Программа пусконаладочных работ",
  "measurement point count": "Количество точек измерения",
  "Вывоз отходов входит в scope": "Вывоз отходов входит в состав работ",
  "Точный шифр применимой расценки КРЕРп 01-2015 или N_A_WITH_REASON": "Точный шифр применимой расценки КРЕРп 01-2015 либо указание причины неприменимости",
});

const COMPONENT_MAPS = Object.freeze([
  CONCRETE_COMPONENT_TITLE_RU_R542,
  HVAC_COMPONENT_TITLE_RU_R542,
]);

const COMPONENT_ENTRIES = Object.freeze(
  COMPONENT_MAPS.flatMap((map) => Object.entries(map))
    .sort(([left], [right]) => right.length - left.length || left.localeCompare(right)),
);

function replaceTrailingComponent(value: string, source: string, target: string): string {
  if (value === source) return target;
  for (const delimiter of [" — ", ": ", " "]) {
    const suffix = `${delimiter}${source}`;
    if (value.endsWith(suffix)) return `${value.slice(0, -source.length)}${target}`;
  }
  return value;
}

export function localizeTechnologyTitleRu(input: string): string {
  let value = input.trim().replace(/\s+/gu, " ");
  value = EXACT_PUBLIC_LABEL_RU[value] ?? value;
  for (const [source, target] of COMPONENT_ENTRIES) {
    value = replaceTrailingComponent(value, source, target);
  }
  for (const [source, target] of Object.entries(COMPONENT_PARAMETER_PREFIX_RU_R542)) {
    if (value.startsWith(`${source} — `)) value = `${target}${value.slice(source.length)}`;
  }
  value = value.replace(/ — ([A-Z][A-Z0-9_]+)$/u, (whole, machineValue: string) => {
    const label = waterMaterialVariantLabelRuR542(machineValue);
    return label === machineValue ? whole : ` — ${label}`;
  });
  return value
    .replace(/\bproject scope\b/giu, "проектный состав")
    .replace(/\bscope\b/giu, "состав")
    .replace(/\bsubmittals?\b/giu, "технические представления")
    .replace(/\bHVAC owner\b/giu, "ответственная сторона раздела ОВиК")
    .replace(/\bas-found\/as-left\b/giu, "до и после регулировки")
    .replace(/\brecovery\b/giu, "сбор рабочего вещества")
    .replace(/\bchiller\b/giu, "холодильная машина")
    .replace(/\bFire Protection owner\b/giu, "ответственная сторона раздела пожарной защиты")
    .replace(/\bN_A_WITH_REASON\b/gu, "указать причину неприменимости");
}

export function concreteComponentTitleRuR542(input: string): string {
  return CONCRETE_COMPONENT_TITLE_RU_R542[input] ?? input;
}

export function hvacComponentTitleRuR542(input: string): string {
  return HVAC_COMPONENT_TITLE_RU_R542[input] ?? input;
}

export function concreteParameterTitleRuR542(parameterId: string, componentTitleRu?: string): string {
  if (!componentTitleRu) return CONCRETE_PARAMETER_TITLE_RU_R542[parameterId] ?? parameterId;
  const suffix = Object.keys(COMPONENT_PARAMETER_PREFIX_RU_R542)
    .find((candidate) => parameterId === candidate || parameterId.endsWith(`_${candidate}`));
  const prefix = suffix == null ? parameterId : COMPONENT_PARAMETER_PREFIX_RU_R542[suffix];
  return `${prefix} — ${concreteComponentTitleRuR542(componentTitleRu)}`;
}
