import { StyleSheet } from "react-native";

export const consumerRepairRequestScreenStyles = StyleSheet.create({
  screen: {
    backgroundColor: "#F8FAFC",
  },
  content: {
    gap: 14,
    paddingTop: 4,
  },
  lead: {
    color: "#475569",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
  },
  card: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    padding: 14,
    gap: 10,
  },
  label: {
    color: "#0F172A",
    fontSize: 13,
    fontWeight: "900",
  },
  input: {
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#FFFFFF",
    color: "#0F172A",
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    fontWeight: "700",
  },
  textArea: {
    minHeight: 92,
    textAlignVertical: "top",
  },
  status: {
    borderRadius: 10,
    backgroundColor: "#ECFDF5",
    color: "#047857",
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    fontWeight: "900",
  },
  makePdfButton: {
    minHeight: 44,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#CBD5E1",
  },
  makePdfButtonText: {
    color: "#0F172A",
    fontSize: 13,
    fontWeight: "900",
  },
  marketBackButton: {
    minHeight: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  marketBackButtonText: {
    color: "#0F172A",
    fontSize: 13,
    fontWeight: "900",
  },
});
