import { StyleSheet } from "react-native";

export const consumerRepairRequestScreenStyles = StyleSheet.create({
  keyboardRoot: {
    flex: 1,
    minHeight: 0,
  },
  screen: {
    backgroundColor: "#F8FAFC",
  },
  content: {
    gap: 14,
    paddingTop: 4,
  },
  lead: {
    color: "#475569",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
  },
  topEstimateProof: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  topEstimateProofText: {
    color: "#1E293B",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "800",
  },
  launchPrompt: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#99F6E4",
    backgroundColor: "#F0FDFA",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  launchPromptLabel: {
    color: "#0F766E",
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  launchPromptText: {
    color: "#134E4A",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "800",
  },
  runtimeIngressComposer: {
    position: "absolute",
    zIndex: 50,
    elevation: 16,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "#F8FAFC",
    paddingTop: 72,
    paddingHorizontal: 24,
    gap: 14,
  },
  runtimeIngressTitle: {
    color: "#0F172A",
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "900",
  },
  runtimeIngressStatus: {
    color: "#475569",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
  },
  runtimeIngressInput: {
    minHeight: 132,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#0F766E",
    backgroundColor: "#FFFFFF",
    color: "#0F172A",
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    lineHeight: 23,
    textAlignVertical: "top",
  },
  card: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    padding: 14,
    gap: 10,
  },
  label: {
    color: "#0F172A",
    fontSize: 13,
    fontWeight: "900",
  },
  input: {
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#FFFFFF",
    color: "#0F172A",
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    fontWeight: "700",
  },
  textArea: {
    minHeight: 92,
    textAlignVertical: "top",
  },
  status: {
    borderRadius: 10,
    backgroundColor: "#ECFDF5",
    color: "#047857",
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    fontWeight: "900",
  },
  pilotBadge: {
    alignSelf: "flex-start",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#0F766E",
    backgroundColor: "#CCFBF1",
    color: "#134E4A",
    paddingHorizontal: 10,
    paddingVertical: 7,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
  },
  makePdfButton: {
    minHeight: 44,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#CBD5E1",
  },
  makePdfButtonText: {
    color: "#0F172A",
    fontSize: 13,
    fontWeight: "900",
  },
  bottomActions: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#FFFFFF",
    padding: 14,
    marginTop: 2,
  },
  bottomActionsTitle: {
    color: "#0F172A",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "900",
  },
  bottomActionButton: {
    minHeight: 48,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 14,
  },
  bottomActionPrimary: {
    backgroundColor: "#16A34A",
    borderColor: "#16A34A",
  },
  bottomActionSecondary: {
    backgroundColor: "#FFFFFF",
    borderColor: "#CBD5E1",
  },
  bottomActionDanger: {
    backgroundColor: "#DC2626",
    borderColor: "#DC2626",
  },
  bottomActionDisabled: {
    opacity: 0.55,
  },
  bottomActionPrimaryText: {
    flexShrink: 1,
    minWidth: 0,
    color: "#FFFFFF",
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "900",
    textAlign: "center",
  },
  bottomActionSecondaryText: {
    flexShrink: 1,
    minWidth: 0,
    color: "#0F172A",
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "900",
    textAlign: "center",
  },
  deleteDraftConfirmation: {
    gap: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#FCA5A5",
    backgroundColor: "#FEF2F2",
    padding: 12,
  },
  deleteDraftConfirmationTitle: {
    color: "#991B1B",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "900",
  },
  deleteDraftConfirmationText: {
    color: "#7F1D1D",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
  },
  deleteDraftConfirmationActions: {
    flexDirection: "row",
    gap: 8,
  },
  deleteDraftConfirmationButton: {
    flex: 1,
  },
  marketBackButton: {
    minHeight: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  marketBackButtonText: {
    color: "#0F172A",
    fontSize: 13,
    fontWeight: "900",
  },
});
