import type { WorldConstructionDomainDefinition } from "./worldConstructionTypes";

const sharedExclusions = [
  "Проектирование, разрешения и авторский надзор не включены, если не указаны отдельной строкой.",
  "Скрытые дефекты основания и усиление конструкций уточняются после обследования.",
  "Доставка, подъем и доступ к объекту зависят от адреса и условий площадки.",
];

const sharedQuestions = [
  "Укажите город и адрес объекта для локальной ставки и налога.",
  "Подтвердите объем, размеры и состояние основания.",
  "Нужны ли демонтаж, доставка, подъем и вывоз мусора?",
];

function domain(params: WorldConstructionDomainDefinition): WorldConstructionDomainDefinition {
  return params;
}

export const CONSTRUCTION_DOMAIN_DEFINITIONS: readonly WorldConstructionDomainDefinition[] = [
  domain({
    domain: "residential_construction",
    globalCategory: "other",
    labelRu: "Жилое строительство",
    objects: ["site", "wall", "floor", "ceiling"],
    operations: ["installation", "repair", "preparation"],
    methods: ["generic_professional_method"],
    materialSystems: ["general_building"],
    units: ["sq_m", "m3", "set"],
    requiredBoqGroups: ["materials", "labor", "equipment", "delivery"],
    equipment: ["ручной инструмент", "малая механизация"],
    laborTypes: ["общестроительная бригада"],
    exclusions: sharedExclusions,
    clarifyingQuestions: sharedQuestions,
    dangerousOrRegulated: false,
    catalogPolicy: "gap_warning_allowed",
    rateSourcePolicy: "manual_review_required",
  }),
  domain({
    domain: "commercial_construction",
    globalCategory: "other",
    labelRu: "Коммерческое строительство",
    objects: ["site", "wall", "floor", "ceiling"],
    operations: ["installation", "repair", "preparation"],
    methods: ["generic_professional_method"],
    materialSystems: ["general_building"],
    units: ["sq_m", "m3", "set"],
    requiredBoqGroups: ["materials", "labor", "equipment", "delivery"],
    equipment: ["подъемники", "малая механизация"],
    laborTypes: ["общестроительная бригада", "инженерная бригада"],
    exclusions: sharedExclusions,
    clarifyingQuestions: sharedQuestions,
    dangerousOrRegulated: false,
    catalogPolicy: "gap_warning_allowed",
    rateSourcePolicy: "manual_review_required",
  }),
  domain({
    domain: "industrial_construction",
    globalCategory: "concrete",
    labelRu: "Промышленное строительство",
    objects: ["site", "hydropower_unit"],
    operations: ["installation", "commissioning", "design_survey"],
    methods: ["hydro_turbine_equipment_install", "generic_professional_method"],
    materialSystems: ["industrial_equipment"],
    units: ["set", "pcs", "m3"],
    requiredBoqGroups: ["materials", "labor", "equipment", "delivery"],
    equipment: ["кран", "такелаж", "сварочное оборудование"],
    laborTypes: ["монтажники оборудования", "электромонтажники", "ПНР-инженер"],
    exclusions: [
      ...sharedExclusions,
      "Лицензии, подключение к сети, ЛЭП, трансформатор и проектная экспертиза считаются отдельно.",
    ],
    clarifyingQuestions: [
      "Какая точка подключения и схема работы: сеть или автономно?",
      "Нужны ли трансформатор, ЛЭП, телеметрия и диспетчеризация?",
      ...sharedQuestions,
    ],
    dangerousOrRegulated: true,
    catalogPolicy: "gap_warning_allowed",
    rateSourcePolicy: "manual_review_required",
  }),
  domain({
    domain: "civil_infrastructure",
    globalCategory: "roadworks",
    labelRu: "Гражданская инфраструктура",
    objects: ["road_area", "site"],
    operations: ["paving", "installation", "repair"],
    methods: ["asphalt_hot_mix", "generic_professional_method"],
    materialSystems: ["road_base"],
    units: ["sq_m", "m3", "linear_m"],
    requiredBoqGroups: ["materials", "labor", "equipment", "delivery"],
    equipment: ["каток", "асфальтоукладчик", "погрузчик"],
    laborTypes: ["дорожная бригада", "геодезист"],
    exclusions: sharedExclusions,
    clarifyingQuestions: sharedQuestions,
    dangerousOrRegulated: false,
    catalogPolicy: "bind_materials",
    rateSourcePolicy: "source_required",
  }),
  domain({
    domain: "roadworks",
    globalCategory: "roadworks",
    labelRu: "Дорожные работы",
    objects: ["road_area", "site"],
    operations: ["paving", "repair", "preparation"],
    methods: ["asphalt_hot_mix"],
    materialSystems: ["road_base"],
    units: ["sq_m", "m3", "ton"],
    requiredBoqGroups: ["materials", "labor", "equipment", "delivery"],
    equipment: ["каток", "асфальтоукладчик", "виброплита"],
    laborTypes: ["дорожная бригада"],
    exclusions: sharedExclusions,
    clarifyingQuestions: ["Какая текущая основа: грунт, щебень, старый асфальт или бетон?", ...sharedQuestions],
    dangerousOrRegulated: false,
    catalogPolicy: "bind_materials",
    rateSourcePolicy: "source_required",
  }),
  domain({
    domain: "earthworks",
    globalCategory: "foundation",
    labelRu: "Земляные работы",
    objects: ["site", "strip_foundation"],
    operations: ["preparation", "installation"],
    methods: ["generic_professional_method"],
    materialSystems: ["earthworks"],
    units: ["m3", "sq_m", "linear_m"],
    requiredBoqGroups: ["labor", "equipment", "delivery"],
    equipment: ["экскаватор", "самосвал", "виброплита"],
    laborTypes: ["земляная бригада"],
    exclusions: sharedExclusions,
    clarifyingQuestions: sharedQuestions,
    dangerousOrRegulated: false,
    catalogPolicy: "gap_warning_allowed",
    rateSourcePolicy: "source_required",
  }),
  domain({
    domain: "foundations",
    globalCategory: "foundation",
    labelRu: "Фундаменты",
    objects: ["foundation", "strip_foundation"],
    operations: ["installation", "concrete_pour", "waterproofing"],
    methods: ["generic_professional_method"],
    materialSystems: ["concrete_rebar", "foundation_waterproofing"],
    units: ["m3", "linear_m", "sq_m"],
    requiredBoqGroups: ["materials", "labor", "equipment", "delivery"],
    equipment: ["бетоновоз", "бетононасос", "вибратор"],
    laborTypes: ["бетонщики", "арматурщики"],
    exclusions: sharedExclusions,
    clarifyingQuestions: sharedQuestions,
    dangerousOrRegulated: true,
    catalogPolicy: "bind_materials",
    rateSourcePolicy: "source_required",
  }),
  domain({
    domain: "concrete",
    globalCategory: "concrete",
    labelRu: "Бетонные работы",
    objects: ["site", "floor", "foundation"],
    operations: ["concrete_pour", "repair", "preparation"],
    methods: ["generic_professional_method"],
    materialSystems: ["concrete_rebar"],
    units: ["m3", "sq_m"],
    requiredBoqGroups: ["materials", "labor", "equipment", "delivery"],
    equipment: ["вибратор", "бетононасос"],
    laborTypes: ["бетонщики"],
    exclusions: sharedExclusions,
    clarifyingQuestions: sharedQuestions,
    dangerousOrRegulated: true,
    catalogPolicy: "bind_materials",
    rateSourcePolicy: "source_required",
  }),
  domain({
    domain: "masonry",
    globalCategory: "masonry",
    labelRu: "Кладочные работы",
    objects: ["masonry_wall", "wall"],
    operations: ["masonry", "installation", "repair"],
    methods: ["brick_mortar_masonry"],
    materialSystems: ["brick_masonry"],
    units: ["sq_m", "m3", "pcs"],
    requiredBoqGroups: ["materials", "labor", "delivery"],
    equipment: ["подмости", "миксер"],
    laborTypes: ["каменщики"],
    exclusions: sharedExclusions,
    clarifyingQuestions: ["Толщина кладки и тип кирпича?", ...sharedQuestions],
    dangerousOrRegulated: false,
    catalogPolicy: "bind_materials",
    rateSourcePolicy: "source_required",
  }),
  domain({
    domain: "roofing",
    globalCategory: "roofing",
    labelRu: "Кровельные работы",
    objects: ["roof"],
    operations: ["installation", "repair", "waterproofing"],
    methods: ["gable_roof_frame", "roll_membrane", "pvc_tpo_epdm_membrane", "bitumen_mastic"],
    materialSystems: ["roofing", "roof_waterproofing"],
    units: ["sq_m", "linear_m", "set"],
    requiredBoqGroups: ["materials", "labor", "equipment", "delivery"],
    equipment: ["леса", "подъемник", "страховка"],
    laborTypes: ["кровельщики"],
    exclusions: sharedExclusions,
    clarifyingQuestions: ["Тип кровли: плоская или скатная?", "Есть ли парапеты, проходки и воронки?", ...sharedQuestions],
    dangerousOrRegulated: true,
    catalogPolicy: "bind_materials",
    rateSourcePolicy: "source_required",
  }),
  domain({
    domain: "waterproofing",
    globalCategory: "waterproofing",
    labelRu: "Гидроизоляция",
    objects: ["roof", "bathroom", "foundation", "basement", "balcony_terrace"],
    operations: ["waterproofing", "preparation"],
    methods: ["roll_membrane", "pvc_tpo_epdm_membrane", "bitumen_mastic"],
    materialSystems: ["roof_waterproofing", "wet_area_waterproofing", "foundation_waterproofing"],
    units: ["sq_m", "linear_m"],
    requiredBoqGroups: ["materials", "labor", "delivery"],
    equipment: ["газовая горелка или нанесение мастики", "ручной инструмент"],
    laborTypes: ["гидроизоляционная бригада"],
    exclusions: sharedExclusions,
    clarifyingQuestions: [
      "Уточните объект: кровля, ванная, фундамент, подвал или балкон/терраса?",
      "Какой материал нужен: рулонный, мембрана или мастика?",
    ],
    dangerousOrRegulated: false,
    catalogPolicy: "bind_materials",
    rateSourcePolicy: "source_required",
  }),
  domain({
    domain: "flooring",
    globalCategory: "flooring",
    labelRu: "Полы",
    objects: ["floor"],
    operations: ["installation", "repair", "preparation"],
    methods: ["laminate_floating"],
    materialSystems: ["laminate_flooring"],
    units: ["sq_m", "linear_m", "pcs"],
    requiredBoqGroups: ["materials", "labor", "delivery"],
    equipment: ["ручной инструмент", "пылесос"],
    laborTypes: ["отделочники"],
    exclusions: sharedExclusions,
    clarifyingQuestions: sharedQuestions,
    dangerousOrRegulated: false,
    catalogPolicy: "bind_materials",
    rateSourcePolicy: "source_required",
  }),
  domain({
    domain: "drywall",
    globalCategory: "drywall",
    labelRu: "ГКЛ и сухое строительство",
    objects: ["wall", "ceiling"],
    operations: ["installation", "repair"],
    methods: ["drywall_metal_frame"],
    materialSystems: ["drywall_system"],
    units: ["sq_m", "linear_m"],
    requiredBoqGroups: ["materials", "labor", "delivery"],
    equipment: ["лазерный уровень", "шуруповерт"],
    laborTypes: ["монтажники ГКЛ"],
    exclusions: sharedExclusions,
    clarifyingQuestions: sharedQuestions,
    dangerousOrRegulated: false,
    catalogPolicy: "bind_materials",
    rateSourcePolicy: "source_required",
  }),
  domain({
    domain: "windows",
    globalCategory: "doors_windows",
    labelRu: "Окна",
    objects: ["window_opening"],
    operations: ["installation", "replacement"],
    methods: ["generic_professional_method"],
    materialSystems: ["window_installation"],
    units: ["pcs", "sq_m"],
    requiredBoqGroups: ["materials", "labor", "delivery"],
    equipment: ["пена-пистолет", "уровень"],
    laborTypes: ["монтажники окон"],
    exclusions: sharedExclusions,
    clarifyingQuestions: ["Сколько окон и какие размеры?", ...sharedQuestions],
    dangerousOrRegulated: false,
    catalogPolicy: "bind_materials",
    rateSourcePolicy: "source_required",
  }),
  domain({
    domain: "electrical",
    globalCategory: "electrical",
    labelRu: "Электромонтаж",
    objects: ["electrical_network"],
    operations: ["installation", "replacement", "repair"],
    methods: ["electrical_cable_install"],
    materialSystems: ["electrical_installation"],
    units: ["set", "pcs", "linear_m"],
    requiredBoqGroups: ["materials", "labor", "equipment"],
    equipment: ["тестер", "штроборез"],
    laborTypes: ["электромонтажники"],
    exclusions: sharedExclusions,
    clarifyingQuestions: ["Однофазная или трехфазная сеть?", "Нужна ли схема и допуск?", ...sharedQuestions],
    dangerousOrRegulated: true,
    catalogPolicy: "bind_materials",
    rateSourcePolicy: "manual_review_required",
  }),
  domain({
    domain: "ventilation",
    globalCategory: "heating_hvac",
    labelRu: "Вентиляция",
    objects: ["ventilation_network"],
    operations: ["installation", "replacement", "repair"],
    methods: ["duct_ventilation"],
    materialSystems: ["ventilation_system"],
    units: ["set", "linear_m", "sq_m"],
    requiredBoqGroups: ["materials", "labor", "equipment", "delivery"],
    equipment: ["леса", "подъемник", "измерительный прибор"],
    laborTypes: ["монтажники вентиляции"],
    exclusions: sharedExclusions,
    clarifyingQuestions: ["Расход воздуха и схема трасс известны?", ...sharedQuestions],
    dangerousOrRegulated: false,
    catalogPolicy: "bind_materials",
    rateSourcePolicy: "source_required",
  }),
  domain({
    domain: "solar",
    globalCategory: "electrical",
    labelRu: "Солнечная энергетика",
    objects: ["solar_array", "roof", "site"],
    operations: ["installation", "commissioning"],
    methods: ["solar_mounting"],
    materialSystems: ["solar_pv_system"],
    units: ["set", "pcs"],
    requiredBoqGroups: ["materials", "labor", "equipment", "delivery"],
    equipment: ["подъемник", "электроизмерительный прибор"],
    laborTypes: ["монтажники СЭС", "электромонтажники"],
    exclusions: sharedExclusions,
    clarifyingQuestions: ["Мощность станции и тип подключения?", ...sharedQuestions],
    dangerousOrRegulated: true,
    catalogPolicy: "bind_materials",
    rateSourcePolicy: "manual_review_required",
  }),
  domain({
    domain: "hydropower",
    globalCategory: "concrete",
    labelRu: "Гидроэнергетика",
    objects: ["hydropower_unit"],
    operations: ["installation", "commissioning", "design_survey"],
    methods: ["hydro_turbine_equipment_install"],
    materialSystems: ["hydro_turbine_system"],
    units: ["set", "pcs"],
    requiredBoqGroups: ["materials", "labor", "equipment", "delivery"],
    equipment: ["кран", "такелаж", "сварочное оборудование", "электроизмерительный прибор"],
    laborTypes: ["механомонтажники", "электромонтажники", "ПНР-инженер"],
    exclusions: [
      "Не включены ЛЭП, трансформатор, проектная экспертиза, водопользование и лицензии.",
      "Состав оборудования уточняется по напору H и расходу Q.",
      ...sharedExclusions,
    ],
    clarifyingQuestions: [
      "Напор H и расход Q?",
      "Тип турбины и схема водовода?",
      "Диаметр и длина напорной трубы?",
      "Состояние машинного зала?",
      "Точка подключения и режим работы: сеть или автономно?",
      "Нужен ли трансформатор и ЛЭП?",
    ],
    dangerousOrRegulated: true,
    catalogPolicy: "gap_warning_allowed",
    rateSourcePolicy: "manual_review_required",
  }),
  domain({
    domain: "well_drilling",
    globalCategory: "foundation",
    labelRu: "Бурение скважин",
    objects: ["well", "site"],
    operations: ["drilling", "installation"],
    methods: ["rotary_well_drilling"],
    materialSystems: ["well_drilling_system"],
    units: ["linear_m", "set"],
    requiredBoqGroups: ["materials", "labor", "equipment", "delivery"],
    equipment: ["буровая установка", "компрессор", "насос"],
    laborTypes: ["буровая бригада"],
    exclusions: sharedExclusions,
    clarifyingQuestions: ["Глубина, геология и требуемый дебит?", ...sharedQuestions],
    dangerousOrRegulated: true,
    catalogPolicy: "gap_warning_allowed",
    rateSourcePolicy: "manual_review_required",
  }),
  domain({
    domain: "demolition",
    globalCategory: "demolition",
    labelRu: "Демонтаж",
    objects: ["wall", "floor", "ceiling", "site"],
    operations: ["demolition", "preparation"],
    methods: ["generic_professional_method"],
    materialSystems: ["demolition"],
    units: ["sq_m", "m3", "set"],
    requiredBoqGroups: ["labor", "equipment", "delivery"],
    equipment: ["перфоратор", "контейнер", "пылеудаление"],
    laborTypes: ["демонтажная бригада"],
    exclusions: sharedExclusions,
    clarifyingQuestions: ["Есть ли несущие конструкции и инженерные сети?", ...sharedQuestions],
    dangerousOrRegulated: true,
    catalogPolicy: "gap_warning_allowed",
    rateSourcePolicy: "source_required",
  }),
];

const coveredDomains = new Set(CONSTRUCTION_DOMAIN_DEFINITIONS.map((item) => item.domain));

const macroDomains = [
  "steel_structures",
  "canopies",
  "wood_structures",
  "facade",
  "insulation",
  "doors",
  "walls",
  "ceilings",
  "screeds",
  "plastering",
  "putty",
  "painting",
  "tiling",
  "plumbing",
  "heating",
  "air_conditioning",
  "low_voltage",
  "fire_alarm",
  "security_systems",
  "water_supply",
  "sewerage",
  "drainage",
  "landscaping",
  "fencing",
  "site_preparation",
  "commercial_fit_out",
  "industrial_fit_out",
  "renovation",
  "restoration",
  "structural_repair",
] as const;

function macroGlobalCategory(
  domainName: (typeof macroDomains)[number],
): WorldConstructionDomainDefinition["globalCategory"] {
  if (domainName === "tiling") return "tile";
  if (domainName === "screeds") return "flooring";
  if (domainName === "plastering") return "plastering";
  if (domainName === "putty") return "putty";
  if (domainName === "painting") return "painting";
  if (domainName === "plumbing") return "plumbing";
  if (domainName === "facade") return "facade";
  if (domainName === "landscaping") return "landscaping";
  if (domainName === "doors") return "doors_windows";
  if (domainName === "ceilings") return "ceiling";
  if (domainName === "steel_structures" || domainName === "canopies") return "metalworks";
  if (domainName === "wood_structures") return "carpentry";
  if (domainName === "insulation") return "insulation";
  return "other";
}

export const CONSTRUCTION_DOMAIN_MAP: readonly WorldConstructionDomainDefinition[] = [
  ...CONSTRUCTION_DOMAIN_DEFINITIONS,
  ...macroDomains
    .filter((domainName) => !coveredDomains.has(domainName))
    .map((domainName) =>
      domain({
        domain: domainName,
        globalCategory: macroGlobalCategory(domainName),
        labelRu: domainName.replace(/_/g, " "),
        objects: ["site", "wall", "floor", "ceiling", "unknown"],
        operations: ["installation", "repair", "preparation"],
        methods: ["generic_professional_method"],
        materialSystems: ["general_building"],
        units: ["sq_m", "linear_m", "set"],
        requiredBoqGroups: ["materials", "labor", "equipment", "delivery"],
        equipment: ["профессиональный инструмент"],
        laborTypes: ["профильная бригада"],
        exclusions: sharedExclusions,
        clarifyingQuestions: sharedQuestions,
        dangerousOrRegulated: ["low_voltage", "fire_alarm", "security_systems", "structural_repair"].includes(domainName),
        catalogPolicy: "gap_warning_allowed",
        rateSourcePolicy: "manual_review_required",
      }),
    ),
];

export function getConstructionDomainDefinition(domainName: string): WorldConstructionDomainDefinition {
  return CONSTRUCTION_DOMAIN_MAP.find((item) => item.domain === domainName) ?? CONSTRUCTION_DOMAIN_MAP[0];
}
