import type { WarehouseActionQuestion, WarehouseScreenId, WarehouseStockIntent } from "./warehouseStockTypes";

export const WAREHOUSE_ACTION_QUESTION_MAP: readonly WarehouseActionQuestion[] = [
  {
    screenId: "warehouse.main",
    actionId: "today_stock_summary",
    labelRu: "Stock today",
    concreteQuestionRu: "Summarize stock today: critical materials, incoming, issue blockers, missing documents, and next safe action.",
    requiredContext: ["screen"],
    allowedSources: ["warehouse_stock", "warehouse_incoming", "warehouse_issue", "material", "document", "approval"],
    answerMode: "read",
  },
  {
    screenId: "warehouse.main",
    actionId: "critical_materials",
    labelRu: "Critical materials",
    concreteQuestionRu: "Show materials that are critical for works, with stock, reserved quantity, incoming quantity, deficit and sources.",
    requiredContext: ["screen"],
    allowedSources: ["warehouse_stock", "warehouse_issue", "material", "procurement_request"],
    answerMode: "read",
  },
  {
    screenId: "warehouse.issue",
    actionId: "what_to_issue_by_object",
    labelRu: "Issue by object",
    concreteQuestionRu: "Show what can be issued by object and work, what is blocked, and what source confirms the request.",
    requiredContext: ["object", "work"],
    allowedSources: ["warehouse_stock", "warehouse_issue", "material", "object", "work", "procurement_request"],
    answerMode: "read",
  },
  {
    screenId: "warehouse.issue",
    actionId: "issue_readiness_check",
    labelRu: "Check issue readiness",
    concreteQuestionRu: "Check issue readiness: stock, reserved quantity, work/object link, approval, and documents. Do not issue material.",
    requiredContext: ["issue"],
    allowedSources: ["warehouse_stock", "warehouse_issue", "material", "work", "object", "approval"],
    answerMode: "read",
  },
  {
    screenId: "warehouse.incoming",
    actionId: "incoming_readiness",
    labelRu: "Check incoming",
    concreteQuestionRu: "Check incoming materials: quantity, unit, documents, supplier label, discrepancy and safe receiving status. Do not accept stock.",
    requiredContext: ["incoming"],
    allowedSources: ["warehouse_incoming", "material", "document", "pdf_chunk", "approval"],
    answerMode: "read",
  },
  {
    screenId: "warehouse.incoming",
    actionId: "incoming_discrepancy_check",
    labelRu: "Incoming discrepancies",
    concreteQuestionRu: "Find incoming discrepancies by material, quantity, unit and documents, then prepare an approval-safe route.",
    requiredContext: ["incoming"],
    allowedSources: ["warehouse_incoming", "warehouse_stock", "material", "document", "approval"],
    answerMode: "read",
  },
  {
    screenId: "warehouse.main",
    actionId: "specification_match_check",
    labelRu: "Check specification",
    concreteQuestionRu: "Compare warehouse materials against linked specification, project PDFs and documents. Do not invent specification facts.",
    requiredContext: ["material"],
    allowedSources: ["material", "specification", "pdf_chunk", "document", "work", "object"],
    answerMode: "read",
  },
  {
    screenId: "warehouse.main",
    actionId: "unit_conversion_check",
    labelRu: "Check units",
    concreteQuestionRu: "Check units and conversion basis before comparing or issuing material. If conversion factor is missing, say so exactly.",
    requiredContext: ["material"],
    allowedSources: ["material", "specification", "warehouse_stock", "document"],
    answerMode: "read",
  },
  {
    screenId: "warehouse.main",
    actionId: "procurement_handoff",
    labelRu: "Handoff to buyer",
    concreteQuestionRu: "Prepare a draft handoff to buyer for material deficit with object, work, quantity, unit and source. Do not create purchase request.",
    requiredContext: ["material"],
    allowedSources: ["warehouse_stock", "warehouse_issue", "procurement_request", "material", "approval"],
    answerMode: "draft",
  },
  {
    screenId: "warehouse.issue",
    actionId: "foreman_handoff",
    labelRu: "Tell foreman",
    concreteQuestionRu: "Prepare a draft message to foreman about what material blocks the work and what is missing. Do not change work status.",
    requiredContext: ["work"],
    allowedSources: ["warehouse_stock", "warehouse_issue", "work", "object", "chat_message"],
    answerMode: "draft",
  },
  {
    screenId: "warehouse.incoming",
    actionId: "document_request_draft",
    labelRu: "Request documents",
    concreteQuestionRu: "Prepare a draft request for missing incoming documents, certificates or waybills. Do not send it finally.",
    requiredContext: ["incoming"],
    allowedSources: ["warehouse_incoming", "document", "pdf_chunk", "material"],
    answerMode: "draft",
  },
  {
    screenId: "warehouse.main",
    actionId: "approval_route",
    labelRu: "Route to approval",
    concreteQuestionRu: "Prepare an approval route for disputed stock, incoming or issue blockers. Do not approve automatically.",
    requiredContext: ["screen"],
    allowedSources: ["warehouse_stock", "warehouse_incoming", "warehouse_issue", "approval", "document"],
    answerMode: "approval_route",
  },
] as const;

export function getWarehouseActionQuestion(
  actionId: WarehouseStockIntent,
  screenId?: WarehouseScreenId,
): WarehouseActionQuestion | null {
  return WAREHOUSE_ACTION_QUESTION_MAP.find((action) =>
    action.actionId === actionId && (!screenId || action.screenId === screenId),
  ) ?? WAREHOUSE_ACTION_QUESTION_MAP.find((action) => action.actionId === actionId) ?? null;
}
