import type { WarehouseStockSourceType } from "./warehouseStockTypes";

export const WAREHOUSE_ROLE_POLICY = Object.freeze({
  role: "warehouse",
  canReadSources: [
    "stock_item",
    "warehouse_location",
    "incoming",
    "issue",
    "reservation",
    "transfer",
    "inventory_count",
    "procurement_request",
    "supplier_offer",
    "marketplace_offer",
    "waybill",
    "invoice",
    "document",
    "pdf_chunk",
    "work",
    "object",
    "estimate_line",
    "project_specification",
    "approval",
    "warehouse_stock",
    "warehouse_incoming",
    "warehouse_issue",
    "material",
    "specification",
    "zone",
    "chat_message",
  ] satisfies WarehouseStockSourceType[],
  cannotReadSources: [
    "full_company_cashflow",
    "all_company_payments",
    "supplier_margin",
    "payroll",
    "security_event",
    "role_permissions",
    "runtime_debug",
    "provider_payload",
    "env_secret",
  ] as const,
  directReceiveAllowed: false,
  directIssueAllowed: false,
  directWriteoffAllowed: false,
  directTransferAllowed: false,
  directStockAdjustmentAllowed: false,
  autoApprovalAllowed: false,
  dbWritesFromAiAllowed: false,
  fakeStockAllowed: false,
  fakeIncomingAllowed: false,
  fakeIssueAllowed: false,
  fakeReserveAllowed: false,
  fakeLocationAllowed: false,
  fakeEtaAllowed: false,
  fakeWaybillAllowed: false,
  fakeDocumentsAllowed: false,
});

export function warehouseCanReadSource(type: WarehouseStockSourceType): boolean {
  return WAREHOUSE_ROLE_POLICY.canReadSources.includes(type);
}
