import type { ReferencePriceItem } from "./referencePriceTypes";

const CHECKED_AT = "2026-05-21T00:00:00+06:00";

export const REFERENCE_PRICE_BOOK: ReferencePriceItem[] = [
  {
    id: "flooring.covering.parquet_laminate",
    countryCode: "KG",
    cityOrRegion: "Bishkek",
    currency: "KGS",
    category: "flooring",
    itemRu: "Паркет / ламинат",
    unit: "m2",
    priceMin: 2800,
    priceMax: 2800,
    sourceType: "configured_reference",
    checkedAt: CHECKED_AT,
    requiresReview: true,
  },
  {
    id: "flooring.covering.laminate",
    countryCode: "KG",
    cityOrRegion: "Bishkek",
    currency: "KGS",
    category: "flooring",
    itemRu: "Ламинат",
    unit: "m2",
    priceMin: 1200,
    priceMax: 1800,
    sourceType: "configured_reference",
    checkedAt: CHECKED_AT,
    requiresReview: true,
  },
  {
    id: "flooring.underlay",
    countryCode: "KG",
    cityOrRegion: "Bishkek",
    currency: "KGS",
    category: "flooring",
    itemRu: "Подложка",
    unit: "m2",
    priceMin: 350,
    priceMax: 350,
    sourceType: "configured_reference",
    checkedAt: CHECKED_AT,
    requiresReview: true,
  },
  {
    id: "flooring.plinth",
    countryCode: "KG",
    cityOrRegion: "Bishkek",
    currency: "KGS",
    category: "flooring",
    itemRu: "Плинтус",
    unit: "m",
    priceMin: 220,
    priceMax: 220,
    sourceType: "configured_reference",
    checkedAt: CHECKED_AT,
    requiresReview: true,
  },
  {
    id: "flooring.threshold",
    countryCode: "KG",
    cityOrRegion: "Bishkek",
    currency: "KGS",
    category: "flooring",
    itemRu: "Пороги / стыки",
    unit: "pcs",
    priceMin: 600,
    priceMax: 600,
    sourceType: "configured_reference",
    checkedAt: CHECKED_AT,
    requiresReview: true,
  },
  {
    id: "flooring.consumables",
    countryCode: "KG",
    cityOrRegion: "Bishkek",
    currency: "KGS",
    category: "flooring",
    itemRu: "Расходники для пола",
    unit: "set",
    priceMin: 10000,
    priceMax: 10000,
    sourceType: "configured_reference",
    checkedAt: CHECKED_AT,
    requiresReview: true,
  },
  {
    id: "flooring.work.prep",
    countryCode: "KG",
    cityOrRegion: "Bishkek",
    currency: "KGS",
    category: "flooring",
    itemRu: "Подготовка основания",
    unit: "m2",
    priceMin: 100,
    priceMax: 100,
    sourceType: "configured_reference",
    checkedAt: CHECKED_AT,
    requiresReview: true,
  },
  {
    id: "flooring.work.install",
    countryCode: "KG",
    cityOrRegion: "Bishkek",
    currency: "KGS",
    category: "flooring",
    itemRu: "Укладка покрытия",
    unit: "m2",
    priceMin: 650,
    priceMax: 650,
    sourceType: "configured_reference",
    checkedAt: CHECKED_AT,
    requiresReview: true,
  },
  {
    id: "flooring.work.plinth_install",
    countryCode: "KG",
    cityOrRegion: "Bishkek",
    currency: "KGS",
    category: "flooring",
    itemRu: "Монтаж плинтуса",
    unit: "m",
    priceMin: 180,
    priceMax: 180,
    sourceType: "configured_reference",
    checkedAt: CHECKED_AT,
    requiresReview: true,
  },
  {
    id: "flooring.work.threshold_install",
    countryCode: "KG",
    cityOrRegion: "Bishkek",
    currency: "KGS",
    category: "flooring",
    itemRu: "Установка порогов",
    unit: "pcs",
    priceMin: 500,
    priceMax: 500,
    sourceType: "configured_reference",
    checkedAt: CHECKED_AT,
    requiresReview: true,
  },
  {
    id: "flooring.work.cleanup",
    countryCode: "KG",
    cityOrRegion: "Bishkek",
    currency: "KGS",
    category: "flooring",
    itemRu: "Уборка после работ",
    unit: "set",
    priceMin: 5000,
    priceMax: 5000,
    sourceType: "configured_reference",
    checkedAt: CHECKED_AT,
    requiresReview: true,
  },
  {
    id: "flooring.delivery_lift",
    countryCode: "KG",
    cityOrRegion: "Bishkek",
    currency: "KGS",
    category: "flooring",
    itemRu: "Доставка / подъем",
    unit: "set",
    priceMin: 8000,
    priceMax: 8000,
    sourceType: "configured_reference",
    checkedAt: CHECKED_AT,
    requiresReview: true,
  },
  {
    id: "asphalt.mix_and_laying",
    countryCode: "KG",
    cityOrRegion: "Bishkek",
    currency: "KGS",
    category: "asphalt",
    itemRu: "Асфальтобетонная смесь с укладкой",
    unit: "m2",
    priceMin: 1450,
    priceMax: 1850,
    sourceType: "configured_reference",
    checkedAt: CHECKED_AT,
    requiresReview: true,
  },
  {
    id: "asphalt.base_prep",
    countryCode: "KG",
    cityOrRegion: "Bishkek",
    currency: "KGS",
    category: "asphalt",
    itemRu: "Подготовка основания под асфальт",
    unit: "m2",
    priceMin: 250,
    priceMax: 350,
    sourceType: "configured_reference",
    checkedAt: CHECKED_AT,
    requiresReview: true,
  },
  {
    id: "plaster.mix",
    countryCode: "KG",
    cityOrRegion: "Bishkek",
    currency: "KGS",
    category: "plastering",
    itemRu: "Штукатурная смесь",
    unit: "kg",
    priceMin: 14,
    priceMax: 18,
    sourceType: "configured_reference",
    checkedAt: CHECKED_AT,
    requiresReview: true,
  },
  {
    id: "plaster.work",
    countryCode: "KG",
    cityOrRegion: "Bishkek",
    currency: "KGS",
    category: "plastering",
    itemRu: "Штукатурные работы",
    unit: "m2",
    priceMin: 380,
    priceMax: 520,
    sourceType: "configured_reference",
    checkedAt: CHECKED_AT,
    requiresReview: true,
  },
  {
    id: "drywall.sheet",
    countryCode: "KG",
    cityOrRegion: "Bishkek",
    currency: "KGS",
    category: "drywall",
    itemRu: "ГКЛ 12.5 мм",
    unit: "pcs",
    priceMin: 430,
    priceMax: 560,
    sourceType: "configured_reference",
    checkedAt: CHECKED_AT,
    requiresReview: true,
  },
];
