import {
  compareSuppliersInputSchema,
  compareSuppliersOutputSchema,
  draftActInputSchema,
  draftActOutputSchema,
  draftReportInputSchema,
  draftReportOutputSchema,
  draftRequestInputSchema,
  draftRequestOutputSchema,
  getActionStatusInputSchema,
  getActionStatusOutputSchema,
  getFinanceSummaryInputSchema,
  getFinanceSummaryOutputSchema,
  getWarehouseStatusInputSchema,
  getWarehouseStatusOutputSchema,
  searchCatalogInputSchema,
  searchCatalogOutputSchema,
  submitForApprovalInputSchema,
  submitForApprovalOutputSchema,
} from "../schemas/aiToolSchemas";
import type { AiToolDefinition, AiToolName } from "./aiToolTypes";

export const AI_TOOL_NAMES: readonly AiToolName[] = [
  "search_catalog",
  "compare_suppliers",
  "get_warehouse_status",
  "get_finance_summary",
  "draft_request",
  "draft_report",
  "draft_act",
  "submit_for_approval",
  "get_action_status",
];

export const AI_TOOL_REGISTRY: readonly AiToolDefinition[] = [
  {
    name: "search_catalog",
    description: "Search marketplace catalog materials and return redacted evidence references.",
    domain: "marketplace",
    riskLevel: "safe_read",
    inputSchema: searchCatalogInputSchema,
    outputSchema: searchCatalogOutputSchema,
    requiredRoles: ["director", "control", "buyer"],
    approvalRequired: false,
    idempotencyRequired: false,
    auditEvent: "ai.action.allowed",
    rateLimitScope: "marketplace.catalog.search",
    cacheAllowed: true,
    evidenceRequired: true,
  },
  {
    name: "compare_suppliers",
    description: "Compare supplier options without choosing or confirming a supplier.",
    domain: "marketplace",
    riskLevel: "safe_read",
    inputSchema: compareSuppliersInputSchema,
    outputSchema: compareSuppliersOutputSchema,
    requiredRoles: ["director", "control", "buyer"],
    approvalRequired: false,
    idempotencyRequired: false,
    auditEvent: "ai.action.allowed",
    rateLimitScope: "ai.tool.compare_suppliers",
    cacheAllowed: false,
    evidenceRequired: true,
  },
  {
    name: "get_warehouse_status",
    description: "Read scoped warehouse availability and movement status summaries.",
    domain: "warehouse",
    riskLevel: "safe_read",
    inputSchema: getWarehouseStatusInputSchema,
    outputSchema: getWarehouseStatusOutputSchema,
    requiredRoles: ["director", "control", "foreman", "buyer", "warehouse"],
    approvalRequired: false,
    idempotencyRequired: false,
    auditEvent: "ai.action.allowed",
    rateLimitScope: "ai.tool.get_warehouse_status",
    cacheAllowed: false,
    evidenceRequired: true,
  },
  {
    name: "get_finance_summary",
    description: "Read scoped debt, payment, and document aggregates without raw finance rows.",
    domain: "finance",
    riskLevel: "safe_read",
    inputSchema: getFinanceSummaryInputSchema,
    outputSchema: getFinanceSummaryOutputSchema,
    requiredRoles: ["director", "control", "accountant"],
    approvalRequired: false,
    idempotencyRequired: false,
    auditEvent: "ai.action.allowed",
    rateLimitScope: "ai.tool.get_finance_summary",
    cacheAllowed: false,
    evidenceRequired: true,
  },
  {
    name: "draft_request",
    description: "Prepare a request draft for human review without submitting it.",
    domain: "procurement",
    riskLevel: "draft_only",
    inputSchema: draftRequestInputSchema,
    outputSchema: draftRequestOutputSchema,
    requiredRoles: ["director", "control", "foreman", "buyer", "warehouse"],
    approvalRequired: false,
    idempotencyRequired: false,
    auditEvent: "ai.action.draft_created",
    rateLimitScope: "ai.tool.draft_request",
    cacheAllowed: false,
    evidenceRequired: true,
  },
  {
    name: "draft_report",
    description: "Prepare a report draft for human review without final submission.",
    domain: "reports",
    riskLevel: "draft_only",
    inputSchema: draftReportInputSchema,
    outputSchema: draftReportOutputSchema,
    requiredRoles: ["director", "control", "foreman", "buyer", "accountant", "warehouse", "contractor", "office", "admin"],
    approvalRequired: false,
    idempotencyRequired: false,
    auditEvent: "ai.action.draft_created",
    rateLimitScope: "ai.tool.draft_report",
    cacheAllowed: false,
    evidenceRequired: true,
  },
  {
    name: "draft_act",
    description: "Prepare an act draft from scoped subcontract evidence without sending it.",
    domain: "subcontracts",
    riskLevel: "draft_only",
    inputSchema: draftActInputSchema,
    outputSchema: draftActOutputSchema,
    requiredRoles: ["director", "control", "foreman", "contractor"],
    approvalRequired: false,
    idempotencyRequired: false,
    auditEvent: "ai.action.draft_created",
    rateLimitScope: "ai.tool.draft_act",
    cacheAllowed: false,
    evidenceRequired: true,
  },
  {
    name: "submit_for_approval",
    description: "Submit a prepared draft to the approval gate without executing the final mutation.",
    domain: "documents",
    riskLevel: "approval_required",
    inputSchema: submitForApprovalInputSchema,
    outputSchema: submitForApprovalOutputSchema,
    requiredRoles: ["director", "control", "foreman", "buyer", "accountant", "warehouse", "contractor", "office", "admin"],
    approvalRequired: true,
    idempotencyRequired: true,
    auditEvent: "ai.action.approval_required",
    rateLimitScope: "ai.tool.submit_for_approval",
    cacheAllowed: false,
    evidenceRequired: true,
  },
  {
    name: "get_action_status",
    description: "Read approval or action status using redacted evidence references.",
    domain: "documents",
    riskLevel: "safe_read",
    inputSchema: getActionStatusInputSchema,
    outputSchema: getActionStatusOutputSchema,
    requiredRoles: ["director", "control", "foreman", "buyer", "accountant", "warehouse", "contractor", "office", "admin"],
    approvalRequired: false,
    idempotencyRequired: false,
    auditEvent: "ai.policy.checked",
    rateLimitScope: "ai.tool.get_action_status",
    cacheAllowed: false,
    evidenceRequired: true,
  },
];

export function listAiToolDefinitions(): AiToolDefinition[] {
  return [...AI_TOOL_REGISTRY];
}

export function getAiToolDefinition(name: AiToolName): AiToolDefinition | null {
  return AI_TOOL_REGISTRY.find((tool) => tool.name === name) ?? null;
}
