import type { DirectorCompanySourceType } from "./directorCompanyTypes";

export const DIRECTOR_ROLE_POLICY = {
  role: "director",
  canQueryAllBusinessDomains: true,
  allowedBusinessDomains: [
    "field",
    "procurement",
    "marketplace",
    "warehouse",
    "finance",
    "documents",
    "reports",
    "office",
    "approvals",
    "security_summary",
  ] as const,
  allowedSources: [
    "work",
    "object",
    "contractor",
    "procurement_request",
    "supplier_offer",
    "marketplace_offer",
    "warehouse_stock",
    "warehouse_incoming",
    "warehouse_issue",
    "payment",
    "invoice",
    "act",
    "cashflow",
    "document",
    "pdf_chunk",
    "report",
    "approval",
    "chat_message",
    "office_task",
    "security_summary",
  ] satisfies DirectorCompanySourceType[],
  canSeeRawRuntime: false,
  canSeeRawSecurityEvents: false,
  canSeeRawSecrets: false,
  canSeeServiceRoleKeys: false,
  canSeeProviderPayloads: false,
  directApproveRejectAllowed: false,
  directPaymentAllowed: false,
  directOrderAllowed: false,
  directStockMutationAllowed: false,
  directWorkCloseAllowed: false,
  directSigningAllowed: false,
  finalSubmitAllowed: false,
  rolePolicyMutationAllowed: false,
  dbWritesFromAiAnswerAllowed: false,
  autoApprovalAllowed: false,
  fakeCompanyDataAllowed: false,
  forbiddenNormalUserCopy: [
    "safe_read",
    "draft_only",
    "approval_required",
    "provider",
    "runtime",
    "transport",
    "mutation",
    "service_role",
    "raw payload",
    "debug",
    "generic fallback",
  ],
} as const;

export type DirectorRolePolicy = typeof DIRECTOR_ROLE_POLICY;
