import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

import { isTimeoutOrMemoryWeakeningDiffLine } from "./noTestWeakeningPolicy";

const BASE_CHECKPOINT = "e4daae88344f3f8f07e943701df5529aa9c64b74";
const USER_OWNED_TEST_PATHS = new Set([
  "tests/e2e/androidDeepLinkLaunchContract.contract.test.ts",
]);
const GUARDED_FIXTURES = [
  "tests/fixtures/aiPlatform/eval/aiEstimateGoldenEvalCases.json",
  "tests/fixtures/estimate/productionGradeWebAndroidCriticalCases.json",
] as const;
const REVIEWED_GUARDED_FIXTURE_CHANGES: Readonly<Record<string, {
  base_blob: string;
  reviewed_blob: string;
  production_reason: string;
  proof_coverage_not_reduced: string;
}>> = {
  "tests/fixtures/aiPlatform/eval/aiEstimateGoldenEvalCases.json": {
    base_blob: "b6f0e6b69318312c2604f24343b7a9ebebe7a8a6",
    reviewed_blob: "c4ccc9d173a34a0a43ef102a07c6cfeb62c92ec1",
    production_reason: "make every road golden request explicitly select the complete road-structure scope instead of relying on a forbidden implicit default",
    proof_coverage_not_reduced: "all 700 cases and their expected outputs remain present; only the 35 road prompts are strengthened with explicit base-course and two-layer asphalt evidence",
  },
  "tests/fixtures/estimate/productionGradeWebAndroidCriticalCases.json": {
    base_blob: "72bfbeddc03b040e3310f6d1415eabecb148bac3",
    reviewed_blob: "f6465ef8908e4ee2bec9f17da265d317e17e0623",
    production_reason: "keep the exact canonical work identities and require the electrical runtime case to provide an explicit object, route length and separate outlet, switch and lighting-point quantities",
    proof_coverage_not_reduced: "the fixture remains exactly 100 cases across all ten coverage groups; the reviewed blob retains every prior exact family and unit assertion while strengthening the electrical case from area-only input to a complete dimensional basis that the canonical compiler can approve",
  },
};

type TestContractAuditEntry = {
  path: string;
  old_expectation: string;
  new_expectation: string;
  production_reason: string;
  proof_coverage_not_reduced: string;
};

function entry(
  pathValue: string,
  oldExpectation: string,
  newExpectation: string,
  productionReason: string,
  proof: string,
): TestContractAuditEntry {
  return {
    path: pathValue,
    old_expectation: oldExpectation,
    new_expectation: newExpectation,
    production_reason: productionReason,
    proof_coverage_not_reduced: proof,
  };
}

const HONEST_STOP_MIGRATION_TEST_PATHS = [
  "tests/estimateAcceptance/blackboxNoGenericFallback.contract.test.ts",
  "tests/estimateBackfill/autonomousPriorityPlan.contract.test.ts",
  "tests/estimateBackfill/catalogBackfillBatches.contract.test.ts",
  "tests/estimateBackfill/selectNextProfessionalEstimateBatch.contract.test.ts",
  "tests/estimateCatalog/professionalCatalogCoverage.contract.test.ts",
  "tests/estimateNPlus/productionTrustNPlusPrecondition.contract.test.ts",
  "tests/estimateNorms/baseCatalogWrongUnitsRemediation.test.ts",
  "tests/estimateNorms/estimate10000ReadinessManifest.contract.test.ts",
  "tests/estimateNorms/expanded1610ProfessionalBoqSeal.test.ts",
  "tests/estimateNorms/productionGradeBackendLayers.test.ts",
  "tests/estimateNorms/professionalBoqTruthAudit10000.test.ts",
  "tests/estimateNorms/wave2aStructuralNormPacksAudit.contract.test.ts",
  "tests/estimateReadiness/all10000ReadyProfessional.contract.test.ts",
  "tests/estimateReadiness/noGenericFallback10000.contract.test.ts",
  "tests/estimateReadiness/noP0GenericFallback.contract.test.ts",
  "tests/estimateReadiness/noP0SyntheticFamilyDefault.contract.test.ts",
  "tests/estimateReadiness/noReadyFromGenericSource.contract.test.ts",
  "tests/estimateReadiness/p0CriticalBatchReady.contract.test.ts",
  "tests/estimateReadiness/professionalReadinessAudit.contract.test.ts",
  "tests/estimateReadiness/readinessCountsImprove.contract.test.ts",
  "tests/estimateReality/functionalRealityAuditStop.contract.test.ts",
  "tests/estimateReality/renderedSnapshots10000.contract.test.ts",
  "tests/estimateTruthAudit/noGenericFallback10000.contract.test.ts",
  "tests/estimateTruthAudit/noSyntheticFamilyDefault10000.contract.test.ts",
  "tests/estimateTruthAudit/professionalInventory10000.contract.test.ts",
  "tests/estimateTruthAudit/templateProfessionalReadiness.contract.test.ts",
] as const;

const HONEST_STOP_MIGRATION_TEST_CONTRACT_AUDIT: readonly TestContractAuditEntry[] =
  HONEST_STOP_MIGRATION_TEST_PATHS.map((testPath) =>
    entry(
      testPath,
      "structurally compiled or catalog-prefixed rows were asserted as fully professional across 10000/11610 templates",
      "the same full corpus and positive BOQ/PDF/buyer invariants remain exact while unregistered norm sources produce explicit STOP counters and blockers",
      "separate mechanical completeness from independently verified formula, norm, unit and price readiness",
      "no test is skipped or removed; exact 10000/11610 template, 599000-row and P0/P1/P2/P3 batch sizes remain asserted, with additional no-fake-green and blocker assertions",
    )
  );

export const CURRENT_CORE_TEST_CONTRACT_AUDIT: readonly TestContractAuditEntry[] = [
  ...HONEST_STOP_MIGRATION_TEST_CONTRACT_AUDIT,
  entry("src/components/map/leafletWebCss.test.ts", "double-cast partial Document fixture", "typed minimal CSS document adapter", "remove an unsafe test cast while matching the production dependency boundary", "the same two calls still assert exactly one stylesheet insertion and exact id, rel and href"),
  entry("src/features/ai/assistantStorage.test.ts", "double-cast AsyncStorage mock", "structurally typed AsyncStorage mock", "remove an unsafe test cast without changing storage behavior", "bounded retention, expiry envelope, clear behavior and foreman snapshot trimming assertions are unchanged"),
  entry("src/lib/ai_reports.test.ts", "double-cast Supabase from mock", "typed Jest module mock", "remove an unsafe test cast and retain the real transport chain", "the exact select and rik_code filter remain asserted and the removed company_id filter remains forbidden"),
  entry("src/lib/crossStorage.test.ts", "double-cast AsyncStorage mock", "structurally typed AsyncStorage mock", "remove an unsafe test cast without changing persistence semantics", "protected envelope, legacy plaintext, safe parse and circular stringify assertions are unchanged"),
  entry("src/lib/consumerRequests/consumerRequestPdfStorage.web.test.ts", "web request PDFs had no resource-lifetime or prewarm contract", "upload creates one stable Blob URL, repeated opens reuse it and storage deletion revokes it", "remove base64 encode/decode from the PDF-open critical path with explicit storage ownership", "adds positive reuse and cleanup assertions without replacing signed expiry or binary validation coverage"),
  entry("src/lib/estimatePdf/generatedPdfViewerFile.test.ts", "the viewer session retained a multi-megabyte data URI and concurrent opens could create duplicate immutable assets", "the same route carries only session identity, uses one session-owned Blob URL through single-flight, and changes identity on snapshot drift", "keep large PDF bytes out of navigation while proving concurrent reuse and immutable revision invalidation", "retains the no-URI/blob-ownership assertions and adds concurrent equality plus changed-snapshot inequality"),
  entry("src/lib/pdf/pdfViewerWebRenderUriCleanup.test.ts", "the viewer revoked every blob URI regardless of owner", "only explicitly viewer-owned blobs are revocable; storage/session-owned blobs survive render cleanup", "prevent rerenders from invalidating prewarmed document assets", "retains platform, scheme and unmount-state coverage and adds a negative external-ownership assertion"),
  entry("src/lib/pdf/pdfViewerWebFramePool.test.ts", "warm PDF navigation destroyed and recreated the browser plugin for the same immutable Blob", "a three-entry LRU/TTL render pool remounts the exact loaded iframe and releases evicted frames", "remove browser plugin teardown from unchanged-revision warm opens without unbounded iframe retention", "retains exact DOM identity and loaded-state reuse while adding hard maximum and eviction-release coverage"),
  entry("src/lib/documents/pdfWebPreviewCache.test.ts", "short PDF routes became unrecoverable when memory was recreated and cache ownership was not principal-scoped", "the immutable asset is restored only for the active tenant/company/user/session identity, every revision field participates in the key, and lifecycle purge removes IndexedDB access", "preserve reload recovery without cross-user/company leakage or stale revision reuse", "retains memory-loss and byte-reuse coverage and adds cross-principal rejection, logout purge, and nine independent cache-key mutation assertions"),
  entry("src/lib/session/sessionBoundary.test.ts", "logout cleanup did not own the new browser PDF cache, frame pool, generated-session map, or storage Blob URLs", "the centralized session boundary clears all four PDF runtime owners before document sessions and persistent app cache", "make logout and company-boundary reset revoke every browser PDF access path", "retains all prior cleaner assertions and adds exact calls for the four PDF lifecycle cleaners"),
  entry("tests/consumerRepair/consumerEstimatePdfOpen.contract.test.ts", "the PDF open contract covered access but not repeated generation", "two opens of one unchanged request revision retain one identical PDF record", "enforce warm-open immutable reuse at the service boundary", "retains signed-access assertions and adds exact identity plus generation-count coverage"),
  entry("tests/architecture/requestStateNoDuplicateDraftLogic.contract.test.ts", "the adapter boundary named the always-generate PDF command", "the adapter boundary now requires the revision-aware ensure/reuse command", "preserve one service owner while removing repeated PDF generation", "changes only the required service symbol; duplicate-draft prohibitions remain"),
  entry("tests/architecture/requestStateDoesNotReplacePdfRenderer.contract.test.ts", "the renderer boundary named the always-generate PDF command", "the renderer boundary now requires the revision-aware ensure/reuse command", "keep rendering outside request state while enabling immutable reuse", "all prohibitions on screen-local or replacement PDF renderers remain"),
  entry("tests/architecture/requestEstimateDoesNotBreakLegacyPdf.contract.test.ts", "the legacy lifecycle contract named the always-generate PDF command", "the legacy lifecycle contract now requires the revision-aware ensure/reuse command", "retain the same PDF service and viewer route with a faster open policy", "viewer-route and shared-renderer assertions remain unchanged"),
  entry("tests/architecture/pdfArchAuditNoScreenLocalPdfLayout.contract.test.ts", "the PDF architecture audit named the always-generate command", "the audit now requires the revision-aware ensure/reuse command", "keep screen components free of PDF layout while reusing immutable output", "all screen-local renderer prohibitions remain unchanged"),
  entry("tests/architecture/entrypointFixDoesNotReplacePdfRenderer.contract.test.ts", "the entrypoint audit named the always-generate command", "the audit now requires the revision-aware ensure/reuse command", "preserve the existing lifecycle across the faster entrypoint", "third-party renderer prohibitions remain unchanged"),
  entry("tests/architecture/consumerEstimateNoOfficeLeak.contract.test.ts", "the isolation contract named the always-generate command", "the isolation contract now requires the revision-aware ensure/reuse command", "retain consumer-only ownership while eliminating repeated generation", "all Office/B2B leak prohibitions remain unchanged"),
  entry("tests/performance/asphaltPdfPerformance.contract.test.ts", "Asphalt Reference V1 had row-parity tests but no PDF cold/warm budget or parser-independent FlateDecode proof", "54-row and 702-row immutable revisions retain budgets while a separate Node process parses compressed bytes with pdfjs and matches every 54-row UI title", "prevent slow/repeated/corrupt PDF work while proving Russian text, row parity, and exact revision binding outside the in-process validator", "retains both canonical performance scopes and adds external-parser, FlateDecode, Cyrillic, row-title and revision-hash assertions"),
  entry("tests/pdf/estimatePdfValidBinary.contract.test.ts", "binary validation covered base64 data URIs but not raw PDF binary strings containing bytes above ASCII", "raw compressed PDF strings must round-trip every byte from 0 through 255 without UTF-8 expansion", "seal the storage-to-validator binary boundary that corrupted FlateDecode streams", "retains the real data-URI PDF assertion and adds a byte-exact raw-string regression without removing or relaxing any validation"),
  entry("tests/e2e/asphaltReferenceV1PdfPerformance.web.spec.ts", "the PDF service budget had no browser proof for tap feedback, first page, reload recovery or repeat navigation", "Chromium measures 54/702 cold and warm first-page latency, sub-100ms feedback, exact-route IndexedDB recovery and zero console/page errors", "seal the real user-visible PDF path and prevent memory-only sessions or repeated generation from returning", "adds browser timing and reload evidence without replacing service identity, row-parity or immutable-storage contracts"),
  entry("src/lib/developerOverride.test.ts", "localhost or native development could open override without explicit opt-in", "explicit opt-in is required together with local, development or internal runtime proof", "keep temporary developer access while production remains fail-closed", "adds production denial and opt-in checks while retaining local web, native dev, internal channel and automation coverage"),
  entry("src/lib/estimate/v4/asphalt/roadScopeTruthV4.test.ts", "non-road template word collision was uncovered", "drawings inside a non-road ID must remain NOT_ROAD", "road intent is determined from semantic subject, not incidental substrings", "adds a negative resolver case"),
  entry("src/lib/exports/xlsxExport.test.ts", "mocked third-party xlsx runtime", "deterministic bounded OOXML without formulas, macros or external links", "remove vulnerable universal parser from runtime", "adds archive determinism, malicious payload and bounds checks"),
  entry("src/lib/filePick.test.ts", "minimal detached input mock", "DOM-attached input lifecycle mock", "match the production browser file-pick lifecycle", "same user behavior plus cleanup coverage"),
  entry("src/lib/observability/console.governance.test.ts", "Jasmine global fail helper", "portable thrown Error", "Jest runtime no longer exposes the legacy helper consistently", "violation scan and failure semantics are unchanged"),
  entry("src/lib/supabaseClient.test.ts", "single concatenated logger argument", "structured logger prefix and message arguments", "match governed logger ownership", "warning text and once-only behavior remain asserted"),
  entry("src/screens/profile/AddListingScreen.contract.test.ts", "two-destination single-line ternary", "seller, my-listings and market return destinations", "the add-listing flow now preserves its exact entry destination", "adds the third governed return route while retaining seller and market coverage"),
  entry("src/screens/profile/addListingCatalogItem.contract.test.ts", "catalog item construction lived inside the screen without an owner contract", "pure catalog-item owner preserves identity, unit, kind and city precedence", "decompose AddListingScreen without changing listing semantics", "adds exact deterministic output coverage for the extracted owner"),
  entry("src/screens/profile/addListingCoordinates.contract.test.ts", "location permission and coordinate validation lived inside the screen", "injected coordinate gateway fails closed and accepts only finite coordinates", "make permission and sensor failure behavior independently testable", "adds denied, valid and non-finite coordinate cases"),
  entry("src/screens/profile/addListingNavigation.contract.test.ts", "return-route ternary lived inside the screen", "typed navigation owner covers seller, my-listings and market", "preserve deep-link return ownership after decomposition", "adds exact assertions for every supported destination"),
  entry("src/screens/profile/addListingProjection.contract.test.ts", "instant listing projection lived inside the screen", "pure projection owner preserves catalog, seller, media and numeric semantics", "separate view orchestration from market domain projection", "adds exact normalized price, quantity, identity and image assertions"),
  entry("src/screens/profile/addListingSubmission.contract.test.ts", "coordinate lookup, mutation and instant caches were coupled inside the screen", "submission owner has injected gateways and explicit coordinate failure result", "make the publish transaction independently verifiable", "adds a negative no-mutation case and exact dual-cache success coverage"),
  entry("src/screens/profile/addListingValidation.contract.test.ts", "validation rules lived inside the screen", "pure validation owner rejects incomplete input and parses positive decimal prices", "separate form policy from UI orchestration", "adds malformed-field, locale decimal, zero and nonnumeric negative cases"),
  entry("src/screens/profile/hooks/useAddListingOwners.contract.test.ts", "owner loading and form state were embedded in AddListingScreen", "source contract requires dedicated form and owner-context hooks", "enforce real responsibility boundaries below the 500-line component limit", "requires both owner hooks and forbids the extracted services in the screen"),
  entry("tests/ai/assistantClientModelGatewayMigration.contract.test.ts", "assistantClient was required to import AiModelGateway directly", "assistantClient uses ServerAiModelProvider and the provider owns AiModelGateway", "enforce the canonical AI platform provider boundary", "still forbids legacy Gemini and requestAiGeneratedText while additionally proving both chain links"),
  entry("tests/aiEstimateV4/catalogProfessionalCoverageLedgerV4.contract.test.ts", "no honest 11610 corpus classification ledger", "exact 12/7152/1288/3158 classification", "prevent technical templates from being promoted to passports", "adds exact totals, uniqueness, ownership and unresolved-input checks"),
  entry("tests/aiEstimateV4/estimateRevisionAsyncStorageFallback.contract.test.ts", "native durable storage eagerly required ExpoSQLite even when the installed binary did not contain that optional native module", "capability selection keeps SQLite when available and otherwise uses an immutable-envelope AsyncStorage backend with a single pointer commit point", "preserve durable 702-row revisions across native binary migration without rebuilding the protected API34 APK or falling back to volatile memory", "adds pre-commit crash recovery, post-commit interruption, exact read-back, per-draft writer serialization and CAS-conflict assertions; all existing SQLite, IndexedDB and large-road failure-recovery suites remain unchanged"),
  entry("tests/aiEstimateV4/roadFullRevisionDurableFailureRecoveryV4.contract.test.ts", "the browser-storage compatibility fixture relied on the Jest host platform implicitly", "the fixture explicitly selects web and restores Platform.OS after every test", "keep localStorage compatibility coverage behind the same explicit platform boundary used in production", "all 702-row R1/R2, quota and 12 controlled failure assertions remain unchanged and pass with exact platform cleanup"),
  entry("tests/aiEstimateV4/estimateRevisionSafeJsonBoundary.contract.test.ts", "durable envelope parsing had no malformed or size mutation matrix", "checksum-valid input passes while malformed, truncated, primitive, wrong-version, corrupted and oversized payloads fail closed", "bound durable JSON before checksum and parse in UTF-8 bytes", "adds eleven positive and negative read/write boundary assertions without removing recovery coverage"),
  entry("tests/app/office-index-route-scope.test.tsx", "brittle receipt projection harness", "exact route consumes and clears receipt", "verify the real route ownership boundary", "assertions cover both projection and one-time consumption"),
  entry("tests/architecture/aiEstimateArchitectureFitnessMatrix.contract.test.ts", "opaque status mismatch", "same matrix assertions with diagnostic payload", "make failures actionable without changing a threshold", "1000/1000, 200/200 and 100/100 remain exact"),
  entry("tests/architecture/architectureAntiRegressionSuite.test.ts", "component debt fixture asserted only file, line and hook counts and AI ownership stopped at a direct gateway import", "fixture asserts all eight component metrics and the AI test proves assistant-to-platform-provider-to-gateway ownership", "keep the unit contract aligned with the strengthened live architecture scanner", "exact equality remains in place and five component metrics plus the provider chain are added"),
  entry("tests/architecture/allRoutesHaveErrorBoundary.contract.test.ts", "53 exact routes", "54 exact routes", "route inventory gained one governed route", "boundary equality remains exact and the inventory count increases"),
  entry("tests/architecture/consumerRepairRequestScreenSingleCanonicalChrome.contract.test.ts", "sent or approved always opened the existing PDF", "only a finalized current revision opens the existing PDF", "an edited finalized request needs a fresh PDF and approval", "retains both PDF actions and adds stale-revision protection"),
  entry("tests/architecture/globalLocalAndroidApi34Smoke.contract.test.ts", "obsolete visible-line component strings", "current editable row and top-proof semantic anchors", "follow canonical request presentation ownership", "requires row count, editable status and representative visible lines"),
  entry("tests/architecture/godComponentsDecomposition.contract.test.ts", "scanner GREEN did not prove the physical AddListingScreen boundary", "AddListingScreen must be below 500 physical and callable meaningful lines with all metrics present", "prevent formatter or StyleSheet accounting from hiding a real monolith", "adds exact live-scanner metric presence and two unchanged 500-line thresholds"),
  entry("tests/architecture/transportOwnershipMap.test.ts", "70 owners including deleted xlsx loader", "69 live transport owners", "unsafe xlsx transport owner was removed", "owner map still equals the complete live transport inventory"),
  entry("tests/boqDepth/masonryDepth.contract.test.ts", "masonry depth assertion accepted eight or more rows", "masonry compiler must return exactly 75 governed rows", "seal the current professional masonry BOM/WBS depth against truncation", "changes a lower bound into exact equality at a substantially higher row count"),
  entry("tests/boqDepth/professionalDocumentationPackage.contract.test.ts", "professional depth coverage did not independently reject procurement materials fabricated from as-built documentation", "as-built documentation is exactly one governed labor set with no material projection and valid unit/depth semantics", "keep documentation ownership in labor and out of procurement", "adds a negative material-row assertion plus exact section, unit, quantity, trace, unit-semantics and depth validation"),
  entry("tests/boqDepth/professionalWbsNoPadding.contract.test.ts", "generic WBS metadata checks", "mini-CHP phase-by-phase applicability and governance", "prove depth comes from plant systems rather than row padding", "adds exact 20 phases, five roles, formulas, sources and procurement flags"),
  entry("tests/consumerRepair/approvedHistoryDurableStorageMigration.contract.test.ts", "hard-coded 500-row assumptions", "large revisions use durable storage and compact revisions remain local", "exercise the actual transactional size boundary", "adds recovery, failure injection and edited-row parity"),
  entry("tests/consumerRepair/approvedHistoryReloadPersistence.contract.test.ts", "the reload fixture relied on the Jest host platform implicitly", "the fixture explicitly selects web and restores Platform.OS during cleanup", "prove browser persistence without allowing native execution to touch localStorage", "the same approved-history reload identity and persistence assertions remain exact"),
  entry("tests/consumerRepair/nativeDurableStoragePlatformBoundary.contract.test.ts", "native hydration had no hostile web-global or per-draft failure boundary proof", "Android hydration runs with a throwing localStorage getter and isolates a corrupt draft from a healthy draft", "guarantee native code never touches browser storage and one bad record cannot hide the rest", "adds zero-access and independent-recovery assertions without skipping or replacing any durability test"),
  entry("tests/consumerRepair/nativeDurableStorageStartupUi.contract.test.tsx", "the request route rendered an empty fragment until unbounded hydration completed", "the real request screen mounts immediately and a three-second bound exposes a working recovery action", "keep navigation and draft creation responsive while native persistence recovers asynchronously", "adds immediate-screen, bounded recovery, repeat-attempt and successful hydration-refresh assertions"),
  entry("tests/consumerRepair/durableQuantityEditTransaction.contract.test.ts", "expected raw internal trace toggle in row UI", "internal trace is absent from editable public row", "internal identifiers are projected through sanitized summary/PDF owners", "structured trace persistence and sanitized projection remain covered elsewhere"),
  entry("tests/architecture/androidAppRootReadyMarkerCanonicalReplay.contract.test.ts", "the replay accepted a generic embedded-AI route or prior history surface before proving the current launch payload, and consecutive warm launches could reuse the prior assistant instance", "AI replay keeps its two governed URI candidates but accepts one only after authenticated route readiness plus current loading or response evidence; each new launchId remounts the assistant", "prevent a static foreman/history screen from blocking the working fallback or masquerading as a submitted current estimate", "adds positive current-loading/current-response and negative history-only readiness assertions plus the launchId remount contract while retaining every route, auth and fake-artifact prohibition"),
  entry("tests/e2e/androidHarnessInputText.contract.test.ts", "the canonical replay could accept a static AI history route before launch application and scroll past a progressively rendered request estimate without activating its visible load-more control", "canonical replay requires current AI loading/response before accepting an URI candidate and activates the stable request load-more resource before its bounded swipes", "make exact API34 proof reach the applied prompt and complete request/assistant output instead of accepting static panels or only the first rendered row page", "retains every bounded attempt, timeout, ANR, blank-screen, adb argument, four-domain threshold and existing 6+8 capture budget; adds fail-closed current-launch readiness and load-more assertions"),
  entry("tests/e2e/androidApi34ProofEnvironment.contract.test.ts", "hard-coded work tokens, an obsolete eager AI-screen import shape and a request remount key that ignored exact draft identity", "semantic BOQ anchors plus the actual lazy route, bounded Suspense fallback, readiness marker chain and a draftId/prompt/mode remount identity", "separate route readiness from chunk implementation while retaining visible Android proof and exact-draft isolation", "requires semantic anchors, representative domain tokens, the real lazy screen consumer, its fallback, the embedded-AI readiness marker and both draftId and prompt route identities"),
  entry("tests/estimateArchitecture/noSplitBrainEstimateEngine.contract.test.ts", "synthetic family fallback was tolerated", "synthetic family fallback must be zero", "canonical family ownership is now complete", "strictly strengthens the architecture gate"),
  entry("tests/estimateAcceptance/blackboxPromptToSnapshot.contract.test.ts", "530-case blackbox treated generic catalog evidence as 10000 professional norm packs", "the same corpus must report the exact 0/10000 normative deficit, 523 blocked cases and a typed STOP", "keep functional corpus execution distinct from independently registered normative provenance", "all 530 cases and 500 random cases remain required, every family remains represented, mutation gates must pass, manual GREEN stays forbidden and representative norm-source blockers are asserted"),
  entry("tests/estimateAcceptance/blackboxBuyerHandoff.contract.test.ts", "all 530 buyer projections were treated as approved source-backed quantities", "all projections retain exact procurement parity while only 7 proven cases can create revisions/director payloads and 523 remain blocked", "separate a deterministic buyer projection from authorization to approve unverified quantities", "keeps all 530 cases, exact 526 row-bearing cases, subset parity and no-generated-price assertions while adding exact proven/blocked authorization counts"),
  entry("tests/estimateAcceptance/blackboxHistoricalBrokenCases.contract.test.ts", "all ten historical cases were called professional", "seven specialist outcomes remain proven while the three 59-row catalog estimates are explicitly blocked", "preserve historical specialist fixes without promoting unregistered masonry, screed and reinforcement norms", "retains every exact specialist template and missing-parameter assertion and adds exact identities/counts for both trust partitions"),
  entry("tests/estimateAcceptance/blackboxNoBlindQuantityCopy.contract.test.ts", "formula provenance and normative-source proof were collapsed into one quantity blocker", "all 530 formula-backed cases pass the blind-copy dimension while only 7 independently sourced cases can create artifacts and 523 remain source-blocked", "keep formula trace and normative trust independent without promoting catalog-derived sources", "keeps the 530-case corpus, exact 7/523 artifact partition, formula traces and confirmation requirements while asserting the precise source blocker and absence of a false blind-copy blocker"),
  entry("tests/estimateAcceptance/blackboxPdfSnapshotParity.contract.test.ts", "PDF parity was conflated with complete normative provenance", "all 530 PDFs retain row/text parity while exactly 7 cases have proven norm sources and 523 expose the deficit", "separate deterministic rendering from source trust", "keeps generation, extraction, exact row parity, formula trace and mojibake assertions and adds exact source partitions"),
  entry("tests/estimateBackfill/catalogBackfillBatches.contract.test.ts", "95 concrete/electrical templates were counted as transport", "exact corrected P1/P2 counts and zero misclassified templates", "family classification follows construction domain ownership", "adds a semantic regression assertion in addition to exact counts"),
  entry("tests/estimateCalculator/familyMaterialSlotPolicies.test.ts", "selected a fence case that did not explicitly request a gate", "gate scenario explicitly asks for a 4 m gate", "test optional material applicability, not resolver ambiguity", "the paired no-gate assertion still proves absence when not requested"),
  entry("tests/estimateCalculator/concreteP0.contract.test.ts", "all 59 catalog rows were called source-backed professional norms", "the exact 3 registered norm rows are separated from 56 unregistered catalog rows and readiness remains blocked", "preserve volume/formula/procurement mechanics without promoting catalog references to normative evidence", "adds exact total and registered counts while retaining source token, units, formula and buyer assertions"),
  entry("tests/estimateCalculator/electricalP0.contract.test.ts", "all 63 catalog rows were called source-backed professional norms", "the exact zero registered norm rows are reported and readiness remains blocked", "preserve electrical formula/procurement mechanics without promoting catalog references to normative evidence", "adds exact total and registered counts while retaining source token, units, formula and buyer assertions"),
  entry("tests/requestEstimate/electricalBlockingUnifiedUi.contract.test.tsx", "an area-only electrical request could expose a legacy priced estimate and leave the shared parameter editor closed", "the canonical request remains rowless and unpriced until all five quantitative scope fields are supplied, opens the shared editor, and exposes one formation action without a duplicate composer", "prevent a partial electrical prompt from looking contract-ready and keep the estimate interaction identical across work types", "adds negative legacy-row, price, total, approval and duplicate-composer assertions together with positive shared-editor and action-label assertions; no existing UI case is removed or skipped"),
  entry("tests/requestEstimate/electricalBoqIntegrityV1.contract.test.ts", "electrical row depth had no dedicated duplicate-identity, double-count or procurement-applicability gate", "the canonical BOQ rejects duplicate semantic identities, repeated aggregate cable accounting, conditional procurement leakage and totals containing unknown prices", "prove that professional detail comes from distinct applicable assemblies rather than padded or multiply counted rows", "adds exact semantic-identity, cable-basis, price-null and procurement-exclusion assertions without changing or relaxing any prior BOQ expectation"),
  entry("tests/requestEstimate/electricalCircuitScheduleV1.contract.test.ts", "electrical quantities were not reconciled through a typed circuit schedule before BOQ compilation", "outlet, lighting and dedicated-load circuits reconcile exact point counts, phases, protection and cable allocation, while incomplete schedules block compilation", "make circuit grouping and protection selection explicit and dimensionally checkable instead of deriving hidden aggregate defaults", "adds positive single- and three-phase schedules plus negative missing-load and count-mismatch cases; all prior electrical parameter tests remain required"),
  entry("tests/requestEstimate/electricalProductionRuntimeTruth.contract.test.ts", "legacy persisted 42-row electrical drafts and arbitrary catalog aliases could re-enter the ready runtime path", "list, reload and explicit-catalog ingress migrate stale electrical drafts to the canonical blocking state, clear rows, PDF and procurement, and preserve revision provenance", "seal every production entrypoint against the user-visible legacy fallback while retaining recoverable draft identity", "adds direct, persisted, reload, migration-event and catalog-precedence assertions with exact zero-row and no-price outcomes; it does not replace or weaken existing storage or resolver coverage"),
  entry("tests/estimateCalculator/formworkP0.contract.test.ts", "all 59 catalog rows were called source-backed professional norms", "the exact 3 registered norm rows are separated from 56 unregistered catalog rows and readiness remains blocked", "preserve contact-area formula/procurement mechanics without promoting catalog references to normative evidence", "adds exact total and registered counts while retaining source token, units, formula and buyer assertions"),
  entry("tests/estimateCalculator/masonryP0.contract.test.ts", "the 59-row gas-block template was called fully professional", "the exact 3 registered norm rows are separated from 56 unregistered catalog rows and readiness remains blocked", "preserve masonry identity/formula/procurement mechanics without promoting catalog references to normative evidence", "adds exact total and registered counts while retaining work identity, units, formula and buyer assertions"),
  entry("tests/estimateCalculator/metalworkP0.contract.test.ts", "all 59 catalog rows were called source-backed professional norms", "the exact zero registered norm rows are reported and readiness remains blocked", "preserve metalwork formula/procurement mechanics without promoting catalog references to normative evidence", "adds exact total and registered counts while retaining family, source token, formula and buyer assertions"),
  entry("tests/estimateCalculator/plumbingP0.contract.test.ts", "all 63 catalog rows were called source-backed professional norms", "the exact zero registered norm rows are reported and readiness remains blocked", "preserve plumbing formula/procurement mechanics without promoting catalog references to normative evidence", "adds exact total and registered counts while retaining source token, units, formula and buyer assertions"),
  entry("tests/estimateCalculator/reinforcementP0.contract.test.ts", "all 59 catalog rows were called source-backed professional norms", "the exact 3 registered norm rows are separated from 56 unregistered catalog rows and readiness remains blocked", "preserve kg-based formula/procurement mechanics without promoting catalog references to normative evidence", "adds exact total and registered counts while retaining source token, units, formula and buyer assertions"),
  entry("tests/estimateCalculator/roofingP0.contract.test.ts", "all 59 catalog rows were called source-backed professional norms", "the exact zero registered norm rows are reported and readiness remains blocked", "preserve roofing formula/procurement mechanics without promoting catalog references to normative evidence", "adds exact total and registered counts while retaining source token, units, formula and buyer assertions"),
  entry("tests/estimateCalculator/screedP0.contract.test.ts", "the 59-row screed template was called fully professional", "the exact 2 registered norm rows are separated from 57 unregistered catalog rows and readiness remains blocked", "preserve the 100 m2 by 50 mm formula/procurement mechanics without promoting catalog references to normative evidence", "adds exact total and registered counts while retaining work identity, source token, formula and buyer assertions"),
  entry("tests/estimateCalculator/p1RepairCalculators.contract.test.ts", "every row in nine P1 samples was called a source-backed professional norm", "the exact registered subset vector is locked while all 531 rows retain formulas, sections and procurement", "separate independently registered normative evidence from complete runtime mechanics", "keeps all nine identities and every mechanical assertion, adding exact row and registered-norm counts"),
  entry("tests/estimateCalculator/p2StructuralCalculators.contract.test.ts", "every row in ten P2 samples was called a source-backed professional norm", "the exact registered subset vector is locked while all 590 rows retain trace and honest missing-price behavior", "separate independently registered normative evidence from complete runtime mechanics", "keeps all ten identities and every trace/price assertion, adding exact row and registered-norm counts"),
  entry("tests/estimateInfrastructure/aiEstimateQuantityTrace.contract.test.ts", "ambiguous road prompt implicitly chose scope", "trace test supplies explicit ROAD_SURFACING_ONLY scope", "isolate quantity-trace behavior from the separately tested scope selector", "road ambiguity remains covered by roadScopeTruth and resolver suites"),
  entry("tests/estimateNorms/productionGradeLayerMatrix.test.ts", "claimed all 11610 templates were production-grade ready and required a zero exit code", "captures the intentional STOP exit and seals the exact 1610 ready / 10000 blocked readiness split", "keep technical runtime execution distinct from professional readiness while the 10000-template deficit remains open", "all 11610 templates, 100/100 critical runtime cases, exact blockers, sample output floor, fake-green=false, no release and no production database mutation remain asserted"),
  entry("tests/estimateRuntime/estimatorMemoryLifecycleGate.contract.test.ts", "sharding could hide retained estimator objects", "synthetic plateau passes and retained growth fails", "keep a one-process leak gate independent of sharding", "adds a new negative memory-growth contract"),
  entry("tests/estimateRuntime/full11610MaterialCompletenessAudit.test.ts", "claimed source GREEN even when the exact-SHA real-named prerequisite ledger was absent", "retains all 11610 material and projection proofs but requires the typed STOP and exact missing-prerequisite blockers", "prevent independently successful material decomposition from masquerading as a complete professional readiness chain", "exact 11610/11610 material completeness, 582550 slots, zero missing/truncation/generic/filler/duplicate rows, 100/100 critical cases, projection parity, fake-green=false and the full blocker list remain asserted"),
  entry("tests/estimateRuntime/full11610TrustedCostingAudit.test.ts", "claimed 11610 preliminary prices", "exact 11270 preliminary plus 340 PRICE_INPUT_REQUIRED outcomes", "missing rates must not become fake prices", "all 11610 outcomes, zero fake totals and exact priority splits remain asserted"),
  entry("tests/estimateRuntime/professionalBoqRuntimeContract.test.ts", "runtime contract did not reject duplicate fallback equipment or an area-priced tile primer", "fence equipment must reuse specialized BOQ rows and tile primer must remain a consumable quantity", "prevent literal-name fallback matching from adding unpriced duplicate equipment and preserve physical material units", "adds two negative duplicate-row assertions and an exact kg primer-unit assertion while retaining the full 18-case runtime contract"),
  entry("tests/estimateStructuredPipeline/requestUsesStructuredPayload.contract.test.ts", "raw visible text equality", "sanitized canonical visible text equality", "public projection must not expose internal keys", "same payload rows and top-proof lines remain covered after sanitation"),
  entry("tests/officeEstimate/directorPdfNormSources.contract.test.ts", "PDF exposed normId key syntax", "PDF shows public certified provenance labels", "preserve evidence without leaking internal identifiers", "asserts all three provenance concepts and rejects internal key syntax"),
  entry("tests/officeEstimate/professionalCostingPdfBuyerHandoff.test.ts", "no below-threshold price outcome case", "PRICE_INPUT_REQUIRED parity across costing, PDF and buyer handoff", "prevent partial totals from being presented as preliminary totals", "adds a complete negative price-coverage path"),
  entry("tests/pdf/pdfDocumentViewerEntry.test.ts", "single concatenated logger argument", "structured logger prefix, event and payload", "match governed observability API", "navigation payload assertions are unchanged"),
  entry("tests/professionalBoq/apartmentRenovationBoqDepth.contract.test.ts", "eighteen apartment concepts were matched only in one exact grammatical form", "the same eighteen concepts are matched by stable Russian semantic stems across the 1468-row professional BOQ", "keep the depth gate independent of inflection and display-copy refinements", "the minimum row count stays 30 and all eighteen distinct demolition, engineering, finish, logistics and reserve concepts remain mandatory"),
  entry("tests/projectExecution/procurementHandoffVisibleLabels.contract.test.ts", "price status was inferred from catalog-item presence and trusted price fields were forbidden", "price status must agree with the selected price trace, positive price, selected amount and missing-price flag", "project execution now carries governed price provenance from the structured estimate even without a product catalog item", "human labels and forbidden internal-token checks remain, while price proof is strengthened to its exact source and amount chain"),
  entry("tests/perf/performance-budget.test.ts", "consumer-repair governance/persistence, row display, unit semantics, and seven post-checkpoint core modules counted in broader budgets", "all four exact owner groups have independent caps", "keep module attribution aligned with extracted domain and current-core boundaries", "the pre-existing growth and aggregate source budgets are unchanged; each extracted group receives its own exact cap"),
  entry("tests/perf/flatListTuningBatchB.contract.test.ts", "initial/batch render budget 6", "stricter initial/batch render budget 5", "reduce initial list work", "budget is tightened and refresh completion remains asserted"),
  entry("tests/perf/reactMemoBarriersBatchB.contract.test.ts", "format-sensitive source assertion", "whitespace-normalized exact memo export assertion", "avoid formatter-only failures", "same 15 memo barriers and export owners remain exact"),
  entry("tests/releasePipeline/deterministicShardedFullJestRunner.contract.test.ts", "no full-manifest shard integrity contract", "stable weighted plan with duplicate/missing rejection", "make full regression scalable without excluding suites", "adds exact union and determinism checks"),
  entry("tests/requestEstimate/trustedCostingUi.test.ts", "UI covered preliminary amount only", "UI distinguishes preliminary and PRICE_INPUT_REQUIRED", "show honest price resolution", "adds missing-price negative coverage without removing preliminary coverage"),
  entry("tests/scale/renderExpoWebStagingServer.contract.test.ts", "stale retired release branch", "current production-candidate branch", "match checked-in Render configuration", "server command, health check and deployment contract remain asserted"),
  entry("tests/scale/routeErrorBoundaryCoverage.contract.test.ts", "53 routes", "54 routes with 54 boundaries or explicit exceptions", "inventory gained one governed route", "coverage remains 100 percent with a higher exact route count"),
  entry("tests/security/securityScannerMutationFixtures.contract.test.ts", "security scan had no self-test mutations", "seven sensitive payload classes must turn the scanner RED and clean evidence must return GREEN", "prove the scanner detects secrets, private URLs and personal data instead of trusting a static green report", "adds API key, bearer, private URL, email, phone, local path and authorization-header mutations plus clean-state recovery"),
  entry("tests/ui/stickyActionBar.contract.test.ts", "pointerEvents component prop source shape", "shared pointerNone style source shape", "use the canonical cross-platform style owner", "still requires pointerEvents none and the shared button-content wrapper"),
  entry("tests/aiEstimateV4/estimateRevisionDurableStore.contract.test.ts", "durable adapters covered round-trip, checksum rejection and recovery without a typed capacity boundary", "memory, IndexedDB and SQLite adapters reject oversized writes with adapter-specific PAYLOAD_TOO_LARGE diagnostics and retain the last valid revision", "make persistence capacity an explicit cross-platform contract", "all existing round-trip, corruption, migration and recovery assertions remain, with six new positive and negative capacity assertions"),
  entry("tests/aiEstimateV4/roadScopeProductionIntegrationV4.contract.test.ts", "ambiguous road prompts could inherit an implicit complete-structure scope", "production integration requires an explicit road scope and preserves the selected scope through calculation", "prevent hidden scope assumptions at the production boundary", "the same road quantity and layer assertions remain while ambiguity is now rejected rather than silently defaulted"),
  entry("tests/estimateBackfill/backfillProgressDashboard.contract.test.ts", "dashboard promoted catalog-prefix evidence to 10000 professional norm packs", "dashboard requires zero unsupported professional-ready templates, an explicit normative STOP and the exact 10000-template deficit", "separate successful catalog mapping from independently registered normative provenance", "the exact corpus and P1/P2/P3 partitions remain, synthetic generic rows must still decrease, and fake 10000 GREEN is now explicitly forbidden"),
  entry("tests/estimateBackfill/catalogBackfillConveyor.contract.test.ts", "idempotent P1 mapping was treated as a fully professional norm backfill", "the conveyor remains idempotent but must STOP with 0/4127 independently proven P1 norms", "catalog mapping cannot manufacture normative sources", "batch size, idempotence, marketplace isolation, zero fake-source generation and exact blocker are all asserted"),
  entry("tests/estimateBenchmark/benchmarkRunner.contract.test.ts", "golden comparison execution was skipped entirely when the independent trust layer was not ready", "all 277 reference cases and the critical subset still execute and pass while the aggregate retains the typed trust-layer STOP", "separate deterministic comparison quality from independently registered normative readiness", "case count, all-case parity, critical coverage, zero tolerance violations, PDF/buyer parity, zero fake prices and the exact trust blocker are asserted"),
  entry("tests/estimateCalculator/drywall80UsesRealNormPack.contract.test.ts", "every source id with the professional catalog prefix was treated as an independently registered norm source", "registered public or manufacturer rows are separated from honest generic reference rows", "stop generic catalog evidence from masquerading as professional normative provenance", "the Knauf formula, quantities and registered-source assertions remain exact and a new generic-source boundary is asserted"),
  entry("tests/estimateCalculator/paint200UsesRealNormPack.contract.test.ts", "every source id with the professional catalog prefix was treated as an independently registered norm source", "registered public or manufacturer rows are separated from honest generic reference rows", "stop generic catalog evidence from masquerading as professional normative provenance", "the Ceresit formula, quantities and registered-source assertions remain exact and a new generic-source boundary is asserted"),
  entry("tests/estimateCalculator/plaster300UsesRealNormPack.contract.test.ts", "every source id with the professional catalog prefix was treated as an independently registered norm source", "registered public or manufacturer rows are separated from honest generic reference rows", "stop generic catalog evidence from masquerading as professional normative provenance", "the governed plaster formula, quantities and registered-source assertions remain exact and a new generic-source boundary is asserted"),
  entry("tests/estimateCalculator/professionalAssumptionsEngine.test.ts", "professional assumptions could rely on an implicit road scope in the shared fixture", "road assumptions use an explicit governed scope", "separate assumptions coverage from road-scope selection coverage", "all assumption, confidence and missing-input assertions remain and scope ambiguity is covered by dedicated negative contracts"),
  entry("tests/estimateCatalog/catalogQualityDashboard.contract.test.ts", "persisted dashboard claimed 10000/10000 professional norms from generic catalog evidence", "dashboard preserves exact mapped partitions while reporting 0/10000 independently proven template norms and an explicit STOP", "make persisted quality evidence agree with the registered-source boundary", "the exact 10000 manifest, 4127 P1, 3964 P2, P0 case inventory, no-marketplace boundary and zero fake GREEN remain asserted"),
  entry("tests/estimateExpandedComplex/expandedComplexTaxonomy.contract.test.ts", "expanded taxonomy admitted a broad transport fallback for concrete and interior electrical identities", "taxonomy resolves those identities to their exact domain owners", "prevent fallback taxonomy from hiding canonical family defects", "coverage remains exhaustive and adds negative assertions against the former transport classification"),
  entry("tests/estimateNorms/sourceBackedNormRequiredForProfessional.contract.test.ts", "professional status was inferred from a source-id prefix without a dimensional source claim", "professional rows require registered provenance and an exact work-unit to resource-unit dimensional contract", "make normative provenance and consumption dimensions machine-verifiable", "existing source-backed rejection remains and new m3-to-kg, applicability and generic-masquerading negatives strengthen it"),
  entry("tests/estimatePresentation/visibleEstimateLabelPolicy.contract.test.ts", "visible labels could expose an internal fallback category after family correction", "public labels use canonical domain wording and suppress internal fallback identifiers", "keep classification repair consistent at the public projection boundary", "all existing sanitation checks remain and the corrected family projection is added"),
  entry("tests/estimateReadiness/p1HighVolumeRepairReady.contract.test.ts", "P1 mapping count 4127 was equated with 4127 professional norm packs", "P1 retains exactly 4127 mappings but reports zero independently proven professional templates and a typed blocker", "prevent generic catalog provenance from masquerading as normative readiness", "the full P1 count, zero synthetic fallback rows and no full-10000 GREEN remain exact"),
  entry("tests/estimateReadiness/p2StructuralExteriorReady.contract.test.ts", "P2 mapping count 3964 was equated with 3964 professional norm packs", "P2 retains exactly 3964 mappings but reports zero independently proven professional templates and a typed blocker", "prevent generic catalog provenance from masquerading as normative readiness", "the full P2 count, zero synthetic fallback rows and no full-10000 GREEN remain exact"),
  entry("tests/estimateRuntime/replayableCoreContract.test.ts", "replay records could reconstruct current revisions from the original prompt and share an unversioned fallback with legacy records", "new records replay directly from checksummed canonical resolved identity while only schema-v1 records enter an explicit legacy migration", "eliminate prompt re-resolution drift for current records without rewriting history", "all 380 replay parity checks remain and new assertions require zero prompt fallback plus typed unsafe legacy failure"),
  entry("tests/foreman/aiEstimateRuntimeBoundaryForemanFlow.contract.test.ts", "foreman flow fixture depended on an implicit estimate scope", "foreman flow carries the explicit selected scope through the runtime boundary", "prove the user-selected scope survives orchestration", "the same structured payload, result and handoff assertions remain while exact scope propagation is added"),
  entry("tests/ai/aiEnterpriseArchitecturePolicy.contract.test.ts", "exact AI layer inventory stopped before four current estimator owners", "exact inventory includes continuous detection, pricing, expanded-complex works and the professional calculator", "keep the architecture contract equal to every governed production layer", "exact ordered equality remains and four production owners are added without removing any prior layer"),
  entry("tests/ai/liveRouteWiring/liveRouteMediaEntrypointActions.contract.test.ts", "media action contract required a single-asset replace signature and singleton asset projection", "replace accepts an optional exact asset id and projects all uploaded asset ids and public URLs", "align the route action proof with multi-item media ownership", "replace/remove action test ids and empty-state assertions remain, while multi-item id and URL projection assertions are added"),
  entry("tests/architecture/consumerRepairNoBottomNavOverlap.contract.test.ts", "sent or approved request state activated the finalized action layout", "only a finalized current revision activates the finalized action layout", "keep bottom-navigation clearance aligned with revision finality", "the overlap geometry, sticky action ownership and non-finalized layout assertions remain exact"),
  entry("tests/architecture/consumerRepairNoFrontendOnlySubmit.contract.test.ts", "the screen was required to call the backend service directly", "the screen delegates to its screen-action owner and that owner calls the backend service", "enforce the extracted orchestration boundary without removing the backend mutation", "the contract proves both chain links and still forbids frontend-only submission"),
  entry("tests/architecture/marketplaceAddDoesNotBypassBackendService.contract.test.ts", "marketplace publish source was matched against a stale createMarketListing symbol", "marketplace publish must call the canonical submitAddListing service owner", "follow the current backend mutation boundary", "the same source scanner still requires a backend-owned publish call and rejects bypasses"),
  entry("tests/architecture/noDuplicateGlobalPlus.contract.test.ts", "bottom tabs could expose a raw add route alongside the governed global plus", "the raw add tab is forbidden and the single plus navigates through ADD_LISTING_ROUTE", "seal one canonical add-listing entrypoint", "exactly one global plus remains required and duplicate route exposure is now explicitly rejected"),
  entry("tests/architecture/noRawAddRouteInBottomTabs.contract.test.ts", "the contract looked for a stale raw add route declaration", "the contract forbids any add tab declaration and requires canonical ADD_LISTING_ROUTE navigation", "match the production route constant and prevent hidden duplicate tabs", "the negative raw-route assertion is strengthened while the positive governed entrypoint assertion remains"),
  entry("tests/architecture/screenShellResponsibility.contract.test.ts", "the owner-hook delta was expected to remain zero", "the governed owner-hook delta is recorded as present after responsibility extraction", "report the real shell decomposition rather than a stale baseline flag", "all shell size, hook ownership, service extraction and threshold assertions remain unchanged"),
  entry("tests/marketAddScreen/marketAddScreenPublishRealMedia.contract.test.ts", "publish proof expected backend mutation and instant-cache code inside AddListingScreen", "the screen-to-submission-owner-to-backend/cache chain is required", "follow the extracted transactional owner without losing real media publication", "all uploaded-media, stable-URL, backend confirmation, instant-cache and five-kind smoke assertions remain"),
  entry("tests/marketAddScreen/marketAddScreenValidationHints.contract.test.ts", "validation helpers were expected under obsolete names inside the screen", "the screen must call the exact add-listing validation owner and the owner must enforce media presence", "match the extracted pure validation boundary", "all visible field errors, hints, error summary and submit prevention remain asserted"),
  entry("tests/marketAddScreen/validationPublishState.contract.test.ts", "all validation details were expected inline in AddListingScreen", "the screen owns state while the validation module owns price, phone and media rules", "keep UI orchestration separate from validation policy", "publish stages, real listing result, visible errors and every former validation rule remain covered across both chain links"),
  entry("tests/marketMyListings/marketMyListingsPublicMarketUnaffected.contract.test.ts", "return-to-my-listings routing was expected inline in AddListingScreen", "the screen delegates to the typed navigation owner which resolves MARKET_MY_LISTINGS_ROUTE", "follow the extracted return-navigation owner", "the public market remains free of owner-only blocks and profile, seller, screen and navigation links are all asserted"),
  entry("tests/ui/bottomTabsRequestLabelNoDuplicatePlus.contract.test.ts", "a hidden raw add tab was tolerated beside the custom marketplace action", "zero raw add tabs and one ADD_LISTING_ROUTE action are required", "remove the duplicate route while preserving the visible marketplace entrypoint", "the request tab labels, one custom add test id, accessible label and absence of plus tab labels remain exact"),
  entry("tests/ui/marketplaceAddProductScreenStillWorks.contract.test.ts", "the UI contract expected createMarketListing directly in AddListingScreen", "the route reaches AddListingScreen, which reaches submitAddListing, whose owner reaches createMarketListing", "prove the current backend ownership chain after decomposition", "all publish, close, sticky action, media controls, upload copy and negative local-media assertions remain"),
  entry("tests/ui/noDuplicatePlusNoRawRoutes.contract.test.ts", "one hidden raw add tab was accepted", "the raw add tab count must be zero and the custom action must use ADD_LISTING_ROUTE", "seal the single canonical marketplace-add entrypoint", "negative raw route and label checks remain while duplicate-tab tolerance is removed"),
  entry("tests/aiEstimate/inlineWorkTemplateCanonicalClassifier.contract.test.ts", "composite industrial-roadworks and bridge-culvert phrases had no explicit canonical matcher lock", "road subgrade and bridge construction win only when both domain anchors are present", "prevent a scope adjective or the narrower culvert token from overriding the complete construction context", "all prior natural-language, technical-key rejection, fence and diamond-drilling assertions remain, with two positive conflict regressions added"),
  entry("tests/globalEstimate/globalWorkTypeResolver.contract.test.ts", "single aliases industrial_earthworks and culverts overrode stronger composite contexts", "the production resolver returns exact roadworks and concrete owners for both composite prompts", "keep the real Built-in AI ingress aligned with the complete domain phrase", "all prior resolver assertions remain and the two formerly failing production prompts now require exact work key, category and high confidence"),
  entry("tests/semanticRegression/unitSemanticsGoldenLock.contract.test.ts", "the golden lock did not exercise contextual formwork, concrete-delivery WBS, or generic area-based metal material rows", "the validator must accept their physically correct sq_m and m3 units without weakening unrelated concrete, delivery or structural-metal rules", "seal the latent unit-semantics failures exposed by clean artifact-free Built-in AI regeneration", "the original five-domain unit-variety loop remains unchanged and three new positive regressions assert exact row families, physical units and zero validator failures"),
  entry("tests/estimateGolden/extendedUnitsByWorkGroup.contract.test.ts", "the aggregate unit check did not name the four masonry cases that exposed mixed public aliases", "all four masonry goldens must independently pass the canonical public-unit invariant", "seal canonical sq_m and pcs projection at the compiler boundary instead of accepting internal m2 and piece aliases in public BOQ rows", "the existing all-100 unit diversity and detector assertions remain; four exact formerly failing case identities are added"),
  entry("tests/estimateReality/noBlindQuantityCopy.contract.test.ts", "the detector could rename traced identity copies without proving coefficient or dimensional semantics", "formula-free blind copy, unverified identity coefficient, unit mismatch, runtime validity, registered norm and professional readiness are independent fail-closed facts", "prevent 400 m2 to 400 m3/set/piece and metres to tonnes from becoming GREEN merely because a trace string exists", "retains traced-versus-blind separation and adds four explicit incompatible-unit identity cases with runtime-valid but semantic-RED assertions"),
  entry("tests/estimateCatalog/catalogQualityDashboard.contract.test.ts", "the dashboard could hide 336 formula-bearing trust failures by reducing the blind-copy counter", "dashboard reports mechanical compilation, runtime formula, unit dimension, norm registration, procurement, price and professional acceptance independently", "report the full readiness lattice without promoting generated norms or hiding semantic debt", "retains all 10,000 STOP totals and adds nonzero identity/mismatch/unregistered/semantic counters plus zero professional-ready enforcement"),
  entry("tests/estimateInfrastructure/professionalWorkPassportTemplateIndex.contract.test.ts", "the 750-case runtime matrix constructed all 11,610 heavy BOQ passports merely to select metadata samples", "a cached lightweight complete metadata index preserves identity order, shares the registry fingerprint, invalidates on fingerprint drift, and resolves representative passports through O(1) lookup", "remove runtime timeout without shrinking samples or allowing stale metadata", "retains exact 11,610 uniqueness/order and representative equivalence while adding same-reference reuse, registry/index fingerprint equality, and drift rejection"),
  entry("src/features/consumerRepair/consumerRepairAsphaltV4Phase1B.test.ts", "scope selection without geometry compiled a reference 1000 m2 BOQ", "scope selection without confirmed geometry must remain PARAMETERS_REQUIRED with zero revisions and rows", "remove the forbidden hidden reference-area fallback from the active DraftSession workflow", "all existing Asphalt Phase1B/1C assembly, formula and scope tests remain; the stale fallback assertion is replaced by stricter no-compile, no-revision and missing-parameter assertions"),
  entry("tests/aiEstimateV4/asphaltReferenceV1Freeze.contract.test.ts", "the Asphalt compiler had distributed scope tests but no single versioned four-scope reference freeze", "all four scope profiles have independent counts, corpus hashes, WBS boundaries, formula/source/unit traces, price truth and extensibility proof", "freeze the quantity reference honestly before any 11610-work scale rollout", "adds four deterministic engineering goldens, required and forbidden row ownership, replay parity, honest readiness and a second-profile registration proof without removing any existing Asphalt coverage"),
  entry("tests/consumerRepair/reloadDoesNotRestoreApprovedEstimateAsActiveDraft.contract.test.ts", "reload coverage distinguished approved and one exact draft but did not prove unknown IDs or a 34-draft history", "unknown exact IDs fail closed and 34 active drafts cannot auto-open without a route draftId", "eliminate latest-workspace hydration and make route identity the only active restore authority", "retains the approved and exact-reload cases and adds unknown-ID plus 34-draft negative isolation cases"),
  entry("tests/estimateDraftSession/estimateDraftSession.contract.test.ts", "active estimate state had no standalone aggregate transition contract", "atomic work/scope/parameter/compile/history/clone/legacy transitions are validated with epoch and complete compile-context rejection", "make DraftSession the single domain owner and prevent stale asynchronous results", "adds positive readiness and deterministic hash tests plus negative draft, epoch, scope, schema, strategy, legacy and history-mismatch tests"),
  entry("tests/estimateDraftSession/estimateDraftSessionPersistence.contract.test.ts", "durable consumer bundles had no exact DraftSession round-trip or corrupted-state contract", "exact sessions round-trip, corrupted snapshots fail closed and repository writes overwrite tampered compatibility projections", "prevent storage and pending-scope adapters from becoming parallel mutable state", "adds valid, corrupted and deliberate-tampering cases while preserving all existing durable bundle tests"),
  entry("tests/estimateRuntime/inlineWorkPromptParamParser.test.ts", "road dimensions covered only one value-before-label phrase", "one typed extractor covers bidirectional labels, inflections, unit conversion, dimension pairs, zero/negative/unrelated values, outliers and geometry conflicts", "preserve current-session geometry without phrase-specific patches or unsafe numeric fallback", "retains every prior general construction parser assertion and adds table-driven positive and negative matrices plus derived-area provenance"),
  entry("tests/requestEstimate/roadScopeSelectionUi.contract.test.tsx", "scope buttons were coupled to a road-specific UI list and could render behind an empty summary", "scope options come from the registered WorkProfile and the selector is ordered before any estimate summary", "keep request UI generic and ensure ambiguous work always exposes an actionable scope transition", "retains four-option, accessibility, busy-state and internal-ID rejection checks while adding registry ownership and source-order assertions"),
  entry("tests/e2e/asphaltReferenceV1DraftSession.web.spec.ts", "the active request flow had no real-browser contract for exact DraftSession routing and the four Asphalt scopes", "Chromium must prove manual 5400-by-15 and 2000-by-32 entry, visible canonical scope choice, 702/54 outputs, exact reload, clean new draft and missing-geometry artifact blocking without console errors", "seal the user-visible DraftSession and Asphalt Reference V1 path before 11610-work scaling", "adds end-to-end browser coverage without replacing any component, service, revision, replay, PDF or procurement contract"),
  entry("src/lib/navigation/requestEstimateLaunchPayload.test.ts", "Android request and AI launch parameters had no versioned canonical payload boundary", "versioned launch payloads preserve Unicode and reserved characters, share cold/warm identity, and reject malformed, unknown, empty or oversized input", "make Android intent delivery deterministic and fail closed before request or AI state mutation", "adds positive round-trip and launch-identity coverage plus corrupt, unknown-field, empty-intent and size-bound negatives without replacing any protected device proof"),
  entry("src/screens/office/office.layout.model.test.ts", "the developer panel model did not distinguish a local UI context from a server-authorized platform developer", "both contexts are visible for diagnostics while only the server context carries actor, entitlement and authorization source", "show effective-role provenance without turning a local UI flag into authorization", "retains the normal Office section model assertions and adds exact local-versus-server developer context projections"),
  entry("src/screens/office/officeAccess.services.localDeveloper.test.ts", "a local developer flag fabricated an actor identity and bypassed auth/profile loading", "Office access always requires the real authenticated user/profile boundary and never consults a local override after auth failure", "remove client-side identity fabrication from the privileged access path", "replaces the permissive bypass expectation with stricter rejection, exact auth/profile calls and zero override-RPC calls"),
  entry("tests/api/foremanAuthTransport.contract.test.ts", "foreman transport allowed a local developer identity fallback after session lookup", "foreman transport requires a real signed-in session and forbids the local flag and sentinel actor identity", "keep local UI convenience outside authenticated foreman data access", "retains the session-first and subcontract-history ownership assertions while strengthening the fallback into two explicit prohibitions"),
  entry("tests/app/nativeIntentPublicRequest.contract.test.ts", "cold Android request links preserved a loose prompt query and warm handling depended only on event delivery", "all supported cold variants normalize to a versioned launch payload while warm delivery also polls the native linking snapshot and deduplicates by launch identity", "make cold and warm request delivery equivalent on the protected installed APK", "retains every prior URI variant and unrelated-route negative while adding exact decoded payload, native snapshot and launch-id ownership assertions"),
  entry("tests/office/devOverrideUiBoundary.contract.test.ts", "the UI contract expected a local developer flag to participate in auth guards while hiding the effective-role panel", "the panel exposes actor, effective role and source for developer contexts while auth lifecycle and guards forbid local authorization bypass", "separate observable developer UI state from server-authorized access", "retains the Office policy, section and live-runner boundaries while adding negative auth-bypass and positive entitlement-source assertions"),
  entry("tests/office/useOfficeHubRoleAccess.test.tsx", "the Office hub developer fixture lacked explicit actor role, entitlement and authorization provenance", "the fixture represents a server-authorized platform developer with exact entitlement metadata", "exercise role access through the same provenance-bearing context returned by the protected backend RPC", "all existing full-route and ordinary-role access expectations remain; only the privileged fixture gains required server authorization facts"),
  entry("tests/officeAuth/platformDeveloperEntitlement.contract.test.ts", "platform-wide developer ownership had no single fail-closed server authorization and route-matrix contract", "the protected migration, audit actor/effective roles, real route inventory, admin gate and ordinary-role negative matrix are asserted together", "prove super access is a server entitlement rather than a client flag or hardcoded identity", "adds new positive server-entitlement and real-module coverage plus forged/local developer, buyer/accountant, foreman/director and contractor/warehouse isolation negatives"),
  entry("scripts/release/noTestWeakeningPolicy.test.ts", "the audit matched the ordinary word retry anywhere in an added line, including a test title", "the scanner detects concrete Jest timeout/retry calls, retry configuration, CLI memory/timeout/force flags and pass-without-tests policy while ignoring prose", "prevent false blockers without allowing executable test-policy weakening", "adds two ordinary-prose negatives and seven executable/configuration positives; the audit remains fail-closed for every governed policy mechanism"),
  entry("src/lib/navigation/requestEstimateLaunchLifecycle.test.ts", "warm request and AI intents had separate pending and processed sets without an acknowledgment state", "one pure lifecycle enforces launchId idempotency, new-launch replay, cross-route latest-wins and session-boundary clearing", "prevent stale pre-auth intents and URL-string dedupe from losing or duplicating DraftSessions", "adds exact transition assertions for pending, applied, UI-ready, acknowledged, duplicate, replacement and session reset states without replacing device-level proof"),
  entry("tests/app/requestEstimateIntentLifecycleOwners.contract.test.ts", "route owners had no single contract proving that ACK follows DraftSession and visible UI or that authenticated user replacement clears intent state", "request and AI owners must emit draft-ready, UI-ready and acknowledged in order while root auth boundaries clear pending and dedupe state on logout and user-id change", "seal the real route-owner acknowledgment boundary and prevent an intent captured for one user from applying to another", "adds positive source-order checks for both real screen owners and exact dual session-boundary clearing without removing any lifecycle or Android device proof"),
  entry("scripts/release/androidWarmDeepLinkProbeHarness.test.ts", "the Android probe parser had no isolated terminal, timeout, cleanup or stale-process regression suite", "the harness self-test exercises lifecycle ordering, UI evidence, terminal aggregation and cleanup without product mutation", "prove the official device runner itself cannot manufacture a GREEN or leak probe identities", "adds fail-closed negative cases and an exact self-test token without replacing any protected API34 device assertion"),
  entry("tests/android/androidAuthHarnessInputIdempotency.contract.test.ts", "the Android auth helper could repeat text entry after a delayed readable field update", "one bounded input identity is applied once and confirmed before authentication continues", "prevent probe retries from duplicating credentials or perturbing the product route", "retains real selector and login ownership assertions while adding exactly-once input and delayed-readback coverage"),
  entry("tests/app/androidHarnessLoginSnapshotReuse.contract.test.ts", "each Android case could create a fresh login session even when an authenticated snapshot was already valid", "the harness reuses only a readable same-user authenticated snapshot and fails closed otherwise", "remove authentication contention from the four-case proof without bypassing real session validation", "adds valid-reuse, stale, mismatched and unreadable snapshot cases; no login or auth assertion is removed"),
  entry("tests/consumerRepair/approvedHistoryGrowthAfterParameterCards.contract.test.ts", "the 100-record browser audit relied on the host Platform.OS and performed a synchronous reload across asynchronous transactional writes", "the fixture explicitly selects web, flushes atomic writes, hydrates transactionally and restores the original platform", "make the cap-13, reload and compaction proof exercise the same durable boundary as the product", "all exact 14, 25 and 100 counts and both reload/compaction assertions remain; only the formerly implicit platform and write completion are made explicit"),
  entry("tests/entrypoints/embeddedAiUsesGlobalEstimateResult.contract.test.ts", "embedded AI coverage did not lock canonical route ownership and visible parameter-backed output together", "known work uses the shared global estimate result while incomplete canonical work exposes its governed clarification row", "prevent the embedded entrypoint from reintroducing a local template or hidden default", "retains global-result and professional-row assertions and adds canonical visibility without skipping any entrypoint"),
  entry("tests/globalEstimate/globalEstimateProfessionalBoq.contract.test.ts", "professional routing distinguished full foundation concrete from foundation rebar but did not protect generic rebar as an independent public work identity", "generic rebar installation preserves its own key, non-foundation title and explicit quantity/unit while foundation-specific rebar remains on the foundation template", "prevent a shared template alias from collapsing distinct catalog work identities and silently changing estimate semantics", "retains every laminate, infrastructure, foundation concrete and foundation rebar assertion and adds a separate positive generic-rebar identity, title, quantity and unit regression without relaxing any expectation"),
  entry("tests/estimateStructuredPipeline/structuredEstimatePayload.contract.test.ts", "structured payload coverage did not carry the universal canonical parameter session and revision identity", "the payload preserves schema, sources, assumptions, formula dependencies and immutable calculation version", "make one structured payload the source for UI, PDF, history and recalculation", "all existing row, total and provenance checks remain and new parameter/revision fields are asserted fail-closed"),
  entry("tests/professionalBoq/electricalMissingParametersConditionalRows.contract.test.ts", "an incomplete electrical prompt could omit cable entirely or acquire an unexplained priced default", "a visible zero-total manual-review cable row names every blocking parameter and is excluded from estimate and procurement", "show missing electrical scope honestly without charging a hidden quantity", "adds positive visibility and exact blocker/trace assertions plus negative price/procurement assertions; no existing electrical case is replaced"),
  entry("tests/real10000/real10000ElectricalCompatibility.contract.test.ts", "the specialized canonical electrical compiler had no focused regression proving compatibility with the work-specific row contract used by all five electrical Real10000 domains", "electrical installation, industrial electrical, power lines, street lighting and high voltage each preserve cable, panel, route-marking, cable-laying and chasing-equipment scope without missing-row failures", "prevent the canonical electrical owner from narrowing the established universal estimator contract when parameters remain unconfirmed", "adds five positive runtime cases against the unchanged Real10000 fixtures and evaluator; it removes no case, changes no timeout or threshold and requires an empty failure list for every affected domain"),
  entry("tests/professionalBoq/electricalNormativeAssemblyDepth.contract.test.ts", "electrical depth coverage accepted a small aggregate BOQ without independently named containment, panel, testing and handover assemblies", "the canonical electrical profile requires an explicit WBS matrix of applicable containment, wiring, point, panel, protection, earthing, verification, documentation, equipment and logistics rows with formula traces, separated KG and IEC sources, conditional price-null semantics and route recalculation", "prove professional completeness by semantic scope coverage rather than a row-count target while keeping every unknown design decision outside contractual totals", "adds three positive and negative production contracts covering 41 exact WBS mappings and categories, unique visible names, separated source families, one explicit conditional SPD blocker and 154-to-200 quantity changes; no existing test is removed, skipped or relaxed"),
  entry("tests/requestEstimate/canonicalElectricalParameterCore.contract.test.ts", "electrical input could collapse outlet, switch and light counts and lose the explicit route length", "87/154/10/10/8 remain separate canonical values with sources, assumptions, dependencies and deterministic 154-to-200 recalculation", "prove the universal parameter core on a second domain after Asphalt", "adds full, partial, missing, derived-total and recalculation cases with exact identities and no default substitution"),
  entry("tests/requestEstimate/electricalNativeColdRestart.contract.test.ts", "Native consumer estimate persistence was covered for large revisions but not a canonical electrical draft below the large-bundle threshold", "the real AsyncStorage transactional backend restores the exact electrical revision, canonical session, delivery fields and a persisted 500-to-650 route edit across two cold restarts", "prevent small Native estimates from reporting a successful save while remaining only in volatile memory", "adds two real repository reload boundaries, exact revision identity and parameter-source assertions; it does not replace or relax the existing SQLite, AsyncStorage fallback, large-road or Web persistence suites"),
  entry("tests/requestEstimate/electricalRevisionProjectionParity.contract.test.ts", "electrical UI items could retain provisional procurement metadata while PDF and buyer handoff used the corrected immutable revision", "UI, PDF, history and procurement are projected from one exact revision, including row identity, quantity, unit, price-null semantics and procurement eligibility", "eliminate a second projection truth and prevent stale UI rows or unsupported priced totals from reaching downstream artifacts", "adds positive equality across all four projections plus negative missing-price assertions; all existing payload, PDF and buyer-package contracts remain unchanged"),
  entry("tests/estimateInfrastructure/scaleFoundation11610.contract.test.ts", "the 11610 catalog had audit ledgers but no single fail-closed readiness registry contract separating structural admission from per-work professional readiness", "a deterministic manifest classifies L0 through L5 monotonically, requires all versioned registries and five exact-SHA audit records, and quarantines false professional or contract-ready claims", "admit the platform foundation for Group 01 without auto-promoting catalog-only or parameter-only works to quantity, cost or normative readiness", "adds exact readiness counts, registry-completeness blockers, independent contract/procurement evidence and false-ready quarantine assertions; no 11610 audit total or existing readiness expectation is reduced"),
  entry("tests/requestEstimate/canonicalElectricalParameterEditorUi.contract.test.tsx", "canonical structured electrical output could render an empty clarification panel", "all explicit and conditional electrical parameters remain visible and editable after calculation", "prevent an apparently complete estimate from hiding its calculation inputs", "adds real component assertions for populated, missing and assumed fields and retains structured BOQ visibility"),
  entry("tests/requestEstimate/canonicalElectricalPerformance.contract.test.ts", "electrical correctness had no bounded warm/cold construction contract", "canonical extraction, parameter session, exact 132-row incomplete-input BOQ and persisted bundle are measured under the governed budgets", "keep the scalable registry path interactive while accepting the explicitly requested professional assembly depth", "the deterministic row count is strengthened from 33 to 132 while the one-second compile and two-second edit thresholds remain unchanged; no case is skipped"),
  entry("tests/requestEstimate/requestAutoPrepareSourceBackedStructuredEstimate.contract.test.ts", "auto-prepare could expose rows and PDF without proving that canonical electrical values and sources survived persistence", "the real request action preserves separate parameters, recalculates dependent cable rows and renders the same revision in PDF", "seal request-to-storage-to-PDF propagation instead of accepting card presence alone", "retains source-backed structured estimate coverage and adds exact 87/154/10/10/8, missing-field, revision and PDF assertions"),
  entry("tests/requestEstimate/requestEstimateMountedLaunchPrompt.contract.test.tsx", "warm request intent proof stopped at route dispatch and did not require the mounted composer to own the exact prompt", "the mounted request screen shows the exact launch prompt once and acknowledges only after its UI-ready boundary", "tie Android lifecycle ACK to the user-visible route owner", "adds mounted prompt, duplicate launch and fresh launch identity cases without replacing protected device evidence"),
  entry("tests/requestEstimate/structuredEstimateLegacySessionDoesNotBlockUi.contract.test.tsx", "a null compatibility DraftSession was used to make canonical structured BOQ visible", "the compatibility session remains non-null while the canonical parameter session controls blockers and the BOQ stays visible", "remove the session-null bypass and keep one parameter owner", "adds non-null session, visible rows and registered-incomplete blocking assertions while retaining the original structured-result UI expectation"),
];

function git(args: string[], fallback = ""): string {
  try {
    return execFileSync("git", args, {
      cwd: process.cwd(),
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
      timeout: 30_000,
      maxBuffer: 50 * 1024 * 1024,
    }).trim();
  } catch {
    return fallback;
  }
}

function changedTestPaths(): string[] {
  const testPathspecs = ["*.test.ts", "*.test.tsx", "*.spec.ts", "*.spec.tsx"];
  const tracked = git(["diff", "--name-only", BASE_CHECKPOINT, "--", ...testPathspecs])
    .split(/\r?\n/);
  const untracked = git(["ls-files", "--others", "--exclude-standard", "--", ...testPathspecs])
    .split(/\r?\n/);
  return [...new Set([...tracked, ...untracked]
    .map((value) => value.trim().replace(/\\/g, "/"))
    .filter((value) => value && !USER_OWNED_TEST_PATHS.has(value)))]
    .sort();
}

function addedDiffLines(): string[] {
  return git([
    "diff",
    "--unified=0",
    BASE_CHECKPOINT,
    "--",
    ".",
    ":(exclude)scripts/release/auditCurrentCoreNoTestWeakening.ts",
    ":(exclude)package-lock.json",
  ])
    .split(/\r?\n/)
    .filter((line) => line.startsWith("+") && !line.startsWith("+++"));
}

function writeJson(filePath: string, value: unknown): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function main(): void {
  const subjectSha = git(["rev-parse", "HEAD"], "unknown");
  const changedTests = changedTestPaths();
  const ledgerPaths = CURRENT_CORE_TEST_CONTRACT_AUDIT.map((item) => item.path).sort();
  const missingLedgerEntries = changedTests.filter((file) => !ledgerPaths.includes(file));
  const staleLedgerEntries = ledgerPaths.filter((file) => !changedTests.includes(file));
  const additions = addedDiffLines();
  const forbiddenFocusChanges = additions.filter((line) =>
    /\.(?:only|skip)\s*\(|\b(?:fdescribe|fit|xdescribe|xit|xtest)\s*\(/.test(line)
  );
  const timeoutOrMemoryWeakening = additions.filter(
    isTimeoutOrMemoryWeakeningDiffLine,
  );
  const modifiedGuardedFixtures = GUARDED_FIXTURES.filter((file) =>
    git(["diff", "--name-only", BASE_CHECKPOINT, "--", file]).trim() === file
  );
  const guardedFixtureReviews = modifiedGuardedFixtures.map((file) => {
    const review = REVIEWED_GUARDED_FIXTURE_CHANGES[file];
    const baseBlob = git(["rev-parse", `${BASE_CHECKPOINT}:${file}`], "missing");
    const currentBlob = git(["hash-object", file], "missing");
    return {
      path: file,
      base_blob: baseBlob,
      current_blob: currentBlob,
      review: review ?? null,
      exact_review_match:
        review != null &&
        review.base_blob === baseBlob &&
        review.reviewed_blob === currentBlob,
    };
  });
  const unreviewedModifiedGuardedFixtures = guardedFixtureReviews
    .filter((item) => !item.exact_review_match)
    .map((item) => item.path);
  const costingTest = fs.readFileSync(
    path.join(process.cwd(), "tests", "estimateRuntime", "full11610TrustedCostingAudit.test.ts"),
    "utf8",
  );
  const ledgerTest = fs.readFileSync(
    path.join(process.cwd(), "tests", "aiEstimateV4", "catalogProfessionalCoverageLedgerV4.contract.test.ts"),
    "utf8",
  );
  const explicitTruthAssertionsPresent =
    costingTest.includes("templates_costing_ready).toBe(11270)") &&
    costingTest.includes("templates_price_input_required).toBe(340)") &&
    ledgerTest.includes("DISTINCT_PROFESSIONAL_PASSPORT: 12") &&
    ledgerTest.includes("SCOPE_PRESET: 7152") &&
    ledgerTest.includes("PARAMETERIZED_VARIANT: 1288") &&
    ledgerTest.includes("DOMAIN_REVIEW_REQUIRED: 3158");
  const architectureAllowlist = fs.readFileSync(
    path.join(process.cwd(), "src", "lib", "ai", "enterpriseGuardrails", "aiEnterpriseAllowedLayers.ts"),
    "utf8",
  );
  const architectureLayersCovered = [
    "estimateContinuousDetection",
    "estimatePricing",
    "expandedComplexWorks",
    "professionalEstimateCalculator",
  ].every((layer) => architectureAllowlist.includes(`layer: "${layer}"`));
  const blockers = [
    ...missingLedgerEntries.map((file) => `test_change_without_audit:${file}`),
    ...staleLedgerEntries.map((file) => `stale_test_audit_entry:${file}`),
    ...forbiddenFocusChanges.map((line) => `focused_or_skipped_test_added:${line}`),
    ...timeoutOrMemoryWeakening.map((line) => `timeout_or_memory_weakening_added:${line}`),
    ...unreviewedModifiedGuardedFixtures.map((file) => `guarded_fixture_modified_without_exact_review:${file}`),
    explicitTruthAssertionsPresent ? "" : "honest_11610_exact_assertions_missing",
    architectureLayersCovered ? "" : "architecture_layer_inventory_incomplete",
  ].filter(Boolean);
  const summary = {
    final_status: blockers.length === 0
      ? "GREEN_CURRENT_CORE_NO_TEST_WEAKENING_AUDIT"
      : "STOP_CURRENT_CORE_NO_TEST_WEAKENING_AUDIT",
    base_checkpoint: BASE_CHECKPOINT,
    subject_sha: subjectSha,
    changed_test_files_count: changedTests.length,
    changed_test_files: changedTests,
    guarded_fixtures: GUARDED_FIXTURES,
    guarded_fixtures_modified: modifiedGuardedFixtures,
    guarded_fixture_reviews: guardedFixtureReviews,
    forbidden_focus_changes: forbiddenFocusChanges,
    timeout_or_memory_weakening_changes: timeoutOrMemoryWeakening,
    explicit_11610_truth_assertions_present: explicitTruthAssertionsPresent,
    architecture_allowlist_inventory_complete: architectureLayersCovered,
    audit_entries: CURRENT_CORE_TEST_CONTRACT_AUDIT,
    blockers,
    fake_green_claimed: false,
  };
  const outputPath = path.join(
    process.cwd(),
    ".release-runtime",
    "current-core-no-test-weakening",
    subjectSha,
    "summary.json",
  );
  writeJson(outputPath, summary);
  console.info(JSON.stringify(summary, null, 2));
  if (blockers.length > 0) process.exitCode = 1;
}

if (process.argv[1]?.replace(/\\/g, "/").endsWith("/scripts/release/auditCurrentCoreNoTestWeakening.ts")) {
  main();
}
