/**
 * Historical evidence read by the 153-suite current-core remediation surface.
 *
 * The exact-SHA worktree is intentionally clean and therefore does not contain
 * gitignored closeout evidence. Keep this list file-granular: the runner hashes
 * every source before copying it and must never hydrate whole artifact trees.
 */
const REAL10000_SHARD_EVIDENCE_PATHS = Array.from(
  { length: 100 },
  (_, index) => {
    const shard = `shard_${String(index).padStart(3, "0")}`;
    const root =
      "artifacts/S_REAL_10000_DIVERSE_CONSTRUCTION_WORKS/shards";
    return [
      `${root}/${shard}/matrix.json`,
      `${root}/${shard}/failures.json`,
    ];
  },
).flat();

export const CURRENT_CORE_REMEDIATION_EVIDENCE_PATHS = [
  "artifacts/S_RPC_1_runtime_validation_matrix.json",
  "artifacts/S_RPC_2_runtime_validation_matrix.json",
  "artifacts/S_RPC_3_runtime_validation_matrix.json",
  "artifacts/S_RPC_4_runtime_validation_matrix.json",
  "artifacts/S_RPC_5_runtime_validation_matrix.json",
  "artifacts/S_RPC_6_high_risk_rpc_validation_matrix.json",
  "artifacts/S_RPC_6_high_risk_rpc_validation_proof.md",
  "artifacts/S_RPC_7_mutation_result_envelopes_matrix.json",
  "artifacts/S_RPC_7_mutation_result_envelopes_proof.md",
  "artifacts/S_RT_5_realtime_fanout_reduction_matrix.json",
  "artifacts/S_RT_6_realtime_fanout_budget_proof_matrix.json",

  "artifacts/S_REAL_10000_DIVERSE_CONSTRUCTION_WORKS/runtime_results.json",
  "artifacts/S_REAL_10000_DIVERSE_CONSTRUCTION_WORKS/boq_quality_results.json",
  "artifacts/S_REAL_10000_DIVERSE_CONSTRUCTION_WORKS/pdf_text_extract.json",
  "artifacts/S_REAL_10000_DIVERSE_CONSTRUCTION_WORKS/pdf_parity.json",
  "artifacts/S_REAL_10000_DIVERSE_CONSTRUCTION_WORKS/merged_matrix.json",
  "artifacts/S_REAL_10000_DIVERSE_CONSTRUCTION_WORKS/matrix.json",
  "artifacts/S_REAL_10000_DIVERSE_CONSTRUCTION_WORKS/web_live_results.json",
  "artifacts/S_REAL_10000_DIVERSE_CONSTRUCTION_WORKS/android_api34_results.json",
  "artifacts/S_REAL_10000_DIVERSE_CONSTRUCTION_WORKS/web_screenshots.json",
  "artifacts/S_REAL_10000_DIVERSE_CONSTRUCTION_WORKS/android_screenshots.json",
  "artifacts/S_REAL_10000_DIVERSE_CONSTRUCTION_WORKS/android_ui_dumps.json",
  ...REAL10000_SHARD_EVIDENCE_PATHS,
  "artifacts/S_REAL_10000_AUDIT_P0_REMEDIATION/type_ratchet_before.json",
  "artifacts/S_REAL_10000_AUDIT_P0_REMEDIATION/type_ratchet_after.json",
  "artifacts/S_REAL_10000_AUDIT_P0_REMEDIATION/unsafe_cast_remediation.json",

  "artifacts/S_AI_OBS_01_TRACE_AUDIT_OBSERVABILITY_inventory.json",
  "artifacts/S_AI_OBS_01_TRACE_AUDIT_OBSERVABILITY_matrix.json",
  "artifacts/S_AI_OBS_01_TRACE_AUDIT_OBSERVABILITY_proof.md",
  "artifacts/S_AI_OBSERVABILITY_01_TRACE_BUDGET_REDACTION_inventory.json",
  "artifacts/S_AI_OBSERVABILITY_01_TRACE_BUDGET_REDACTION_matrix.json",
  "artifacts/S_AI_OBSERVABILITY_01_TRACE_BUDGET_REDACTION_proof.md",

  "artifacts/S_CURRENT_GREEN_CLAIMS_REPLAY_AUDIT_matrix.json",
  "artifacts/S_CURRENT_GREEN_CLAIMS_REPLAY_AUDIT_ledger.json",
  "artifacts/S_RLS_DYNAMIC_CROSS_TENANT_matrix.json",
  "artifacts/S_RLS_DYNAMIC_CROSS_TENANT_storage_policies.json",
  "artifacts/S_ALL_SCREENS_matrix.json",
  "artifacts/S_ENTERPRISE_RELEASE_CANDIDATE_matrix.json",

  "artifacts/S_50K_SYNTHETIC_FIXTURE_matrix.json",
  "artifacts/S_WHOLE_APP_50K_matrix.json",
  "artifacts/S_QUERY_BOUNDARY_matrix.json",
  "artifacts/S_QUERY_BOUNDARY_resolutions.json",
  "artifacts/S_MEDIA_STORAGE_100K_matrix.json",
  "artifacts/S_AI_ROLE_LIVE_TRANSCRIPT_matrix.json",
  "artifacts/S_AI_ROLE_LIVE_TRANSCRIPT_scorecard.json",
  "artifacts/S_AI_ROLE_LIVE_TRANSCRIPT_transcripts.json",
  "artifacts/S_AI_DOMAIN_GATEWAY_matrix.json",
  "artifacts/S_BACKEND_SERVICE_BOUNDARY_matrix.json",
  "artifacts/S_CORE_WORKFLOWS_matrix.json",
  "artifacts/S_OBSERVABILITY_matrix.json",
  "artifacts/S_SECURITY_PRIVACY_matrix.json",
  "artifacts/S_RELEASE_PIPELINE_matrix.json",
  "artifacts/S_B2C_REQUEST_MARKETPLACE_VALIDATION_PDF_BACKEND_50K_scale_summary.json",
  "artifacts/S_B2C_REQUEST_MARKETPLACE_VALIDATION_PDF_BACKEND_50K_explain_detail.json",
  "artifacts/S_B2C_REQUEST_MARKETPLACE_VALIDATION_PDF_BACKEND_50K_idempotency.json",
  "artifacts/S_SCALE_01_BOUNDED_DATABASE_QUERIES_matrix.json",
  "artifacts/S_50K_READINESS_MASTER_MATRIX_REFRESH_7_matrix.json",
  "artifacts/S_50K_WAREHOUSE_REQ_ISSUE_MODAL_MARGIN_matrix.json",
  "artifacts/S_AI_DIRECTOR_REAL_COMPANY_FUNNEL_matrix.json",
  "artifacts/S_AI_CONSTRUCTION_INTENT_ESTIMATE_ENGINE_RECOVERY_matrix.json",
  "artifacts/S_AI_BUYER_REAL_SOURCING_FUNNEL_matrix.json",
  "artifacts/S_AI_ACCOUNTANT_REAL_FINANCE_FUNNEL_matrix.json",
  "artifacts/S_AI_CONTRACTOR_REAL_ACCEPTANCE_DELIVERY_FUNNEL_matrix.json",
  "artifacts/S_AI_SUPPLIER_CONTRACTOR_MARKETPLACE_INTAKE_matrix.json",
  "artifacts/S_GREEN_CLOSEOUT_matrix.json",
  "artifacts/S_UI_LIVE_LAYOUT_SHEETS_CHAT_CONTRACTOR_MEDIA_BLOCKER_FIX_matrix.json",
  "artifacts/S_UI_MOBILE_MESSENGER_MEDIA_AI_UX_REDESIGN_matrix.json",
  "artifacts/S_AI_ENTERPRISE_RELEASE_CLOSEOUT_CHANGE_CONTROL_matrix.json",

  "artifacts/S_B2C_REQUEST_EMBEDDED_AI_EXPANDED_ESTIMATE_FIX/matrix.json",
  "artifacts/S_B2C_REQUEST_EMBEDDED_AI_EXPANDED_ESTIMATE_FIX/failures.json",
  "artifacts/S_GLOBAL_LOCAL_ESTIMATE_PLATFORM/matrix.json",
  "artifacts/S_GLOBAL_LOCAL_ESTIMATE_PLATFORM/failures.json",
  "artifacts/S_LIVE_B2C_REQUEST_EMBEDDED_AI_ESTIMATE_REALITY/matrix.json",
  "artifacts/S_LIVE_B2C_REQUEST_EMBEDDED_AI_ESTIMATE_REALITY/failures.json",
  "artifacts/S_OPEN_WORLD_ESTIMATE_SEMANTIC_COVERAGE/matrix.json",
  "artifacts/S_OPEN_WORLD_ESTIMATE_SEMANTIC_COVERAGE/failures.json",
  "artifacts/S_OPEN_WORLD_PRIMITIVE_BOQ_COMPILER/matrix.json",
  "artifacts/S_OPEN_WORLD_PRIMITIVE_BOQ_COMPILER/failures.json",
  "artifacts/S_AI_ESTIMATE_PERFORMANCE/matrix.json",
  "artifacts/S_AI_ESTIMATE_PERFORMANCE/failures.json",
  "artifacts/S_AI_ESTIMATE_CHANGE_CONTROL/matrix.json",
  "artifacts/S_AI_ESTIMATE_CHANGE_CONTROL/failures.json",
  "artifacts/S_ANDROID_API34_CANONICAL_REPLAY_B2C_EXPANDED_ESTIMATE_BINDING/matrix.json",
  "artifacts/S_ANDROID_API34_CANONICAL_REPLAY_B2C_EXPANDED_ESTIMATE_BINDING/failures.json",
  "artifacts/S_LIVE_B2C_ESTIMATE_REALITY_RELEASE_CLOSEOUT/canonical_api34_evidence.json",
  "artifacts/S_RELEASE_PIPELINE_STABILIZATION/android_verify.json",

  "artifacts/S_CATALOG_WORK_PLATFORM_ADDITIVE_ONTOLOGY_MIGRATION/no_second_catalog_proof.json",
  "artifacts/S_CATALOG_WORK_PLATFORM_ADDITIVE_ONTOLOGY_MIGRATION/seed_matrix.json",
  "artifacts/S_CATALOG_WORK_PLATFORM_ADDITIVE_ONTOLOGY_MIGRATION/no_prompt_lookup_proof.json",
  "artifacts/S_CATALOG_WORK_PLATFORM_ADDITIVE_ONTOLOGY_MIGRATION/normalization_matrix.json",
  "artifacts/S_CATALOG_WORK_PLATFORM_ADDITIVE_ONTOLOGY_MIGRATION/standards_license_guard.json",
  "artifacts/S_CATALOG_WORK_PLATFORM_ADDITIVE_ONTOLOGY_MIGRATION/catalog_items_untouched_proof.json",
  "artifacts/S_CATALOG_WORK_PLATFORM_ADDITIVE_ONTOLOGY_MIGRATION/rls_policy_matrix.json",
  "artifacts/S_CATALOG_WORK_PLATFORM_ADDITIVE_ONTOLOGY_MIGRATION/repository_contract_matrix.json",
  "artifacts/S_CATALOG_WORK_PLATFORM_ADDITIVE_ONTOLOGY_MIGRATION/product_no_regression_matrix.json",

  "artifacts/S_AI_ESTIMATE_CANARY_EVALUATION/prerequisite_ledger.json",
  "artifacts/S_AI_ESTIMATE_CANARY_EVALUATION/evidence_ledger.json",
  "artifacts/S_AI_ESTIMATE_CANARY_EVALUATION/real_usage_evaluation.json",
  "artifacts/S_AI_ESTIMATE_CANARY_EVALUATION/decision_policy.json",
  "artifacts/S_AI_ESTIMATE_CANARY_EVALUATION/internal_canary_summary.json",
  "artifacts/S_AI_ESTIMATE_CANARY_EVALUATION/error_budget.json",
  "artifacts/S_AI_ESTIMATE_CANARY_EVALUATION/feedback_evaluation.json",
  "artifacts/S_AI_ESTIMATE_CANARY_EVALUATION/manual_estimator_review.json",
  "artifacts/S_AI_ESTIMATE_CANARY_EVALUATION/rollout_decision.json",
  "artifacts/S_AI_ESTIMATE_CANARY_EVALUATION/limited_public_beta_plan.json",
  "artifacts/S_AI_ESTIMATE_CANARY_EVALUATION/rollback_redrill.json",
  "artifacts/S_AI_ESTIMATE_CANARY_EVALUATION/web_results.json",
  "artifacts/S_AI_ESTIMATE_CANARY_EVALUATION/android_api34_results.json",
  "artifacts/S_AI_ESTIMATE_CANARY_EVALUATION/pdf_text_extract.json",
  "artifacts/S_AI_ESTIMATE_CANARY_EVALUATION/matrix.json",
  "artifacts/S_AI_ESTIMATE_CANARY_EVALUATION/proof.md",

  "artifacts/S_AI_ESTIMATE_INTERNAL_CANARY_EXECUTION/prerequisite_ledger.json",
  "artifacts/S_AI_ESTIMATE_INTERNAL_CANARY_EXECUTION/canary_policy.json",
  "artifacts/S_AI_ESTIMATE_INTERNAL_CANARY_EXECUTION/replay_results.json",
  "artifacts/S_AI_ESTIMATE_INTERNAL_CANARY_EXECUTION/error_budget.json",
  "artifacts/S_AI_ESTIMATE_INTERNAL_CANARY_EXECUTION/telemetry_audit.json",
  "artifacts/S_AI_ESTIMATE_INTERNAL_CANARY_EXECUTION/feedback_audit.json",
  "artifacts/S_AI_ESTIMATE_INTERNAL_CANARY_EXECUTION/kill_switch_drill.json",
  "artifacts/S_AI_ESTIMATE_INTERNAL_CANARY_EXECUTION/rollback_drill.json",
  "artifacts/S_AI_ESTIMATE_INTERNAL_CANARY_EXECUTION/web_results.json",
  "artifacts/S_AI_ESTIMATE_INTERNAL_CANARY_EXECUTION/android_api34_results.json",
  "artifacts/S_AI_ESTIMATE_INTERNAL_CANARY_EXECUTION/pdf_text_extract.json",
  "artifacts/S_AI_ESTIMATE_INTERNAL_CANARY_EXECUTION/failures.json",
  "artifacts/S_AI_ESTIMATE_INTERNAL_CANARY_EXECUTION/matrix.json",
  "artifacts/S_AI_ESTIMATE_INTERNAL_CANARY_EXECUTION/proof.md",

  "artifacts/S_MULTI_DOMAIN_PROFESSIONAL_BOQ_RECIPE_COMPILER_EXACT_MATERIALS/matrix.json",
  "artifacts/S_MULTI_DOMAIN_PROFESSIONAL_BOQ_RECIPE_COMPILER_EXACT_MATERIALS/live_ui_visible_label_proof.json",

  "artifacts/S_SELECTED_WORK_ENTERPRISE_VISIBLE_1000_REAL_INPUT_ESTIMATE_ACCEPTANCE/dataset_matrix.json",
  "artifacts/S_SELECTED_WORK_ENTERPRISE_VISIBLE_1000_REAL_INPUT_ESTIMATE_ACCEPTANCE/matrix.json",
  "artifacts/S_SELECTED_WORK_ENTERPRISE_VISIBLE_1000_REAL_INPUT_ESTIMATE_ACCEPTANCE/previous_green_validation.json",
  "artifacts/S_SELECTED_WORK_ENTERPRISE_VISIBLE_1000_REAL_INPUT_ESTIMATE_ACCEPTANCE/selected_work_matrix.json",
  "artifacts/S_SELECTED_WORK_ENTERPRISE_VISIBLE_1000_REAL_INPUT_ESTIMATE_ACCEPTANCE/quantity_matrix.json",
  "artifacts/S_SELECTED_WORK_ENTERPRISE_VISIBLE_1000_REAL_INPUT_ESTIMATE_ACCEPTANCE/boq_exact_materials_matrix.json",
  "artifacts/S_SELECTED_WORK_ENTERPRISE_VISIBLE_1000_REAL_INPUT_ESTIMATE_ACCEPTANCE/visible_label_scan.json",
  "artifacts/S_SELECTED_WORK_ENTERPRISE_VISIBLE_1000_REAL_INPUT_ESTIMATE_ACCEPTANCE/control_rows_scan.json",
  "artifacts/S_SELECTED_WORK_ENTERPRISE_VISIBLE_1000_REAL_INPUT_ESTIMATE_ACCEPTANCE/english_fallback_scan.json",
  "artifacts/S_SELECTED_WORK_ENTERPRISE_VISIBLE_1000_REAL_INPUT_ESTIMATE_ACCEPTANCE/catalog_label_matrix.json",
  "artifacts/S_SELECTED_WORK_ENTERPRISE_VISIBLE_1000_REAL_INPUT_ESTIMATE_ACCEPTANCE/ui_pdf_parity_matrix.json",
  "artifacts/S_SELECTED_WORK_ENTERPRISE_VISIBLE_1000_REAL_INPUT_ESTIMATE_ACCEPTANCE/request_history_foreman_parity_matrix.json",
  "artifacts/S_SELECTED_WORK_ENTERPRISE_VISIBLE_1000_REAL_INPUT_ESTIMATE_ACCEPTANCE/pdf_ready_1000_matrix.json",
  "artifacts/S_SELECTED_WORK_ENTERPRISE_VISIBLE_1000_REAL_INPUT_ESTIMATE_ACCEPTANCE/actual_pdf_250_matrix.json",
] as const;
