export const T8_PHASE_C_PRIMARY_ROOT_CAUSE_SUITES = Object.freeze({
  ROUTE_ADMIN_INVENTORY: "tests/app/route-contract.test.ts",
  REVISION_IDEMPOTENCY: "tests/requestEstimate/assumptionReplacementUi.test.ts",
  CONSOLE_GOVERNANCE: "src/lib/observability/console.governance.test.ts",
  EXTENDED_CANONICAL_PACK: "tests/estimateGolden/extended100Cases.contract.test.ts",
  TRANSPORT_MAP_DRIFT: "tests/architecture/transportOwnershipMap.test.ts",
  FLATLIST_STALE_PROOF: "tests/performance/flatListTuning.contract.test.ts",
  CATALOG_DEBOUNCE: "tests/requestEstimateSelectedWorkUx/catalogPickerLiveSearch.contract.test.tsx",
  OFFICE_FACADE_BUDGET: "tests/office/officeHubCollaborationSections.decomposition.test.ts",
  ROUTE_ESTIMATE_BOUNDARY: "tests/architecture/noRouteLocalEstimateLogic.contract.test.ts",
  TIMER_OWNER: "tests/scale/timerLifecycleCleanup.contract.test.ts",
  CENTRAL_JSON_PARSE: "tests/scale/sParse2JsonParse.contract.test.ts",
  REALTIME_OWNER_CLASSIFICATION: "tests/scale/realtimeManagerEnforcement.contract.test.ts",
  PDF_VISUAL_EVIDENCE: "tests/estimate/aiEstimate11610PdfVisualProof.contract.test.ts",
  REAL10000_UNIT_NORMALIZATION: "tests/real10000/real10000FailedUnit130Regression.contract.test.ts",
  CONSUMER_FEATURE_BOUNDARY: "tests/architecture/consumerRepairNoUnauthorizedDbWrite.contract.test.ts",
  CONSUMER_MOJIBAKE: "tests/requestEstimateSelectedWorkUx/mojibakeRootCauseScan.contract.test.ts",
  SEMANTIC_AI_FRAMEWORK_SCANNER: "tests/architecture/consumerRepairNoSecondAiFramework.contract.test.ts",
  CONSUMER_APPLICATION_SERVICE: "tests/architecture/globalEstimateNoOfficeLeakToConsumer.contract.test.ts",
  PDF_INTERNAL_KEY: "tests/estimateStructuredPipeline/noInternalKeysVisibleInPdf.contract.test.ts",
  AI_CHAT_RUNTIME: "tests/allScreensRuntime/aiChatEstimatePdfRuntime.contract.test.ts",
} as const);

export const T8_PHASE_C_SUPPLEMENTARY_SUITES = Object.freeze([
  "tests/release/t8PhaseCAdmissionManifest.contract.test.ts",
  "tests/aiEstimateV4/multiDomainIndependentGoldensV4.contract.test.ts",
  "tests/aiEstimateV4/multiDomainReferenceNlpV4.contract.test.ts",
  "tests/aiEstimateV4/roadScopeResolver120V4.contract.test.ts",
  "tests/pdf/pdfViewerDecompositionAudit.test.ts",
  "src/lib/api/f2_2_financeRollupMigration.test.ts",
  "tests/release/releaseGuard.shared.test.ts",
  "tests/aiEstimateV4/roadGeometry40V4.contract.test.ts",
  "src/lib/lifecycle/lifecycle.s3.test.ts",
  "tests/architecture/architectureAntiRegressionSuite.test.ts",
  "src/lib/api/f2_1_financeSummaryMigration.test.ts",
  "src/lib/offline/o5_offlineConflictClassifier.test.ts",
  "tests/scale/bffStagingServerBoundary.test.ts",
  "tests/android/androidAuthHarnessInputIdempotency.contract.test.ts",
  "tests/api/api-contract.test.ts",
  "tests/app/office-layout.test.tsx",
  "tests/pdf/pdfOpenLatencyAudit.test.ts",
  "src/screens/warehouse/w2_warehouseStockSummaryMigration.test.ts",
  "src/lib/offline/o4_offlineQueueRecovery.test.ts",
  "tests/release/boundedMigrationRunner.shared.test.ts",
  "tests/director/directorReportsControllerBoundary.test.ts",
  "src/screens/foreman/foreman.bootstrapReconciliation.test.ts",
  "tests/aiEstimateV4/multiDomainReferenceProductProjectionV4.contract.test.ts",
  "tests/navigation/officeReentryBreadcrumbs.test.ts",
  "tests/scale/rateEnforcementBoundary.test.ts",
  "src/lib/lifecycle/lifecycle.contract.test.ts",
  "tests/load/stagingLoadCore.test.ts",
  "src/screens/profile/profile.services.test.ts",
  "src/screens/foreman/foreman.draftLifecycle.model.test.ts",
  "tests/offline/offline-ux-consistency.test.ts",
  "tests/pdf/pdfMobilePreviewSizeGuard.test.ts",
  "tests/exports/export-import-boundary.test.ts",
  "tests/scale/cacheIntegrationBoundary.test.ts",
  "tests/catalog/catalog.request.transport.test.ts",
  "tests/errors/error-propagation.test.ts",
  "tests/modules/module-boundary.test.ts",
] as const);

export const T8_PHASE_C_ADMISSION_SUITES = Object.freeze([
  ...Object.values(T8_PHASE_C_PRIMARY_ROOT_CAUSE_SUITES),
  ...T8_PHASE_C_SUPPLEMENTARY_SUITES,
]);

export const T8_PHASE_C_EXPECTED_ROOT_CAUSES = 20;
export const T8_PHASE_C_MIN_SUITES = 56;
export const T8_PHASE_C_MIN_TESTS = 260;
