import type { AiReadyProposal } from "./aiScreenReadyProposalTypes";

function proposal(
  input: Omit<AiReadyProposal, "canExecuteDirectly" | "requiresApproval"> & { requiresApproval?: boolean },
): AiReadyProposal {
  return {
    ...input,
    requiresApproval: input.requiresApproval ?? input.actionKind === "approval_required",
    canExecuteDirectly: false,
  };
}

export const AI_SCREEN_READY_PROPOSAL_REGISTRY: readonly AiReadyProposal[] = [
  proposal({
    id: "buyer.main.inbox_triage",
    screenId: "buyer.main",
    domain: "procurement",
    title: "Разобрать входящие позиции",
    summary: "Сгруппировать заявки по срочности, статусу и готовности evidence.",
    evidence: ["screen_state:buyer_inbox", "policy:procurement_read"],
    riskLevel: "low",
    actionKind: "safe_read",
    primaryActionLabel: "Разобрать входящие",
  }),
  proposal({
    id: "buyer.main.compare_suppliers",
    screenId: "buyer.main",
    domain: "procurement",
    title: "Сравнить поставщиков",
    summary: "Сопоставить внутренние варианты, риски, документы, цены и сроки, если они есть в evidence.",
    evidence: ["screen_state:buyer_inbox", "tool_contract:compare_suppliers"],
    riskLevel: "low",
    actionKind: "safe_read",
    primaryActionLabel: "Сравнить поставщиков",
  }),
  proposal({
    id: "buyer.main.draft_request",
    screenId: "buyer.main",
    domain: "procurement",
    title: "Подготовить черновик запроса",
    summary: "Собрать draft для запроса поставщика без создания заказа и без подтверждения поставщика.",
    evidence: ["policy:draft_only", "approval_policy:procurement"],
    riskLevel: "medium",
    actionKind: "draft_only",
    primaryActionLabel: "Подготовить черновик",
  }),
  proposal({
    id: "buyer.main.submit_for_approval",
    screenId: "buyer.main",
    domain: "procurement",
    title: "Отправить на согласование",
    summary: "Передать пакет выбора поставщика через approval ledger.",
    evidence: ["approval_policy:required", "ledger:approval_required"],
    riskLevel: "high",
    actionKind: "approval_required",
    primaryActionLabel: "Отправить на согласование",
  }),
  proposal({
    id: "warehouse.main.stock_check",
    screenId: "warehouse.main",
    domain: "warehouse",
    title: "Проверить остатки",
    summary: "Показать доступные остатки, ожидаемый приход и риск дефицита.",
    evidence: ["screen_state:warehouse", "policy:warehouse_read"],
    riskLevel: "low",
    actionKind: "safe_read",
    primaryActionLabel: "Проверить остатки",
  }),
  proposal({
    id: "warehouse.main.shortage_risk",
    screenId: "warehouse.main",
    domain: "warehouse",
    title: "Найти риск дефицита",
    summary: "Выделить позиции, где заявка есть, а доступного количества недостаточно.",
    evidence: ["screen_state:warehouse", "report:low_stock"],
    riskLevel: "medium",
    actionKind: "safe_read",
    primaryActionLabel: "Проверить риски",
  }),
  proposal({
    id: "warehouse.main.draft_transfer",
    screenId: "warehouse.main",
    domain: "warehouse",
    title: "Подготовить черновик перемещения",
    summary: "Собрать черновик перемещения или дозакупки без складской мутации.",
    evidence: ["policy:draft_only", "approval_policy:warehouse"],
    riskLevel: "medium",
    actionKind: "draft_only",
    primaryActionLabel: "Черновик перемещения",
  }),
  proposal({
    id: "warehouse.main.submit_for_approval",
    screenId: "warehouse.main",
    domain: "warehouse",
    title: "Отправить на согласование",
    summary: "Складское изменение остаётся approval-required.",
    evidence: ["approval_policy:required", "ledger:approval_required"],
    riskLevel: "high",
    actionKind: "approval_required",
    primaryActionLabel: "Отправить на согласование",
  }),
  proposal({
    id: "accountant.payment.check",
    screenId: "accountant.payment",
    domain: "finance",
    title: "Проверить платеж",
    summary: "Сверить основание, документы, сумму, сроки и риск дубля.",
    evidence: ["screen_state:accountant_payment", "policy:finance_read"],
    riskLevel: "low",
    actionKind: "safe_read",
    primaryActionLabel: "Проверить платеж",
  }),
  proposal({
    id: "accountant.payment.risk",
    screenId: "accountant.payment",
    domain: "finance",
    title: "Найти риск",
    summary: "Показать причины, почему платеж стоит проверить до согласования.",
    evidence: ["screen_state:accountant_payment", "policy:risk_check"],
    riskLevel: "medium",
    actionKind: "safe_read",
    primaryActionLabel: "Проверить риски",
  }),
  proposal({
    id: "accountant.payment.rationale",
    screenId: "accountant.payment",
    domain: "finance",
    title: "Подготовить rationale",
    summary: "Собрать пояснение для согласования без создания оплаты.",
    evidence: ["policy:draft_only", "approval_policy:finance"],
    riskLevel: "medium",
    actionKind: "draft_only",
    primaryActionLabel: "Подготовить rationale",
  }),
  proposal({
    id: "accountant.payment.submit_for_approval",
    screenId: "accountant.payment",
    domain: "finance",
    title: "Отправить на согласование",
    summary: "Платёжное действие остаётся approval-required.",
    evidence: ["approval_policy:required", "ledger:approval_required"],
    riskLevel: "high",
    actionKind: "approval_required",
    primaryActionLabel: "Отправить на согласование",
  }),
  proposal({
    id: "foreman.main.missing_evidence",
    screenId: "foreman.main",
    domain: "projects",
    title: "Собрать missing evidence",
    summary: "Проверить, каких данных не хватает для заявки, акта, отчёта или сообщения.",
    evidence: ["screen_state:foreman", "policy:project_scope"],
    riskLevel: "low",
    actionKind: "safe_read",
    primaryActionLabel: "Собрать evidence",
  }),
  proposal({
    id: "foreman.main.draft_document",
    screenId: "foreman.main",
    domain: "projects",
    title: "Подготовить акт/отчёт/сообщение",
    summary: "Собрать черновик рабочего документа без финальной отправки.",
    evidence: ["policy:draft_only", "approval_policy:project"],
    riskLevel: "medium",
    actionKind: "draft_only",
    primaryActionLabel: "Подготовить черновик",
  }),
  proposal({
    id: "foreman.main.submit_for_approval",
    screenId: "foreman.main",
    domain: "projects",
    title: "Отправить на согласование",
    summary: "Передать подготовленный документ через согласование.",
    evidence: ["approval_policy:required", "ledger:approval_required"],
    riskLevel: "high",
    actionKind: "approval_required",
    primaryActionLabel: "Отправить на согласование",
  }),
  proposal({
    id: "director.dashboard.next_actions",
    screenId: "director.dashboard",
    domain: "control",
    title: "Показать срочные next actions",
    summary: "Собрать ближайшие решения по закупкам, складу, финансам и отчётам.",
    evidence: ["screen_state:director", "approval_inbox:summary"],
    riskLevel: "low",
    actionKind: "safe_read",
    primaryActionLabel: "Показать next actions",
  }),
  proposal({
    id: "director.dashboard.risks",
    screenId: "director.dashboard",
    domain: "control",
    title: "Показать риски",
    summary: "Выделить финансовые, закупочные и складские риски без исполнения действий.",
    evidence: ["screen_state:director", "policy:risk_check"],
    riskLevel: "medium",
    actionKind: "safe_read",
    primaryActionLabel: "Показать риски",
  }),
  proposal({
    id: "director.dashboard.approval_inbox",
    screenId: "director.dashboard",
    domain: "control",
    title: "Открыть approval inbox",
    summary: "Перейти к очереди согласований и evidence.",
    evidence: ["approval_inbox:route", "ledger:approval_required"],
    riskLevel: "high",
    actionKind: "approval_required",
    primaryActionLabel: "Открыть approval inbox",
  }),
  proposal({
    id: "documents.main.explain",
    screenId: "documents.main",
    domain: "documents",
    title: "Объяснить документ",
    summary: "Кратко объяснить назначение документа и связанный процесс.",
    evidence: ["document_metadata", "policy:document_read"],
    riskLevel: "low",
    actionKind: "safe_read",
    primaryActionLabel: "Объяснить документ",
  }),
  proposal({
    id: "documents.main.missing_evidence",
    screenId: "documents.main",
    domain: "documents",
    title: "Выделить missing evidence",
    summary: "Показать, каких реквизитов или подтверждений не хватает.",
    evidence: ["document_metadata", "policy:evidence_check"],
    riskLevel: "medium",
    actionKind: "safe_read",
    primaryActionLabel: "Проверить evidence",
  }),
  proposal({
    id: "documents.main.draft",
    screenId: "documents.main",
    domain: "documents",
    title: "Подготовить черновик",
    summary: "Собрать черновик ответа или сопроводительного текста без подписания и удаления.",
    evidence: ["policy:draft_only", "approval_policy:documents"],
    riskLevel: "medium",
    actionKind: "draft_only",
    primaryActionLabel: "Подготовить черновик",
  }),
];

export function listAiScreenReadyProposalRegistry(): AiReadyProposal[] {
  return [...AI_SCREEN_READY_PROPOSAL_REGISTRY];
}
