import { validateBuiltInAi50000RuntimeResult, BUILT_IN_AI_50000_FULL_CASES } from "../../src/lib/ai/builtInAi50000";
import type { BuiltInAiAnswer } from "../../src/lib/ai/builtInAi";

describe("built-in AI 50000 Phase 2 shard runner source guard", () => {
  it("fails an estimate result when priced rows have no source evidence", () => {
    const testCase = BUILT_IN_AI_50000_FULL_CASES.find((item) => item.intent === "estimate")!;
    const answer: BuiltInAiAnswer = {
      handled: true,
      route: {
        originalText: testCase.promptRu,
        screenContext: "chat",
        intent: "estimate",
        confidence: "high",
        mustUseBackendTool: true,
        allowedTools: ["calculate_global_estimate"],
        forbiddenFallbacks: testCase.forbiddenRowsContain,
        traceId: "missing-source-test",
        workKey: testCase.workKey,
        category: testCase.category,
        volume: testCase.volume,
        unit: testCase.unit,
      },
      runtimeTrace: {
        traceId: "missing-source-test",
        input: testCase.promptRu,
        screenContext: "chat",
        detectedIntent: "estimate",
        selectedRoute: "estimate",
        selectedTool: "calculate_global_estimate",
        workKey: testCase.workKey,
        category: testCase.category,
        volume: testCase.volume,
        unit: testCase.unit,
        backendCalled: true,
        outputContract: {
          hasTable: true,
          hasMaterials: true,
          hasLabor: true,
          hasSources: false,
          hasPdfAction: true,
        },
      },
      toolResult: {
        toolName: "calculate_global_estimate",
        backendCalled: true,
        estimate: {
          estimateId: "missing-source-estimate",
          work: { workKey: testCase.workKey, title: testCase.expectedRowsContain[0] ?? testCase.workKey, category: testCase.category },
          locale: {
            countryCode: "KG",
            addressPrecision: "country",
            language: "ru",
            locale: "ru-KG",
            unitSystem: "metric",
            currency: "KGS",
            taxMode: "unknown",
            taxIncludedByDefault: false,
            source: "fallback",
            confidence: "high",
          },
          input: {
            volume: testCase.volume ?? 1,
            unit: testCase.unit ?? "м²",
            originalText: testCase.promptRu,
          },
          assumptions: ["test assumption"],
          sections: [
            {
              sectionNumber: "1",
              title: "Материалы",
              type: "materials",
              rows: [
                {
                  rowNumber: "1.1",
                  code: "MAT-1",
                  name: testCase.expectedRowsContain[0] ?? "Материал",
                  quantity: 1,
                  unit: testCase.unit ?? "м²",
                  displayQuantity: "1",
                  unitPrice: 1,
                  displayUnitPrice: "1 KGS",
                  total: 1,
                  displayTotal: "1 KGS",
                  currency: "KGS",
                  priceStatus: "priced",
                  sourceId: "missing",
                  sourceEvidence: [],
                  confidence: "high",
                },
              ],
            },
            {
              sectionNumber: "2",
              title: "Работы",
              type: "labor",
              rows: [
                {
                  rowNumber: "2.1",
                  code: "LAB-1",
                  name: testCase.expectedRowsContain[1] ?? "Монтаж",
                  quantity: 1,
                  unit: testCase.unit ?? "м²",
                  displayQuantity: "1",
                  unitPrice: 1,
                  displayUnitPrice: "1 KGS",
                  total: 1,
                  displayTotal: "1 KGS",
                  currency: "KGS",
                  priceStatus: "priced",
                  sourceId: "missing",
                  sourceEvidence: [],
                  confidence: "high",
                },
              ],
            },
          ],
          tax: {
            taxType: "unknown",
            taxLabel: "Налог требует уточнения",
            taxableBase: 2,
            taxAmount: 0,
            included: false,
            requiresLocationPrecision: true,
            warning: "Нужно уточнить регион",
          },
          totals: {
            materialsTotal: 1,
            laborTotal: 1,
            equipmentTotal: 0,
            deliveryTotal: 0,
            taxTotal: 0,
            grandTotal: 2,
            currency: "KGS",
            displayMaterialsTotal: "1 KGS",
            displayLaborTotal: "1 KGS",
            displayTaxTotal: "0 KGS",
            displayGrandTotal: "2 KGS",
          },
          outputContract: {
            format: "professional_boq",
            hasIntro: true,
            hasAssumptions: true,
            hasMaterialsSection: true,
            hasLaborSection: true,
            hasGrandTotal: true,
            hasTaxStatus: true,
            hasRegionalRisks: true,
            hasClarifyingQuestions: true,
          },
          regionalRisks: [{ title: "Регион", text: "Нужно уточнить регион" }],
          costIncreaseFactors: ["scope"],
          clarifyingQuestions: ["location?"],
          sources: [],
          confidence: "high",
          requiresReview: false,
        },
      },
      actions: [{ id: "make_pdf", labelRu: "Сделать PDF", toolName: "generate_estimate_pdf", visible: true }],
      answerTextRu: "ok",
    };
    expect(validateBuiltInAi50000RuntimeResult(testCase, answer).failureCodes).toContain("SOURCE_EVIDENCE_MISSING");
  });
});
