import type { GlobalTaxRule } from "./globalEstimateTypes";

const CHECKED_AT = "2026-05-22T00:00:00+06:00";
const EFFECTIVE_FROM = "2026-01-01";

/**
 * Tax lookup is a latency-sensitive boundary used by every estimate.
 * Keep these rules isolated from the much larger work/rate seed catalog so a
 * canonical estimate does not evaluate thousands of unrelated work records
 * merely to resolve one country tax rule.
 */
export const GLOBAL_TAX_RULES: readonly GlobalTaxRule[] = [
  {
    id: "tax_us_tx_dallas_75201_sales_tax_configured",
    countryCode: "US",
    stateOrRegion: "TX",
    city: "Dallas",
    postalCode: "75201",
    taxType: "sales_tax",
    taxLabel: "Estimated Dallas TX sales tax",
    taxRate: 0.0825,
    appliesTo: "materials",
    customerType: "unknown",
    projectType: "unknown",
    includedInPrice: false,
    requiresPreciseAddress: true,
    requiredPrecision: "postal_code",
    sourceType: "configured_reference",
    sourceLabel:
      "Configured US sales tax reference; validate with address-based tax provider before billing",
    effectiveFrom: EFFECTIVE_FROM,
    checkedAt: CHECKED_AT,
    active: true,
  },
  {
    id: "tax_kg_nds_configured",
    countryCode: "KG",
    taxType: "nds",
    taxLabel: "НДС Кыргызстан",
    taxRate: 0.12,
    appliesTo: "all",
    customerType: "unknown",
    projectType: "unknown",
    includedInPrice: false,
    requiresPreciseAddress: false,
    sourceType: "configured_reference",
    sourceLabel: "Configured Kyrgyzstan NDS reference",
    effectiveFrom: EFFECTIVE_FROM,
    checkedAt: CHECKED_AT,
    active: true,
  },
  {
    id: "tax_de_vat_standard_configured",
    countryCode: "DE",
    taxType: "vat",
    taxLabel: "VAT Germany standard reference",
    taxRate: 0.19,
    appliesTo: "all",
    customerType: "unknown",
    projectType: "unknown",
    includedInPrice: true,
    requiresPreciseAddress: false,
    sourceType: "configured_reference",
    sourceLabel:
      "Configured EU VAT reference; category-specific reduced rates require review",
    effectiveFrom: EFFECTIVE_FROM,
    checkedAt: CHECKED_AT,
    active: true,
  },
  {
    id: "tax_fr_vat_standard_configured",
    countryCode: "FR",
    taxType: "vat",
    taxLabel: "TVA France standard reference",
    taxRate: 0.2,
    appliesTo: "all",
    customerType: "unknown",
    projectType: "unknown",
    includedInPrice: true,
    requiresPreciseAddress: false,
    sourceType: "configured_reference",
    sourceLabel:
      "Configured EU VAT reference; category-specific reduced rates require review",
    effectiveFrom: EFFECTIVE_FROM,
    checkedAt: CHECKED_AT,
    active: true,
  },
  {
    id: "tax_gb_vat_standard_configured",
    countryCode: "GB",
    taxType: "vat",
    taxLabel: "VAT UK standard reference",
    taxRate: 0.2,
    appliesTo: "all",
    customerType: "unknown",
    projectType: "unknown",
    includedInPrice: true,
    requiresPreciseAddress: false,
    sourceType: "configured_reference",
    sourceLabel:
      "Configured UK VAT reference; project category requires review",
    effectiveFrom: EFFECTIVE_FROM,
    checkedAt: CHECKED_AT,
    active: true,
  },
  {
    id: "tax_sg_gst_configured",
    countryCode: "SG",
    taxType: "gst",
    taxLabel: "Singapore GST reference",
    taxRate: 0.09,
    appliesTo: "all",
    customerType: "unknown",
    projectType: "unknown",
    includedInPrice: false,
    requiresPreciseAddress: false,
    sourceType: "configured_reference",
    sourceLabel: "Configured Singapore GST reference",
    effectiveFrom: EFFECTIVE_FROM,
    checkedAt: CHECKED_AT,
    active: true,
  },
  {
    id: "tax_ae_vat_configured",
    countryCode: "AE",
    taxType: "vat",
    taxLabel: "UAE VAT reference",
    taxRate: 0.05,
    appliesTo: "all",
    customerType: "unknown",
    projectType: "unknown",
    includedInPrice: false,
    requiresPreciseAddress: false,
    sourceType: "configured_reference",
    sourceLabel: "Configured UAE VAT reference",
    effectiveFrom: EFFECTIVE_FROM,
    checkedAt: CHECKED_AT,
    active: true,
  },
  {
    id: "tax_in_gst_configured",
    countryCode: "IN",
    taxType: "gst",
    taxLabel: "India GST reference",
    taxRate: 0.18,
    appliesTo: "all",
    customerType: "unknown",
    projectType: "unknown",
    includedInPrice: false,
    requiresPreciseAddress: false,
    sourceType: "configured_reference",
    sourceLabel:
      "Configured India GST reference; work/material category requires review",
    effectiveFrom: EFFECTIVE_FROM,
    checkedAt: CHECKED_AT,
    active: true,
  },
];
