export const calculateGlobalEstimateToolSchema = {
  name: "calculate_global_estimate",
  description: "Calculates localized construction estimate using regional prices, local units and tax rules.",
  parameters: {
    type: "object",
    properties: {
      work_type: { type: "string" },
      volume: { type: "number" },
      unit: { type: "string" },
      country_code: { type: "string" },
      state_or_region: { type: "string" },
      county: { type: "string" },
      city: { type: "string" },
      postal_code: { type: "string" },
      language: { type: "string" },
      locale: { type: "string" },
      currency: { type: "string" },
      price_tier: { type: "string", enum: ["budget", "standard", "premium"] },
      tax_preference: { type: "string", enum: ["included", "added", "auto"] },
      project_type: { type: "string", enum: ["residential", "commercial", "industrial", "unknown"] },
      customer_type: { type: "string", enum: ["b2c", "b2b", "unknown"] },
      surface_condition: { type: "string", enum: ["good", "needs_preparation", "unknown"] },
      include_materials: { type: "boolean" },
      include_labor: { type: "boolean" },
      include_delivery: { type: "boolean" },
      include_tax: { type: "boolean" },
      original_text: { type: "string" },
    },
    required: ["work_type", "volume", "unit"],
  },
} as const;

export function mapGlobalEstimateToolInput(input: Record<string, unknown>) {
  return {
    explicitWorkKey: typeof input.work_type === "string" ? input.work_type : undefined,
    volume: typeof input.volume === "number" ? input.volume : undefined,
    unit: typeof input.unit === "string" ? input.unit : undefined,
    countryCode: typeof input.country_code === "string" ? input.country_code : undefined,
    stateOrRegion: typeof input.state_or_region === "string" ? input.state_or_region : undefined,
    county: typeof input.county === "string" ? input.county : undefined,
    city: typeof input.city === "string" ? input.city : undefined,
    postalCode: typeof input.postal_code === "string" ? input.postal_code : undefined,
    language: typeof input.language === "string" ? input.language : undefined,
    locale: typeof input.locale === "string" ? input.locale : undefined,
    currency: typeof input.currency === "string" ? input.currency : undefined,
    priceTier: input.price_tier === "budget" || input.price_tier === "standard" || input.price_tier === "premium" ? input.price_tier : undefined,
    projectType: input.project_type === "residential" || input.project_type === "commercial" || input.project_type === "industrial" || input.project_type === "unknown" ? input.project_type : undefined,
    customerType: input.customer_type === "b2c" || input.customer_type === "b2b" || input.customer_type === "unknown" ? input.customer_type : undefined,
    surfaceCondition: input.surface_condition === "good" || input.surface_condition === "needs_preparation" || input.surface_condition === "unknown" ? input.surface_condition : undefined,
    includeMaterials: typeof input.include_materials === "boolean" ? input.include_materials : undefined,
    includeLabor: typeof input.include_labor === "boolean" ? input.include_labor : undefined,
    includeDelivery: typeof input.include_delivery === "boolean" ? input.include_delivery : undefined,
    includeTax: typeof input.include_tax === "boolean" ? input.include_tax : undefined,
    taxPreference: input.tax_preference === "included" || input.tax_preference === "added" || input.tax_preference === "auto" ? input.tax_preference : undefined,
    text: typeof input.original_text === "string" ? input.original_text : undefined,
  };
}
