import type {
  CatalogWorkV4,
  NormativeEvidenceV4,
  WorkIdentityV4,
  WorkScopeV4,
  WbsNodeV4,
} from "../professionalEstimateV4Contract";
import { ASPHALT_WORK_SPECIFIC_PARAMETER_SCHEMA_V4 } from "./asphaltWorkSpecificParameterSchemaV4";
import {
  ASPHALT_FAMILY_ID_V4,
  ASPHALT_PASSPORT_VERSION_V4,
  ASPHALT_PROFESSIONAL_NAME_RU_V4,
  ASPHALT_WORK_ID_V4,
} from "./asphaltV4Constants";

export const ASPHALT_CATALOG_WORK_V4: CatalogWorkV4 = {
  stable_work_id: ASPHALT_WORK_ID_V4,
  catalog_version: ASPHALT_PASSPORT_VERSION_V4,
  active: true,
};

export const ASPHALT_WORK_IDENTITY_V4: WorkIdentityV4 = {
  stable_work_id: ASPHALT_WORK_ID_V4,
  professional_name_ru: ASPHALT_PROFESSIONAL_NAME_RU_V4,
  synonyms_ru: ["асфальтирование", "укладка асфальта", "асфальтобетонное покрытие", "ремонт асфальтового покрытия"],
  industry: "road_construction",
  family_id: ASPHALT_FAMILY_ID_V4,
  action: "устройство",
  object: "асфальтобетонное дорожное покрытие",
  technology: "послойное устройство дорожной одежды с асфальтобетонным покрытием",
  purpose: "получение измеримого покрытия с подтверждаемым составом слоёв и контролем качества",
};

export const ASPHALT_WORK_SCOPE_V4: WorkScopeV4 = {
  scope_class: "trade_assembly",
  purpose_ru: "Устройство или ремонт асфальтобетонного покрытия по подтверждённой геометрии и послойной конструкции.",
  included_scope_ru: [
    "подтверждённые подготовительные операции",
    "послойные материалы и работы дорожной одежды",
    "асфальтобетонные смеси по отдельным слоям",
    "подтверждённые машины, труд, транспорт и лабораторный контроль",
    "закупочная ведомость материалов с техническими спецификациями",
  ],
  excluded_scope_ru: [
    "бетонное дорожное покрытие",
    "неподтверждённые трубы, водоотвод, знаки и барьерные ограждения",
    "скрытые цены и итог 0 сом при отсутствии цен",
    "проектирование дорожной одежды и окончательная инженерная экспертиза",
  ],
  applicability_rules: [
    "фрезерование включается только для ремонта при подтверждённом milling_required",
    "песок, щебень, геотекстиль и каждый асфальтобетонный слой включаются раздельно по фактам",
    "бордюр, водоотвод, знаки и ограждение включаются только при положительном измеримом объёме",
    "испытания включаются только по выбранной программе контроля и её измеримой частоте",
  ],
  complexity_rules: [
    "количество BOQ-строк определяется применимыми слоями и ресурсами, а не фиксированным размером",
    "каждый слой имеет собственную спецификацию, формулу и explanation trace",
    "неподтверждённая производительность блокирует соответствующие трудо- и машино-часы, но не материальные количества",
  ],
  regional_conditions: ["регион, сезон, расстояние до АБЗ и расстояние вывоза задаются отдельно"],
};

export const ASPHALT_WBS_V4: readonly WbsNodeV4[] = [
  { wbs_code: "01", parent_wbs_code: null, title_ru: "Исходные данные и геодезия", phase: "preparation", applicability: "always", sequence: 10 },
  { wbs_code: "02", parent_wbs_code: null, title_ru: "Подготовка существующего покрытия", phase: "preparation", applicability: "construction_mode == repair", sequence: 20 },
  { wbs_code: "03", parent_wbs_code: null, title_ru: "Основание дорожной одежды", phase: "base", applicability: "base_layers_applicable", sequence: 30 },
  { wbs_code: "04", parent_wbs_code: null, title_ru: "Асфальтобетонное покрытие", phase: "pavement", applicability: "always", sequence: 40 },
  { wbs_code: "05", parent_wbs_code: null, title_ru: "Обустройство и водоотвод", phase: "road_furniture", applicability: "conditional_scope_confirmed", sequence: 50 },
  { wbs_code: "06", parent_wbs_code: null, title_ru: "Контроль качества", phase: "quality", applicability: "laboratory_control_confirmed", sequence: 60 },
  { wbs_code: "07", parent_wbs_code: null, title_ru: "Транспорт и закупки", phase: "logistics", applicability: "materials_or_waste_applicable", sequence: 70 },
];

export const ASPHALT_NORMATIVE_EVIDENCE_V4: readonly NormativeEvidenceV4[] = [
  {
    source_id: "eaeu_tr_ts_014_2011",
    url_or_document_id: "https://eec.eaeunion.org/comission/department/deptexreg/tr/bezopAutodorog.php",
    title: "ТР ТС 014/2011 «Безопасность автомобильных дорог»",
    organization: "Евразийская экономическая комиссия",
    jurisdiction: "ЕАЭС / Кыргызская Республика",
    effective_date: "2015-02-15",
    accessed_at: "2026-07-22",
    applicability: "Обязательная рамка безопасности для проектирования, строительства, реконструкции, ремонта и эксплуатации дорог; не является источником произвольных количественных коэффициентов.",
    version: "Решение Комиссии Таможенного союза №827 от 2011-10-18",
    checksum: "external_official_source_verify_at_release",
    license_state: "official_publication_link",
    linked_row_ids: [],
    linked_parameter_ids: [],
    extracted_fact_ids: [],
    confidence: "high",
  },
  {
    source_id: "kg_mtd_road_quality_control",
    url_or_document_id: "https://mtd.gov.kg/polozhenie-ob-obespechenii-sistemnosti-kontrolya-kachestva-rabot-pri-stroitelstve-rekonstruktsii-i-remonte-avtomobilnyh-dorog-obshhego-polzovaniya/",
    title: "Положение об обеспечении системности контроля качества дорожных работ",
    organization: "Министерство транспорта и коммуникаций Кыргызской Республики",
    jurisdiction: "Кыргызская Республика",
    effective_date: "unknown",
    accessed_at: "2026-07-22",
    applicability: "Подтверждает необходимость входного, операционного и приёмочного контроля по проекту и применимой нормативно-технической документации.",
    version: "web publication accessed 2026-07-22",
    checksum: "external_official_source_verify_at_release",
    license_state: "official_publication_link",
    linked_row_ids: ["laboratory_tests"],
    linked_parameter_ids: [],
    extracted_fact_ids: [],
    confidence: "high",
  },
  {
    source_id: "kg_krer_2015_collection_27",
    url_or_document_id: "https://minstroy.gov.kg/ru/kyzmat/443/show",
    title: "КРЕР-2015, сборник №27 «Автомобильные дороги»",
    organization: "Министерство строительства Кыргызской Республики",
    jurisdiction: "Кыргызская Республика",
    effective_date: "2015-01-01",
    accessed_at: "2026-07-22",
    applicability: "Кандидатный официальный источник ресурсов и производительностей; конкретная таблица должна быть выбрана и подтверждена для конструкции и условий проекта.",
    version: "КРЕР-2015",
    checksum: "external_official_source_verify_at_release",
    license_state: "official_publication_link",
    linked_row_ids: [],
    linked_parameter_ids: [],
    extracted_fact_ids: [],
    confidence: "high",
  },
  {
    source_id: "kg_sp_kr_32_107_2024_consultation_draft",
    url_or_document_id: "https://minstroy.gov.kg/index.php/ru/document/102/show",
    title: "Проект СП КР 32-107:2024 «Автомобильные дороги»",
    organization: "Министерство строительства Кыргызской Республики",
    jurisdiction: "Кыргызская Республика",
    effective_date: "not_effective_consultation_draft",
    accessed_at: "2026-07-22",
    applicability: "Только навигационный технический источник: страница обозначает документ как проект общественного обсуждения. Запрещено считать действующей нормой без проверки утверждения.",
    version: "consultation draft published 2024-06-24",
    checksum: "external_official_source_verify_at_release",
    license_state: "official_consultation_publication_link",
    linked_row_ids: [],
    linked_parameter_ids: [],
    extracted_fact_ids: [],
    confidence: "medium",
  },
  {
    source_id: "world_bank_road_boq_structure",
    url_or_document_id: "https://documents1.worldbank.org/curated/en/099008211282534197/pdf/IDU-4a40e516-dd5d-4265-9ac4-cd3a1ce94000.pdf",
    title: "Standard Procurement Document: Bill of Quantities for Road Rehabilitation and Improvement Works",
    organization: "World Bank",
    jurisdiction: "international procurement reference",
    effective_date: "2025-11-01",
    accessed_at: "2026-07-22",
    applicability: "Публичный профессиональный пример структуры BOQ: количества должны следовать обследованию, спецификациям и чертежам; источник не копируется как норма количества.",
    version: "standard procurement document accessed 2026-07-22",
    checksum: "external_primary_source_verify_at_release",
    license_state: "public_document_link",
    linked_row_ids: [],
    linked_parameter_ids: [],
    extracted_fact_ids: [],
    confidence: "medium",
  },
  {
    source_id: "manufacturer_bitumina_emulsion_technical_note",
    url_or_document_id: "https://www.bitumina.co.uk/bitumen-emulsions.html",
    title: "Bitumen Emulsions — technical application note",
    organization: "BITUMINA",
    jurisdiction: "manufacturer technical reference",
    effective_date: "unknown",
    accessed_at: "2026-07-22",
    applicability: "Подтверждает назначение tack coat между слоями; конкретная норма розлива должна поступать из проекта или техкарты выбранного материала.",
    version: "web technical note accessed 2026-07-22",
    checksum: "external_manufacturer_source_verify_at_release",
    license_state: "manufacturer_publication_link",
    linked_row_ids: ["emulsion_material"],
    linked_parameter_ids: [],
    extracted_fact_ids: [],
    confidence: "medium",
  },
];

export const ASPHALT_PROFESSIONAL_PASSPORT_BASE_V4 = {
  catalog_work: ASPHALT_CATALOG_WORK_V4,
  identity: ASPHALT_WORK_IDENTITY_V4,
  scope: ASPHALT_WORK_SCOPE_V4,
  parameter_schema: ASPHALT_WORK_SPECIFIC_PARAMETER_SCHEMA_V4,
  wbs: [...ASPHALT_WBS_V4],
  normative_evidence: [...ASPHALT_NORMATIVE_EVIDENCE_V4],
  expert_review_status: "EXPERT_REVIEW_REQUIRED" as const,
  assumptions_ru: ["Количества не получают скрытых типовых коэффициентов: отсутствующие нормы блокируют только зависимые строки."],
  uncertainty_ru: ["Типы слоёв, производительности, коэффициенты, программа испытаний и применимость условных элементов требуют проекта или дорожного инженера."],
};
