import type { AiSafeActionKind, AiSafeActionRegistryEntry } from "./aiSafeActionTypes";

const COMMON_GKL_REFS = [
  "golden:procurement_request:req_124",
  "golden:work:work_31",
  "golden:warehouse_issue:warehouse_issue_88",
  "golden:warehouse_stock:warehouse_stock_gkl",
] as const;

const PAYMENT_REFS = [
  "golden:payment:payment_77",
  "golden:payment:payment_78",
  "golden:payment:payment_79",
  "golden:pdf_document:pdf_invoice_45",
  "golden:procurement_request:req_124",
  "golden:work:work_31",
] as const;

export const AI_SAFE_ACTION_REGISTRY: readonly AiSafeActionRegistryEntry[] = [
  {
    actionKind: "procurement_purchase_draft",
    titleRu: "Подготовить черновик закупки",
    defaultRole: "buyer",
    defaultScreenId: "buyer.procurement",
    mode: "approval_required",
    draftType: "purchase_request",
    ledgerActionType: "draft_request",
    requiredSourceRefIds: [...COMMON_GKL_REFS, "golden:marketplace_product:market_product_gkl_12_5"],
    approvalType: "director_approval",
    approverRoles: ["director"],
    forbiddenFinalActionsRu: [
      "закупка не создана финально",
      "поставщик не выбран автоматически",
      "склад не изменен",
      "директор не утвердил автоматически",
    ],
  },
  {
    actionKind: "warehouse_deficit_request_draft",
    titleRu: "Подготовить заявку на дефицит",
    defaultRole: "warehouse",
    defaultScreenId: "warehouse.trace",
    mode: "approval_required",
    draftType: "purchase_request",
    ledgerActionType: "draft_request",
    requiredSourceRefIds: [...COMMON_GKL_REFS],
    approvalType: "director_approval",
    approverRoles: ["director", "buyer"],
    forbiddenFinalActionsRu: [
      "склад не изменен",
      "товар не списан",
      "товар не выдан",
      "закупка не создана финально",
    ],
  },
  {
    actionKind: "warehouse_discrepancy_draft",
    titleRu: "Подготовить акт расхождения",
    defaultRole: "warehouse",
    defaultScreenId: "warehouse.discrepancy",
    mode: "approval_required",
    draftType: "warehouse_discrepancy",
    ledgerActionType: "draft_report",
    requiredSourceRefIds: [...COMMON_GKL_REFS],
    approvalType: "warehouse_manager_review",
    approverRoles: ["warehouse", "director"],
    forbiddenFinalActionsRu: ["остатки не изменены", "акт расхождения не создан финально"],
  },
  {
    actionKind: "accountant_payment_checklist_draft",
    titleRu: "Подготовить чеклист оплаты",
    defaultRole: "accountant",
    defaultScreenId: "accountant.payments",
    mode: "draft_only",
    draftType: "payment_checklist",
    ledgerActionType: "finance_risk",
    requiredSourceRefIds: [...PAYMENT_REFS],
    approvalType: "accountant_review",
    approverRoles: ["accountant"],
    forbiddenFinalActionsRu: ["платежи не проведены", "проводки не утверждены", "документы не созданы автоматически"],
  },
  {
    actionKind: "accounting_entry_reference_draft",
    titleRu: "Подготовить справку по проводке",
    defaultRole: "accountant",
    defaultScreenId: "accountant.entries",
    mode: "draft_only",
    draftType: "payment_checklist",
    ledgerActionType: "finance_risk",
    requiredSourceRefIds: ["golden:payment:payment_77", "golden:pdf_document:pdf_invoice_45"],
    approvalType: "accountant_review",
    approverRoles: ["accountant"],
    forbiddenFinalActionsRu: ["проводка не утверждена", "платеж не проведен", "требуется проверка бухгалтером"],
  },
  {
    actionKind: "foreman_act_draft",
    titleRu: "Подготовить черновик акта",
    defaultRole: "foreman",
    defaultScreenId: "foreman.closeout",
    mode: "approval_required",
    draftType: "act_draft",
    ledgerActionType: "draft_act",
    requiredSourceRefIds: ["golden:work:work_32", "golden:work:work_31"],
    approvalType: "foreman_review",
    approverRoles: ["foreman", "director"],
    forbiddenFinalActionsRu: ["акт не подписан", "работа не закрыта", "подрядчик не принят автоматически"],
  },
  {
    actionKind: "work_closeout_checklist_draft",
    titleRu: "Подготовить чеклист закрытия работы",
    defaultRole: "foreman",
    defaultScreenId: "foreman.closeout",
    mode: "draft_only",
    draftType: "act_draft",
    ledgerActionType: "draft_act",
    requiredSourceRefIds: ["golden:work:work_31", "golden:work:work_32", "golden:work:work_34"],
    approvalType: "foreman_review",
    approverRoles: ["foreman"],
    forbiddenFinalActionsRu: ["работа не закрыта", "акт не подписан"],
  },
  {
    actionKind: "contractor_remark_response_draft",
    titleRu: "Подготовить ответ по замечанию",
    defaultRole: "contractor",
    defaultScreenId: "contractor.acceptance",
    mode: "draft_only",
    draftType: "reminder",
    ledgerActionType: "draft_report",
    requiredSourceRefIds: ["golden:contractor:contractor_golden", "golden:work:work_31"],
    approvalType: "none",
    approverRoles: [],
    forbiddenFinalActionsRu: ["замечание не закрыто", "работа не принята", "оплата не обещана"],
  },
  {
    actionKind: "document_link_suggestion_draft",
    titleRu: "Подготовить черновик связи документа",
    defaultRole: "documents",
    defaultScreenId: "documents.invoice",
    mode: "approval_required",
    draftType: "document_link",
    ledgerActionType: "document_send",
    requiredSourceRefIds: [
      "golden:pdf_document:pdf_invoice_45",
      "golden:invoice:invoice_45",
      "golden:payment:payment_77",
      "golden:procurement_request:req_124",
    ],
    approvalType: "document_review",
    approverRoles: ["accountant", "office"],
    forbiddenFinalActionsRu: ["документ не связан финально", "платеж не проведен", "акт не создан"],
  },
  {
    actionKind: "marketplace_product_card_draft",
    titleRu: "Подготовить карточку товара",
    defaultRole: "marketplace_user",
    defaultScreenId: "marketplace.productDraft",
    mode: "approval_required",
    draftType: "marketplace_product",
    ledgerActionType: "draft_request",
    requiredSourceRefIds: ["golden:marketplace_product:market_product_gkl_12_5"],
    approvalType: "marketplace_moderation",
    approverRoles: ["marketplace_user", "admin"],
    forbiddenFinalActionsRu: ["товар не опубликован", "цена не придумана", "остаток не создан", "поставщик не назначен автоматически"],
  },
  {
    actionKind: "office_reminder_draft",
    titleRu: "Подготовить напоминание",
    defaultRole: "office",
    defaultScreenId: "office.stuckTasks",
    mode: "draft_only",
    draftType: "reminder",
    ledgerActionType: "draft_report",
    requiredSourceRefIds: ["golden:payment:payment_77", "golden:pdf_document:pdf_invoice_45", "golden:procurement_request:req_124"],
    approvalType: "none",
    approverRoles: [],
    forbiddenFinalActionsRu: ["напоминание не отправлено", "задачи не закрыты", "approval не изменен"],
  },
  {
    actionKind: "client_progress_report_draft",
    titleRu: "Подготовить клиентский отчет",
    defaultRole: "client",
    defaultScreenId: "client.progress",
    mode: "approval_required",
    draftType: "client_report",
    ledgerActionType: "draft_report",
    requiredSourceRefIds: ["golden:report:client_weekly_report", "golden:work:work_31"],
    approvalType: "client_report_review",
    approverRoles: ["office", "director"],
    forbiddenFinalActionsRu: ["отчет не опубликован клиенту", "внутренние финансы не раскрыты"],
  },
] as const;

export function listAiSafeActionRegistryEntries(): AiSafeActionRegistryEntry[] {
  return [...AI_SAFE_ACTION_REGISTRY];
}

export function getAiSafeActionRegistryEntry(actionKind: AiSafeActionKind): AiSafeActionRegistryEntry {
  const entry = AI_SAFE_ACTION_REGISTRY.find((candidate) => candidate.actionKind === actionKind);
  if (!entry) {
    throw new Error(`Unknown safe action kind: ${actionKind}`);
  }
  return entry;
}
