import type { ExpandedComplexCalculatorId, ExpandedComplexUnit } from "../index";
import type { S2BWave2Kind } from "./types";

export type S2BReadinessStatus = "SOFTWARE_READY_FOR_DOMAIN_EXPERT_REVIEW";

export type S2BFamilyManifestEntry = {
  work_family_id: string;
  calculator_id: ExpandedComplexCalculatorId;
  kind: S2BWave2Kind;
  parameter_passport_id: string;
  required_p0_parameters: readonly string[];
  required_domain_blocks: readonly string[];
  allowed_units: readonly ExpandedComplexUnit[];
  forbidden_calculators: readonly ExpandedComplexCalculatorId[];
  formula_trace_required: true;
  price_policy: "PRICE_MISSING_NO_FINAL_TOTAL";
  safety_policy: "STANDARD_PRELIMINARY_NOTICE" | "REGULATED_ENGINEERING_REVIEW_REQUIRED";
  readiness_status: S2BReadinessStatus;
  blocking_reasons: readonly string[];
};

const ready = "SOFTWARE_READY_FOR_DOMAIN_EXPERT_REVIEW" as const;

export const S2B_INFRASTRUCTURE_FAMILY_MANIFEST: readonly S2BFamilyManifestEntry[] = [
  {
    work_family_id: "asphalt_concrete_pavement",
    calculator_id: "roadConstructionCalculator",
    kind: "road",
    parameter_passport_id: "expanded_complex.transport.road_surface.v1",
    required_p0_parameters: ["area_m2"],
    required_domain_blocks: ["earthworks", "base", "asphalt_lower", "drainage", "laboratory"],
    allowed_units: ["m2", "m3", "m", "t", "l", "pcs", "set", "shift", "hour", "trip"],
    forbidden_calculators: ["highRiseBuildingCalculator", "sewerNetworkCalculator", "villageWaterSupplyCalculator"],
    formula_trace_required: true,
    price_policy: "PRICE_MISSING_NO_FINAL_TOTAL",
    safety_policy: "STANDARD_PRELIMINARY_NOTICE",
    readiness_status: ready,
    blocking_reasons: [],
  },
  {
    work_family_id: "road_construction",
    calculator_id: "roadConstructionCalculator",
    kind: "road",
    parameter_passport_id: "expanded_complex.transport.road_linear.v1",
    required_p0_parameters: ["length_m", "width_m"],
    required_domain_blocks: ["subgrade", "geotextile", "crushed_stone", "asphalt_upper", "marking"],
    allowed_units: ["m2", "m3", "m", "t", "l", "pcs", "set", "shift", "hour", "trip"],
    forbidden_calculators: ["highRiseBuildingCalculator", "sewerNetworkCalculator", "villageWaterSupplyCalculator"],
    formula_trace_required: true,
    price_policy: "PRICE_MISSING_NO_FINAL_TOTAL",
    safety_policy: "STANDARD_PRELIMINARY_NOTICE",
    readiness_status: ready,
    blocking_reasons: [],
  },
  {
    work_family_id: "village_water_supply",
    calculator_id: "villageWaterSupplyCalculator",
    kind: "water",
    parameter_passport_id: "expanded_complex.water_supply.linear_pipe.v1",
    required_p0_parameters: ["length_m", "diameter_mm"],
    required_domain_blocks: ["trench", "pipe", "fittings", "valves", "disinfection"],
    allowed_units: ["m", "m3", "pcs", "set", "shift", "trip", "hour"],
    forbidden_calculators: ["sewerNetworkCalculator", "stormwaterNetworkCalculator", "highRiseBuildingCalculator"],
    formula_trace_required: true,
    price_policy: "PRICE_MISSING_NO_FINAL_TOTAL",
    safety_policy: "STANDARD_PRELIMINARY_NOTICE",
    readiness_status: ready,
    blocking_reasons: [],
  },
  {
    work_family_id: "village_sewer_network",
    calculator_id: "sewerNetworkCalculator",
    kind: "sewer",
    parameter_passport_id: "expanded_complex.sewer.gravity_pipe.v1",
    required_p0_parameters: ["length_m", "diameter_mm"],
    required_domain_blocks: ["slope", "trench", "pipe", "manholes", "hydraulic_testing"],
    allowed_units: ["m", "m3", "pcs", "set", "shift", "trip", "hour"],
    forbidden_calculators: ["villageWaterSupplyCalculator", "stormwaterNetworkCalculator", "highRiseBuildingCalculator"],
    formula_trace_required: true,
    price_policy: "PRICE_MISSING_NO_FINAL_TOTAL",
    safety_policy: "STANDARD_PRELIMINARY_NOTICE",
    readiness_status: ready,
    blocking_reasons: [],
  },
  {
    work_family_id: "stormwater_drainage",
    calculator_id: "stormwaterNetworkCalculator",
    kind: "stormwater",
    parameter_passport_id: "expanded_complex.stormwater.network.v1",
    required_p0_parameters: ["length_m", "diameter_mm"],
    required_domain_blocks: ["catchment_profile", "trench", "pipe", "rain_inlets", "outlet"],
    allowed_units: ["m", "m2", "m3", "pcs", "set", "shift", "trip"],
    forbidden_calculators: ["sewerNetworkCalculator", "villageWaterSupplyCalculator", "highRiseBuildingCalculator"],
    formula_trace_required: true,
    price_policy: "PRICE_MISSING_NO_FINAL_TOTAL",
    safety_policy: "STANDARD_PRELIMINARY_NOTICE",
    readiness_status: ready,
    blocking_reasons: [],
  },
  {
    work_family_id: "heat_network",
    calculator_id: "gasHeatNetworkCalculator",
    kind: "pipeline",
    parameter_passport_id: "expanded_complex.heat_network.pipeline.v1",
    required_p0_parameters: ["length_m", "diameter_mm"],
    required_domain_blocks: ["route", "pipe", "welds", "insulation", "pressure_testing"],
    allowed_units: ["m", "m2", "m3", "pcs", "set", "shift", "trip"],
    forbidden_calculators: ["heatingVentilationCalculator", "villageWaterSupplyCalculator", "highRiseBuildingCalculator"],
    formula_trace_required: true,
    price_policy: "PRICE_MISSING_NO_FINAL_TOTAL",
    safety_policy: "REGULATED_ENGINEERING_REVIEW_REQUIRED",
    readiness_status: ready,
    blocking_reasons: [],
  },
  {
    work_family_id: "underground_cable_line",
    calculator_id: "powerCableLineCalculator",
    kind: "electrical",
    parameter_passport_id: "expanded_complex.electrical.cable_line.v1",
    required_p0_parameters: ["length_m", "voltage_kv"],
    required_domain_blocks: ["trench", "ducts", "cable", "joints", "testing"],
    allowed_units: ["m", "m3", "pcs", "set", "shift", "trip"],
    forbidden_calculators: ["electricalNetworkCalculator", "highRiseBuildingCalculator", "villageWaterSupplyCalculator"],
    formula_trace_required: true,
    price_policy: "PRICE_MISSING_NO_FINAL_TOTAL",
    safety_policy: "STANDARD_PRELIMINARY_NOTICE",
    readiness_status: ready,
    blocking_reasons: [],
  },
  {
    work_family_id: "transformer_substation",
    calculator_id: "transformerSubstationCalculator",
    kind: "substation",
    parameter_passport_id: "expanded_complex.electrical.substation.v1",
    required_p0_parameters: ["voltage_kv", "equipment_specification"],
    required_domain_blocks: ["foundation", "switchgear", "grounding", "cable_trench", "testing"],
    allowed_units: ["m", "m3", "pcs", "set", "shift"],
    forbidden_calculators: ["electricalNetworkCalculator", "highRiseBuildingCalculator", "villageWaterSupplyCalculator"],
    formula_trace_required: true,
    price_policy: "PRICE_MISSING_NO_FINAL_TOTAL",
    safety_policy: "REGULATED_ENGINEERING_REVIEW_REQUIRED",
    readiness_status: ready,
    blocking_reasons: [],
  },
  {
    work_family_id: "bridge_construction",
    calculator_id: "bridgeCalculator",
    kind: "bridge",
    parameter_passport_id: "expanded_complex.bridge.span.v1",
    required_p0_parameters: ["length_m", "width_m"],
    required_domain_blocks: ["foundations", "abutments", "girders", "bearings", "expansion_joints"],
    allowed_units: ["m", "m2", "m3", "pcs", "t", "set", "shift", "hour"],
    forbidden_calculators: ["roadConstructionCalculator", "highRiseBuildingCalculator", "sewerNetworkCalculator"],
    formula_trace_required: true,
    price_policy: "PRICE_MISSING_NO_FINAL_TOTAL",
    safety_policy: "REGULATED_ENGINEERING_REVIEW_REQUIRED",
    readiness_status: ready,
    blocking_reasons: [],
  },
  {
    work_family_id: "tunnel_construction",
    calculator_id: "tunnelCalculator",
    kind: "tunnel",
    parameter_passport_id: "expanded_complex.tunnel.linear.v1",
    required_p0_parameters: ["length_m", "section_m2"],
    required_domain_blocks: ["excavation", "temporary_support", "lining", "ventilation", "fire_safety"],
    allowed_units: ["m", "m2", "m3", "pcs", "set", "shift", "hour"],
    forbidden_calculators: ["roadConstructionCalculator", "highRiseBuildingCalculator", "sewerNetworkCalculator"],
    formula_trace_required: true,
    price_policy: "PRICE_MISSING_NO_FINAL_TOTAL",
    safety_policy: "REGULATED_ENGINEERING_REVIEW_REQUIRED",
    readiness_status: ready,
    blocking_reasons: [],
  },
  {
    work_family_id: "retaining_wall",
    calculator_id: "retainingWallCalculator",
    kind: "retaining_wall",
    parameter_passport_id: "expanded_complex.retaining_wall.face.v1",
    required_p0_parameters: ["length_m", "height_m"],
    required_domain_blocks: ["geology", "excavation", "concrete_or_gabion", "drainage", "stability_check"],
    allowed_units: ["m", "m2", "m3", "kg", "t", "pcs", "set", "shift"],
    forbidden_calculators: ["roadConstructionCalculator", "highRiseBuildingCalculator", "sewerNetworkCalculator"],
    formula_trace_required: true,
    price_policy: "PRICE_MISSING_NO_FINAL_TOTAL",
    safety_policy: "STANDARD_PRELIMINARY_NOTICE",
    readiness_status: ready,
    blocking_reasons: [],
  },
  {
    work_family_id: "technological_pipeline",
    calculator_id: "technologicalPipelineCalculator",
    kind: "pipeline",
    parameter_passport_id: "expanded_complex.pipeline.process.v1",
    required_p0_parameters: ["length_m", "diameter_mm"],
    required_domain_blocks: ["pipe", "supports", "welds", "ndt", "pressure_testing"],
    allowed_units: ["m", "m2", "m3", "pcs", "set", "shift", "t"],
    forbidden_calculators: ["gasHeatNetworkCalculator", "heatingVentilationCalculator", "highRiseBuildingCalculator"],
    formula_trace_required: true,
    price_policy: "PRICE_MISSING_NO_FINAL_TOTAL",
    safety_policy: "REGULATED_ENGINEERING_REVIEW_REQUIRED",
    readiness_status: ready,
    blocking_reasons: [],
  },
  {
    work_family_id: "ventilation_system",
    calculator_id: "heatingVentilationCalculator",
    kind: "heating_ventilation",
    parameter_passport_id: "expanded_complex.mep.ventilation.v1",
    required_p0_parameters: ["area_m2"],
    required_domain_blocks: ["airflow", "ducts", "fans", "filters", "balancing"],
    allowed_units: ["m", "m2", "m3_h", "pcs", "set", "shift"],
    forbidden_calculators: ["technologicalPipelineCalculator", "gasHeatNetworkCalculator", "highRiseBuildingCalculator"],
    formula_trace_required: true,
    price_policy: "PRICE_MISSING_NO_FINAL_TOTAL",
    safety_policy: "STANDARD_PRELIMINARY_NOTICE",
    readiness_status: ready,
    blocking_reasons: [],
  },
  {
    work_family_id: "boiler_house",
    calculator_id: "boilerHouseCalculator",
    kind: "boiler",
    parameter_passport_id: "expanded_complex.energy.boiler_house.v1",
    required_p0_parameters: ["capacity_mw"],
    required_domain_blocks: ["heat_load", "boilers", "pumps", "fuel_system", "commissioning"],
    allowed_units: ["m", "m3", "pcs", "set", "shift"],
    forbidden_calculators: ["heatingVentilationCalculator", "technologicalPipelineCalculator", "highRiseBuildingCalculator"],
    formula_trace_required: true,
    price_policy: "PRICE_MISSING_NO_FINAL_TOTAL",
    safety_policy: "REGULATED_ENGINEERING_REVIEW_REQUIRED",
    readiness_status: ready,
    blocking_reasons: [],
  },
  {
    work_family_id: "well_construction",
    calculator_id: "wellConstructionCalculator",
    kind: "well",
    parameter_passport_id: "expanded_complex.water_supply.well.v1",
    required_p0_parameters: ["depth_m", "diameter_mm"],
    required_domain_blocks: ["geology", "drilling", "casing", "filter", "water_analysis"],
    allowed_units: ["m", "m3", "pcs", "set", "shift"],
    forbidden_calculators: ["villageWaterSupplyCalculator", "miningEarthworksCalculator", "highRiseBuildingCalculator"],
    formula_trace_required: true,
    price_policy: "PRICE_MISSING_NO_FINAL_TOTAL",
    safety_policy: "REGULATED_ENGINEERING_REVIEW_REQUIRED",
    readiness_status: ready,
    blocking_reasons: [],
  },
  {
    work_family_id: "solar_power_plant",
    calculator_id: "solarWindEnergyCalculator",
    kind: "solar",
    parameter_passport_id: "expanded_complex.energy.solar.v1",
    required_p0_parameters: ["capacity_mw"],
    required_domain_blocks: ["capacity_region", "foundations", "panels", "inverters", "grid_connection"],
    allowed_units: ["m", "m2", "m3", "pcs", "set", "shift", "MW", "hour"],
    forbidden_calculators: ["substationCalculator", "electricalNetworkCalculator", "highRiseBuildingCalculator"],
    formula_trace_required: true,
    price_policy: "PRICE_MISSING_NO_FINAL_TOTAL",
    safety_policy: "STANDARD_PRELIMINARY_NOTICE",
    readiness_status: ready,
    blocking_reasons: [],
  },
  {
    work_family_id: "multi_utility_trench",
    calculator_id: "utilityConnectionCalculator",
    kind: "external_networks",
    parameter_passport_id: "expanded_complex.utility_connections.combined.v1",
    required_p0_parameters: ["length_m", "network_count"],
    required_domain_blocks: ["utility_conditions", "combined_trench", "water_branch", "chambers", "testing"],
    allowed_units: ["m", "m2", "m3", "pcs", "set", "shift", "trip"],
    forbidden_calculators: ["highRiseBuildingCalculator", "roadConstructionCalculator", "sewerNetworkCalculator"],
    formula_trace_required: true,
    price_policy: "PRICE_MISSING_NO_FINAL_TOTAL",
    safety_policy: "STANDARD_PRELIMINARY_NOTICE",
    readiness_status: ready,
    blocking_reasons: [],
  },
  {
    work_family_id: "earth_dam",
    calculator_id: "damHydraulicCalculator",
    kind: "hydraulic",
    parameter_passport_id: "expanded_complex.hydraulic.dam.v1",
    required_p0_parameters: ["length_m", "height_m"],
    required_domain_blocks: ["earthworks", "core", "slope_protection", "spillway", "monitoring"],
    allowed_units: ["m", "m2", "m3", "pcs", "set", "shift", "hour", "t", "trip"],
    forbidden_calculators: ["roadConstructionCalculator", "highRiseBuildingCalculator", "sewerNetworkCalculator"],
    formula_trace_required: true,
    price_policy: "PRICE_MISSING_NO_FINAL_TOTAL",
    safety_policy: "REGULATED_ENGINEERING_REVIEW_REQUIRED",
    readiness_status: ready,
    blocking_reasons: [],
  },
];

export function getS2BManifestEntry(workFamilyId: string): S2BFamilyManifestEntry | null {
  return S2B_INFRASTRUCTURE_FAMILY_MANIFEST.find((entry) => entry.work_family_id === workFamilyId) ?? null;
}
