import {
  AI_LIVE_SCREEN_BUTTON_RESULT_REQUIREMENT,
  type AiLiveScreenButton,
  type AiLiveScreenButtonEntity,
  type AiLiveScreenButtonIntent,
  type AiLiveScreenOpenLinkType,
  type AiLiveScreenSourcePlanHint,
  type AiLiveScreenActionMode,
} from "./aiLiveScreenButtonContract";
import { listAiLiveScreenManifests } from "./aiLiveScreenManifest";

type ButtonInput = {
  id: string;
  screenId: string;
  role: string;
  labelRu: string;
  concreteQuestionRu: string;
  intent: AiLiveScreenButtonIntent;
  entity: AiLiveScreenButtonEntity;
  actionMode?: AiLiveScreenActionMode;
  sourcePlanHint: AiLiveScreenSourcePlanHint[];
  expectedAnswerSignalsRu: string[];
  forbiddenAnswerSignalsRu?: string[];
  expectedOpenLinkTypes?: AiLiveScreenOpenLinkType[];
};

function button(input: ButtonInput): AiLiveScreenButton {
  return {
    ...input,
    actionMode: input.actionMode ?? "safe_read",
    forbiddenAnswerSignalsRu: input.forbiddenAnswerSignalsRu ?? [
      "выполнено напрямую",
      "данные изменены",
      "создан финально",
      "платеж проведен",
      "работа закрыта",
      "товар списан",
    ],
    expectedOpenLinkTypes: input.expectedOpenLinkTypes ?? [],
    resultRequirement: AI_LIVE_SCREEN_BUTTON_RESULT_REQUIREMENT,
  };
}

const APP_GRAPH: AiLiveScreenSourcePlanHint[] = ["app_context_graph", "app_data"];
const DOCS: AiLiveScreenSourcePlanHint[] = ["app_context_graph", "app_data", "pdf_document"];
const MARKET: AiLiveScreenSourcePlanHint[] = ["app_context_graph", "app_data", "internal_marketplace", "supplier_history"];

export const AI_LIVE_SCREEN_BUTTONS: readonly AiLiveScreenButton[] = [
  button({
    id: "director.today_decisions",
    screenId: "director",
    role: "director",
    labelRu: "Что мне решить сегодня",
    concreteQuestionRu: "Покажи, какие решения директор должен принять сегодня, с причиной, риском, связанными заявками, платежами, складом, работами и документами.",
    intent: "director_decision_summary",
    entity: "approval",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["решения", "риск", "заявка", "платеж", "документ"],
    expectedOpenLinkTypes: ["procurement_request", "payment", "document", "work"],
  }),
  button({
    id: "director.critical_risks",
    screenId: "director",
    role: "director",
    labelRu: "Показать критические риски",
    concreteQuestionRu: "Покажи критические риски по объектам, платежам, заявкам, складу, работам и документам с источниками и ссылками.",
    intent: "director_decision_summary",
    entity: "approval",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["риски", "объект", "платеж", "заявка"],
    expectedOpenLinkTypes: ["payment", "procurement_request", "work"],
  }),
  button({
    id: "director.pending_approvals",
    screenId: "director",
    role: "director",
    labelRu: "Показать заявки на утверждение",
    concreteQuestionRu: "Покажи заявки, ожидающие согласования: кто создал, объект, этаж, работа, товары, сумма, документы и ссылку открыть заявку.",
    intent: "procurement_request_review",
    entity: "procurement_request",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["заявки", "утверждение", "объект", "этаж"],
    expectedOpenLinkTypes: ["procurement_request", "document", "work"],
  }),
  button({
    id: "director.risky_payments",
    screenId: "director",
    role: "director",
    labelRu: "Показать платежи с риском",
    concreteQuestionRu: "Покажи платежи с риском: без документов, частичные оплаты, долги, связанные PDF, заявки и работы.",
    intent: "finance_payment_review",
    entity: "payment",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["платежи", "риск", "документы", "PDF"],
    expectedOpenLinkTypes: ["payment", "pdf_document", "procurement_request"],
  }),
  button({
    id: "director.object_blockers",
    screenId: "director",
    role: "director",
    labelRu: "Что блокирует объект",
    concreteQuestionRu: "Покажи, что блокирует объект: заявки, склад, работы, документы, платежи и следующий безопасный шаг.",
    intent: "director_decision_summary",
    entity: "work",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["блокирует", "объект", "работы", "документы"],
    expectedOpenLinkTypes: ["work", "procurement_request", "payment"],
  }),
  button({
    id: "director.unlinked_documents",
    screenId: "director",
    role: "director",
    labelRu: "Показать документы без связи",
    concreteQuestionRu: "Покажи документы без связи с заявкой, платежом, работой или объектом и что нужно связать.",
    intent: "document_missing_links_review",
    entity: "document",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["документы", "связь", "заявка", "работа"],
    expectedOpenLinkTypes: ["document", "pdf_document"],
  }),
  button({
    id: "director.executive_summary",
    screenId: "director",
    role: "director",
    labelRu: "Собрать сводку для директора",
    concreteQuestionRu: "Собери сводку для директора по решениям: риски, деньги, заявки, склад, работы, документы и безопасный следующий шаг.",
    intent: "director_decision_summary",
    entity: "approval",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["сводку", "решения", "риски", "следующий шаг"],
    expectedOpenLinkTypes: ["procurement_request", "payment", "work"],
  }),

  button({
    id: "foreman.close_today",
    screenId: "foreman",
    role: "foreman",
    labelRu: "Что мне закрыть сегодня",
    concreteQuestionRu: "Покажи, что прорабу нужно закрыть сегодня: работы, фото, акты, материалы, блокеры и ссылки.",
    intent: "field_work_closeout_help",
    entity: "work",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["закрыть", "работы", "фото", "акты"],
    expectedOpenLinkTypes: ["work", "document", "warehouse_issue"],
  }),
  button({
    id: "foreman.floor_works",
    screenId: "foreman",
    role: "foreman",
    labelRu: "Показать работы по этажу",
    concreteQuestionRu: "Покажи работы по первому этажу с объектом, зоной, материалами, заявками, документами и ссылками.",
    intent: "field_work_review",
    entity: "work",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["работы", "первый этаж", "материалы"],
    expectedOpenLinkTypes: ["work", "procurement_request"],
  }),
  button({
    id: "foreman.missing_photos",
    screenId: "foreman",
    role: "foreman",
    labelRu: "Каких фото не хватает",
    concreteQuestionRu: "Покажи, каких фото не хватает для закрытия моих работ, с работой, этажом, актом и документами.",
    intent: "field_work_closeout_help",
    entity: "photo",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["фото", "не хватает", "работа"],
    expectedOpenLinkTypes: ["work", "document"],
  }),
  button({
    id: "foreman.issued_materials",
    screenId: "foreman",
    role: "foreman",
    labelRu: "Какие материалы выданы",
    concreteQuestionRu: "Покажи, какие материалы выданы на мои работы, с объектом, этажом, работой, заявкой и складской выдачей.",
    intent: "warehouse_issue_trace",
    entity: "warehouse_issue",
    sourcePlanHint: APP_GRAPH,
    expectedAnswerSignalsRu: ["материалы", "выданы", "работа", "заявка"],
    expectedOpenLinkTypes: ["warehouse_issue", "work", "procurement_request"],
  }),
  button({
    id: "foreman.work_blockers",
    screenId: "foreman",
    role: "foreman",
    labelRu: "Что блокирует работы",
    concreteQuestionRu: "Покажи, что блокирует мои работы: материалы, фото, акты, документы, заявки и следующий шаг.",
    intent: "field_work_closeout_help",
    entity: "work",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["блокирует", "работы", "материалы"],
    expectedOpenLinkTypes: ["work", "document", "warehouse_issue"],
  }),
  button({
    id: "foreman.act_draft",
    screenId: "foreman",
    role: "foreman",
    labelRu: "Подготовить черновик акта",
    concreteQuestionRu: "Подготовь черновик акта по готовым работам, укажи недостающие фото, материалы, документы и что требует согласования.",
    intent: "field_work_closeout_help",
    entity: "act",
    actionMode: "draft_only",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["черновик", "акт", "согласование"],
    expectedOpenLinkTypes: ["work", "act", "document"],
  }),
  button({
    id: "foreman.work_estimate",
    screenId: "foreman",
    role: "foreman",
    labelRu: "Собрать смету по работе",
    concreteQuestionRu: "Дай смету на штукатурку 100 м² по работе как черновик, сначала проверь проектные данные, документы и только потом справочные источники.",
    intent: "construction_estimate",
    entity: "work",
    actionMode: "draft_only",
    sourcePlanHint: ["app_context_graph", "app_data", "pdf_document", "public_web", "general_construction_knowledge"],
    expectedAnswerSignalsRu: ["смета", "черновик", "100 м²"],
    expectedOpenLinkTypes: ["work", "document"],
  }),

  button({
    id: "buyer.requests_to_purchase",
    screenId: "buyer",
    role: "buyer",
    labelRu: "Показать заявки в закупку",
    concreteQuestionRu: "Покажи утвержденные заявки, которые пришли в закупку, с объектом, этажом, работой, товарами, складом и документами.",
    intent: "procurement_request_review",
    entity: "procurement_request",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["заявки", "закупку", "склад"],
    expectedOpenLinkTypes: ["procurement_request", "work"],
  }),
  button({
    id: "buyer.options_by_request",
    screenId: "buyer",
    role: "buyer",
    labelRu: "Подобрать варианты по заявке",
    concreteQuestionRu: "Подбери варианты закупки по утвержденным заявкам: сначала склад, затем внутренний маркетплейс, история поставщиков, проверенные поставщики и только потом внешние источники.",
    intent: "procurement_offer_selection",
    entity: "procurement_request",
    actionMode: "draft_only",
    sourcePlanHint: MARKET,
    expectedAnswerSignalsRu: ["варианты", "заявка", "маркетплейс", "склад"],
    expectedOpenLinkTypes: ["procurement_request", "marketplace_product", "supplier"],
  }),
  button({
    id: "buyer.stock_before_purchase",
    screenId: "buyer",
    role: "buyer",
    labelRu: "Проверить склад перед закупкой",
    concreteQuestionRu: "Проверь склад перед закупкой: что есть, что зарезервировано, что выдано и сколько нужно докупить по заявкам.",
    intent: "warehouse_stock_review",
    entity: "warehouse_stock",
    sourcePlanHint: APP_GRAPH,
    expectedAnswerSignalsRu: ["склад", "докупить", "заявка"],
    expectedOpenLinkTypes: ["warehouse_issue", "procurement_request"],
  }),
  button({
    id: "buyer.find_suppliers",
    screenId: "buyer",
    role: "buyer",
    labelRu: "Найти поставщиков",
    concreteQuestionRu: "Найди поставщиков ГКЛ: сначала внутренний маркетплейс, затем история поставщиков, проверенные поставщики и только потом внешние источники.",
    intent: "marketplace_supplier_search",
    entity: "supplier",
    sourcePlanHint: MARKET,
    expectedAnswerSignalsRu: ["поставщики", "ГКЛ", "маркетплейс"],
    expectedOpenLinkTypes: ["supplier", "marketplace_product"],
  }),
  button({
    id: "buyer.compare_offers",
    screenId: "buyer",
    role: "buyer",
    labelRu: "Сравнить предложения",
    concreteQuestionRu: "Сравни предложения поставщиков по цене, срокам, наличию, истории закупок, рискам и связи с заявкой.",
    intent: "procurement_offer_selection",
    entity: "supplier",
    actionMode: "draft_only",
    sourcePlanHint: MARKET,
    expectedAnswerSignalsRu: ["сравни", "предложения", "поставщики"],
    expectedOpenLinkTypes: ["supplier", "marketplace_product", "procurement_request"],
  }),
  button({
    id: "buyer.purchase_draft",
    screenId: "buyer",
    role: "buyer",
    labelRu: "Подготовить черновик закупки",
    concreteQuestionRu: "Подготовь черновик закупки по заявке, не создавая закупку финально, с товарами, складом, поставщиками и согласованием.",
    intent: "procurement_offer_selection",
    entity: "procurement_request",
    actionMode: "draft_only",
    sourcePlanHint: MARKET,
    expectedAnswerSignalsRu: ["черновик", "закупки", "согласование"],
    expectedOpenLinkTypes: ["procurement_request", "supplier"],
  }),
  button({
    id: "buyer.requests_without_supplier",
    screenId: "buyer",
    role: "buyer",
    labelRu: "Показать заявки без поставщика",
    concreteQuestionRu: "Покажи заявки без поставщика, с объектом, этажом, работой, товарами, складом и следующим безопасным шагом.",
    intent: "procurement_request_review",
    entity: "procurement_request",
    sourcePlanHint: APP_GRAPH,
    expectedAnswerSignalsRu: ["заявки", "без поставщика", "объект"],
    expectedOpenLinkTypes: ["procurement_request", "work"],
  }),

  button({
    id: "accountant.payments_without_docs",
    screenId: "accountant",
    role: "accountant",
    labelRu: "Показать платежи без документов",
    concreteQuestionRu: "Покажи платежи без полного пакета документов: счет, компания, сумма, акт, договор, PDF, заявка, работа, согласование и что блокирует оплату.",
    intent: "finance_payment_review",
    entity: "payment",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["платежи", "документы", "сумма", "PDF"],
    expectedOpenLinkTypes: ["payment", "invoice", "pdf_document", "procurement_request"],
  }),
  button({
    id: "accountant.invoices_to_pay",
    screenId: "accountant",
    role: "accountant",
    labelRu: "Показать счета к оплате",
    concreteQuestionRu: "Покажи счета к оплате с компанией, суммой, PDF, заявкой, работой, платежом и недостающими документами.",
    intent: "finance_payment_review",
    entity: "invoice",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["счета", "оплате", "компания"],
    expectedOpenLinkTypes: ["invoice", "payment", "pdf_document"],
  }),
  button({
    id: "accountant.partial_payments",
    screenId: "accountant",
    role: "accountant",
    labelRu: "Показать частичные оплаты",
    concreteQuestionRu: "Покажи частичные оплаты: счет, сумма, компания, документы, платежи, остаток и что требует проверки.",
    intent: "finance_partial_payment_review",
    entity: "payment",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["частичные", "оплаты", "счет"],
    expectedOpenLinkTypes: ["payment", "invoice"],
  }),
  button({
    id: "accountant.debts",
    screenId: "accountant",
    role: "accountant",
    labelRu: "Показать долги",
    concreteQuestionRu: "Покажи долги по компаниям с документами, счетами, платежами, актами, сроками и ссылками.",
    intent: "finance_debt_review",
    entity: "payment",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["долги", "компания", "платеж"],
    expectedOpenLinkTypes: ["payment", "invoice", "act"],
  }),
  button({
    id: "accountant.payment_docs_check",
    screenId: "accountant",
    role: "accountant",
    labelRu: "Проверить документы для оплаты",
    concreteQuestionRu: "Проверь документы для оплаты: счет, акт, договор, PDF, заявка, работа, согласование и что блокирует проведение.",
    intent: "document_payment_blocker_review",
    entity: "document",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["документы", "оплаты", "блокирует"],
    expectedOpenLinkTypes: ["document", "payment", "pdf_document"],
  }),
  button({
    id: "accountant.accounting_entry_reference",
    screenId: "accountant",
    role: "accountant",
    labelRu: "Подготовить справку по проводке",
    concreteQuestionRu: "Подготовь справочную рекомендацию по бухгалтерской проводке для выбранного счета или платежа с учетом страны учета и отметкой, что требуется проверка бухгалтером.",
    intent: "accounting_entry_help",
    entity: "invoice",
    actionMode: "approval_required",
    sourcePlanHint: ["app_context_graph", "app_data", "pdf_document", "accounting_reference", "public_web"],
    expectedAnswerSignalsRu: ["проводке", "страна учета", "проверка бухгалтером"],
    expectedOpenLinkTypes: ["invoice", "payment", "document"],
  }),
  button({
    id: "accountant.company_payments",
    screenId: "accountant",
    role: "accountant",
    labelRu: "Показать платежи по компании",
    concreteQuestionRu: "Покажи платежи по компании с суммами, счетами, актами, PDF, заявками, работами и статусом документов.",
    intent: "finance_payment_review",
    entity: "payment",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["платежи", "компания", "сумма"],
    expectedOpenLinkTypes: ["payment", "invoice", "pdf_document"],
  }),

  button({
    id: "warehouse.stock",
    screenId: "warehouse",
    role: "warehouse",
    labelRu: "Показать остатки",
    concreteQuestionRu: "Покажи складские остатки с материалом, количеством, объектом, этажом, работой, заявкой и источниками.",
    intent: "warehouse_stock_review",
    entity: "warehouse_stock",
    sourcePlanHint: APP_GRAPH,
    expectedAnswerSignalsRu: ["остатки", "материал", "склад"],
    expectedOpenLinkTypes: ["warehouse_issue", "procurement_request", "work"],
  }),
  button({
    id: "warehouse.deficits",
    screenId: "warehouse",
    role: "warehouse",
    labelRu: "Показать дефициты",
    concreteQuestionRu: "Покажи дефициты материалов: что нужно докупить, по какой заявке, работе, этажу и объекту.",
    intent: "warehouse_deficit_review",
    entity: "warehouse_stock",
    sourcePlanHint: APP_GRAPH,
    expectedAnswerSignalsRu: ["дефициты", "материалы", "докупить"],
    expectedOpenLinkTypes: ["warehouse_issue", "procurement_request"],
  }),
  button({
    id: "warehouse.item_trace",
    screenId: "warehouse",
    role: "warehouse",
    labelRu: "Куда ушёл товар",
    concreteQuestionRu: "Покажи движение выбранного товара: приход, остаток, выдачи, получатель, объект, этаж, работа, заявка и документы.",
    intent: "warehouse_issue_trace",
    entity: "warehouse_issue",
    sourcePlanHint: APP_GRAPH,
    expectedAnswerSignalsRu: ["движение", "выдачи", "получатель", "заявка"],
    expectedOpenLinkTypes: ["warehouse_issue", "work", "procurement_request"],
  }),
  button({
    id: "warehouse.floor_issues",
    screenId: "warehouse",
    role: "warehouse",
    labelRu: "Что выдали на этаж",
    concreteQuestionRu: "Покажи, что выдали на первый этаж: материалы, количество, получатель, работа, заявка и складская выдача.",
    intent: "warehouse_issue_trace",
    entity: "warehouse_issue",
    sourcePlanHint: APP_GRAPH,
    expectedAnswerSignalsRu: ["выдали", "первый этаж", "материалы"],
    expectedOpenLinkTypes: ["warehouse_issue", "work", "procurement_request"],
  }),
  button({
    id: "warehouse.today_incoming",
    screenId: "warehouse",
    role: "warehouse",
    labelRu: "Что пришло сегодня",
    concreteQuestionRu: "Покажи сегодняшние приходы на склад с поставщиком, документами, PDF, заявкой и остатком.",
    intent: "warehouse_stock_review",
    entity: "warehouse_stock",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["пришло", "сегодня", "поставщик"],
    expectedOpenLinkTypes: ["document", "pdf_document", "procurement_request"],
  }),
  button({
    id: "warehouse.reservations",
    screenId: "warehouse",
    role: "warehouse",
    labelRu: "Показать резервы",
    concreteQuestionRu: "Покажи складские резервы по материалам, заявкам, работам, этажам и объектам.",
    intent: "warehouse_stock_review",
    entity: "warehouse_stock",
    sourcePlanHint: APP_GRAPH,
    expectedAnswerSignalsRu: ["резервы", "материалы", "заявки"],
    expectedOpenLinkTypes: ["procurement_request", "work"],
  }),
  button({
    id: "warehouse.deficit_request_draft",
    screenId: "warehouse",
    role: "warehouse",
    labelRu: "Подготовить черновик заявки на дефицит",
    concreteQuestionRu: "Подготовь черновик заявки на дефицит материалов по складу, не создавая заявку финально, с объектом, этажом, работой и источниками.",
    intent: "warehouse_deficit_review",
    entity: "warehouse_stock",
    actionMode: "draft_only",
    sourcePlanHint: APP_GRAPH,
    expectedAnswerSignalsRu: ["черновик", "дефицит", "заявки"],
    expectedOpenLinkTypes: ["warehouse_issue", "work"],
  }),

  button({
    id: "contractor.close_my_work",
    screenId: "contractor",
    role: "contractor",
    labelRu: "Что мне закрыть",
    concreteQuestionRu: "Покажи только мои работы, которые нужно закрыть, с замечаниями, фото, актами и разрешенными ссылками.",
    intent: "contractor_acceptance_review",
    entity: "work",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["мои работы", "закрыть", "замечания"],
    expectedOpenLinkTypes: ["work", "act", "document"],
  }),
  button({
    id: "contractor.photos_needed",
    screenId: "contractor",
    role: "contractor",
    labelRu: "Какие фото нужны",
    concreteQuestionRu: "Покажи, какие фото нужны по моим работам для приемки, без чужих работ и полных финансов.",
    intent: "contractor_acceptance_review",
    entity: "photo",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["фото", "мои работы", "приемки"],
    expectedOpenLinkTypes: ["work", "document"],
  }),
  button({
    id: "contractor.open_remarks",
    screenId: "contractor",
    role: "contractor",
    labelRu: "Какие замечания открыты",
    concreteQuestionRu: "Покажи открытые замечания по моим работам, кто следующий и что нужно приложить.",
    intent: "contractor_acceptance_review",
    entity: "work",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["замечания", "открыты", "мои работы"],
    expectedOpenLinkTypes: ["work", "document"],
  }),
  button({
    id: "contractor.acceptance_blockers",
    screenId: "contractor",
    role: "contractor",
    labelRu: "Что мешает приёмке",
    concreteQuestionRu: "Покажи, что мешает приемке моих работ: фото, замечания, акты, документы и безопасный следующий шаг.",
    intent: "contractor_acceptance_review",
    entity: "work",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["мешает", "приемке", "мои работы"],
    expectedOpenLinkTypes: ["work", "act", "document"],
  }),
  button({
    id: "contractor.my_acts",
    screenId: "contractor",
    role: "contractor",
    labelRu: "Какие акты по моим работам",
    concreteQuestionRu: "Покажи акты по моим работам, статус, документы, что не хватает и ссылки.",
    intent: "contractor_acceptance_review",
    entity: "act",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["акты", "мои работы", "статус"],
    expectedOpenLinkTypes: ["act", "work", "document"],
  }),
  button({
    id: "contractor.payment_blockers",
    screenId: "contractor",
    role: "contractor",
    labelRu: "Что мешает оплате",
    concreteQuestionRu: "Покажи разрешенный статус оплаты по моим работам и что мешает оплате, без полных финансов и чужих работ.",
    intent: "contractor_acceptance_review",
    entity: "payment",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["оплате", "мои работы", "доступ"],
    expectedOpenLinkTypes: ["work", "document"],
  }),
  button({
    id: "contractor.foreman_reply_draft",
    screenId: "contractor",
    role: "contractor",
    labelRu: "Подготовить ответ прорабу",
    concreteQuestionRu: "Подготовь черновик ответа прорабу по моим работам, замечаниям, фото и актам, не отправляя сообщение финально.",
    intent: "contractor_acceptance_review",
    entity: "work",
    actionMode: "draft_only",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["черновик", "ответ", "прорабу"],
    expectedOpenLinkTypes: ["work", "document"],
  }),

  button({
    id: "documents.pdf_explain",
    screenId: "documents",
    role: "documents",
    labelRu: "Что в этом PDF",
    concreteQuestionRu: "Что в этом PDF: тип документа, номер, сумма, компания, товары, связанные платежи, заявки, работы и missing links.",
    intent: "document_pdf_explanation",
    entity: "pdf_document",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["PDF", "документ", "сумма", "компания"],
    expectedOpenLinkTypes: ["pdf_document", "payment", "procurement_request", "work"],
  }),
  button({
    id: "documents.linked_entities",
    screenId: "documents",
    role: "documents",
    labelRu: "С чем связан документ",
    concreteQuestionRu: "Покажи, с чем связан этот документ: счет, акт, платеж, заявка, работа, объект, этаж, компания и что не найдено.",
    intent: "document_pdf_explanation",
    entity: "document",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["связан", "документ", "платеж", "заявка"],
    expectedOpenLinkTypes: ["document", "pdf_document", "payment", "procurement_request"],
  }),
  button({
    id: "documents.missing_documents",
    screenId: "documents",
    role: "documents",
    labelRu: "Каких документов не хватает",
    concreteQuestionRu: "Покажи, каких документов не хватает по оплатам, заявкам и работам: счет, акт, договор, PDF и согласование.",
    intent: "document_missing_links_review",
    entity: "document",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["документов", "не хватает", "акт"],
    expectedOpenLinkTypes: ["document", "pdf_document", "payment"],
  }),
  button({
    id: "documents.payment_blocker",
    screenId: "documents",
    role: "documents",
    labelRu: "Что блокирует оплату",
    concreteQuestionRu: "Покажи, какой документ блокирует оплату, связанные счет, платеж, заявка, работа, PDF и что нужно запросить.",
    intent: "document_payment_blocker_review",
    entity: "document",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["блокирует", "оплату", "PDF"],
    expectedOpenLinkTypes: ["payment", "pdf_document", "document"],
  }),
  button({
    id: "documents.work_close_blocker",
    screenId: "documents",
    role: "documents",
    labelRu: "Что блокирует закрытие работы",
    concreteQuestionRu: "Покажи, какие документы блокируют закрытие работы: акт, фото, PDF, заявка, складская выдача и согласование.",
    intent: "document_missing_links_review",
    entity: "work",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["блокируют", "закрытие", "работы"],
    expectedOpenLinkTypes: ["work", "document", "pdf_document"],
  }),
  button({
    id: "documents.unlinked_documents",
    screenId: "documents",
    role: "documents",
    labelRu: "Показать документы без связи",
    concreteQuestionRu: "Покажи документы без связи с заявкой, платежом, работой, актом или объектом и безопасный следующий шаг.",
    intent: "document_missing_links_review",
    entity: "document",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["документы", "без связи", "следующий шаг"],
    expectedOpenLinkTypes: ["document", "pdf_document"],
  }),
  button({
    id: "documents.link_draft",
    screenId: "documents",
    role: "documents",
    labelRu: "Связать как черновик",
    concreteQuestionRu: "Подготовь черновик связи документа с заявкой, платежом, работой или актом, не создавая финальную связь без проверки.",
    intent: "document_missing_links_review",
    entity: "document",
    actionMode: "draft_only",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["черновик", "связи", "документа"],
    expectedOpenLinkTypes: ["document", "pdf_document"],
  }),

  button({
    id: "market.product_from_photo",
    screenId: "market",
    role: "marketplace_user",
    labelRu: "Определить товар по фото",
    concreteQuestionRu: "Определи товар по фото как черновик карточки: название, категория, единица, применение, характеристики и что нужно уточнить.",
    intent: "marketplace_product_draft",
    entity: "marketplace_product",
    actionMode: "draft_only",
    sourcePlanHint: ["internal_marketplace", "general_construction_knowledge"],
    expectedAnswerSignalsRu: ["товар", "фото", "черновик"],
    expectedOpenLinkTypes: ["marketplace_product"],
  }),
  button({
    id: "market.product_card_draft",
    screenId: "market",
    role: "marketplace_user",
    labelRu: "Подготовить карточку",
    concreteQuestionRu: "Подготовь черновик карточки товара: название, категория, характеристики, применение, ключевые слова и что нужно уточнить.",
    intent: "marketplace_product_draft",
    entity: "marketplace_product",
    actionMode: "draft_only",
    sourcePlanHint: ["internal_marketplace", "general_construction_knowledge"],
    expectedAnswerSignalsRu: ["карточки", "товара", "черновик"],
    expectedOpenLinkTypes: ["marketplace_product"],
  }),
  button({
    id: "market.category",
    screenId: "market",
    role: "marketplace_user",
    labelRu: "Подобрать категорию",
    concreteQuestionRu: "Подбери категорию товара для маркетплейса, похожие товары, характеристики и что нужно уточнить перед публикацией.",
    intent: "marketplace_product_draft",
    entity: "marketplace_product",
    actionMode: "draft_only",
    sourcePlanHint: ["internal_marketplace", "general_construction_knowledge"],
    expectedAnswerSignalsRu: ["категория", "товара", "уточнить"],
    expectedOpenLinkTypes: ["marketplace_product"],
  }),
  button({
    id: "market.characteristics",
    screenId: "market",
    role: "marketplace_user",
    labelRu: "Показать характеристики",
    concreteQuestionRu: "Покажи характеристики товара, которые нужно заполнить: размер, материал, производитель, маркировка, единица измерения и применение.",
    intent: "marketplace_product_draft",
    entity: "marketplace_product",
    actionMode: "draft_only",
    sourcePlanHint: ["internal_marketplace", "general_construction_knowledge"],
    expectedAnswerSignalsRu: ["характеристики", "товара", "размер"],
    expectedOpenLinkTypes: ["marketplace_product"],
  }),
  button({
    id: "market.similar_products",
    screenId: "market",
    role: "marketplace_user",
    labelRu: "Показать похожие товары",
    concreteQuestionRu: "Покажи похожие товары во внутреннем маркетплейсе, аналоги, категорию, отличия и что нужно уточнить.",
    intent: "marketplace_supplier_search",
    entity: "marketplace_product",
    sourcePlanHint: ["internal_marketplace", "supplier_history"],
    expectedAnswerSignalsRu: ["похожие", "товары", "маркетплейс"],
    expectedOpenLinkTypes: ["marketplace_product", "supplier"],
  }),
  button({
    id: "market.work_usage",
    screenId: "market",
    role: "marketplace_user",
    labelRu: "Для каких работ используется",
    concreteQuestionRu: "Покажи, для каких строительных работ используется этот товар, какие характеристики важны и что нужно уточнить.",
    intent: "construction_estimate",
    entity: "marketplace_product",
    actionMode: "draft_only",
    sourcePlanHint: ["internal_marketplace", "general_construction_knowledge"],
    expectedAnswerSignalsRu: ["работ", "товар", "характеристики"],
    expectedOpenLinkTypes: ["marketplace_product"],
  }),
  button({
    id: "market.clarifications",
    screenId: "market",
    role: "marketplace_user",
    labelRu: "Что нужно уточнить",
    concreteQuestionRu: "Покажи, что нужно уточнить перед публикацией карточки товара: цена, остаток, поставщик, размер, производитель и маркировка.",
    intent: "marketplace_product_draft",
    entity: "marketplace_product",
    actionMode: "draft_only",
    sourcePlanHint: ["internal_marketplace", "general_construction_knowledge"],
    expectedAnswerSignalsRu: ["уточнить", "цена", "остаток"],
    expectedOpenLinkTypes: ["marketplace_product", "supplier"],
  }),

  button({
    id: "office.stuck_documents",
    screenId: "office",
    role: "office",
    labelRu: "Показать зависшие документы",
    concreteQuestionRu: "Покажи зависшие документы: причина, кто следующий, связанная задача, согласование, работа и безопасный следующий шаг.",
    intent: "office_stuck_work_review",
    entity: "document",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["зависшие", "документы", "причина"],
    expectedOpenLinkTypes: ["document", "work"],
  }),
  button({
    id: "office.overdue_tasks",
    screenId: "office",
    role: "office",
    labelRu: "Показать просроченные задачи",
    concreteQuestionRu: "Покажи просроченные задачи офиса, связанные документы, согласование, ответственных и следующий безопасный шаг.",
    intent: "office_stuck_work_review",
    entity: "work",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["просроченные", "задачи", "ответственных"],
    expectedOpenLinkTypes: ["document", "work"],
  }),
  button({
    id: "office.reminders",
    screenId: "office",
    role: "office",
    labelRu: "Кому напомнить",
    concreteQuestionRu: "Покажи, кому нужно напомнить по зависшим документам, задачам и согласованию, но не отправляй напоминание финально.",
    intent: "office_stuck_work_review",
    entity: "document",
    actionMode: "draft_only",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["напомнить", "документы", "согласование"],
    expectedOpenLinkTypes: ["document", "work"],
  }),
  button({
    id: "office.awaiting_approval",
    screenId: "office",
    role: "office",
    labelRu: "Что ждёт согласование",
    concreteQuestionRu: "Покажи, что ждет согласование: заявки, платежи, документы, работы, кто следующий и что блокирует.",
    intent: "office_stuck_work_review",
    entity: "approval",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["согласование", "ждет", "заявки"],
    expectedOpenLinkTypes: ["procurement_request", "payment", "document"],
  }),
  button({
    id: "office.reports_to_check",
    screenId: "office",
    role: "office",
    labelRu: "Какие отчёты проверить",
    concreteQuestionRu: "Покажи, какие отчеты нужно проверить, с документами, работами, рисками и безопасным следующим шагом.",
    intent: "office_stuck_work_review",
    entity: "document",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["отчеты", "проверить", "риски"],
    expectedOpenLinkTypes: ["document", "work"],
  }),
  button({
    id: "office.reminder_draft",
    screenId: "office",
    role: "office",
    labelRu: "Подготовить черновик напоминания",
    concreteQuestionRu: "Подготовь черновик напоминания по зависшему документу или задаче, но не отправляй его финально.",
    intent: "office_stuck_work_review",
    entity: "document",
    actionMode: "draft_only",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["черновик", "напоминания", "не отправляй"],
    expectedOpenLinkTypes: ["document", "work"],
  }),

  button({
    id: "client.progress",
    screenId: "client",
    role: "client",
    labelRu: "Показать прогресс",
    concreteQuestionRu: "Покажи клиентский прогресс проекта: что сделано, что задерживается, фото, документы и доступный следующий шаг.",
    intent: "client_progress_review",
    entity: "work",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["прогресс", "проект", "сделано"],
    expectedOpenLinkTypes: ["work", "document"],
  }),
  button({
    id: "client.photo_report",
    screenId: "client",
    role: "client",
    labelRu: "Показать фотоотчёт",
    concreteQuestionRu: "Покажи клиентский фотоотчет по проекту без внутренних финансов и скрытых документов.",
    intent: "client_progress_review",
    entity: "photo",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["фотоотчет", "проект", "клиент"],
    expectedOpenLinkTypes: ["work", "document"],
  }),
  button({
    id: "client.weekly_done",
    screenId: "client",
    role: "client",
    labelRu: "Что сделано за неделю",
    concreteQuestionRu: "Покажи, что сделано за неделю по клиентскому проекту: работы, фото, документы и задержки.",
    intent: "client_progress_review",
    entity: "work",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["сделано", "неделю", "работы"],
    expectedOpenLinkTypes: ["work", "document"],
  }),
  button({
    id: "client.delays",
    screenId: "client",
    role: "client",
    labelRu: "Что задерживается",
    concreteQuestionRu: "Покажи клиенту, что задерживается по проекту, без внутренних финансов, споров подрядчиков и скрытых документов.",
    intent: "client_progress_review",
    entity: "work",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["задерживается", "проект", "клиент"],
    expectedOpenLinkTypes: ["work", "document"],
  }),
  button({
    id: "client.documents",
    screenId: "client",
    role: "client",
    labelRu: "Показать клиентские документы",
    concreteQuestionRu: "Покажи клиентские документы проекта, доступные ссылки, что не найдено и следующий безопасный шаг.",
    intent: "client_progress_review",
    entity: "document",
    sourcePlanHint: DOCS,
    expectedAnswerSignalsRu: ["клиентские", "документы", "доступные"],
    expectedOpenLinkTypes: ["document", "pdf_document"],
  }),
] as const;

const BUTTONS_BY_ID = new Map(AI_LIVE_SCREEN_BUTTONS.map((item) => [item.id, item]));

export function listAiLiveScreenButtons(): AiLiveScreenButton[] {
  return [...AI_LIVE_SCREEN_BUTTONS];
}

export function listAiLiveScreenButtonsForScreen(screenId: string): AiLiveScreenButton[] {
  return AI_LIVE_SCREEN_BUTTONS.filter((buttonItem) => buttonItem.screenId === screenId);
}

export function getAiLiveScreenButton(buttonId: string): AiLiveScreenButton {
  const found = BUTTONS_BY_ID.get(buttonId);
  if (!found) throw new Error(`Unknown AI live screen button: ${buttonId}`);
  return found;
}

export function assertAiLiveScreenButtonRegistryMatchesManifest(): void {
  for (const manifest of listAiLiveScreenManifests()) {
    const ids = new Set(listAiLiveScreenButtonsForScreen(manifest.screenId).map((buttonItem) => buttonItem.id));
    for (const requiredId of manifest.requiredAiButtons) {
      if (!ids.has(requiredId)) {
        throw new Error(`Missing AI live button ${requiredId} for screen ${manifest.screenId}`);
      }
    }
  }
}
