import { Platform, StyleSheet } from "react-native";

const webViewportHeight = (Platform.OS === "web" ? "100dvh" : "100%") as "100%";

export const aiAssistantScreenStyles = StyleSheet.create({
  flex: {
    flex: 1,
    minHeight: 0,
  },
  safe: {
    flex: 1,
    height: webViewportHeight,
    minHeight: webViewportHeight,
    backgroundColor: "#F8FAFC",
    overflow: "hidden",
  },
  chatShell: {
    flex: 1,
    minHeight: 0,
    flexDirection: "column",
    overflow: "hidden",
  },
  bootContainer: {
    flex: 1,
    backgroundColor: "#F8FAFC",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  bootText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#475569",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 8,
    gap: 12,
  },
  headerIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    alignItems: "center",
    justifyContent: "center",
  },
  headerText: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: "#0F172A",
  },
  headerSubtitle: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: "600",
    color: "#64748B",
  },
  noticeCard: {
    marginHorizontal: 16,
    marginTop: 4,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#EFF6FF",
    borderWidth: 1,
    borderColor: "#BFDBFE",
  },
  noticeTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#1D4ED8",
  },
  noticeText: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 18,
    color: "#1E3A8A",
  },
  noticeHidden: {
    display: "none",
  },
  productStatusCard: {
    marginHorizontal: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: "#F1F5F9",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  productStatusText: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
    color: "#334155",
  },
  readyProposalBlock: {
    marginHorizontal: 16,
    marginTop: 8,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#E2E8F0",
  },
  readyProposalTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: "#0F172A",
  },
  readyProposalScroller: {
    flexGrow: 0,
    maxHeight: 42,
    marginTop: 8,
  },
  readyProposalRow: {
    gap: 8,
    paddingRight: 16,
  },
  readyProposalChip: {
    height: 34,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    alignItems: "center",
    justifyContent: "center",
  },
  readyProposalChipText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#0F172A",
  },
  supplierProposalBlock: {
    marginHorizontal: 16,
    marginTop: 8,
    maxHeight: 190,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#E2E8F0",
    overflow: "hidden",
  },
  supplierOptionCard: {
    marginTop: 8,
    padding: 10,
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  supplierOptionTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: "#0F172A",
  },
  supplierOptionText: {
    marginTop: 6,
    fontSize: 12,
    lineHeight: 17,
    color: "#334155",
  },
  supplierOptionMeta: {
    marginTop: 4,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: "700",
    color: "#64748B",
  },
  scopeCard: {
    marginHorizontal: 16,
    marginTop: 10,
    maxHeight: 260,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    overflow: "hidden",
  },
  scopeCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  scopeCardTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#0F172A",
  },
  scopeCardText: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 18,
    color: "#334155",
  },
  scopeCardMeta: {
    marginTop: 8,
    fontSize: 11,
    fontWeight: "700",
    color: "#64748B",
  },
  scopeCardError: {
    marginTop: 8,
    fontSize: 12,
    fontWeight: "700",
    color: "#B91C1C",
  },
  routeRow: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 2,
    gap: 8,
  },
  routeScroller: {
    flexGrow: 0,
    maxHeight: 58,
  },
  routeChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#CBD5E1",
  },
  routeChipText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#334155",
  },
  quickPromptRow: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 2,
    gap: 8,
  },
  quickPromptScroller: {
    flexGrow: 0,
    maxHeight: 62,
  },
  quickPromptChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  quickPromptText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#0F172A",
  },
  messages: {
    flex: 1,
    minHeight: 0,
    marginTop: 8,
    overflow: "scroll",
  },
  messagesContent: {
    paddingHorizontal: 16,
    paddingBottom: 16,
    gap: 12,
  },
  messageBubble: {
    maxWidth: "88%",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 18,
  },
  assistantBubble: {
    alignSelf: "flex-start",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  userBubble: {
    alignSelf: "flex-end",
    backgroundColor: "#2563EB",
  },
  messageText: {
    fontSize: 14,
    lineHeight: 20,
  },
  assistantText: {
    color: "#0F172A",
  },
  userText: {
    color: "#FFFFFF",
  },
  loadingBubble: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  loadingInlineText: {
    color: "#475569",
    fontSize: 13,
    fontWeight: "600",
  },
  runtimeInlineMarker: {
    width: 1,
    height: 1,
  },
  composer: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 10,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
  },
  voiceButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E2E8F0",
    borderWidth: 1,
    borderColor: "#CBD5E1",
  },
  voiceButtonActive: {
    backgroundColor: "#2563EB",
    borderColor: "#2563EB",
  },
  voiceButtonMuted: {
    opacity: 0.72,
  },
  input: {
    flex: 1,
    minHeight: 48,
    maxHeight: 120,
    borderRadius: 18,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    paddingHorizontal: 14,
    paddingTop: 13,
    paddingBottom: 13,
    color: "#0F172A",
    fontSize: 15,
  },
  sendButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#2563EB",
    alignItems: "center",
    justifyContent: "center",
  },
  sendButtonDisabled: {
    backgroundColor: "#94A3B8",
  },
  voiceStatusRow: {
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: "#FFFFFF",
  },
  voiceStatusText: {
    color: "#475569",
    fontSize: 12,
    lineHeight: 17,
  },
  voiceStatusError: {
    color: "#B91C1C",
    fontWeight: "700",
  },
});
