import {
  AI_CONTRACT_RUNTIME_ARTIFACT_PREFIX,
  AI_CONTRACT_RUNTIME_GREEN_STATUS,
  AI_CONTRACT_RUNTIME_WAVE,
} from "../../../src/lib/ai/contractRuntime";

describe("AI contract runtime core", () => {
  it("locks the enterprise invariant proof wave constants", () => {
    expect(AI_CONTRACT_RUNTIME_WAVE).toBe("S_AI_ENTERPRISE_CONTRACT_RUNTIME_INVARIANT_PROOF_CORE_POINT_OF_NO_RETURN");
    expect(AI_CONTRACT_RUNTIME_ARTIFACT_PREFIX).toBe("S_AI_ENTERPRISE_CONTRACT_RUNTIME_INVARIANT_PROOF_CORE");
    expect(AI_CONTRACT_RUNTIME_GREEN_STATUS).toBe("GREEN_AI_ENTERPRISE_CONTRACT_RUNTIME_INVARIANT_PROOF_CORE_READY");
  });
});
