import type { AiUserRole } from "../policy/aiRolePolicy";
import type { AiButtonActionEntry } from "./aiAppActionTypes";

const CONTROL_ROLES: readonly AiUserRole[] = ["director", "control"];
const BUYER_ROLES: readonly AiUserRole[] = ["director", "control", "buyer"];
const FOREMAN_ROLES: readonly AiUserRole[] = ["director", "control", "foreman"];
const WAREHOUSE_ROLES: readonly AiUserRole[] = ["director", "control", "warehouse"];
const ACCOUNTANT_ROLES: readonly AiUserRole[] = ["director", "control", "accountant"];
const OFFICE_ROLES: readonly AiUserRole[] = ["director", "control", "office", "admin"];
const MARKET_ROLES: readonly AiUserRole[] = ["director", "control", "buyer", "foreman"];
const COMMAND_CENTER_ROLES: readonly AiUserRole[] = [
  "director",
  "control",
  "foreman",
  "buyer",
  "accountant",
  "warehouse",
  "contractor",
  "office",
  "admin",
];

export const AI_BUTTON_ACTION_REGISTRY: readonly AiButtonActionEntry[] = [
  {
    screenId: "director.dashboard",
    buttonId: "director.finance.debt.open",
    testId: "director-finance-dashboard-debt-card",
    label: "Open finance debts",
    domain: "finance",
    intent: "read",
    riskLevel: "safe_read",
    allowedRoles: CONTROL_ROLES,
    requiredTool: "get_finance_summary",
    approvalRequired: false,
    evidenceRequired: true,
    sourceEntities: ["company_debt", "payment", "pdf_document"],
  },
  {
    screenId: "director.dashboard",
    buttonId: "director.reports.open",
    testId: "director-reports-home-card",
    label: "Open reports",
    domain: "reports",
    intent: "read",
    riskLevel: "safe_read",
    allowedRoles: CONTROL_ROLES,
    requiredTool: "draft_report",
    approvalRequired: false,
    evidenceRequired: true,
    sourceEntities: ["report", "project", "pdf_document"],
  },
  {
    screenId: "ai.command.center",
    buttonId: "ai.command.center.ask_why",
    testId: "ai.command.center.action.ask-why",
    label: "Explain why",
    domain: "control",
    intent: "explain",
    riskLevel: "safe_read",
    allowedRoles: COMMAND_CENTER_ROLES,
    approvalRequired: false,
    evidenceRequired: true,
    sourceEntities: ["project", "request", "supplier", "warehouse_item", "payment", "report"],
  },
  {
    screenId: "ai.command.center",
    buttonId: "ai.command.center.create_draft",
    testId: "ai.command.center.action.create-draft",
    label: "Create draft",
    domain: "documents",
    intent: "draft",
    riskLevel: "draft_only",
    allowedRoles: COMMAND_CENTER_ROLES,
    requiredTool: "draft_request",
    approvalRequired: false,
    evidenceRequired: true,
    sourceEntities: ["request", "material", "pdf_document", "act"],
  },
  {
    screenId: "ai.command.center",
    buttonId: "ai.command.center.submit_for_approval",
    testId: "ai.command.center.action.submit-for-approval",
    label: "Submit for approval",
    domain: "documents",
    intent: "submit_for_approval",
    riskLevel: "approval_required",
    allowedRoles: COMMAND_CENTER_ROLES,
    requiredTool: "submit_for_approval",
    approvalRequired: true,
    evidenceRequired: true,
    sourceEntities: ["request", "report", "act", "pdf_document"],
  },
  {
    screenId: "buyer.main",
    buttonId: "buyer.request.tab.inbox",
    testId: "buyer-tab-inbox",
    label: "Open new requests",
    domain: "procurement",
    intent: "read",
    riskLevel: "safe_read",
    allowedRoles: BUYER_ROLES,
    approvalRequired: false,
    evidenceRequired: true,
    sourceEntities: ["request", "material"],
  },
  {
    screenId: "buyer.main",
    buttonId: "buyer.rfq.open",
    testId: "buyer-rfq-open",
    label: "Prepare RFQ",
    domain: "procurement",
    intent: "draft",
    riskLevel: "draft_only",
    allowedRoles: BUYER_ROLES,
    requiredTool: "draft_request",
    approvalRequired: false,
    evidenceRequired: true,
    sourceEntities: ["request", "material", "supplier"],
  },
  {
    screenId: "buyer.main",
    buttonId: "buyer.proposals.send",
    testId: "buyer-create-proposals-send",
    label: "Send proposal package",
    domain: "procurement",
    intent: "submit_for_approval",
    riskLevel: "approval_required",
    allowedRoles: BUYER_ROLES,
    requiredTool: "submit_for_approval",
    approvalRequired: true,
    evidenceRequired: true,
    sourceEntities: ["request", "supplier", "pdf_document"],
  },
  {
    screenId: "market.home",
    buttonId: "market.search.input",
    testId: "market_search_input",
    label: "Search marketplace catalog",
    domain: "marketplace",
    intent: "search",
    riskLevel: "safe_read",
    allowedRoles: MARKET_ROLES,
    requiredTool: "search_catalog",
    approvalRequired: false,
    evidenceRequired: true,
    sourceEntities: ["material", "supplier"],
  },
  {
    screenId: "market.home",
    buttonId: "market.add_to_request",
    testId: "market_add_to_request_${listing.id}",
    label: "Add marketplace item to request draft",
    domain: "marketplace",
    intent: "draft",
    riskLevel: "draft_only",
    allowedRoles: ["director", "control", "buyer"],
    requiredTool: "draft_request",
    approvalRequired: false,
    evidenceRequired: true,
    sourceEntities: ["supplier", "material", "request"],
  },
  {
    screenId: "accountant.main",
    buttonId: "accountant.proposal.open",
    testId: "accountant-proposal-row-${proposalId}",
    label: "Open proposal finance document",
    domain: "finance",
    intent: "read",
    riskLevel: "safe_read",
    allowedRoles: ACCOUNTANT_ROLES,
    requiredTool: "get_finance_summary",
    approvalRequired: false,
    evidenceRequired: true,
    sourceEntities: ["payment", "company_debt", "accounting_posting", "pdf_document"],
  },
  {
    screenId: "accountant.main",
    buttonId: "accountant.submit.payment.boundary",
    testId: "accountant-payment-submit",
    label: "Submit payment document for approval",
    domain: "finance",
    intent: "submit_for_approval",
    riskLevel: "approval_required",
    allowedRoles: ACCOUNTANT_ROLES,
    requiredTool: "submit_for_approval",
    approvalRequired: true,
    evidenceRequired: true,
    sourceEntities: ["payment", "company_debt", "accounting_posting", "pdf_document"],
  },
  {
    screenId: "foreman.main",
    buttonId: "foreman.materials.open",
    testId: "foreman-main-materials-open",
    label: "Open materials",
    domain: "procurement",
    intent: "read",
    riskLevel: "safe_read",
    allowedRoles: FOREMAN_ROLES,
    requiredTool: "get_warehouse_status",
    approvalRequired: false,
    evidenceRequired: true,
    sourceEntities: ["project", "request", "material", "warehouse_item"],
  },
  {
    screenId: "foreman.main",
    buttonId: "foreman.subcontracts.open",
    testId: "foreman-main-subcontracts-open",
    label: "Open subcontracts",
    domain: "subcontracts",
    intent: "read",
    riskLevel: "safe_read",
    allowedRoles: FOREMAN_ROLES,
    approvalRequired: false,
    evidenceRequired: true,
    sourceEntities: ["project", "subcontract", "contractor", "act"],
  },
  {
    screenId: "foreman.subcontract",
    buttonId: "foreman.subcontract.draft.act",
    testId: "foreman-subcontract-draft-open",
    label: "Prepare subcontract act draft",
    domain: "subcontracts",
    intent: "draft",
    riskLevel: "draft_only",
    allowedRoles: FOREMAN_ROLES,
    requiredTool: "draft_act",
    approvalRequired: false,
    evidenceRequired: true,
    sourceEntities: ["subcontract", "contractor", "act", "report"],
  },
  {
    screenId: "warehouse.main",
    buttonId: "warehouse.tab.stock",
    testId: "warehouse-tab-stock",
    label: "Open stock status",
    domain: "warehouse",
    intent: "read",
    riskLevel: "safe_read",
    allowedRoles: WAREHOUSE_ROLES,
    requiredTool: "get_warehouse_status",
    approvalRequired: false,
    evidenceRequired: true,
    sourceEntities: ["warehouse_item", "stock_movement", "material"],
  },
  {
    screenId: "warehouse.main",
    buttonId: "warehouse.day.materials.pdf",
    testId: "warehouse-day-materials-pdf",
    label: "Prepare warehouse materials document",
    domain: "warehouse",
    intent: "draft",
    riskLevel: "draft_only",
    allowedRoles: WAREHOUSE_ROLES,
    requiredTool: "draft_report",
    approvalRequired: false,
    evidenceRequired: true,
    sourceEntities: ["warehouse_item", "stock_movement", "pdf_document"],
  },
  {
    screenId: "contractor.main",
    buttonId: "contractor.work.card.open",
    testId: "contractor-work-card-${cardToken}",
    label: "Open own subcontract task",
    domain: "subcontracts",
    intent: "read",
    riskLevel: "safe_read",
    allowedRoles: ["contractor"],
    approvalRequired: false,
    evidenceRequired: true,
    sourceEntities: ["subcontract", "contractor", "act", "pdf_document"],
  },
  {
    screenId: "contractor.main",
    buttonId: "contractor.progress.submit",
    testId: "contractor-progress-submit",
    label: "Submit progress for review",
    domain: "subcontracts",
    intent: "submit_for_approval",
    riskLevel: "approval_required",
    allowedRoles: ["contractor"],
    requiredTool: "submit_for_approval",
    approvalRequired: true,
    evidenceRequired: true,
    sourceEntities: ["subcontract", "contractor", "act", "report"],
  },
  {
    screenId: "office.hub",
    buttonId: "office.invite.create",
    testId: "office-create-invite",
    label: "Prepare member invitation",
    domain: "office",
    intent: "submit_for_approval",
    riskLevel: "approval_required",
    allowedRoles: OFFICE_ROLES,
    requiredTool: "submit_for_approval",
    approvalRequired: true,
    evidenceRequired: true,
    sourceEntities: ["office_member", "contractor"],
  },
  {
    screenId: "map.main",
    buttonId: "map.catalog.search",
    testId: "map-catalog-search-open",
    label: "Open map catalog search",
    domain: "real_estate",
    intent: "search",
    riskLevel: "safe_read",
    allowedRoles: MARKET_ROLES,
    requiredTool: "search_catalog",
    approvalRequired: false,
    evidenceRequired: true,
    sourceEntities: ["real_estate_object", "land_plot", "commercial_space", "map_object"],
  },
  {
    screenId: "chat.main",
    buttonId: "chat.message.send",
    testId: "chat-send-button",
    label: "Send chat message",
    domain: "chat",
    intent: "submit_for_approval",
    riskLevel: "approval_required",
    allowedRoles: COMMAND_CENTER_ROLES,
    requiredTool: "submit_for_approval",
    approvalRequired: true,
    evidenceRequired: true,
    sourceEntities: ["chat_thread", "pdf_document", "office_member"],
  },
  {
    screenId: "buyer.main",
    buttonId: "buyer.confirm_supplier.direct",
    testId: "buyer-confirm-supplier-direct-forbidden",
    label: "Direct supplier confirmation",
    domain: "procurement",
    intent: "execute_approved",
    riskLevel: "forbidden",
    allowedRoles: [],
    approvalRequired: true,
    evidenceRequired: true,
    sourceEntities: ["supplier", "request"],
  },
] as const;

export function getAiButtonActionEntry(buttonId: string): AiButtonActionEntry | null {
  const normalized = String(buttonId || "").trim();
  return AI_BUTTON_ACTION_REGISTRY.find((entry) => entry.buttonId === normalized) ?? null;
}

export function listAiButtonActionEntriesForScreen(screenId: string): AiButtonActionEntry[] {
  const normalized = String(screenId || "").trim();
  return AI_BUTTON_ACTION_REGISTRY.filter((entry) => entry.screenId === normalized);
}

export function listAiButtonActionEntries(): AiButtonActionEntry[] {
  return [...AI_BUTTON_ACTION_REGISTRY];
}
