import type { AiUserRole } from "../policy/aiRolePolicy";
import type { AiAppActionIntent, AiScreenActionEntry } from "./aiAppActionTypes";

const CONTROL_ROLES: readonly AiUserRole[] = ["director", "control"];
const ALL_OPERATION_ROLES: readonly AiUserRole[] = [
  "director",
  "control",
  "foreman",
  "buyer",
  "accountant",
  "warehouse",
  "contractor",
  "office",
  "admin",
];
const READ_EXPLAIN_NAVIGATE: readonly AiAppActionIntent[] = ["read", "explain", "navigate"];
const READ_SEARCH_COMPARE_DRAFT: readonly AiAppActionIntent[] = [
  "read",
  "search",
  "compare",
  "explain",
  "draft",
  "submit_for_approval",
  "navigate",
];

export const AI_MAJOR_SCREEN_IDS = [
  "director.dashboard",
  "ai.command.center",
  "buyer.main",
  "market.home",
  "accountant.main",
  "foreman.main",
  "foreman.subcontract",
  "warehouse.main",
  "contractor.main",
  "office.hub",
  "map.main",
  "chat.main",
] as const;

export const AI_SCREEN_ACTION_REGISTRY: readonly AiScreenActionEntry[] = [
  {
    screenId: "director.dashboard",
    domain: "control",
    allowedRoles: CONTROL_ROLES,
    businessEntities: [
      "project",
      "request",
      "supplier",
      "warehouse_item",
      "payment",
      "company_debt",
      "report",
      "act",
      "subcontract",
      "contractor",
    ],
    allowedIntents: [
      "read",
      "search",
      "compare",
      "explain",
      "draft",
      "submit_for_approval",
      "approve",
      "execute_approved",
      "navigate",
    ],
    blockedIntents: [],
    approvalBoundary: "approval_required",
    evidenceRequired: true,
    source: "app_action_graph_registry_v1",
  },
  {
    screenId: "ai.command.center",
    domain: "control",
    allowedRoles: ALL_OPERATION_ROLES,
    businessEntities: [
      "project",
      "request",
      "supplier",
      "material",
      "warehouse_item",
      "payment",
      "company_debt",
      "report",
      "pdf_document",
      "act",
      "subcontract",
      "contractor",
      "office_member",
    ],
    allowedIntents: READ_SEARCH_COMPARE_DRAFT,
    blockedIntents: ["approve", "execute_approved"],
    approvalBoundary: "approval_required",
    evidenceRequired: true,
    source: "app_action_graph_registry_v1",
  },
  {
    screenId: "buyer.main",
    domain: "procurement",
    allowedRoles: ["director", "control", "buyer"],
    businessEntities: ["request", "material", "supplier", "pdf_document", "subcontract"],
    allowedIntents: READ_SEARCH_COMPARE_DRAFT,
    blockedIntents: ["approve", "execute_approved"],
    approvalBoundary: "approval_required",
    evidenceRequired: true,
    source: "app_action_graph_registry_v1",
  },
  {
    screenId: "market.home",
    domain: "marketplace",
    allowedRoles: ["director", "control", "buyer", "foreman"],
    businessEntities: ["supplier", "material", "request", "map_object"],
    allowedIntents: ["read", "search", "compare", "explain", "draft", "navigate"],
    blockedIntents: ["approve", "execute_approved", "submit_for_approval"],
    approvalBoundary: "draft_only",
    evidenceRequired: true,
    source: "app_action_graph_registry_v1",
  },
  {
    screenId: "accountant.main",
    domain: "finance",
    allowedRoles: ["director", "control", "accountant"],
    businessEntities: [
      "payment",
      "company_debt",
      "accounting_posting",
      "act",
      "pdf_document",
      "supplier",
    ],
    allowedIntents: READ_SEARCH_COMPARE_DRAFT,
    blockedIntents: ["approve", "execute_approved"],
    approvalBoundary: "approval_required",
    evidenceRequired: true,
    source: "app_action_graph_registry_v1",
  },
  {
    screenId: "foreman.main",
    domain: "procurement",
    allowedRoles: ["director", "control", "foreman"],
    businessEntities: ["project", "request", "material", "warehouse_item", "report"],
    allowedIntents: READ_SEARCH_COMPARE_DRAFT,
    blockedIntents: ["approve", "execute_approved"],
    approvalBoundary: "draft_only",
    evidenceRequired: true,
    source: "app_action_graph_registry_v1",
  },
  {
    screenId: "foreman.subcontract",
    domain: "subcontracts",
    allowedRoles: ["director", "control", "foreman"],
    businessEntities: ["project", "subcontract", "contractor", "act", "report", "pdf_document"],
    allowedIntents: READ_SEARCH_COMPARE_DRAFT,
    blockedIntents: ["approve", "execute_approved"],
    approvalBoundary: "approval_required",
    evidenceRequired: true,
    source: "app_action_graph_registry_v1",
  },
  {
    screenId: "warehouse.main",
    domain: "warehouse",
    allowedRoles: ["director", "control", "warehouse"],
    businessEntities: ["warehouse_item", "stock_movement", "material", "request", "pdf_document"],
    allowedIntents: ["read", "search", "explain", "draft", "submit_for_approval", "navigate"],
    blockedIntents: ["compare", "approve", "execute_approved"],
    approvalBoundary: "approval_required",
    evidenceRequired: true,
    source: "app_action_graph_registry_v1",
  },
  {
    screenId: "contractor.main",
    domain: "subcontracts",
    allowedRoles: ["contractor"],
    businessEntities: ["subcontract", "contractor", "act", "pdf_document", "report"],
    allowedIntents: ["read", "explain", "draft", "submit_for_approval", "navigate"],
    blockedIntents: ["search", "compare", "approve", "execute_approved"],
    approvalBoundary: "approval_required",
    evidenceRequired: true,
    source: "app_action_graph_registry_v1",
  },
  {
    screenId: "office.hub",
    domain: "office",
    allowedRoles: ["director", "control", "office", "admin"],
    businessEntities: ["office_member", "contractor", "supplier", "project"],
    allowedIntents: ["read", "explain", "draft", "submit_for_approval", "navigate"],
    blockedIntents: ["compare", "approve", "execute_approved"],
    approvalBoundary: "approval_required",
    evidenceRequired: true,
    source: "app_action_graph_registry_v1",
  },
  {
    screenId: "map.main",
    domain: "real_estate",
    allowedRoles: ["director", "control", "buyer", "foreman"],
    businessEntities: ["real_estate_object", "land_plot", "commercial_space", "map_object", "supplier"],
    allowedIntents: READ_EXPLAIN_NAVIGATE,
    blockedIntents: ["compare", "draft", "submit_for_approval", "approve", "execute_approved"],
    approvalBoundary: "none",
    evidenceRequired: true,
    source: "app_action_graph_registry_v1",
  },
  {
    screenId: "chat.main",
    domain: "chat",
    allowedRoles: ALL_OPERATION_ROLES,
    businessEntities: ["chat_thread", "pdf_document", "office_member"],
    allowedIntents: ["read", "explain", "draft", "submit_for_approval", "navigate"],
    blockedIntents: ["compare", "approve", "execute_approved"],
    approvalBoundary: "approval_required",
    evidenceRequired: true,
    source: "app_action_graph_registry_v1",
  },
] as const;

export function getAiScreenActionEntry(screenId: string): AiScreenActionEntry | null {
  const normalized = String(screenId || "").trim();
  return AI_SCREEN_ACTION_REGISTRY.find((entry) => entry.screenId === normalized) ?? null;
}

export function listAiScreenActionEntries(): AiScreenActionEntry[] {
  return [...AI_SCREEN_ACTION_REGISTRY];
}
