import type { ConstructionKnowledgeSource } from "../../src/lib/ai/constructionKnowledgeCore";
import type { AccountantFinanceContext } from "../../src/lib/ai/accountantFinance";

const sources: ConstructionKnowledgeSource[] = [
  {
    id: "src:invoice:INV-204",
    type: "payment",
    labelRu: "Счет INV-204 от Бетон Плюс, 480000 KGS",
    linkedObjectId: "OBJ-7",
    linkedWorkId: "WRK-701",
    linkedEstimateLineId: "EST-91",
    confidence: "high",
  },
  {
    id: "src:act:ACT-701",
    type: "act",
    labelRu: "Акт ACT-701: бетонные работы, подписан прорабом",
    documentId: "DOC-ACT-701",
    fileName: "act_701.pdf",
    page: 1,
    linkedObjectId: "OBJ-7",
    linkedWorkId: "WRK-701",
    linkedEstimateLineId: "EST-91",
    confidence: "high",
  },
  {
    id: "src:estimate:EST-91",
    type: "estimate_pdf",
    labelRu: "Смета объекта, строка EST-91: бетон М300",
    documentId: "DOC-EST-7",
    fileName: "estimate_obj7.pdf",
    page: 9,
    linkedObjectId: "OBJ-7",
    linkedWorkId: "WRK-701",
    linkedEstimateLineId: "EST-91",
    confidence: "high",
  },
  {
    id: "src:project:KJ-22",
    type: "engineering_pdf",
    labelRu: "Проект КЖ.pdf, раздел бетонные работы",
    documentId: "DOC-KJ",
    fileName: "project_kj.pdf",
    page: 22,
    linkedObjectId: "OBJ-7",
    linkedWorkId: "WRK-701",
    confidence: "high",
  },
  {
    id: "src:procurement:MR-701",
    type: "procurement_request",
    labelRu: "Заявка MR-701: бетон М300",
    linkedObjectId: "OBJ-7",
    linkedWorkId: "WRK-701",
    linkedMaterialId: "MAT-BETON",
    confidence: "high",
  },
  {
    id: "src:supplier:KP-701",
    type: "supplier_offer",
    labelRu: "КП Бетон Плюс, действует до 2026-05-25",
    documentId: "DOC-KP-701",
    fileName: "kp_beton_plus.pdf",
    page: 1,
    linkedMaterialId: "MAT-BETON",
    confidence: "high",
  },
  {
    id: "src:object:OBJ-7",
    type: "object",
    labelRu: "Объект: Складской корпус",
    linkedObjectId: "OBJ-7",
    confidence: "high",
  },
  {
    id: "src:work:WRK-701",
    type: "work",
    labelRu: "Работа WRK-701: бетонная подготовка",
    linkedObjectId: "OBJ-7",
    linkedWorkId: "WRK-701",
    confidence: "high",
  },
  {
    id: "src:payment:PAY-10",
    type: "payment",
    labelRu: "Платеж PAY-10: 120000 KGS, pending approval",
    linkedObjectId: "OBJ-7",
    linkedWorkId: "WRK-701",
    confidence: "high",
  },
  {
    id: "src:approval:INV-204",
    type: "approval",
    labelRu: "Approval route INV-204: директор",
    linkedObjectId: "OBJ-7",
    linkedWorkId: "WRK-701",
    confidence: "high",
  },
  {
    id: "src:country:KG",
    type: "country_profile",
    labelRu: "Country profile KG: KGS, local document names",
    countryCode: "KG",
    confidence: "high",
  },
  {
    id: "src:company:accounts",
    type: "company_standard",
    labelRu: "Стандарт компании: план счетов и маршрут оплат",
    confidence: "high",
  },
  {
    id: "src:security:hidden",
    type: "chat_message",
    labelRu: "runtime debug provider secret hidden",
    confidence: "high",
  },
];

export function buildAccountantRealFinanceFixture(
  overrides: Partial<AccountantFinanceContext> = {},
): AccountantFinanceContext {
  return {
    screenId: "accountant.invoice.detail",
    role: "accountant",
    questionRu: "почему этот счет можно или нельзя оплачивать",
    selectedInvoiceId: "INV-204",
    selectedPaymentId: "PAY-10",
    countryCode: "KG",
    currency: "KGS",
    invoices: [
      {
        id: "INV-204",
        numberRu: "INV-204",
        supplierNameRu: "Бетон Плюс",
        amount: 480000,
        currency: "KGS",
        invoiceDate: "2026-05-19",
        dueDate: "2026-05-23",
        status: "needs_check",
        requestId: "MR-701",
        actId: "ACT-701",
        workId: "WRK-701",
        objectId: "OBJ-7",
        estimateLineId: "EST-91",
        sourceRefs: ["src:invoice:INV-204"],
      },
    ],
    acts: [
      {
        id: "ACT-701",
        titleRu: "Акт ACT-701: бетонная подготовка",
        amount: 480000,
        currency: "KGS",
        signedByHuman: true,
        linkedWorkId: "WRK-701",
        linkedEstimateLineId: "EST-91",
        sourceRefs: ["src:act:ACT-701"],
      },
    ],
    payments: [
      {
        id: "PAY-10",
        invoiceId: "INV-204",
        amount: 120000,
        currency: "KGS",
        status: "pending_approval",
        sourceRefs: ["src:payment:PAY-10"],
      },
    ],
    cashflow: [
      {
        id: "cashflow:obj7:may",
        scope: "object",
        periodRu: "май 2026",
        outgoingAmount: 120000,
        incomingAmount: 0,
        currency: "KGS",
        sourceRefs: ["src:payment:PAY-10"],
      },
    ],
    sources,
    chartOfAccountsConfigured: true,
    countryTaxProfileConfigured: true,
    ...overrides,
  };
}

export function buildAccountantMissingSourceFixture(): AccountantFinanceContext {
  return buildAccountantRealFinanceFixture({
    sources: sources.filter((source) => !["country_profile", "company_standard", "engineering_pdf", "estimate_pdf"].includes(source.type)),
    chartOfAccountsConfigured: false,
    countryTaxProfileConfigured: false,
    invoices: [
      {
        id: "INV-205",
        numberRu: "INV-205",
        supplierNameRu: "Документы не полные",
        amount: 250000,
        currency: "KGS",
        invoiceDate: "2026-05-19",
        status: "blocked",
        sourceRefs: ["src:invoice:INV-204"],
      },
    ],
    acts: [],
    payments: [],
    selectedInvoiceId: "INV-205",
  });
}
