import type { ConstructionKnowledgeSource } from "../../src/lib/ai/constructionKnowledgeCore";
import type {
  BuyerSourcingContext,
  BuyerSourcingOffer,
} from "../../src/lib/ai/buyerSourcing";

const sources: ConstructionKnowledgeSource[] = [
  {
    id: "src:procurement:MR-1042",
    type: "procurement_request",
    labelRu: "Заявка MR-1042: ГКЛ 12.5 мм, дефицит 24 листа",
    linkedObjectId: "OBJ-1",
    linkedWorkId: "WRK-1042",
    linkedMaterialId: "MAT-GKL",
    confidence: "high",
  },
  {
    id: "src:object:dom1",
    type: "object",
    labelRu: "Объект: Дом 1",
    linkedObjectId: "OBJ-1",
    confidence: "high",
  },
  {
    id: "src:work:1042",
    type: "work",
    labelRu: "Работа WRK-1042: монтаж перегородок",
    linkedObjectId: "OBJ-1",
    linkedWorkId: "WRK-1042",
    confidence: "high",
  },
  {
    id: "src:material:gkl",
    type: "material",
    labelRu: "ГКЛ 12.5 мм",
    linkedWorkId: "WRK-1042",
    linkedMaterialId: "MAT-GKL",
    confidence: "high",
  },
  {
    id: "src:stock:gkl",
    type: "warehouse_stock",
    labelRu: "Склад: ГКЛ 12.5 мм, доступно 18 листов",
    linkedObjectId: "OBJ-1",
    linkedWorkId: "WRK-1042",
    linkedMaterialId: "MAT-GKL",
    confidence: "high",
  },
  {
    id: "src:estimate:77",
    type: "estimate_pdf",
    labelRu: "Смета объекта, строка EST-77",
    documentId: "DOC-EST",
    fileName: "estimate_dom1.pdf",
    page: 12,
    linkedWorkId: "WRK-1042",
    linkedMaterialId: "MAT-GKL",
    linkedEstimateLineId: "EST-77",
    confidence: "high",
  },
  {
    id: "src:project:ar14",
    type: "architecture_pdf",
    labelRu: "Проект АР.pdf, раздел Перегородки",
    documentId: "DOC-AR",
    fileName: "project_ar.pdf",
    page: 14,
    linkedObjectId: "OBJ-1",
    linkedWorkId: "WRK-1042",
    linkedMaterialId: "MAT-GKL",
    confidence: "high",
  },
  {
    id: "src:spec:gkl",
    type: "specification",
    labelRu: "Спецификация: ГКЛ 12.5 мм",
    documentId: "DOC-SPEC",
    fileName: "spec_gkl.pdf",
    page: 3,
    linkedObjectId: "OBJ-1",
    linkedWorkId: "WRK-1042",
    linkedMaterialId: "MAT-GKL",
    confidence: "high",
  },
  {
    id: "src:approval:MR-1042",
    type: "approval",
    labelRu: "Approval route MR-1042: директор",
    linkedObjectId: "OBJ-1",
    linkedWorkId: "WRK-1042",
    linkedMaterialId: "MAT-GKL",
    confidence: "high",
  },
  {
    id: "src:supplier:offer:karta",
    type: "supplier_offer",
    labelRu: "КП ГипсМаркет, действует до 2026-05-21",
    documentId: "DOC-KP-1",
    fileName: "kp_gipsmarket.pdf",
    page: 1,
    linkedMaterialId: "MAT-GKL",
    confidence: "high",
  },
  {
    id: "src:payment:hidden",
    type: "payment",
    labelRu: "Full company cashflow hidden from buyer",
    confidence: "high",
  },
];

const offers: BuyerSourcingOffer[] = [
  {
    id: "offer:market:221",
    requestId: "MR-1042",
    requestLineId: "MRL-1",
    sourceType: "own_marketplace",
    supplierId: "SUP-MARKET",
    supplierNameRu: "ОсОО СтройМаркет",
    itemNameRu: "ГКЛ 12.5 мм",
    brand: "Knauf",
    specificationMatch: "exact",
    quantityAvailable: 50,
    unit: "лист",
    price: 125,
    currency: "KGS",
    priceDate: "2026-05-19",
    deliveryDays: 1,
    deliveryRegion: "Бишкек",
    availability: "in_stock",
    riskLevel: "low",
    riskReasonsRu: [],
    sourceLabelRu: "наш marketplace MK-221",
    sourceDocumentId: "MK-221",
    lastCheckedAt: "2026-05-19T09:00:00+06:00",
  },
  {
    id: "offer:market:222",
    requestId: "MR-1042",
    requestLineId: "MRL-1",
    sourceType: "own_marketplace",
    supplierId: "SUP-NORTH",
    supplierNameRu: "База Север",
    itemNameRu: "ГКЛ 12.5 мм",
    specificationMatch: "exact",
    quantityAvailable: 40,
    unit: "лист",
    price: 130,
    currency: "KGS",
    priceDate: "2026-05-19",
    deliveryDays: 2,
    deliveryRegion: "Бишкек",
    availability: "in_stock",
    riskLevel: "medium",
    riskReasonsRu: ["доставка требует подтверждения"],
    sourceLabelRu: "наш marketplace MK-222",
    sourceDocumentId: "MK-222",
    lastCheckedAt: "2026-05-19T09:05:00+06:00",
  },
  {
    id: "offer:market:223",
    requestId: "MR-1042",
    requestLineId: "MRL-1",
    sourceType: "own_marketplace",
    supplierNameRu: "Профиль Комплект",
    itemNameRu: "ГКЛ 12.5 мм",
    specificationMatch: "exact",
    quantityAvailable: 30,
    unit: "лист",
    price: 128,
    currency: "KGS",
    priceDate: "2026-05-19",
    deliveryDays: 3,
    deliveryRegion: "Бишкек",
    availability: "in_stock",
    riskLevel: "low",
    riskReasonsRu: [],
    sourceLabelRu: "наш marketplace MK-223",
    sourceDocumentId: "MK-223",
    lastCheckedAt: "2026-05-19T09:10:00+06:00",
  },
  {
    id: "offer:market:224",
    requestId: "MR-1042",
    requestLineId: "MRL-1",
    sourceType: "own_marketplace",
    supplierNameRu: "Снаб Дом",
    itemNameRu: "ГКЛ 12.5 мм",
    specificationMatch: "exact",
    quantityAvailable: 24,
    unit: "лист",
    price: 133,
    currency: "KGS",
    priceDate: "2026-05-19",
    deliveryDays: 1,
    deliveryRegion: "Бишкек",
    availability: "limited",
    riskLevel: "medium",
    riskReasonsRu: ["ограниченный остаток"],
    sourceLabelRu: "наш marketplace MK-224",
    sourceDocumentId: "MK-224",
    lastCheckedAt: "2026-05-19T09:15:00+06:00",
  },
  {
    id: "offer:vendor:31",
    requestId: "MR-1042",
    requestLineId: "MRL-1",
    sourceType: "approved_vendor",
    supplierId: "SUP-APPROVED",
    supplierNameRu: "Approved Build KG",
    itemNameRu: "ГКЛ 12.5 мм",
    specificationMatch: "exact",
    quantityAvailable: 80,
    unit: "лист",
    price: 132,
    currency: "KGS",
    priceDate: "2026-05-19",
    deliveryDays: 2,
    deliveryRegion: "Бишкек",
    availability: "in_stock",
    riskLevel: "low",
    riskReasonsRu: [],
    sourceLabelRu: "approved vendor AV-31",
    sourceDocumentId: "AV-31",
    lastCheckedAt: "2026-05-19T09:20:00+06:00",
  },
  {
    id: "offer:history:12",
    requestId: "MR-1042",
    requestLineId: "MRL-1",
    sourceType: "supplier_history",
    supplierNameRu: "История: ГипсТрейд",
    itemNameRu: "ГКЛ 12.5 мм",
    specificationMatch: "exact",
    quantityAvailable: 20,
    unit: "лист",
    price: 127,
    currency: "KGS",
    priceDate: "2026-04-27",
    deliveryDays: 4,
    deliveryRegion: "Бишкек",
    availability: "on_request",
    riskLevel: "medium",
    riskReasonsRu: ["наличие нужно подтвердить"],
    sourceLabelRu: "история закупок PO-870",
    sourceDocumentId: "PO-870",
    lastCheckedAt: "2026-05-19T09:25:00+06:00",
  },
  {
    id: "offer:supplier:kp1",
    requestId: "MR-1042",
    requestLineId: "MRL-1",
    sourceType: "supplier_offer",
    supplierNameRu: "ГипсМаркет",
    itemNameRu: "ГКЛ 12.5 мм",
    specificationMatch: "exact",
    quantityAvailable: 60,
    unit: "лист",
    price: 129,
    currency: "KGS",
    priceDate: "2026-05-19",
    deliveryDays: 2,
    deliveryRegion: "Бишкек",
    availability: "in_stock",
    riskLevel: "low",
    riskReasonsRu: ["цена действует до 2026-05-21"],
    sourceLabelRu: "КП supplier offer DOC-KP-1",
    sourceDocumentId: "DOC-KP-1",
    sourcePage: 1,
    lastCheckedAt: "2026-05-19T09:30:00+06:00",
  },
  {
    id: "offer:external:kg-market",
    requestId: "MR-1042",
    requestLineId: "MRL-1",
    sourceType: "external_marketplace",
    supplierNameRu: "KG Market Pro",
    itemNameRu: "ГКЛ 12.5 мм",
    specificationMatch: "needs_review",
    quantityAvailable: 100,
    unit: "лист",
    price: 122,
    currency: "KGS",
    priceDate: "2026-05-19",
    deliveryDays: 5,
    deliveryRegion: "Бишкек",
    availability: "in_stock",
    riskLevel: "high",
    riskReasonsRu: ["аналог требует проверки проектом", "нет истории документов в компании"],
    sourceLabelRu: "external marketplace KG-MARKET",
    sourceUrl: "https://market.example.test/kg/gkl-12-5",
    lastCheckedAt: "2026-05-19T09:35:00+06:00",
  },
];

export function buildBuyerRealSourcingFixture(
  overrides: Partial<BuyerSourcingContext> = {},
): BuyerSourcingContext {
  return {
    screenId: "buyer.request.detail",
    role: "buyer",
    questionRu: "найди 10 вариантов по этой заявке",
    request: {
      id: "MR-1042",
      status: "approved",
      createdAt: "2026-05-19",
      createdByRu: "Прораб Дом 1",
      approvedByRu: "Директор",
      objectId: "OBJ-1",
      objectRu: "Дом 1, 2 этаж",
      zoneRu: "2 этаж",
      workId: "WRK-1042",
      workRu: "Монтаж перегородок",
      priority: "high",
      sourceRefs: ["src:procurement:MR-1042", "src:work:1042", "src:object:dom1"],
      lines: [
        {
          id: "MRL-1",
          itemRu: "ГКЛ 12.5 мм",
          category: "ГКЛ / профили",
          quantity: 42,
          unit: "лист",
          requiredDate: "2026-05-22",
          specificationText: "ГКЛ 12.5 мм для перегородок, лист, допускаются аналоги после проверки проекта.",
          brandPreference: "Knauf",
          allowAnalogs: true,
          materialId: "MAT-GKL",
        },
      ],
    },
    selectedRequestLineId: "MRL-1",
    countryCode: "KG",
    cityOrRegion: "Бишкек",
    currency: "KGS",
    sources,
    warehouseStock: [
      {
        id: "stock:gkl",
        requestLineId: "MRL-1",
        materialId: "MAT-GKL",
        itemRu: "ГКЛ 12.5 мм",
        availableQty: 18,
        reservedQty: 0,
        incomingQty: 0,
        unit: "лист",
        sourceRef: "src:stock:gkl",
      },
    ],
    offers,
    externalMarketplaceConnected: true,
    internetSourcingConnected: false,
    ...overrides,
  };
}

export function buildBuyerFewOffersFixture(): BuyerSourcingContext {
  return buildBuyerRealSourcingFixture({
    externalMarketplaceConnected: false,
    internetSourcingConnected: false,
    offers: offers.slice(0, 3),
  });
}

export function buildBuyerNoOffersFixture(): BuyerSourcingContext {
  return buildBuyerRealSourcingFixture({
    externalMarketplaceConnected: false,
    internetSourcingConnected: false,
    offers: [],
    warehouseStock: [],
  });
}
