import type { AgentTaskStreamCard } from "../../src/features/ai/agent/agentBffRouteShell";

export const aiCommandCenterTaskCards: AgentTaskStreamCard[] = [
  {
    id: "approval-pending-1",
    type: "approval_pending",
    title: "Approval pending",
    summary: "Request waits for approval",
    domain: "control",
    priority: "critical",
    createdAt: "2026-05-12T10:00:00.000Z",
    evidenceRefs: ["approval:pending:redacted"],
    scope: { kind: "cross_domain" },
    recommendedToolName: "get_action_status",
  },
  {
    id: "finance-risk-1",
    type: "finance_risk",
    title: "Finance risk",
    summary: "Debt bucket requires director/accountant review",
    domain: "finance",
    priority: "critical",
    createdAt: "2026-05-12T09:00:00.000Z",
    evidenceRefs: ["finance:risk:redacted"],
    scope: { kind: "role_domain", allowedRoles: ["director", "control", "accountant"] },
    recommendedToolName: "get_finance_summary",
  },
  {
    id: "supplier-compare-1",
    type: "supplier_price_change",
    title: "Supplier comparison",
    summary: "Supplier comparison should be refreshed",
    domain: "procurement",
    priority: "high",
    createdAt: "2026-05-12T08:00:00.000Z",
    evidenceRefs: ["supplier:compare:redacted"],
    scope: { kind: "role_domain", allowedRoles: ["director", "control", "buyer"] },
    recommendedToolName: "compare_suppliers",
  },
  {
    id: "draft-request-1",
    type: "draft_ready",
    title: "Draft request ready",
    summary: "Request draft can be prepared",
    domain: "procurement",
    priority: "normal",
    createdAt: "2026-05-12T07:00:00.000Z",
    evidenceRefs: ["draft:request:redacted"],
    scope: { kind: "role_domain", allowedRoles: ["director", "control", "buyer", "foreman"] },
    recommendedToolName: "draft_request",
  },
  {
    id: "submit-request-1",
    type: "draft_ready",
    title: "Submit request for approval",
    summary: "Prepared request needs approval routing",
    domain: "procurement",
    priority: "normal",
    createdAt: "2026-05-12T06:00:00.000Z",
    evidenceRefs: ["approval:request:redacted"],
    scope: { kind: "role_domain", allowedRoles: ["director", "control", "buyer", "foreman"] },
    recommendedToolName: "submit_for_approval",
  },
  {
    id: "warehouse-low-1",
    type: "warehouse_low_stock",
    title: "Warehouse low stock",
    summary: "Material is below threshold",
    domain: "warehouse",
    priority: "high",
    createdAt: "2026-05-12T05:00:00.000Z",
    evidenceRefs: ["warehouse:low:redacted"],
    scope: { kind: "role_domain", allowedRoles: ["director", "control", "warehouse"] },
    recommendedToolName: "get_warehouse_status",
  },
  {
    id: "report-ready-1",
    type: "report_ready",
    title: "Report draft ready",
    summary: "Project report draft needs review",
    domain: "reports",
    priority: "normal",
    createdAt: "2026-05-12T04:00:00.000Z",
    evidenceRefs: ["report:ready:redacted"],
    scope: { kind: "role_domain", allowedRoles: ["director", "control", "foreman"] },
    recommendedToolName: "draft_report",
  },
  {
    id: "contractor-own-doc-1",
    type: "missing_document",
    title: "Own contractor document",
    summary: "Own act document is missing",
    domain: "subcontracts",
    priority: "normal",
    createdAt: "2026-05-12T03:00:00.000Z",
    evidenceRefs: ["contractor:own:redacted"],
    scope: { kind: "own_record", ownerUserIdHash: "contractor-user" },
    recommendedToolName: "draft_act",
  },
  {
    id: "contractor-other-doc-1",
    type: "missing_document",
    title: "Other contractor document",
    summary: "Other contractor document must not leak",
    domain: "subcontracts",
    priority: "normal",
    createdAt: "2026-05-12T02:00:00.000Z",
    evidenceRefs: ["contractor:other:redacted"],
    scope: { kind: "own_record", ownerUserIdHash: "other-contractor-user" },
    recommendedToolName: "draft_act",
  },
  {
    id: "no-evidence-1",
    type: "recommended_next_action",
    title: "No evidence",
    summary: "This must not become an actionable card",
    domain: "reports",
    priority: "low",
    createdAt: "2026-05-12T01:00:00.000Z",
    evidenceRefs: [],
    scope: { kind: "role_domain", allowedRoles: ["director", "control", "foreman"] },
    recommendedToolName: "draft_report",
  },
];
