import type { DirectorCompanyContext } from "../../src/lib/ai/directorCompany";

export function buildDirectorRealCompanyFixture(): DirectorCompanyContext {
  return {
    screenId: "director.dashboard",
    role: "director",
    period: {
      from: "2026-05-19",
      to: "2026-05-19",
      labelRu: "19 мая 2026",
    },
    forecastProviderConnected: true,
    securitySummaryProviderConnected: true,
    sources: [
      { id: "src:approval:APR-55", type: "approval", labelRu: "Approval APR-55 pending director review", date: "2026-05-19" },
      { id: "src:invoice:INV-1042", type: "invoice", labelRu: "Invoice INV-1042 125000 KGS", date: "2026-05-19" },
      { id: "src:payment:PAY-1042", type: "payment", labelRu: "Payment package PAY-1042", date: "2026-05-19" },
      { id: "src:request:MR-1042", type: "procurement_request", labelRu: "Request MR-1042 GKL 12.5 mm", date: "2026-05-19" },
      { id: "src:supplier:SO-221", type: "supplier_offer", labelRu: "Supplier offer SO-221 delivery needs confirmation", date: "2026-05-19" },
      { id: "src:market:MK-221", type: "marketplace_offer", labelRu: "Marketplace offer MK-221", date: "2026-05-19" },
      { id: "src:stock:STK-221", type: "warehouse_stock", labelRu: "Stock STK-221 GKL deficit", date: "2026-05-19" },
      { id: "src:incoming:INC-221", type: "warehouse_incoming", labelRu: "Incoming INC-221 not confirmed", date: "2026-05-19" },
      { id: "src:work:WRK-1042", type: "work", labelRu: "Work WRK-1042 partitions", date: "2026-05-19" },
      { id: "src:object:OBJ-1", type: "object", labelRu: "Object House 1 floor 2" },
      { id: "src:contractor:CTR-7", type: "contractor", labelRu: "Contractor CTR-7 missing photos" },
      { id: "src:document:DOC-WB", type: "document", labelRu: "Waybill missing placeholder source", date: "2026-05-19" },
      { id: "src:report:RPT-19", type: "report", labelRu: "Daily report RPT-19 needs evidence", date: "2026-05-19" },
      { id: "src:cashflow:CF-7", type: "cashflow", labelRu: "Cashflow forecast source week 21", date: "2026-05-19" },
      { id: "src:office:OFF-3", type: "office_task", labelRu: "Office package OFF-3 overdue", date: "2026-05-19" },
      { id: "src:security:SAFE-1", type: "security_summary", labelRu: "Safe security summary SAFE-1", date: "2026-05-19" },
    ],
    unsafeTechnicalSources: [
      { id: "unsafe:service-role", type: "service_role", labelRu: "service_role secret must never be visible" },
      { id: "unsafe:provider-payload", type: "provider_payload", labelRu: "raw provider payload must never be visible" },
    ],
    approvals: [
      {
        id: "APR-55",
        titleRu: "Согласовать платёж INV-1042",
        status: "pending",
        approvalId: "APR-55",
        ownerRole: "director",
        riskLevel: "high",
        dueAt: "2026-05-19",
        linkedObjectId: "OBJ-1",
        linkedWorkId: "WRK-1042",
        linkedRequestId: "MR-1042",
        linkedInvoiceId: "INV-1042",
        missingData: ["нет накладной", "нет подтверждённого прихода склада"],
        sourceRefs: ["src:approval:APR-55", "src:invoice:INV-1042"],
      },
    ],
    works: [
      {
        id: "WRK-1042",
        objectId: "OBJ-1",
        objectNameRu: "Дом 1, 2 этаж",
        workNameRu: "Монтаж перегородок",
        status: "blocked",
        contractorNameRu: "Бригада Перегородки",
        materialNameRu: "ГКЛ 12.5 мм",
        missingPhotos: true,
        missingSignature: true,
        missingAct: true,
        blockerRu: "Работа не закрывается из-за дефицита ГКЛ и missing фото после выполнения.",
        sourceRefs: ["src:work:WRK-1042", "src:object:OBJ-1", "src:contractor:CTR-7"],
      },
    ],
    procurementRequests: [
      {
        id: "MR-1042",
        objectId: "OBJ-1",
        objectNameRu: "Дом 1, 2 этаж",
        workId: "WRK-1042",
        workNameRu: "Монтаж перегородок",
        itemRu: "ГКЛ 12.5 мм",
        supplierNameRu: "ОсОО СтройМаркет",
        status: "delivery_risk",
        deliveryDueAt: "2026-05-22",
        missingData: ["срок доставки не подтверждён"],
        sourceRefs: ["src:request:MR-1042", "src:supplier:SO-221", "src:market:MK-221"],
      },
    ],
    warehouse: [
      {
        id: "STK-221",
        materialNameRu: "ГКЛ 12.5 мм",
        objectId: "OBJ-1",
        objectNameRu: "Дом 1, 2 этаж",
        workId: "WRK-1042",
        workNameRu: "Монтаж перегородок",
        requestedQty: 42,
        availableQty: 8,
        deficitQty: 34,
        unit: "лист",
        incomingConfirmed: false,
        sourceRefs: ["src:stock:STK-221", "src:incoming:INC-221", "src:request:MR-1042"],
      },
    ],
    finance: [
      {
        id: "FIN-1042",
        invoiceId: "INV-1042",
        paymentId: "PAY-1042",
        supplierNameRu: "ОсОО СтройМаркет",
        amount: 125000,
        currency: "KGS",
        status: "blocked",
        riskLevel: "high",
        missingDocuments: ["накладная", "подтверждение прихода склада", "approval директора"],
        linkedRequestId: "MR-1042",
        linkedWorkId: "WRK-1042",
        linkedObjectId: "OBJ-1",
        sourceRefs: ["src:invoice:INV-1042", "src:payment:PAY-1042", "src:approval:APR-55"],
      },
    ],
    documents: [
      {
        id: "DOC-WB",
        titleRu: "Накладная по INV-1042",
        documentType: "waybill",
        status: "missing",
        linkedObjectId: "OBJ-1",
        linkedWorkId: "WRK-1042",
        sourceRefs: ["src:document:DOC-WB"],
      },
    ],
    reports: [
      {
        id: "RPT-19",
        titleRu: "Ежедневный отчёт 19.05",
        periodRu: "19 мая 2026",
        status: "needs_evidence",
        missingData: ["фото после выполнения WRK-1042"],
        sourceRefs: ["src:report:RPT-19"],
      },
    ],
    officeTasks: [
      {
        id: "OFF-3",
        titleRu: "Собрать payment package по INV-1042",
        ownerRole: "office",
        status: "overdue",
        dueAt: "2026-05-19",
        overdueDays: 1,
        sourceRefs: ["src:office:OFF-3"],
      },
    ],
    cashflowForecasts: [
      {
        id: "CF-7",
        periodRu: "неделя 20-26 мая 2026",
        amount: -125000,
        currency: "KGS",
        assumptionRu: "если INV-1042 будет согласован после подтверждения склада",
        sourceRefs: ["src:cashflow:CF-7", "src:invoice:INV-1042"],
      },
    ],
    securitySummaries: [
      {
        id: "SAFE-1",
        titleRu: "Safe security summary",
        riskLevel: "low",
        forbiddenAttemptsCount: 0,
        summaryRu: "Запрещённых direct approve/payment попыток не найдено.",
        sourceRefs: ["src:security:SAFE-1"],
      },
    ],
  };
}
