import type {
  ConstructionKnowledgeSource,
  ConstructionCountryProfile,
} from "../../src/lib/ai/constructionKnowledgeCore";
import type { ForemanWorkdayContext } from "../../src/lib/ai/foremanIntelligence";

const sources: ConstructionKnowledgeSource[] = [
  {
    id: "src:object:dom1",
    type: "object",
    labelRu: "Объект: Дом 1",
    linkedObjectId: "OBJ-1",
    confidence: "high",
  },
  {
    id: "src:zone:dom1:f2",
    type: "zone",
    labelRu: "Зона: Дом 1, 2 этаж",
    linkedObjectId: "OBJ-1",
    confidence: "high",
  },
  {
    id: "src:work:1042",
    type: "work",
    labelRu: "Работа WRK-1042: монтаж перегородок",
    linkedObjectId: "OBJ-1",
    linkedWorkId: "WRK-1042",
    confidence: "high",
  },
  {
    id: "src:work:1051",
    type: "work",
    labelRu: "Работа WRK-1051: гидроизоляция",
    linkedObjectId: "OBJ-2",
    linkedWorkId: "WRK-1051",
    confidence: "high",
  },
  {
    id: "src:photo:219",
    type: "photo",
    labelRu: "Фото PH-219 до работ",
    linkedObjectId: "OBJ-1",
    linkedWorkId: "WRK-1042",
    confidence: "high",
  },
  {
    id: "src:report:daily",
    type: "report",
    labelRu: "Ежедневный отчёт прораба",
    documentId: "DOC-DAILY",
    fileName: "daily_foreman.pdf",
    page: 1,
    confidence: "high",
  },
  {
    id: "src:act:hidden-missing",
    type: "act",
    labelRu: "Акт скрытых работ не найден по санузлу",
    linkedWorkId: "WRK-1051",
    confidence: "medium",
  },
  {
    id: "src:estimate:77",
    type: "estimate_pdf",
    labelRu: "Смета объекта",
    documentId: "DOC-EST",
    fileName: "estimate_dom1.pdf",
    page: 12,
    linkedWorkId: "WRK-1042",
    linkedEstimateLineId: "EST-77",
    confidence: "high",
  },
  {
    id: "src:project:ar14",
    type: "architecture_pdf",
    labelRu: "Проект АР.pdf",
    documentId: "DOC-AR",
    fileName: "project_ar.pdf",
    page: 14,
    sectionTitle: "Перегородки",
    linkedObjectId: "OBJ-1",
    linkedWorkId: "WRK-1042",
    confidence: "high",
  },
  {
    id: "src:norm:closeout",
    type: "normative_pdf",
    labelRu: "Требования к закрытию работ.pdf",
    documentId: "DOC-NORM",
    fileName: "closeout_rules.pdf",
    page: 6,
    countryCode: "KG",
    confidence: "high",
  },
  {
    id: "src:country:kg",
    type: "country_profile",
    labelRu: "Country profile KG",
    countryCode: "KG",
    confidence: "high",
  },
  {
    id: "src:standard:company",
    type: "company_standard",
    labelRu: "Стандарт компании: закрытие работ",
    documentId: "DOC-STANDARD",
    fileName: "company_standard.pdf",
    confidence: "high",
  },
  {
    id: "src:material:gkl",
    type: "material",
    labelRu: "ГКЛ 12.5 мм",
    linkedWorkId: "WRK-1042",
    linkedMaterialId: "MAT-GKL",
    confidence: "high",
  },
  {
    id: "src:stock:gkl",
    type: "warehouse_stock",
    labelRu: "ГКЛ 12.5 мм: на складе 18 листов",
    linkedWorkId: "WRK-1042",
    linkedMaterialId: "MAT-GKL",
    confidence: "high",
  },
  {
    id: "src:req:gkl",
    type: "procurement_request",
    labelRu: "Заявка MR-1042: дефицит 24 листа",
    linkedWorkId: "WRK-1042",
    linkedMaterialId: "MAT-GKL",
    confidence: "high",
  },
  {
    id: "src:approval:act",
    type: "approval",
    labelRu: "Маршрут согласования акта: ожидает ответственного",
    linkedWorkId: "WRK-1042",
    confidence: "high",
  },
  {
    id: "src:chat:contractor",
    type: "chat_message",
    labelRu: "Сообщение подрядчика: фото после работ будет вечером",
    linkedWorkId: "WRK-1042",
    linkedContractorId: "SUB-1",
    confidence: "medium",
  },
  {
    id: "src:payment:secret",
    type: "payment",
    labelRu: "Полный cashflow компании: скрыто для прораба",
    linkedWorkId: "WRK-1042",
    confidence: "high",
  },
];

const countryProfile: ConstructionCountryProfile = {
  countryCode: "KG",
  countryNameRu: "Кыргызстан",
  currency: "KGS",
  unitSystem: "metric",
  sourceRef: "src:country:kg",
};

export function buildForemanRealWorkdayFixture(
  overrides: Partial<ForemanWorkdayContext> = {},
): ForemanWorkdayContext {
  return {
    screenId: "foreman.main",
    role: "foreman",
    currentDate: "2026-05-19",
    periodRu: "19 мая 2026",
    selectedWorkId: undefined,
    countryProfile,
    sources,
    works: [
      {
        id: "WRK-1042",
        nameRu: "Монтаж перегородок",
        date: "2026-05-19",
        objectId: "OBJ-1",
        objectNameRu: "Дом 1",
        zoneId: "ZONE-2F",
        zoneNameRu: "2 этаж",
        contractorId: "SUB-1",
        contractorNameRu: "Бригада ГКЛ",
        plannedQty: 42,
        actualQty: 38,
        unit: "м2",
        status: "ready_for_act",
        estimateLineId: "EST-77",
        materialIds: ["MAT-GKL"],
        blockers: [
          { kind: "photo_missing", textRu: "нет фото после выполнения" },
          { kind: "signature_missing", textRu: "нет подписи ответственного" },
          { kind: "material_missing", textRu: "дефицит ГКЛ 12.5 мм: 24 листа" },
        ],
        sourceRefs: [
          "src:work:1042",
          "src:object:dom1",
          "src:zone:dom1:f2",
          "src:photo:219",
          "src:estimate:77",
          "src:project:ar14",
          "src:material:gkl",
          "src:stock:gkl",
          "src:req:gkl",
          "src:approval:act",
          "src:chat:contractor",
        ],
      },
      {
        id: "WRK-1051",
        nameRu: "Гидроизоляция санузла",
        date: "2026-05-19",
        objectId: "OBJ-2",
        objectNameRu: "Дом 2, санузел",
        contractorId: "SUB-2",
        contractorNameRu: "Бригада мокрых зон",
        plannedQty: 20,
        actualQty: 12,
        unit: "м2",
        status: "partially_done",
        blockers: [
          { kind: "act_missing", textRu: "нет акта скрытых работ" },
          { kind: "document_missing", textRu: "не привязан документ основания" },
          { kind: "remark_open", textRu: "открыто замечание по примыканию" },
        ],
        sourceRefs: ["src:work:1051", "src:act:hidden-missing", "src:report:daily"],
      },
    ],
    ...overrides,
  };
}

export function buildForemanNoPdfFixture(): ForemanWorkdayContext {
  return buildForemanRealWorkdayFixture({
    sources: sources.filter((source) =>
      !["project_pdf", "architecture_pdf", "engineering_pdf", "estimate_pdf", "boq", "normative_pdf", "company_standard", "country_profile"].includes(source.type),
    ),
    countryProfile: null,
  });
}
