import type { OfficeDocumentControlContext } from "../../src/lib/ai/officeDocumentControl";

export function buildOfficeDocumentControlFixture(): OfficeDocumentControlContext {
  return {
    screenId: "office.hub",
    role: "office",
    selectedDocumentId: "DOC-17",
    period: {
      from: "2026-05-20",
      to: "2026-05-20",
      labelRu: "2026-05-20",
    },
    sources: [
      { id: "src:office:TASK-17", type: "office_task", labelRu: "Office task TASK-17 overdue", date: "2026-05-20" },
      { id: "src:doc:DOC-17", type: "document", labelRu: "Unlinked invoice PDF DOC-17", date: "2026-05-20", page: 1 },
      { id: "src:pdf:DOC-17:1", type: "pdf_chunk", labelRu: "PDF chunk DOC-17 page 1", date: "2026-05-20", page: 1 },
      { id: "src:package:PKG-9", type: "approval_package", labelRu: "Approval package PKG-9 incomplete", date: "2026-05-20" },
      { id: "src:approval:APR-9", type: "approval", labelRu: "Approval APR-9 waiting documents", date: "2026-05-20" },
      { id: "src:invoice:INV-900", type: "invoice", labelRu: "Invoice INV-900", date: "2026-05-20" },
      { id: "src:payment:PAY-900", type: "payment", labelRu: "Payment PAY-900 blocked", date: "2026-05-20" },
      { id: "src:request:MR-900", type: "procurement_request", labelRu: "Procurement request MR-900 waits waybill", date: "2026-05-20" },
      { id: "src:warehouse:WH-900", type: "warehouse_issue", labelRu: "Warehouse receipt WH-900 missing", date: "2026-05-20" },
      { id: "src:work:WRK-900", type: "work", labelRu: "Work WRK-900 closeout waits act", date: "2026-05-20" },
      { id: "src:act:ACT-900", type: "act", labelRu: "Act ACT-900 unsigned", date: "2026-05-20" },
      { id: "src:deadline:DL-9", type: "deadline", labelRu: "Deadline DL-9 overdue", date: "2026-05-20" },
      { id: "src:reminder:REM-9", type: "reminder", labelRu: "Reminder draft REM-9", date: "2026-05-20" },
      { id: "src:security:SAFE-OFFICE", type: "safe_security_summary", labelRu: "Safe security summary only", date: "2026-05-20" },
    ],
    unsafeTechnicalSources: [
      { id: "unsafe:runtime", type: "raw_runtime", labelRu: "raw runtime should stay hidden" },
      { id: "unsafe:security", type: "raw_security_event", labelRu: "raw security event should stay hidden" },
      { id: "unsafe:service-role", type: "service_role", labelRu: "service_role_secret" },
      { id: "unsafe:provider", type: "provider_payload", labelRu: "raw provider payload" },
      { id: "unsafe:env", type: "env_secret", labelRu: "OFFICE_SECRET_TOKEN" },
    ],
    tasks: [
      {
        id: "TASK-17",
        titleRu: "Collect payment package for INV-900",
        status: "overdue",
        ownerRole: "office",
        nextOwnerRole: "accountant",
        dueAt: "2026-05-20",
        overdueDays: 1,
        whyStuckRu: "Payment package is overdue because invoice PDF is unlinked and waybill is missing.",
        missingData: ["waybill", "linked PDF evidence"],
        sourceRefs: ["src:office:TASK-17", "src:invoice:INV-900"],
      },
    ],
    documentsQueue: [
      {
        id: "DOC-17",
        titleRu: "Invoice PDF for INV-900",
        documentType: "pdf",
        status: "unlinked",
        ownerRole: "office",
        linkedPaymentId: "PAY-900",
        linkedApprovalPackageId: "PKG-9",
        blocks: ["payment", "approval", "director_package"],
        missingData: ["human link review", "waybill number"],
        sourceRefs: ["src:doc:DOC-17", "src:pdf:DOC-17:1", "src:invoice:INV-900"],
      },
      {
        id: "DOC-NOSOURCE",
        titleRu: "Source-less document must not become green stuck work",
        documentType: "pdf",
        status: "blocked",
        ownerRole: "office",
        blocks: ["approval"],
        missingData: ["source"],
        sourceRefs: [],
      },
      {
        id: "ACT-900",
        titleRu: "Unsigned act for WRK-900",
        documentType: "act",
        status: "needs_signature",
        ownerRole: "foreman",
        linkedWorkId: "WRK-900",
        blocks: ["work_closeout"],
        missingData: ["foreman signature", "contractor evidence"],
        sourceRefs: ["src:act:ACT-900", "src:work:WRK-900"],
      },
    ],
    approvalPackages: [
      {
        id: "PKG-9",
        titleRu: "Director approval package for PAY-900",
        status: "waiting_documents",
        ownerRole: "office",
        approvalId: "APR-9",
        linkedPaymentId: "PAY-900",
        linkedWorkId: "WRK-900",
        relatedDocumentIds: ["DOC-17", "ACT-900"],
        missingDocuments: ["waybill", "warehouse receipt"],
        missingData: ["document link not reviewed"],
        sourceRefs: ["src:package:PKG-9", "src:approval:APR-9", "src:payment:PAY-900", "src:request:MR-900", "src:warehouse:WH-900"],
      },
    ],
    reminders: [
      {
        id: "REM-9",
        targetRole: "accountant",
        targetLabelRu: "accountant for PAY-900",
        status: "draft",
        reasonRu: "Payment remains blocked until waybill and link review are attached to package PKG-9.",
        blocks: ["payment", "approval"],
        sourceRefs: ["src:reminder:REM-9", "src:package:PKG-9"],
        finalSent: false,
      },
    ],
    deadlines: [
      {
        id: "DL-9",
        titleRu: "Package PKG-9 deadline",
        dueAt: "2026-05-20",
        status: "overdue",
        ownerRole: "office",
        linkedItemType: "approval_package",
        linkedItemId: "PKG-9",
        missingData: ["deadline extension rationale"],
        sourceRefs: ["src:deadline:DL-9", "src:package:PKG-9"],
      },
    ],
  };
}
