import type { ConstructionKnowledgeSource } from "../../src/lib/ai/constructionKnowledgeCore";
import type { WarehouseStockContext } from "../../src/lib/ai/warehouseStock";

function sources(): ConstructionKnowledgeSource[] {
  return [
    {
      id: "src:stock:MAT-1",
      type: "warehouse_stock",
      labelRu: "Stock MAT-1 source",
      linkedMaterialId: "MAT-1",
      linkedObjectId: "OBJ-12",
      linkedWorkId: "WRK-300",
      confidence: "high",
    },
    {
      id: "src:material:MAT-1",
      type: "material",
      labelRu: "Material MAT-1 concrete M300",
      linkedMaterialId: "MAT-1",
      confidence: "high",
    },
    {
      id: "src:spec:DOC-17",
      type: "specification",
      labelRu: "Specification DOC-17 page 4",
      documentId: "DOC-17",
      fileName: "spec_concrete.pdf",
      page: 4,
      linkedMaterialId: "MAT-1",
      confidence: "high",
    },
    {
      id: "src:estimate:EST-77",
      type: "estimate_pdf",
      labelRu: "Estimate EST-77: concrete volume",
      documentId: "EST-77",
      fileName: "estimate_block_a.pdf",
      page: 12,
      linkedMaterialId: "MAT-1",
      linkedObjectId: "OBJ-12",
      linkedWorkId: "WRK-300",
      confidence: "high",
    },
    {
      id: "src:supplier-offer:SO-44",
      type: "supplier_offer",
      labelRu: "Supplier offer SO-44 Beton Plus",
      linkedMaterialId: "MAT-1",
      confidence: "high",
    },
    {
      id: "src:request:MR-300",
      type: "procurement_request",
      labelRu: "Request MR-300",
      linkedMaterialId: "MAT-1",
      linkedObjectId: "OBJ-12",
      linkedWorkId: "WRK-300",
      confidence: "high",
    },
    {
      id: "src:work:WRK-300",
      type: "work",
      labelRu: "Work WRK-300",
      linkedObjectId: "OBJ-12",
      linkedWorkId: "WRK-300",
      confidence: "high",
    },
    {
      id: "src:object:OBJ-12",
      type: "object",
      labelRu: "Object OBJ-12",
      linkedObjectId: "OBJ-12",
      confidence: "high",
    },
    {
      id: "src:approval:WH-9",
      type: "approval",
      labelRu: "Approval WH-9",
      confidence: "high",
    },
    {
      id: "src:payment:hidden",
      type: "payment",
      labelRu: "full cashflow and runtime secret must be hidden",
      confidence: "high",
    },
  ];
}

export function buildWarehouseRealStockFixture(): WarehouseStockContext {
  return {
    screenId: "warehouse.main",
    role: "warehouse",
    selectedMaterialId: "MAT-1",
    selectedObjectId: "OBJ-12",
    selectedIssueId: "ISS-30",
    selectedIncomingId: "INC-55",
    unitConversionConfigured: true,
    packageConversionConfigured: true,
    quantityNormalizationConfigured: true,
    documentsProviderConnected: true,
    stockItems: [
      {
        id: "STK-1",
        materialId: "MAT-1",
        materialNameRu: "Concrete M300",
        specificationText: "M300, m3",
        specification: {
          mark: "M300",
          specificationText: "Concrete M300, delivery by mixer",
          sourceRefs: ["src:spec:DOC-17"],
        },
        inStockQty: 18,
        availableQty: 8,
        reservedQty: 10,
        incomingQty: 12,
        unit: "m3",
        warehouseNameRu: "Main warehouse",
        location: {
          warehouseId: "WH-1",
          warehouseNameRu: "Main warehouse",
          zone: "A",
          shelf: "bulk",
          sourceRefs: ["src:stock:MAT-1"],
        },
        objectId: "OBJ-12",
        objectNameRu: "Block A",
        workId: "WRK-300",
        workNameRu: "Slab concreting",
        requestId: "MR-300",
        requestLineId: "MRL-300",
        estimateLineId: "EST-77",
        projectSpecificationId: "DOC-17",
        sourceRefs: ["src:stock:MAT-1"],
      },
    ],
    incoming: [
      {
        id: "INC-55",
        materialId: "MAT-1",
        materialNameRu: "Concrete M300",
        expectedQty: 12,
        actualQty: 10,
        waybillQty: 12,
        quantity: 12,
        unit: "m3",
        supplierId: "SUP-7",
        supplierNameRu: "Beton Plus",
        requestId: "MR-300",
        requestLineId: "MRL-300",
        waybillId: "WB-55",
        invoiceId: "INV-55",
        status: "needs_documents",
        documentRefs: ["WB-55"],
        sourceRefs: ["src:request:MR-300", "src:supplier-offer:SO-44"],
      },
    ],
    issues: [
      {
        id: "ISS-30",
        materialId: "MAT-1",
        materialNameRu: "Concrete M300",
        requestedQty: 15,
        issuedQty: 0,
        unit: "m3",
        objectId: "OBJ-12",
        objectNameRu: "Block A",
        workId: "WRK-300",
        workNameRu: "Slab concreting",
        requestId: "MR-300",
        status: "blocked",
        sourceRefs: ["src:request:MR-300", "src:work:WRK-300"],
      },
    ],
    reservations: [
      {
        id: "RSV-17",
        materialId: "MAT-1",
        materialNameRu: "Concrete M300",
        quantity: 10,
        unit: "m3",
        objectId: "OBJ-13",
        objectNameRu: "Block B",
        workId: "WRK-301",
        workNameRu: "Column concreting",
        requestId: "MR-301",
        status: "active",
        sourceRefs: ["src:stock:MAT-1"],
      },
    ],
    transfers: [
      {
        id: "TR-9",
        materialId: "MAT-1",
        materialNameRu: "Concrete M300",
        quantity: 4,
        unit: "m3",
        fromLocation: {
          warehouseId: "WH-1",
          warehouseNameRu: "Main warehouse",
          zone: "A",
          shelf: "bulk",
          sourceRefs: ["src:stock:MAT-1"],
        },
        toLocation: {
          warehouseId: "OBJ-12",
          warehouseNameRu: "Block A site",
          objectId: "OBJ-12",
          objectNameRu: "Block A",
          sourceRefs: ["src:object:OBJ-12"],
        },
        objectId: "OBJ-12",
        objectNameRu: "Block A",
        workId: "WRK-300",
        workNameRu: "Slab concreting",
        approvalId: "WH-9",
        status: "pending_approval",
        sourceRefs: ["src:stock:MAT-1", "src:approval:WH-9"],
      },
    ],
    inventoryCounts: [
      {
        id: "INVCOUNT-1",
        materialId: "MAT-1",
        materialNameRu: "Concrete M300",
        bookQty: 18,
        countedQty: 17,
        unit: "m3",
        location: {
          warehouseId: "WH-1",
          warehouseNameRu: "Main warehouse",
          zone: "A",
          shelf: "bulk",
          sourceRefs: ["src:stock:MAT-1"],
        },
        status: "mismatch",
        sourceRefs: ["src:stock:MAT-1"],
      },
    ],
    locations: [
      {
        warehouseId: "WH-1",
        warehouseNameRu: "Main warehouse",
        zone: "A",
        shelf: "bulk",
        sourceRefs: ["src:stock:MAT-1"],
      },
    ],
    sources: sources(),
  };
}
