export type FireR5OfficialSource = {
  sourceId: string;
  documentCode: string;
  titleRu: string;
  officialPageUrl: string;
  directPdfUrl?: string;
  contentKind: "PDF" | "HTML";
  role: "LAW" | "RULE" | "DESIGN" | "EXECUTION" | "RATES" | "PRICE" | "GOVERNANCE" | "CONFORMITY";
  status: "ACTIVE_PRIMARY_KR" | "ACTIVE_RULE_KR" | "ACTIVE_RATE_SOURCE_KR" | "ACTIVE_PRICE_SOURCE_KR" | "ACTIVE_PRODUCT_REGULATION_EAEU" | "CURRENT" | "DRAFT_NOT_ACTIVE" | "WITHDRAWN";
};

const minstroy = "https://minstroy.gov.kg";

export const FIRE_R5_OFFICIAL_SOURCES: readonly FireR5OfficialSource[] = Object.freeze([
  { sourceId: "law_kr_118_2022", documentCode: "Закон КР №118", titleRu: "О пожарной безопасности", officialPageUrl: "https://cbd.minjust.gov.kg/4-3236/edition/1855/ru", contentKind: "HTML", role: "LAW", status: "ACTIVE_PRIMARY_KR" },
  { sourceId: "fire_rules_kr_2025", documentCode: "ПКМ КР №251/2025", titleRu: "Правила пожарной безопасности в Кыргызской Республике", officialPageUrl: "https://cbd.minjust.gov.kg/51-655/edition/31951/ru", contentKind: "HTML", role: "RULE", status: "ACTIVE_RULE_KR" },
  { sourceId: "fire_rules_kr_2018_withdrawn", documentCode: "ППКР №381/2018", titleRu: "Прежние Правила пожарной безопасности", officialPageUrl: "https://cbd.minjust.gov.kg/7-2428/edition/904785/ru", contentKind: "HTML", role: "RULE", status: "WITHDRAWN" },
  { sourceId: "law_kr_technical_regulation", documentCode: "Закон КР №67", titleRu: "О техническом регулировании в Кыргызской Республике", officialPageUrl: "https://cbd.minjust.gov.kg/4-1390/edition/1185286/ru", contentKind: "HTML", role: "CONFORMITY", status: "ACTIVE_PRIMARY_KR" },
  { sourceId: "sn_kr_fire_buildings", documentCode: "СН КР Пожарная безопасность зданий и сооружений", titleRu: "Пожарная безопасность зданий и сооружений", officialPageUrl: `${minstroy}/ru/kyzmat/245/show`, directPdfUrl: `${minstroy}/ru/state_program/download-pdf/stroitelnyenormykyrgyzskojrespublikisistemanormativnyhdokumentovvstroitelstvepozarnaabezopasnostzdanijisooruzenij____1-670685a003fe39949.02777997.pdf`, contentKind: "PDF", role: "DESIGN", status: "CURRENT" },
  { sourceId: "sp_kr_21_101_2024_order", documentCode: "Приказ № СП КР 21-101:2024", titleRu: "Утверждение СП КР 21-101:2024", officialPageUrl: `${minstroy}/ru/document/100/show`, directPdfUrl: `${minstroy}/ru/state_program/download-pdf/spkrpozarnaaavtomatika-682672212f86baa01.62395601.pdf`, contentKind: "PDF", role: "GOVERNANCE", status: "CURRENT" },
  { sourceId: "sp_kr_21_101_2024", documentCode: "СП КР 21-101:2024", titleRu: "Пожарная автоматика зданий и сооружений", officialPageUrl: `${minstroy}/ru/kyzmat/217/show`, directPdfUrl: `${minstroy}/ru/state_program/download-pdf/spkr211012024pozarnaaavtomatika-764685911c2138a42.37104393.pdf`, contentKind: "PDF", role: "DESIGN", status: "CURRENT" },
  { sourceId: "sp_kr_41_101_2025", documentCode: "СП КР 41-101:2025 / приказ №436", titleRu: "Струйная вентиляция и дымоудаление закрытых автостоянок", officialPageUrl: `${minstroy}/ru/document/186/show`, directPdfUrl: `${minstroy}/ru/state_program/download-pdf/obedpdffajlyspstrujnyj_compressed-63868c3ccdb6748b7.20700551.pdf`, contentKind: "PDF", role: "DESIGN", status: "CURRENT" },
  { sourceId: "sp_kr_41_101_2025_draft_page", documentCode: "Проект СП КР 41-101:2025", titleRu: "Страница общественного обсуждения струйной вентиляции", officialPageUrl: `${minstroy}/ru/document/175/show`, directPdfUrl: `${minstroy}/ru/state_program/download-pdf/spstrujnaaventilacia-9096870d007970bb9.19416045.pdf`, contentKind: "PDF", role: "GOVERNANCE", status: "DRAFT_NOT_ACTIVE" },
  { sourceId: "project_prices_section_60", documentCode: "СБЦ Раздел 60", titleRu: "Автоматические установки пожаротушения, пожарной и охранной сигнализации", officialPageUrl: `${minstroy}/ru/kyzmat/347/show`, directPdfUrl: `${minstroy}/ru/state_program/download-pdf/razdel60_avtomaticeskieustanovki_pozarotuseniapozarnojiohrannojsignalizacii_compressed-39269004a375834a2.14336674.pdf`, contentKind: "PDF", role: "RATES", status: "ACTIVE_RATE_SOURCE_KR" },
  { sourceId: "price_book_28_fire_security", documentCode: "ССЦ Книга 28", titleRu: "Материалы и оборудование пожарное и охранное", officialPageUrl: `${minstroy}/ru/kyzmat/280/show`, directPdfUrl: `${minstroy}/ru/state_program/download-pdf/kniga28-29868faf1ed588bd4.07902223.pdf`, contentKind: "PDF", role: "PRICE", status: "ACTIVE_PRICE_SOURCE_KR" },
  { sourceId: "krerm_11_2015", documentCode: "КРЕРм №11", titleRu: "Приборы, средства автоматизации и вычислительной техники", officialPageUrl: `${minstroy}/ru/kyzmat/369/show`, directPdfUrl: `${minstroy}/ru/state_program/download-pdf/no11priborysredstvaavtomatizaciiivycislitelnojtehniki_compressed-556690081df7c1812.09755021.pdf`, contentKind: "PDF", role: "RATES", status: "ACTIVE_RATE_SOURCE_KR" },
  { sourceId: "krerp_02_2015", documentCode: "КРЕРп №2", titleRu: "Автоматизированные системы управления", officialPageUrl: `${minstroy}/ru/kyzmat/405/show`, directPdfUrl: `${minstroy}/ru/state_program/download-pdf/no2avtomatizirovannyesistemyupravlenia_compressed-326901fbfa43bce5.19499519.pdf`, contentKind: "PDF", role: "RATES", status: "ACTIVE_RATE_SOURCE_KR" },
  { sourceId: "krer_16_2015", documentCode: "КРЕР №16", titleRu: "Трубопроводы внутренние", officialPageUrl: `${minstroy}/ru/kyzmat/432/show`, directPdfUrl: `${minstroy}/ru/state_program/download-pdf/no16truboprovodyvnutrennie_compressed-154690837388a4dd7.26767770.pdf`, contentKind: "PDF", role: "RATES", status: "ACTIVE_RATE_SOURCE_KR" },
  { sourceId: "krer_20_2015", documentCode: "КРЕР №20", titleRu: "Вентиляция и кондиционирование воздуха", officialPageUrl: `${minstroy}/ru/kyzmat/436/show`, directPdfUrl: `${minstroy}/ru/state_program/download-pdf/no20ventilaciaikondicionirovanievozduha_compressed-216690839a2451120.15137181.pdf`, contentKind: "PDF", role: "RATES", status: "ACTIVE_RATE_SOURCE_KR" },
  { sourceId: "krerp_03_2015", documentCode: "КРЕРп №3", titleRu: "Системы вентиляции и кондиционирования воздуха", officialPageUrl: `${minstroy}/ru/kyzmat/406/show`, directPdfUrl: `${minstroy}/ru/state_program/download-pdf/no3sistemyventilaciiikondicionirovania_compressed-5436901fcd8dc0608.95641023.pdf`, contentKind: "PDF", role: "RATES", status: "ACTIVE_RATE_SOURCE_KR" },
  { sourceId: "krerp_09_2015", documentCode: "КРЕРп №9", titleRu: "Сооружения водоснабжения и канализации", officialPageUrl: `${minstroy}/ru/kyzmat/412/show`, directPdfUrl: `${minstroy}/ru/state_program/download-pdf/no9sooruzeniavodosnabzeniaikanalizacii_compressed-505690200c0f0b699.88346888.pdf`, contentKind: "PDF", role: "RATES", status: "ACTIVE_RATE_SOURCE_KR" },
  { sourceId: "eec_tr_eaeu_043_2017_change_2025", documentCode: "ТР ЕАЭС 043/2017 — изменения перечней 2025", titleRu: "Изменения перечней стандартов к техрегламенту на средства обеспечения пожарной безопасности", officialPageUrl: "https://eec.eaeunion.org/news/vneseny-izmeneniya-v-perechni-standartov-k-tekhreglamentu-na-sredstva-obespecheniya-pozharnoy-bezopa/", contentKind: "HTML", role: "CONFORMITY", status: "ACTIVE_PRODUCT_REGULATION_EAEU" },
]);
