import { Platform, StyleSheet } from 'react-native';

import { UI, TYPO } from '../../screens/foreman/foreman.ui';

export const s = StyleSheet.create({
  header: {
    backgroundColor: UI.bg,
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderColor: UI.border,
    zIndex: 10,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  hTitle: {
    ...TYPO.titleLg,
    color: UI.text,
  },
  hDraftPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(34,197,94,0.1)',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(34,197,94,0.2)',
    marginLeft: 'auto',
    marginRight: 12,
  },
  badge: {
    backgroundColor: UI.accent,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 6,
    paddingHorizontal: 4,
  },
  badgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '900',
  },
  closeBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: UI.btnNeutral,
  },
  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#161B22',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: UI.border,
    height: 50,
  },
  searchInput: {
    flex: 1,
    paddingHorizontal: 10,
    color: UI.text,
    fontSize: 16,
    fontWeight: '700',
  },
  clearSearch: {
    padding: 10,
  },
  loaderBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    gap: 8,
  },
  loaderText: {
    color: UI.sub,
    fontSize: 13,
    fontWeight: '700',
  },
  toastContainer: {
    position: 'absolute',
    top: 140,
    left: 16,
    right: 16,
    zIndex: 100,
    alignItems: 'center',
  },
  toast: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: UI.accent,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  toastText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 14,
  },
  listContent: {
    padding: 16,
  },
  card: {
    backgroundColor: UI.cardBg,
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: UI.border,
  },
  cardHeader: {
    marginBottom: 12,
  },
  cardTitle: {
    ...TYPO.bodyStrong,
    color: UI.text,
    fontSize: 16,
    lineHeight: 22,
  },
  highlight: {
    color: UI.accent,
    backgroundColor: 'rgba(34,197,94,0.15)',
  },
  cardCode: {
    color: UI.sub,
    fontSize: 11,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    marginTop: 4,
  },
  cardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  tag: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  tagText: {
    color: UI.text,
    fontSize: 11,
    fontWeight: '800',
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  qtyInput: {
    width: 70,
    height: 46,
    backgroundColor: UI.bg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: UI.border,
    color: UI.text,
    textAlign: 'center',
    fontWeight: '900',
    fontSize: 15,
  },
  empty: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 60,
  },
  emptyText: {
    color: UI.sub,
    textAlign: 'center',
    marginTop: 16,
    lineHeight: 20,
    ...TYPO.bodyStrong,
  },
});
