import type { AiUserRole } from "../policy/aiRolePolicy";
import type {
  AiScreenActionDefinition,
  AiScreenActionEvidenceSource,
  AiScreenActionIntent,
  AiScreenActionMode,
  AiScreenActionRegistryEntry,
  AiScreenActionRiskLevel,
} from "./aiScreenActionTypes";
import type { AiToolName } from "../tools/aiToolTypes";

const CONTROL_ROLES: readonly AiUserRole[] = ["director", "control"];
const OPERATIONS_ROLES: readonly AiUserRole[] = [
  "director",
  "control",
  "foreman",
  "buyer",
  "accountant",
  "warehouse",
  "contractor",
  "office",
  "admin",
];
const PROCUREMENT_ROLES: readonly AiUserRole[] = ["director", "control", "buyer"];
const MARKET_ROLES: readonly AiUserRole[] = ["director", "control", "buyer", "foreman"];
const FINANCE_ROLES: readonly AiUserRole[] = ["director", "control", "accountant"];
const FOREMAN_ROLES: readonly AiUserRole[] = ["director", "control", "foreman"];
const WAREHOUSE_ROLES: readonly AiUserRole[] = ["director", "control", "warehouse"];
const CONTRACTOR_ROLES: readonly AiUserRole[] = ["director", "control", "contractor"];

export const AI_SCREEN_ACTION_REQUIRED_SCREEN_IDS = [
  "director.dashboard",
  "ai.command_center",
  "buyer.main",
  "buyer.requests",
  "market.home",
  "warehouse.main",
  "accountant.main",
  "foreman.main",
  "foreman.ai.quick_modal",
  "contractor.main",
  "reports.modal",
  "documents.main",
  "approval.inbox",
  "procurement.copilot",
  "screen.runtime",
] as const;

function action(params: {
  actionId: string;
  label: string;
  intent: AiScreenActionIntent;
  mode: AiScreenActionMode;
  roleScope: readonly AiUserRole[];
  aiTool?: AiToolName;
  evidenceSources: readonly AiScreenActionEvidenceSource[];
  forbiddenReason?: string;
}): AiScreenActionDefinition {
  const riskLevelByMode: Record<AiScreenActionMode, AiScreenActionRiskLevel> = {
    safe_read: "low",
    draft_only: "medium",
    approval_required: "high",
    forbidden: "forbidden",
  };

  return {
    actionId: params.actionId,
    label: params.label,
    intent: params.intent,
    riskLevel: riskLevelByMode[params.mode],
    aiTool: params.aiTool,
    mode: params.mode,
    roleScope: params.roleScope,
    requiresApproval: params.mode === "approval_required",
    evidenceRequired: true,
    evidenceSources: params.evidenceSources,
    forbiddenReason: params.forbiddenReason,
    source: "ai_screen_button_action_registry_v1",
  };
}

function entry(
  params: Omit<
    AiScreenActionRegistryEntry,
    "directorControlFullAccess" | "nonDirectorScopedAccess" | "source"
  >,
): AiScreenActionRegistryEntry {
  return {
    ...params,
    directorControlFullAccess: true,
    nonDirectorScopedAccess: true,
    source: "ai_screen_button_action_registry_v1",
  };
}

export const AI_SCREEN_ACTION_REGISTRY: readonly AiScreenActionRegistryEntry[] = [
  entry({
    screenId: "director.dashboard",
    domain: "control",
    allowedRoles: CONTROL_ROLES,
    evidenceSources: ["screen_state", "role_policy", "approval_policy"],
    visibleActions: [
      action({
        actionId: "director.dashboard.find_risk",
        label: "Find cross-domain risks",
        intent: "explain_status",
        mode: "safe_read",
        aiTool: "get_action_status",
        roleScope: CONTROL_ROLES,
        evidenceSources: ["screen_state", "ledger_status"],
      }),
      action({
        actionId: "director.dashboard.finance_summary",
        label: "Read finance summary",
        intent: "read_context",
        mode: "safe_read",
        aiTool: "get_finance_summary",
        roleScope: CONTROL_ROLES,
        evidenceSources: ["finance_summary", "role_policy"],
      }),
      action({
        actionId: "director.dashboard.draft_report",
        label: "Prepare executive report draft",
        intent: "draft_report",
        mode: "draft_only",
        aiTool: "draft_report",
        roleScope: CONTROL_ROLES,
        evidenceSources: ["report_summary", "document_metadata"],
      }),
      action({
        actionId: "director.dashboard.submit_decision_pack",
        label: "Submit decision pack for approval",
        intent: "submit_for_approval",
        mode: "approval_required",
        aiTool: "submit_for_approval",
        roleScope: CONTROL_ROLES,
        evidenceSources: ["approval_policy", "document_metadata"],
      }),
      action({
        actionId: "director.dashboard.final_mutation_forbidden",
        label: "Execute final business mutation directly",
        intent: "forbidden",
        mode: "forbidden",
        roleScope: CONTROL_ROLES,
        evidenceSources: ["approval_policy", "role_policy"],
        forbiddenReason: "Final mutation must go through the approved execution gateway.",
      }),
    ],
  }),
  entry({
    screenId: "ai.command_center",
    domain: "control",
    allowedRoles: OPERATIONS_ROLES,
    evidenceSources: ["screen_state", "role_policy", "tool_contract"],
    visibleActions: [
      action({
        actionId: "ai.command_center.explain_task",
        label: "Explain current task",
        intent: "explain_status",
        mode: "safe_read",
        aiTool: "get_action_status",
        roleScope: OPERATIONS_ROLES,
        evidenceSources: ["screen_state", "ledger_status"],
      }),
      action({
        actionId: "ai.command_center.check_action_status",
        label: "Check action status",
        intent: "check_status",
        mode: "safe_read",
        aiTool: "get_action_status",
        roleScope: OPERATIONS_ROLES,
        evidenceSources: ["ledger_status", "tool_contract"],
      }),
      action({
        actionId: "ai.command_center.draft_request",
        label: "Prepare request draft",
        intent: "draft",
        mode: "draft_only",
        aiTool: "draft_request",
        roleScope: OPERATIONS_ROLES,
        evidenceSources: ["screen_state", "procurement_context"],
      }),
      action({
        actionId: "ai.command_center.submit_for_approval",
        label: "Submit draft for approval",
        intent: "submit_for_approval",
        mode: "approval_required",
        aiTool: "submit_for_approval",
        roleScope: OPERATIONS_ROLES,
        evidenceSources: ["approval_policy", "tool_contract"],
      }),
      action({
        actionId: "ai.command_center.execute_without_ledger_forbidden",
        label: "Execute without approved ledger",
        intent: "forbidden",
        mode: "forbidden",
        roleScope: OPERATIONS_ROLES,
        evidenceSources: ["approval_policy", "role_policy"],
        forbiddenReason: "Execution requires persisted approval ledger state.",
      }),
    ],
  }),
  entry({
    screenId: "buyer.main",
    domain: "procurement",
    allowedRoles: PROCUREMENT_ROLES,
    evidenceSources: ["screen_state", "procurement_context", "tool_contract"],
    visibleActions: [
      action({
        actionId: "buyer.main.find_request",
        label: "Find procurement request",
        intent: "find",
        mode: "safe_read",
        aiTool: "search_catalog",
        roleScope: PROCUREMENT_ROLES,
        evidenceSources: ["screen_state", "procurement_context"],
      }),
      action({
        actionId: "buyer.main.compare_suppliers",
        label: "Compare suppliers",
        intent: "compare",
        mode: "safe_read",
        aiTool: "compare_suppliers",
        roleScope: PROCUREMENT_ROLES,
        evidenceSources: ["procurement_context", "tool_contract"],
      }),
      action({
        actionId: "buyer.main.draft_request",
        label: "Prepare procurement draft",
        intent: "draft",
        mode: "draft_only",
        aiTool: "draft_request",
        roleScope: PROCUREMENT_ROLES,
        evidenceSources: ["procurement_context", "document_metadata"],
      }),
      action({
        actionId: "buyer.main.submit_supplier_pack",
        label: "Submit supplier pack for approval",
        intent: "submit_for_approval",
        mode: "approval_required",
        aiTool: "submit_for_approval",
        roleScope: PROCUREMENT_ROLES,
        evidenceSources: ["approval_policy", "procurement_context"],
      }),
      action({
        actionId: "buyer.main.confirm_supplier_forbidden",
        label: "Confirm supplier directly",
        intent: "forbidden",
        mode: "forbidden",
        roleScope: PROCUREMENT_ROLES,
        evidenceSources: ["approval_policy", "procurement_context"],
        forbiddenReason: "AI cannot confirm a supplier or create the order directly.",
      }),
    ],
  }),
  entry({
    screenId: "buyer.requests",
    domain: "procurement",
    allowedRoles: PROCUREMENT_ROLES,
    evidenceSources: ["screen_state", "procurement_context", "approval_policy"],
    visibleActions: [
      action({
        actionId: "buyer.requests.find_request",
        label: "Find request in inbox",
        intent: "find",
        mode: "safe_read",
        aiTool: "search_catalog",
        roleScope: PROCUREMENT_ROLES,
        evidenceSources: ["screen_state", "procurement_context"],
      }),
      action({
        actionId: "buyer.requests.compare_supplier_quotes",
        label: "Compare supplier quotes",
        intent: "compare",
        mode: "safe_read",
        aiTool: "compare_suppliers",
        roleScope: PROCUREMENT_ROLES,
        evidenceSources: ["procurement_context", "tool_contract"],
      }),
      action({
        actionId: "buyer.requests.draft_request",
        label: "Prepare request draft",
        intent: "draft",
        mode: "draft_only",
        aiTool: "draft_request",
        roleScope: PROCUREMENT_ROLES,
        evidenceSources: ["procurement_context", "document_metadata"],
      }),
      action({
        actionId: "buyer.requests.submit_request",
        label: "Send request to approval",
        intent: "submit_for_approval",
        mode: "approval_required",
        aiTool: "submit_for_approval",
        roleScope: PROCUREMENT_ROLES,
        evidenceSources: ["approval_policy", "document_metadata"],
      }),
      action({
        actionId: "buyer.requests.create_order_forbidden",
        label: "Create purchase order directly",
        intent: "forbidden",
        mode: "forbidden",
        roleScope: PROCUREMENT_ROLES,
        evidenceSources: ["approval_policy", "procurement_context"],
        forbiddenReason: "Purchase order creation is outside AI screen-action authority.",
      }),
    ],
  }),
  entry({
    screenId: "market.home",
    domain: "marketplace",
    allowedRoles: MARKET_ROLES,
    evidenceSources: ["screen_state", "tool_contract", "procurement_context"],
    visibleActions: [
      action({
        actionId: "market.home.search_catalog",
        label: "Search catalog",
        intent: "search",
        mode: "safe_read",
        aiTool: "search_catalog",
        roleScope: MARKET_ROLES,
        evidenceSources: ["screen_state", "tool_contract"],
      }),
      action({
        actionId: "market.home.compare_suppliers",
        label: "Compare marketplace suppliers",
        intent: "compare",
        mode: "safe_read",
        aiTool: "compare_suppliers",
        roleScope: MARKET_ROLES,
        evidenceSources: ["procurement_context", "tool_contract"],
      }),
      action({
        actionId: "market.home.draft_request",
        label: "Add item to request draft",
        intent: "draft",
        mode: "draft_only",
        aiTool: "draft_request",
        roleScope: ["director", "control", "buyer"],
        evidenceSources: ["procurement_context", "document_metadata"],
      }),
      action({
        actionId: "market.home.submit_market_draft",
        label: "Submit marketplace draft for approval",
        intent: "submit_for_approval",
        mode: "approval_required",
        aiTool: "submit_for_approval",
        roleScope: ["director", "control", "buyer"],
        evidenceSources: ["approval_policy", "procurement_context"],
      }),
      action({
        actionId: "market.home.external_fetch_forbidden",
        label: "Fetch live external supplier data",
        intent: "forbidden",
        mode: "forbidden",
        roleScope: MARKET_ROLES,
        evidenceSources: ["tool_contract", "approval_policy"],
        forbiddenReason: "Uncontrolled external live fetch is disabled for this wave.",
      }),
    ],
  }),
  entry({
    screenId: "warehouse.main",
    domain: "warehouse",
    allowedRoles: WAREHOUSE_ROLES,
    evidenceSources: ["screen_state", "warehouse_status", "approval_policy"],
    visibleActions: [
      action({
        actionId: "warehouse.main.stock_status",
        label: "Read stock status",
        intent: "read_context",
        mode: "safe_read",
        aiTool: "get_warehouse_status",
        roleScope: WAREHOUSE_ROLES,
        evidenceSources: ["warehouse_status", "screen_state"],
      }),
      action({
        actionId: "warehouse.main.find_material",
        label: "Find warehouse material",
        intent: "find",
        mode: "safe_read",
        aiTool: "get_warehouse_status",
        roleScope: WAREHOUSE_ROLES,
        evidenceSources: ["warehouse_status", "tool_contract"],
      }),
      action({
        actionId: "warehouse.main.draft_restock_request",
        label: "Prepare restock draft",
        intent: "draft",
        mode: "draft_only",
        aiTool: "draft_request",
        roleScope: WAREHOUSE_ROLES,
        evidenceSources: ["warehouse_status", "document_metadata"],
      }),
      action({
        actionId: "warehouse.main.submit_stock_request",
        label: "Submit stock request for approval",
        intent: "submit_for_approval",
        mode: "approval_required",
        aiTool: "submit_for_approval",
        roleScope: WAREHOUSE_ROLES,
        evidenceSources: ["approval_policy", "warehouse_status"],
      }),
      action({
        actionId: "warehouse.main.change_stock_forbidden",
        label: "Change stock balance directly",
        intent: "forbidden",
        mode: "forbidden",
        roleScope: WAREHOUSE_ROLES,
        evidenceSources: ["approval_policy", "warehouse_status"],
        forbiddenReason: "Warehouse mutations are blocked from AI screen actions.",
      }),
    ],
  }),
  entry({
    screenId: "accountant.main",
    domain: "finance",
    allowedRoles: FINANCE_ROLES,
    evidenceSources: ["screen_state", "finance_summary", "approval_policy"],
    visibleActions: [
      action({
        actionId: "accountant.main.finance_summary",
        label: "Read finance summary",
        intent: "read_context",
        mode: "safe_read",
        aiTool: "get_finance_summary",
        roleScope: FINANCE_ROLES,
        evidenceSources: ["finance_summary", "screen_state"],
      }),
      action({
        actionId: "accountant.main.check_action_status",
        label: "Check payment approval status",
        intent: "check_status",
        mode: "safe_read",
        aiTool: "get_action_status",
        roleScope: FINANCE_ROLES,
        evidenceSources: ["ledger_status", "finance_summary"],
      }),
      action({
        actionId: "accountant.main.draft_act",
        label: "Prepare closing act draft",
        intent: "draft_act",
        mode: "draft_only",
        aiTool: "draft_act",
        roleScope: FINANCE_ROLES,
        evidenceSources: ["document_metadata", "finance_summary"],
      }),
      action({
        actionId: "accountant.main.submit_payment_doc",
        label: "Submit finance document for approval",
        intent: "submit_for_approval",
        mode: "approval_required",
        aiTool: "submit_for_approval",
        roleScope: FINANCE_ROLES,
        evidenceSources: ["approval_policy", "finance_summary"],
      }),
      action({
        actionId: "accountant.main.create_payment_forbidden",
        label: "Create payment directly",
        intent: "forbidden",
        mode: "forbidden",
        roleScope: FINANCE_ROLES,
        evidenceSources: ["approval_policy", "finance_summary"],
        forbiddenReason: "Payments are never created directly from AI screen actions.",
      }),
    ],
  }),
  entry({
    screenId: "foreman.main",
    domain: "projects",
    allowedRoles: FOREMAN_ROLES,
    evidenceSources: ["screen_state", "warehouse_status", "procurement_context"],
    visibleActions: [
      action({
        actionId: "foreman.main.warehouse_status",
        label: "Read object material status",
        intent: "read_context",
        mode: "safe_read",
        aiTool: "get_warehouse_status",
        roleScope: FOREMAN_ROLES,
        evidenceSources: ["warehouse_status", "screen_state"],
      }),
      action({
        actionId: "foreman.main.find_material",
        label: "Find material for object",
        intent: "find",
        mode: "safe_read",
        aiTool: "search_catalog",
        roleScope: FOREMAN_ROLES,
        evidenceSources: ["procurement_context", "tool_contract"],
      }),
      action({
        actionId: "foreman.main.draft_request",
        label: "Prepare material request draft",
        intent: "draft",
        mode: "draft_only",
        aiTool: "draft_request",
        roleScope: FOREMAN_ROLES,
        evidenceSources: ["procurement_context", "document_metadata"],
      }),
      action({
        actionId: "foreman.main.submit_request",
        label: "Submit material request for approval",
        intent: "submit_for_approval",
        mode: "approval_required",
        aiTool: "submit_for_approval",
        roleScope: FOREMAN_ROLES,
        evidenceSources: ["approval_policy", "procurement_context"],
      }),
      action({
        actionId: "foreman.main.final_approve_forbidden",
        label: "Approve own request directly",
        intent: "forbidden",
        mode: "forbidden",
        roleScope: FOREMAN_ROLES,
        evidenceSources: ["approval_policy", "role_policy"],
        forbiddenReason: "Foreman screen actions can draft and submit, not self-approve.",
      }),
    ],
  }),
  entry({
    screenId: "foreman.ai.quick_modal",
    domain: "procurement",
    allowedRoles: FOREMAN_ROLES,
    evidenceSources: ["screen_state", "procurement_context", "approval_policy"],
    visibleActions: [
      action({
        actionId: "foreman.ai.quick_modal.find_context",
        label: "Find request context",
        intent: "find",
        mode: "safe_read",
        aiTool: "search_catalog",
        roleScope: FOREMAN_ROLES,
        evidenceSources: ["screen_state", "procurement_context"],
      }),
      action({
        actionId: "foreman.ai.quick_modal.compare_suppliers",
        label: "Compare supplier options",
        intent: "compare",
        mode: "safe_read",
        aiTool: "compare_suppliers",
        roleScope: FOREMAN_ROLES,
        evidenceSources: ["procurement_context", "tool_contract"],
      }),
      action({
        actionId: "foreman.ai.quick_modal.draft_request",
        label: "Prepare quick request draft",
        intent: "draft",
        mode: "draft_only",
        aiTool: "draft_request",
        roleScope: FOREMAN_ROLES,
        evidenceSources: ["procurement_context", "document_metadata"],
      }),
      action({
        actionId: "foreman.ai.quick_modal.submit_request",
        label: "Submit quick request for approval",
        intent: "submit_for_approval",
        mode: "approval_required",
        aiTool: "submit_for_approval",
        roleScope: FOREMAN_ROLES,
        evidenceSources: ["approval_policy", "procurement_context"],
      }),
      action({
        actionId: "foreman.ai.quick_modal.execute_without_approval_forbidden",
        label: "Execute request without approval",
        intent: "forbidden",
        mode: "forbidden",
        roleScope: FOREMAN_ROLES,
        evidenceSources: ["approval_policy", "role_policy"],
        forbiddenReason: "Quick modal cannot bypass approval ledger state.",
      }),
    ],
  }),
  entry({
    screenId: "contractor.main",
    domain: "subcontracts",
    allowedRoles: CONTRACTOR_ROLES,
    evidenceSources: ["screen_state", "document_metadata", "approval_policy"],
    visibleActions: [
      action({
        actionId: "contractor.main.check_status",
        label: "Check own action status",
        intent: "check_status",
        mode: "safe_read",
        aiTool: "get_action_status",
        roleScope: CONTRACTOR_ROLES,
        evidenceSources: ["ledger_status", "screen_state"],
      }),
      action({
        actionId: "contractor.main.draft_act",
        label: "Prepare own act draft",
        intent: "draft_act",
        mode: "draft_only",
        aiTool: "draft_act",
        roleScope: CONTRACTOR_ROLES,
        evidenceSources: ["document_metadata", "screen_state"],
      }),
      action({
        actionId: "contractor.main.draft_report",
        label: "Prepare progress report draft",
        intent: "draft_report",
        mode: "draft_only",
        aiTool: "draft_report",
        roleScope: CONTRACTOR_ROLES,
        evidenceSources: ["report_summary", "document_metadata"],
      }),
      action({
        actionId: "contractor.main.submit_progress",
        label: "Submit progress for approval",
        intent: "submit_for_approval",
        mode: "approval_required",
        aiTool: "submit_for_approval",
        roleScope: CONTRACTOR_ROLES,
        evidenceSources: ["approval_policy", "document_metadata"],
      }),
      action({
        actionId: "contractor.main.view_cross_role_finance_forbidden",
        label: "Read cross-role finance rows",
        intent: "forbidden",
        mode: "forbidden",
        roleScope: CONTRACTOR_ROLES,
        evidenceSources: ["role_policy", "finance_summary"],
        forbiddenReason: "Contractor scope cannot expose cross-role finance data.",
      }),
    ],
  }),
  entry({
    screenId: "reports.modal",
    domain: "reports",
    allowedRoles: OPERATIONS_ROLES,
    evidenceSources: ["screen_state", "report_summary", "document_metadata"],
    visibleActions: [
      action({
        actionId: "reports.modal.explain_report_status",
        label: "Explain report status",
        intent: "explain_status",
        mode: "safe_read",
        aiTool: "get_action_status",
        roleScope: OPERATIONS_ROLES,
        evidenceSources: ["report_summary", "ledger_status"],
      }),
      action({
        actionId: "reports.modal.draft_report",
        label: "Prepare report draft",
        intent: "draft_report",
        mode: "draft_only",
        aiTool: "draft_report",
        roleScope: OPERATIONS_ROLES,
        evidenceSources: ["report_summary", "document_metadata"],
      }),
      action({
        actionId: "reports.modal.draft_act",
        label: "Prepare act draft from report evidence",
        intent: "draft_act",
        mode: "draft_only",
        aiTool: "draft_act",
        roleScope: OPERATIONS_ROLES,
        evidenceSources: ["report_summary", "document_metadata"],
      }),
      action({
        actionId: "reports.modal.submit_report",
        label: "Submit report for approval",
        intent: "submit_for_approval",
        mode: "approval_required",
        aiTool: "submit_for_approval",
        roleScope: OPERATIONS_ROLES,
        evidenceSources: ["approval_policy", "report_summary"],
      }),
      action({
        actionId: "reports.modal.publish_final_forbidden",
        label: "Publish final report directly",
        intent: "forbidden",
        mode: "forbidden",
        roleScope: OPERATIONS_ROLES,
        evidenceSources: ["approval_policy", "document_metadata"],
        forbiddenReason: "Final report publication requires approved workflow state.",
      }),
    ],
  }),
  entry({
    screenId: "documents.main",
    domain: "documents",
    allowedRoles: OPERATIONS_ROLES,
    evidenceSources: ["screen_state", "document_metadata", "approval_policy"],
    visibleActions: [
      action({
        actionId: "documents.main.check_document_status",
        label: "Check document status",
        intent: "check_status",
        mode: "safe_read",
        aiTool: "get_action_status",
        roleScope: OPERATIONS_ROLES,
        evidenceSources: ["document_metadata", "ledger_status"],
      }),
      action({
        actionId: "documents.main.draft_report",
        label: "Prepare document report draft",
        intent: "draft_report",
        mode: "draft_only",
        aiTool: "draft_report",
        roleScope: OPERATIONS_ROLES,
        evidenceSources: ["document_metadata", "report_summary"],
      }),
      action({
        actionId: "documents.main.draft_act",
        label: "Prepare document act draft",
        intent: "draft_act",
        mode: "draft_only",
        aiTool: "draft_act",
        roleScope: OPERATIONS_ROLES,
        evidenceSources: ["document_metadata", "screen_state"],
      }),
      action({
        actionId: "documents.main.submit_document",
        label: "Submit document for approval",
        intent: "submit_for_approval",
        mode: "approval_required",
        aiTool: "submit_for_approval",
        roleScope: OPERATIONS_ROLES,
        evidenceSources: ["approval_policy", "document_metadata"],
      }),
      action({
        actionId: "documents.main.send_document_forbidden",
        label: "Send final document directly",
        intent: "forbidden",
        mode: "forbidden",
        roleScope: OPERATIONS_ROLES,
        evidenceSources: ["approval_policy", "document_metadata"],
        forbiddenReason: "Document sending is a final action and is not executable from AI map.",
      }),
    ],
  }),
  entry({
    screenId: "approval.inbox",
    domain: "documents",
    allowedRoles: CONTROL_ROLES,
    evidenceSources: ["screen_state", "ledger_status", "approval_policy"],
    visibleActions: [
      action({
        actionId: "approval.inbox.check_status",
        label: "Check approval status",
        intent: "check_status",
        mode: "safe_read",
        aiTool: "get_action_status",
        roleScope: CONTROL_ROLES,
        evidenceSources: ["ledger_status", "screen_state"],
      }),
      action({
        actionId: "approval.inbox.explain_evidence",
        label: "Explain approval evidence",
        intent: "explain_status",
        mode: "safe_read",
        aiTool: "get_action_status",
        roleScope: CONTROL_ROLES,
        evidenceSources: ["ledger_status", "approval_policy"],
      }),
      action({
        actionId: "approval.inbox.draft_revision",
        label: "Prepare revision draft",
        intent: "draft_report",
        mode: "draft_only",
        aiTool: "draft_report",
        roleScope: CONTROL_ROLES,
        evidenceSources: ["document_metadata", "approval_policy"],
      }),
      action({
        actionId: "approval.inbox.submit_rework",
        label: "Submit revised draft for approval",
        intent: "submit_for_approval",
        mode: "approval_required",
        aiTool: "submit_for_approval",
        roleScope: CONTROL_ROLES,
        evidenceSources: ["approval_policy", "ledger_status"],
      }),
      action({
        actionId: "approval.inbox.execute_gateway_forbidden",
        label: "Execute approved action from preview",
        intent: "forbidden",
        mode: "forbidden",
        roleScope: CONTROL_ROLES,
        evidenceSources: ["approval_policy", "ledger_status"],
        forbiddenReason: "Screen intelligence can plan execution but never executes it.",
      }),
    ],
  }),
  entry({
    screenId: "procurement.copilot",
    domain: "procurement",
    allowedRoles: PROCUREMENT_ROLES,
    evidenceSources: ["screen_state", "procurement_context", "approval_policy"],
    visibleActions: [
      action({
        actionId: "procurement.copilot.search_catalog",
        label: "Search catalog for request",
        intent: "search",
        mode: "safe_read",
        aiTool: "search_catalog",
        roleScope: PROCUREMENT_ROLES,
        evidenceSources: ["procurement_context", "tool_contract"],
      }),
      action({
        actionId: "procurement.copilot.compare_suppliers",
        label: "Compare supplier candidates",
        intent: "compare",
        mode: "safe_read",
        aiTool: "compare_suppliers",
        roleScope: PROCUREMENT_ROLES,
        evidenceSources: ["procurement_context", "tool_contract"],
      }),
      action({
        actionId: "procurement.copilot.draft_request",
        label: "Prepare AI request draft",
        intent: "draft",
        mode: "draft_only",
        aiTool: "draft_request",
        roleScope: PROCUREMENT_ROLES,
        evidenceSources: ["procurement_context", "document_metadata"],
      }),
      action({
        actionId: "procurement.copilot.submit_for_approval",
        label: "Submit copilot draft for approval",
        intent: "submit_for_approval",
        mode: "approval_required",
        aiTool: "submit_for_approval",
        roleScope: PROCUREMENT_ROLES,
        evidenceSources: ["approval_policy", "procurement_context"],
      }),
      action({
        actionId: "procurement.copilot.order_create_forbidden",
        label: "Create order from copilot",
        intent: "forbidden",
        mode: "forbidden",
        roleScope: PROCUREMENT_ROLES,
        evidenceSources: ["approval_policy", "procurement_context"],
        forbiddenReason: "Order creation is not part of screen-action intelligence.",
      }),
    ],
  }),
  entry({
    screenId: "screen.runtime",
    domain: "control",
    allowedRoles: OPERATIONS_ROLES,
    evidenceSources: ["screen_state", "role_policy", "tool_contract"],
    visibleActions: [
      action({
        actionId: "screen.runtime.read_context",
        label: "Read current screen context",
        intent: "read_context",
        mode: "safe_read",
        aiTool: "get_action_status",
        roleScope: OPERATIONS_ROLES,
        evidenceSources: ["screen_state", "role_policy"],
      }),
      action({
        actionId: "screen.runtime.check_status",
        label: "Check action or approval status",
        intent: "check_status",
        mode: "safe_read",
        aiTool: "get_action_status",
        roleScope: OPERATIONS_ROLES,
        evidenceSources: ["ledger_status", "tool_contract"],
      }),
      action({
        actionId: "screen.runtime.draft_request",
        label: "Prepare screen-scoped draft",
        intent: "draft",
        mode: "draft_only",
        aiTool: "draft_request",
        roleScope: OPERATIONS_ROLES,
        evidenceSources: ["screen_state", "document_metadata"],
      }),
      action({
        actionId: "screen.runtime.submit_for_approval",
        label: "Submit screen-scoped action for approval",
        intent: "submit_for_approval",
        mode: "approval_required",
        aiTool: "submit_for_approval",
        roleScope: OPERATIONS_ROLES,
        evidenceSources: ["approval_policy", "tool_contract"],
      }),
      action({
        actionId: "screen.runtime.direct_mutation_forbidden",
        label: "Mutate current screen directly",
        intent: "forbidden",
        mode: "forbidden",
        roleScope: OPERATIONS_ROLES,
        evidenceSources: ["approval_policy", "role_policy"],
        forbiddenReason: "Runtime screen intelligence is read-only and plan-only.",
      }),
    ],
  }),
] as const;

export function getAiScreenActionEntry(screenId: string): AiScreenActionRegistryEntry | null {
  const normalized = String(screenId || "").trim();
  return AI_SCREEN_ACTION_REGISTRY.find((entry) => entry.screenId === normalized) ?? null;
}

export function listAiScreenActionEntries(): AiScreenActionRegistryEntry[] {
  return [...AI_SCREEN_ACTION_REGISTRY];
}
