export const BUYER_ROLE_POLICY = {
  role: "buyer",
  canSee: [
    "approved_and_pending_requests",
    "request_materials_services_equipment",
    "linked_object_zone_work",
    "linked_estimate_lines",
    "linked_project_specification_pdf",
    "linked_warehouse_stock",
    "supplier_history_for_similar_items",
    "approved_vendors",
    "supplier_offers",
    "own_marketplace",
    "external_marketplace_with_trace",
    "delivery_terms",
    "currency_units",
    "approval_status",
    "foreman_director_comments_for_request",
  ],
  cannotSee: [
    "full_company_cashflow",
    "unrelated_payments",
    "salaries",
    "company_margin",
    "security_events",
    "role_permissions",
    "runtime_debug",
    "service_role",
    "raw_provider_payload",
    "env_secrets",
    "unrelated_commercial_terms",
  ],
  directOrderAllowed: false,
  directPurchaseOrderAllowed: false,
  directPaymentAllowed: false,
  autoApprovalAllowed: false,
  approvalBypassAllowed: false,
  dbWritesFromAiAnswerAllowed: false,
  fakeSuppliersAllowed: false,
  fakePricesAllowed: false,
  fakeAvailabilityAllowed: false,
  fakeInternetResultsAllowed: false,
} as const;

export const buyerRolePolicy = BUYER_ROLE_POLICY;
