export type Batch005R2FinalGateSnapshotV1 = {
  electrical_ids: number;
  electrical_groups: number;
  production_rows: number;
  expected_to_production_reconciliation_rows: number;
  row_legitimacy_rows: number;
  independent_completeness_decisions: number;
  independent_expected_missing: number;
  production_without_independent_expected: number;
  auditor_imports_production_builder: boolean;
  auditor_imports_production_snapshot: boolean;
  expected_derived_from_serialized_production: boolean;
  duplicate_semantic_rows: number;
  hidden_aggregates: number;
  unsupported_padding_rows: number;
  mutually_exclusive_double_inclusions: number;
  parent_child_double_count: number;
  silent_defaults: number;
  unused_visible_parameters: number;
  invalid_parameter_contracts: number;
  wrong_formula_dependencies: number;
  missing_cost_owners: number;
  silent_zero_prices: number;
  missing_normative_locators: number;
  wrong_jurisdiction_roles: number;
  unexplained_graph_aliases: number;
  lost_durable_rows: number;
  pdf_row_mismatch: number;
  procurement_row_mismatch: number;
  stale_apk_accepted: boolean;
  lifecycle_regressions: number;
  unexplained_ui_cost_deltas: number;
  ui_hidden_durable_rows: number;
  oracle_fixture_obligations_missing: number;
  production_builder_rows_missing: number;
  closeout_before_reconciliation: boolean;
};

export type Batch005R2FinalGateIssueV1 = { code: string; detail: string };

export function auditBatch005R2FinalGateV1(snapshot: Batch005R2FinalGateSnapshotV1): readonly Batch005R2FinalGateIssueV1[] {
  const issues: Batch005R2FinalGateIssueV1[] = [];
  const exact = (condition: boolean, code: string, detail: string) => { if (!condition) issues.push({ code, detail }); };
  const zero = (value: number, code: string) => exact(value === 0, code, String(value));
  exact(snapshot.electrical_ids === 605, "ELECTRICAL_ID_DENOMINATOR", String(snapshot.electrical_ids));
  exact(snapshot.electrical_groups === 107, "ELECTRICAL_GROUP_DENOMINATOR", String(snapshot.electrical_groups));
  exact(snapshot.expected_to_production_reconciliation_rows === snapshot.production_rows, "EXPECTED_TO_PRODUCTION_RECONCILIATION_LOSS", `${snapshot.expected_to_production_reconciliation_rows}/${snapshot.production_rows}`);
  exact(snapshot.row_legitimacy_rows === snapshot.production_rows, "ROW_LEGITIMACY_LOSS", `${snapshot.row_legitimacy_rows}/${snapshot.production_rows}`);
  exact(snapshot.independent_completeness_decisions === 21_780, "INDEPENDENT_COMPLETENESS_DENOMINATOR", String(snapshot.independent_completeness_decisions));
  zero(snapshot.independent_expected_missing, "EXPECTED_CANDIDATE_MISSING_FROM_PRODUCTION");
  zero(snapshot.production_without_independent_expected, "PRODUCTION_ROW_WITHOUT_INDEPENDENT_EXPECTED");
  exact(!snapshot.auditor_imports_production_builder, "AUDITOR_IMPORTS_PRODUCTION_BUILDER", "true");
  exact(!snapshot.auditor_imports_production_snapshot, "AUDITOR_IMPORTS_PRODUCTION_SNAPSHOT", "true");
  exact(!snapshot.expected_derived_from_serialized_production, "EXPECTED_DERIVED_FROM_SERIALIZED_PRODUCTION", "true");
  zero(snapshot.duplicate_semantic_rows, "DUPLICATE_SEMANTIC_ROW");
  zero(snapshot.hidden_aggregates, "HIDDEN_AGGREGATE");
  zero(snapshot.unsupported_padding_rows, "UNSUPPORTED_PADDING");
  zero(snapshot.mutually_exclusive_double_inclusions, "MUTUALLY_EXCLUSIVE_DOUBLE_INCLUSION");
  zero(snapshot.parent_child_double_count, "PARENT_CHILD_DOUBLE_COUNT");
  zero(snapshot.silent_defaults, "SILENT_DEFAULT");
  zero(snapshot.unused_visible_parameters, "UNUSED_VISIBLE_PARAMETER");
  zero(snapshot.invalid_parameter_contracts, "INVALID_PARAMETER_BOUND_CHOICE_OR_UNIT");
  zero(snapshot.wrong_formula_dependencies, "WRONG_FORMULA_DEPENDENCY");
  zero(snapshot.missing_cost_owners, "MISSING_COST_OWNER");
  zero(snapshot.silent_zero_prices, "SILENT_ZERO_PRICE");
  zero(snapshot.missing_normative_locators, "MISSING_NORMATIVE_LOCATOR");
  zero(snapshot.wrong_jurisdiction_roles, "WRONG_JURISDICTION_ROLE");
  zero(snapshot.unexplained_graph_aliases, "IDENTICAL_GRAPH_FOR_INCOMPATIBLE_WORKS");
  zero(snapshot.lost_durable_rows, "LOST_DURABLE_ROW");
  zero(snapshot.pdf_row_mismatch, "PDF_ROW_DIVERGENCE");
  zero(snapshot.procurement_row_mismatch, "PROCUREMENT_ROW_DIVERGENCE");
  exact(!snapshot.stale_apk_accepted, "STALE_APK_ACCEPTED", "true");
  zero(snapshot.lifecycle_regressions, "LIFECYCLE_ACKNOWLEDGEMENT_REGRESSION");
  zero(snapshot.unexplained_ui_cost_deltas, "UNEXPLAINED_UI_COST_DELTA");
  zero(snapshot.ui_hidden_durable_rows, "UI_GROUPING_HIDES_DURABLE_ROWS");
  zero(snapshot.oracle_fixture_obligations_missing, "ORACLE_FIXTURE_OBLIGATION_REMOVED");
  zero(snapshot.production_builder_rows_missing, "PRODUCTION_BUILDER_ROW_REMOVED");
  exact(!snapshot.closeout_before_reconciliation, "CLOSEOUT_WITHOUT_RECONCILIATION", "true");
  return Object.freeze(issues);
}
