const FORBIDDEN_USER_COPY_PATTERNS = [
  /AI APP KNOWLEDGE BLOCK/i,
  /READ_ONLY_FACTS/i,
  /\bscreenId:/i,
  /\bcontextPolicy:/i,
  /\ballowedEntities:/i,
  /allowedIntents/i,
  /blockedIntents/i,
  /documentSources/i,
  /reportSources/i,
  /pdfSources/i,
  /approvalBoundary/i,
  /redactionPolicy/i,
  /professionalAnswerRequirements/i,
  /rawDocumentContent/i,
  /rawPdfContent/i,
  /rawAttachmentContent/i,
  /raw prompt/i,
  /raw provider/i,
  /raw payload/i,
  /raw transport/i,
  /raw policy dump/i,
  /raw screenId/i,
  /raw route key/i,
  /raw JSON/i,
  /provider status/i,
  /transport status/i,
  /runtime label/i,
  /provider unavailable/i,
  /provider not configured/i,
  /module unavailable/i,
  /I cannot help with that/i,
  /I don't have context/i,
  /I do not have context/i,
  /AI-ключи не настроены/i,
  /AI keys are not configured/i,
] as const;

const INTERNAL_CONTEXT_BLOCK_PATTERNS = [
  /AI APP KNOWLEDGE BLOCK/i,
  /READ_ONLY_FACTS/i,
  /\bscreenId:/i,
  /\bcontextPolicy:/i,
  /\ballowedEntities:/i,
  /allowedIntents/i,
  /blockedIntents/i,
  /documentSources/i,
  /reportSources/i,
  /pdfSources/i,
  /approvalBoundary/i,
  /redactionPolicy/i,
  /professionalAnswerRequirements/i,
  /rawDocumentContent/i,
  /rawPdfContent/i,
  /rawAttachmentContent/i,
] as const;

export const AI_SCREEN_MAGIC_SAFE_STATUS_COPY =
  "AI подготовил безопасные ответы, черновики и маршруты согласования по данным текущего экрана.";

const USER_COPY_REPLACEMENTS: readonly [RegExp, string][] = [
  [/\braw provider payload\b/gi, ""],
  [/\braw provider\b/gi, ""],
  [/\bprovider unavailable\b/gi, ""],
  [/\bprovider not configured\b/gi, ""],
  [/\bmodule unavailable\b/gi, ""],
  [/\bsafe_read\b/gi, "показать"],
  [/\bdraft_only\b/gi, "черновик"],
  [/\bapproval_required\b/gi, "согласование"],
  [/\bexact_blocker\b/gi, "причина блокировки"],
  [/\bforbidden\b/gi, "недоступно"],
  [/\bPrepared work\b/gi, "Что подготовлено"],
  [/\bcritical blockers\b/gi, "Что мешает"],
  [/\bmissing documents\b/gi, "не хватает документов"],
  [/\bcritical payments\b/gi, "критические платежи"],
  [/\bmissing data\b/gi, "не хватает данных"],
  [/\bmissing\b/gi, "не хватает"],
  [/\bmissingData\b/gi, "не хватает данных"],
  [/\bnext actions\b/gi, "следующие шаги"],
  [/\bnextActions\b/gi, "следующие шаги"],
  [/\bevidence\b/gi, "основание"],
  [/\brationale\b/gi, "обоснование"],
  [/\bscreenMagic\b/gi, "экранный помощник"],
  [/\bprovider\b/gi, "модуль"],
  [/\bruntime diagnosis\b/gi, "диагностика для администратора"],
  [/\bruntime health\b/gi, "состояние диагностики"],
  [/\bruntime\b/gi, "диагностика"],
  [/\btransport binding\b/gi, "связь проверки"],
  [/\btransport\b/gi, "связь"],
  [/\bapproval ledger\b/gi, "журнал согласования"],
  [/\bledger path\b/gi, "маршрут согласования"],
  [/\bgreen path\b/gi, "разрешённый путь"],
  [/\bservice[_-]role\b/gi, "служебный доступ"],
  [/\bmutation\b/gi, "изменение данных"],
  [/\bexecute directly\b/gi, "выполнить напрямую"],
  [/\bread-result\b/gi, "результат чтения"],
  [/\bhydrated screen context\b/gi, "данные текущего экрана"],
  [/\bhydrated data can show workflow but cannot invent business facts\b/gi, "подтверждённые данные могут показать ход работы, но не выдумывают рабочие факты"],
  [/BLOCKED_AI_SCREEN_WORKFLOW_REAL_DATA_ROUTE_MISSING/gi, "нет маршрута реальных данных для этого экрана"],
  [/\bhydrated\b/gi, "подтверждённые"],
  [/\bdata\b/gi, "данные"],
  [/\bworkflow\b/gi, "ход работы"],
  [/\bbusiness facts\b/gi, "рабочие факты"],
  [/\bcannot invent\b/gi, "нельзя выдумывать"],
  [/\bcan show\b/gi, "можно показать"],
  [/\bbut\b/gi, "но"],
  [/\bsafe preview\b/gi, "безопасный просмотр"],
  [/\bdraft-only preview\b/gi, "предпросмотр черновика"],
  [/\bResult type\b/gi, "Тип результата"],
  [/\bCommand Center\b/gi, "Центр действий"],
  [/\bcommand center\b/gi, "центр действий"],
  [/\bProcurement workbench\b/gi, "Рабочее место снабжения"],
  [/\bSubcontract status\b/gi, "Подрядчик"],
  [/\bSecurity overview\b/gi, "Обзор безопасности"],
  [/\bExecutive summary\b/gi, "Сводка руководителя"],
  [/\bsummary\b/gi, "сводка"],
  [/\breport draft\b/gi, "черновик отчёта"],
  [/\breport\b/gi, "отчёт"],
  [/\bdraft\b/gi, "черновик"],
  [/\bapproval\b/gi, "согласование"],
  [/\bapprove\b/gi, "согласовать"],
  [/\bReject\b/gi, "Отклонить"],
  [/\bSubmit\b/gi, "Отправить"],
  [/\bPrepare\b/gi, "Подготовить"],
  [/\bFinal\b/gi, "Финально"],
  [/\bSign\b/gi, "Подписать"],
  [/\bdirectly\b/gi, "напрямую"],
  [/\bdirect\b/gi, "напрямую"],
  [/\bchecklist\b/gi, "чек-лист"],
  [/\bshortlist\b/gi, "короткий список"],
  [/\bcited\b/gi, "с основанием"],
  [/\binbox\b/gi, "входящие"],
  [/\bpath\b/gi, "маршрут"],
  [/\bpackage\b/gi, "пакет"],
  [/\bpack\b/gi, "пакет"],
  [/\bproposal\b/gi, "предложение"],
  [/\brequest\b/gi, "запрос"],
  [/\bcorrection\b/gi, "исправление"],
  [/\bmarket-backed\b/gi, "с рыночным основанием"],
  [/\bhuman only\b/gi, "только человеком"],
  [/\bhuman\b/gi, "человек"],
  [/\bonly\b/gi, "только"],
  [/\bsubcontract\b/gi, "подрядчик"],
  [/\bprogress\b/gi, "ход работ"],
  [/\bdocument\b/gi, "документ"],
  [/\bchange\b/gi, "изменение"],
  [/\bsite context\b/gi, "данные объекта"],
  [/\bcontext\b/gi, "контекст"],
  [/\breminder\b/gi, "напоминание"],
  [/\brisk roles\b/gi, "роли с риском"],
  [/\brisk\b/gi, "риск"],
  [/\bsecurity\b/gi, "безопасность"],
  [/\battempts\b/gi, "попытки"],
  [/\bexact blocker\b/gi, "точная причина"],
  [/\bexact\b/gi, "точно"],
  [/\bblocker\b/gi, "причина блокировки"],
  [/\brepair command\b/gi, "команда проверки"],
  [/\bcommand\b/gi, "команда"],
  [/\bcomment\b/gi, "комментарий"],
  [/\bgated\b/gi, "через согласование"],
  [/\baction\b/gi, "действие"],
  [/\bapprovals\b/gi, "согласования"],
  [/\bpending\b/gi, "ожидают"],
  [/\btop issues\b/gi, "главные вопросы"],
  [/\btop decision\b/gi, "главное решение"],
  [/\bissue\b/gi, "вопрос"],
  [/\bdecision\b/gi, "решение"],
  [/\bnext\b/gi, "следующий"],
  [/\bpayments\b/gi, "платежи"],
  [/\bpayment\b/gi, "платёж"],
  [/\bsuppliers\b/gi, "поставщики"],
  [/\bsupplier\b/gi, "поставщик"],
  [/\bdeltas\b/gi, "отклонения"],
  [/\bgaps\b/gi, "пробелы"],
  [/\bhigh-risk\b/gi, "с высоким риском"],
  [/\bprocurement\b/gi, "снабжение"],
  [/\bwarehouse\b/gi, "склад"],
  [/\bfinance\b/gi, "финансы"],
  [/\bdocuments\b/gi, "документы"],
  [/\bfield\b/gi, "полевые работы"],
  [/\bbuyer\b/gi, "снабженец"],
  [/\baccountant\b/gi, "бухгалтер"],
  [/\bdirector\b/gi, "директор"],
  [/\bforeman\b/gi, "прораб"],
  [/\boffice\b/gi, "офис"],
  [/\bdeveloper\b/gi, "разработчик"],
  [/\bdev\b/gi, "разработчик"],
  [/\badmin\b/gi, "администратор"],
  [/\bcross-role\b/gi, "межролевой"],
  [/\bdangerous execution\b/gi, "опасное выполнение"],
  [/\bwithout\b/gi, "без"],
  [/\bboundaries\b/gi, "границы"],
  [/\breason\b/gi, "причина"],
  [/\brisks\b/gi, "риски"],
  [/\beffect after\b/gi, "что будет после"],
  [/\bhidden\b/gi, "скрыто"],
  [/\bself\b/gi, "самостоятельно"],
  [/\bsource\b/gi, "источник"],
  [/\bavailability\b/gi, "наличие"],
  [/\bbacked\b/gi, "с основанием"],
  [/\bcomparison\b/gi, "сравнение"],
  [/\bprice\b/gi, "цена"],
  [/\bdelivery\b/gi, "доставка"],
  [/\bsignals\b/gi, "сигналы"],
  [/\bsignal\b/gi, "сигнал"],
  [/\breliability\b/gi, "надёжность"],
  [/\binternal-first\b/gi, "сначала внутренние варианты"],
  [/\brecommendation\b/gi, "рекомендация"],
  [/\bcandidate\b/gi, "кандидат"],
  [/\bcitations\b/gi, "ссылки-основания"],
  [/\bcitation\b/gi, "ссылка-основание"],
  [/\bpreview\b/gi, "предпросмотр"],
  [/\bcoverage\b/gi, "покрытие"],
  [/\bhistory\b/gi, "история"],
  [/\bproof\b/gi, "подтверждение"],
  [/\bstock\b/gi, "остатки"],
  [/\brequired\b/gi, "требуется"],
  [/\bmaterial blockers\b/gi, "материалы мешают"],
  [/\bsubcontractor blockers\b/gi, "подрядчики с блокерами"],
  [/\bconstruction\b/gi, "строительный"],
  [/\bif source exists\b/gi, "если есть источник"],
  [/\bsafety check\b/gi, "проверка безопасности"],
  [/\breview\b/gi, "проверка"],
  [/\bcloseout\b/gi, "закрытие"],
  [/\bsigning\b/gi, "подписание"],
  [/\bcontractor\b/gi, "подрядчик"],
  [/\bwork status\b/gi, "статус работ"],
  [/\bworks\b/gi, "работы"],
  [/\bimportant fields\b/gi, "важные поля"],
  [/\blinked objects\b/gi, "связанные объекты"],
  [/\blinked\b/gi, "связанные"],
  [/\bdecisions\b/gi, "решения"],
  [/\bdiscussion\b/gi, "обсуждение"],
  [/\bextracted tasks\b/gi, "извлечённые задачи"],
  [/\bblockers\b/gi, "что мешает"],
  [/\bneeds\b/gi, "нужны"],
  [/\bneeded\b/gi, "нужно"],
  [/\btasks\b/gi, "задачи"],
  [/\btask\b/gi, "задача"],
  [/\bowner\b/gi, "ответственный"],
  [/\broute risks\b/gi, "риски маршрута"],
  [/\bETA\b/gi, "срок доставки"],
  [/\bnearby\b/gi, "рядом"],
  [/\bobjects\b/gi, "объекты"],
  [/\bstalled\b/gi, "застряли"],
  [/\breports\b/gi, "отчёты"],
  [/\bpermission changes\b/gi, "изменения прав"],
  [/\bpermission\b/gi, "права"],
  [/\baudit\b/gi, "аудит"],
  [/\bsuspicious\b/gi, "подозрительные"],
  [/\bartifact\b/gi, "артефакт"],
  [/\bfallback entries\b/gi, "запасные записи"],
  [/\bfallback\b/gi, "запасной вариант"],
  [/\bfailing child runner\b/gi, "падающая проверка"],
  [/\brecommended\b/gi, "рекомендовано"],
  [/high-/gi, "высокий "],
  [/\bamount deviations\b/gi, "отклонения суммы"],
  [/\bamount deviation\b/gi, "отклонение суммы"],
  [/\bamount\b/gi, "сумма"],
  [/\bfull\b/gi, "полный"],
  [/\bwaiting\b/gi, "ожидают"],
  [/\bqueue\b/gi, "очередь"],
  [/\bcritical deviations\b/gi, "критические отклонения"],
  [/\bcritical deviation\b/gi, "критическое отклонение"],
  [/\bstatus\b/gi, "статус"],
  [/\bledger\b/gi, "журнал"],
  [/\bblocked route\b/gi, "заблокированный маршрут"],
  [/\blast\b/gi, "последний"],
  [/\blabel\b/gi, "метка"],
  [/\bstays blocked\b/gi, "остаётся заблокировано"],
  [/\bApprover\b/gi, "согласующий"],
  [/\bitself\b/gi, "самостоятельно"],
  [/\bprices\b/gi, "цены"],
  [/no-/gi, "нет "],
  [/approved-/gi, "согласовано "],
  [/\bcopilot\b/gi, "помощник"],
  [/\border\b/gi, "заказ"],
  [/\bdrafts\b/gi, "черновики"],
  [/\bif\b/gi, "если"],
  [/\bexists\b/gi, "есть"],
  [/\bphotos\b/gi, "фото"],
  [/\bphoto\b/gi, "фото"],
  [/\bsignature\b/gi, "подпись"],
  [/\bmodal\b/gi, "окно"],
  [/\bquick\b/gi, "быстрый"],
  [/\bclosing\b/gi, "закрытие"],
  [/\bsafe replies\b/gi, "безопасные ответы"],
  [/\bsafe\b/gi, "безопасно"],
  [/\breply to\b/gi, "ответ для"],
  [/\bwith remarks\b/gi, "с замечаниями"],
  [/\bmain events\b/gi, "главные события"],
  [/\brequests\b/gi, "заявки"],
  [/\bobject absent\b/gi, "объект не найден"],
  [/\bobject\b/gi, "объект"],
  [/\bis\b/gi, "это"],
  [/\bact\b/gi, "акт"],
  [/\bdate\b/gi, "дата"],
  [/\bterms\b/gi, "условия"],
  [/\bobligations\b/gi, "обязательства"],
  [/\bobligation\b/gi, "обязательство"],
  [/\bcandidates\b/gi, "кандидаты"],
  [/\bneed\b/gi, "нужно"],
  [/\bfrom chat\b/gi, "из чата"],
  [/\bchat\b/gi, "чат"],
  [/\bdeadline\b/gi, "срок"],
  [/\bdistance\b/gi, "расстояние"],
  [/\bimpact on requests\b/gi, "влияние на заявки"],
  [/\bimpact on\b/gi, "влияние на"],
  [/\bon\b/gi, "на"],
  [/\bcreation\b/gi, "создание"],
  [/\bto process\b/gi, "на обработку"],
  [/\bto\b/gi, "для"],
  [/\bitems requiring\b/gi, "требуют"],
  [/\boverdue\b/gi, "просрочено"],
  [/\bstuck\b/gi, "застряло"],
  [/\broute\b/gi, "маршрут"],
  [/\band\b/gi, "и"],
  [/\brisky role\b/gi, "роль с риском"],
  [/\battempt\b/gi, "попытка"],
  [/\bgap\b/gi, "пробел"],
  [/\btrace\b/gi, "след проверки"],
  [/\bexplicit\b/gi, "явный"],
  [/\bchild runner failed\b/gi, "дочерняя проверка упала"],
  [/\bchild runner\b/gi, "дочерняя проверка"],
  [/\bentry\b/gi, "запись"],
  [/\brunner result\b/gi, "результат проверки"],
  [/\brunner\b/gi, "проверка"],
  [/\bscreen\b/gi, "экран"],
  [/\bor\b/gi, "или"],
  [/\bRisky roles\b/gi, "роли с риском"],
  [/\brisky roles\b/gi, "роли с риском"],
  [/\bpolicy gaps\b/gi, "пробелы в правилах"],
  [/\bpolicy\b/gi, "правила"],
  [/\bforbidden attempts\b/gi, "запрещённые попытки"],
  [/\bForbidden attempts\b/gi, "запрещённые попытки"],
  [/\bstuck requests\b/gi, "застрявшие заявки"],
  [/\boverdue tasks\b/gi, "просроченные задачи"],
  [/\bdocuments to process\b/gi, "документы на обработку"],
  [/\breports to review\b/gi, "отчёты на проверку"],
  [/\bitems requiring approval\b/gi, "требуют согласования"],
];

function includesForbiddenAiScreenMagicUserCopy(value: string): boolean {
  return FORBIDDEN_USER_COPY_PATTERNS.some((pattern) => pattern.test(value));
}

function includesInternalContextBlockCopy(value: string): boolean {
  return INTERNAL_CONTEXT_BLOCK_PATTERNS.some((pattern) => pattern.test(value));
}

export function sanitizeAiScreenMagicUserCopy(value: string): string {
  let next = String(value || "");
  if (includesInternalContextBlockCopy(next)) {
    return AI_SCREEN_MAGIC_SAFE_STATUS_COPY;
  }
  for (const [pattern, replacement] of USER_COPY_REPLACEMENTS) {
    next = next.replace(pattern, replacement);
  }
  for (const pattern of FORBIDDEN_USER_COPY_PATTERNS) {
    next = next.replace(pattern, "");
  }
  return next.replace(/[ \t]{2,}/g, " ").replace(/\n{3,}/g, "\n\n").trim();
}

export function containsForbiddenAiScreenMagicUserCopy(value: string): boolean {
  return includesForbiddenAiScreenMagicUserCopy(value);
}
