import type { AccountantActionQuestion, AccountantIntent, AccountantScreenId } from "./accountantFinanceTypes";

export const ACCOUNTANT_ACTION_QUESTION_MAP: readonly AccountantActionQuestion[] = [
  {
    screenId: "accountant.main",
    actionId: "payment_readiness_check",
    labelRu: "Что можно оплатить",
    concreteQuestionRu: "Проверь платежи и покажи, какие можно готовить к согласованию, а какие нельзя оплачивать из-за отсутствующих документов, склада, акта или approval.",
    requiredContext: ["period"],
    allowedSources: ["payment", "invoice", "act", "document", "approval", "warehouse_incoming", "procurement_request"],
    answerMode: "read",
  },
  {
    screenId: "accountant.main",
    actionId: "critical_payments",
    labelRu: "Проверить рисковые платежи",
    concreteQuestionRu: "Найди платежи с высоким риском: без акта, без накладной, без approval, без подтверждения склада, с расхождением суммы или без связанного основания.",
    requiredContext: ["period"],
    allowedSources: ["payment", "invoice", "act", "waybill", "approval", "warehouse_incoming", "accounting_record"],
    answerMode: "read",
  },
  {
    screenId: "accountant.main",
    actionId: "missing_documents_for_payment",
    labelRu: "Каких документов не хватает",
    concreteQuestionRu: "Покажи платежи и счета, по которым не хватает первичных документов, актов, накладных, договоров или approval.",
    requiredContext: ["period"],
    allowedSources: ["invoice", "act", "contract", "waybill", "document", "approval"],
    answerMode: "read",
  },
  {
    screenId: "accountant.main",
    actionId: "cashflow_summary",
    labelRu: "Показать движение денег",
    concreteQuestionRu: "Покажи движение денег за период: оплачено, ожидает оплаты, заблокировано, ожидает согласования, с разрезом по объектам и поставщикам, если доступно.",
    requiredContext: ["period"],
    allowedSources: ["payment", "cashflow", "cashflow_slice", "accounting_record", "approval", "object"],
    answerMode: "read",
  },
  {
    screenId: "accountant.main",
    actionId: "director_payment_rationale",
    labelRu: "Подготовить rationale директору",
    concreteQuestionRu: "Подготовь объяснение директору по платежам: что можно согласовать, какие риски, какие документы есть, чего не хватает, почему требуется решение.",
    requiredContext: ["period"],
    allowedSources: ["payment", "invoice", "act", "document", "approval", "procurement_request", "warehouse_incoming"],
    answerMode: "draft",
  },
  {
    screenId: "accountant.main",
    actionId: "document_request_draft",
    labelRu: "Запросить документы",
    concreteQuestionRu: "Подготовь черновик запроса поставщику или подрядчику по недостающим первичным документам без финальной отправки.",
    requiredContext: ["invoice"],
    allowedSources: ["invoice", "act", "contract", "waybill", "document", "approval"],
    answerMode: "draft",
  },
  {
    screenId: "accountant.main",
    actionId: "approval_queue_for_finance",
    labelRu: "Отправить на согласование",
    concreteQuestionRu: "Подготовь маршрут согласования по выбранному платежу или пакету платежей без выполнения оплаты и без автоматического approval.",
    requiredContext: ["payment"],
    allowedSources: ["payment", "invoice", "act", "document", "approval"],
    answerMode: "approval_route",
  },
  {
    screenId: "finance.payment.detail",
    actionId: "act_to_payment_reconciliation",
    labelRu: "Проверить склад/акт",
    concreteQuestionRu: "Сверь акт, платеж, счет, работу, объект и approval без выполнения оплаты.",
    requiredContext: ["act"],
    allowedSources: ["act", "payment", "invoice", "work", "object", "approval"],
    answerMode: "read",
  },
  {
    screenId: "finance.payment.detail",
    actionId: "payment_risk_explanation",
    labelRu: "Объяснить риск",
    concreteQuestionRu: "Объясни финансовый риск платежа по источникам: счет, акт, документы, склад, approval и связанные работы.",
    requiredContext: ["payment"],
    allowedSources: ["payment", "invoice", "act", "approval", "warehouse_incoming", "document"],
    answerMode: "read",
  },
  {
    screenId: "finance.invoice.detail",
    actionId: "invoice_to_request_reconciliation",
    labelRu: "Сверить с заявкой",
    concreteQuestionRu: "Сверь счет с закупочной заявкой, поставщиком, КП, документами и approval.",
    requiredContext: ["invoice"],
    allowedSources: ["invoice", "procurement_request", "supplier_offer", "document", "approval"],
    answerMode: "read",
  },
  {
    screenId: "finance.invoice.detail",
    actionId: "invoice_to_warehouse_reconciliation",
    labelRu: "Сверить с приходом",
    concreteQuestionRu: "Сверь счет с приходом склада, накладной и связанными документами.",
    requiredContext: ["invoice"],
    allowedSources: ["invoice", "warehouse_incoming", "warehouse_issue", "waybill", "document"],
    answerMode: "read",
  },
  {
    screenId: "finance.cashflow",
    actionId: "cashflow_forecast",
    labelRu: "Подготовить прогноз",
    concreteQuestionRu: "Подготовь прогноз cashflow на период только как прогноз, с периодом, валютой, источниками и рисками.",
    requiredContext: ["period"],
    allowedSources: ["payment", "cashflow", "invoice", "approval", "contract"],
    answerMode: "read",
  },
  {
    screenId: "accountant.invoice.detail",
    actionId: "estimate_to_act_reconciliation",
    labelRu: "Смета -> акт -> счет",
    concreteQuestionRu: "Свяжи счет со сметой, актом, работой, объектом и документальными источниками.",
    requiredContext: ["invoice"],
    allowedSources: ["invoice", "act", "estimate_line", "project_pdf", "pdf_chunk", "work", "object"],
    answerMode: "read",
  },
  {
    screenId: "accountant.invoice.detail",
    actionId: "payment_risk_explanation",
    labelRu: "Почему риск",
    concreteQuestionRu: "Объясни, почему счет можно или нельзя оплачивать, с источниками и без проведения платежа.",
    requiredContext: ["invoice"],
    allowedSources: ["invoice", "act", "payment", "document", "approval"],
    answerMode: "read",
  },
  {
    screenId: "accountant.invoice.detail",
    actionId: "prepare_payment_rationale",
    labelRu: "Rationale директору",
    concreteQuestionRu: "Подготовь черновик rationale директору по счету: основания, сумма, риски, документы.",
    requiredContext: ["invoice"],
    allowedSources: ["invoice", "act", "estimate_line", "payment", "approval"],
    answerMode: "draft",
  },
  {
    screenId: "accountant.invoice.detail",
    actionId: "prepare_approval_handoff",
    labelRu: "На согласование",
    concreteQuestionRu: "Подготовь маршрут согласования без создания платежа, проводки или автоматического approval.",
    requiredContext: ["invoice"],
    allowedSources: ["invoice", "payment", "approval"],
    answerMode: "approval_route",
  },
  {
    screenId: "finance.copilot",
    actionId: "supplier_debt_summary",
    labelRu: "Дебиторка / кредиторка",
    concreteQuestionRu: "Собери debt/creditor summary по доступным счетам, платежам и cashflow slice.",
    requiredContext: ["period"],
    allowedSources: ["invoice", "payment", "cashflow_slice"],
    answerMode: "read",
  },
  {
    screenId: "accountant.main",
    actionId: "payment_readiness",
    labelRu: "Legacy: что можно оплачивать",
    concreteQuestionRu: "Проверь счета на готовность к оплате: акт, документы, approval, сумма и риски.",
    requiredContext: ["invoice"],
    allowedSources: ["invoice", "act", "payment", "approval", "supplier_document"],
    answerMode: "read",
  },
  {
    screenId: "accountant.invoice.detail",
    actionId: "estimate_act_invoice_chain",
    labelRu: "Legacy: смета -> акт -> счет",
    concreteQuestionRu: "Свяжи счет со сметой, актом, работой, объектом и документальными источниками.",
    requiredContext: ["invoice"],
    allowedSources: ["invoice", "act", "estimate_line", "project_pdf", "pdf_chunk", "work", "object"],
    answerMode: "read",
  },
] as const;

export function getAccountantActionQuestion(
  actionId: AccountantIntent,
  screenId?: AccountantScreenId,
): AccountantActionQuestion | null {
  const action = ACCOUNTANT_ACTION_QUESTION_MAP.find((entry) =>
    entry.actionId === actionId && (!screenId || entry.screenId === screenId),
  ) ?? ACCOUNTANT_ACTION_QUESTION_MAP.find((entry) => entry.actionId === actionId);
  return action
    ? {
      ...action,
      requiredContext: [...action.requiredContext],
      allowedSources: [...action.allowedSources],
    }
    : null;
}
