export const ACCOUNTANT_ROLE_POLICY = {
  role: "accountant",
  canSee: [
    "invoices_assigned_to_accounting",
    "acts_linked_to_invoices",
    "payments_for_accounting_scope",
    "linked_procurement_requests",
    "linked_supplier_offers",
    "linked_objects_works_materials",
    "estimate_lines_linked_to_invoice_or_act",
    "project_documents_linked_to_finance_basis",
    "primary_documents",
    "approval_status",
    "redacted_cashflow_slice",
    "debtor_creditor_summary",
    "chart_of_accounts_when_configured",
    "country_tax_profile_when_configured",
  ],
  cannotSee: [
    "security_events",
    "role_permissions",
    "runtime_debug",
    "service_role",
    "raw_provider_payload",
    "env_secrets",
    "unrelated_payroll",
    "unrelated_supplier_margin",
    "unrelated_commercial_data",
  ],
  directPaymentAllowed: false,
  directPostingAllowed: false,
  directInvoiceMutationAllowed: false,
  autoApprovalAllowed: false,
  approvalBypassAllowed: false,
  dbWritesFromAiAnswerAllowed: false,
  fakeInvoicesAllowed: false,
  fakeActsAllowed: false,
  fakePaymentsAllowed: false,
  fakeDocumentsAllowed: false,
  countryTaxClaimRequiresSource: true,
  chartOfAccountsClaimRequiresSource: true,
} as const;

export const accountantRolePolicy = ACCOUNTANT_ROLE_POLICY;
