import { Platform, StyleSheet } from 'react-native';

export const ds = StyleSheet.create({
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 4,
    elevation: 2,
  },
  cardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
    flex: 1,
    marginRight: 8,
  },
  cardMeta: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '600',
    marginBottom: 2,
  },
  cardMeta2: {
    fontSize: 11,
    color: '#94A3B8',
    fontWeight: '600',
  },
  cardPrice: {
    fontSize: 13,
    color: '#16A34A',
    fontWeight: '800',
    marginTop: 4,
  },
  cardDate: {
    fontSize: 11,
    color: '#CBD5E1',
    marginTop: 4,
    fontWeight: '600',
  },
  badge: {
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '800',
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 16,
    gap: 8,
  },
  filterBtn: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: '#F1F5F9',
    marginRight: 4,
    marginBottom: 4,
  },
  filterBtnActive: {
    backgroundColor: '#0F172A',
  },
  filterText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748B',
  },
  filterTextActive: {
    color: '#FFFFFF',
  },
  emptyText: {
    color: '#94A3B8',
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 32,
    fontSize: 14,
  },
  modalWrap: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    paddingTop: Platform.OS === 'ios' ? 56 : 24,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    gap: 8,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0F172A',
    flex: 1,
  },
  modalScroll: {
    flex: 1,
    paddingHorizontal: 16,
  },
  section: {
    fontSize: 12,
    fontWeight: '900',
    color: '#94A3B8',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginTop: 20,
    marginBottom: 8,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  detailLabel: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '700',
    flex: 1,
  },
  detailValue: {
    fontSize: 13,
    color: '#0F172A',
    fontWeight: '800',
    flex: 2,
    textAlign: 'right',
  },
  commentText: {
    fontSize: 13,
    color: '#334155',
    fontWeight: '600',
    backgroundColor: '#F1F5F9',
    borderRadius: 10,
    padding: 12,
    marginTop: 4,
  },
  actionBlock: {
    marginTop: 24,
    gap: 10,
  },
  btnApprove: {
    backgroundColor: '#16A34A',
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
  },
  btnApproveText: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 15,
  },
  btnReject: {
    backgroundColor: '#DC2626',
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
  },
  btnRejectText: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 15,
  },
  btnCancel: {
    backgroundColor: '#E2E8F0',
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
  },
  btnCancelText: {
    color: '#334155',
    fontWeight: '800',
    fontSize: 14,
  },
  btnDisabled: {
    opacity: 0.5,
  },
  rejectLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#475569',
    marginBottom: 6,
  },
  rejectInput: {
    backgroundColor: '#F1F5F9',
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: '#0F172A',
    minHeight: 80,
    textAlignVertical: 'top',
  },
  closeBtn: {
    margin: 16,
    padding: 15,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
  },
  closeBtnText: {
    color: '#475569',
    fontWeight: '800',
    fontSize: 15,
  },
});
