import type { AiIntent, AiIntentKnowledgeEntry } from "./aiKnowledgeTypes";

export const REQUIRED_AI_INTENTS: readonly AiIntent[] = [
  "find",
  "summarize",
  "compare",
  "explain",
  "draft",
  "prepare_report",
  "prepare_act",
  "prepare_request",
  "check_status",
  "find_risk",
  "submit_for_approval",
  "approve",
  "execute_approved",
];

export const AI_INTENT_REGISTRY: readonly AiIntentKnowledgeEntry[] = [
  {
    intent: "find",
    mapsToActionTypes: ["search_catalog"],
    defaultRisk: "safe_read",
    requiresApproval: false,
    canBeAnsweredWithoutTool: true,
    requiresEvidence: true,
    professionalAnswerSections: ["short conclusion", "what was found", "risk", "next action"],
    executionBoundary: "none",
  },
  {
    intent: "summarize",
    mapsToActionTypes: ["summarize_project", "summarize_finance", "summarize_warehouse"],
    defaultRisk: "safe_read",
    requiresApproval: false,
    canBeAnsweredWithoutTool: true,
    requiresEvidence: true,
    professionalAnswerSections: ["short conclusion", "what was found", "risk", "hidden data"],
    executionBoundary: "none",
  },
  {
    intent: "compare",
    mapsToActionTypes: ["compare_suppliers"],
    defaultRisk: "safe_read",
    requiresApproval: false,
    canBeAnsweredWithoutTool: true,
    requiresEvidence: true,
    professionalAnswerSections: ["options", "price or status", "risk", "approval boundary"],
    executionBoundary: "none",
  },
  {
    intent: "explain",
    mapsToActionTypes: ["explain_status"],
    defaultRisk: "safe_read",
    requiresApproval: false,
    canBeAnsweredWithoutTool: true,
    requiresEvidence: false,
    professionalAnswerSections: ["short conclusion", "status meaning", "next action"],
    executionBoundary: "none",
  },
  {
    intent: "draft",
    mapsToActionTypes: ["draft_request", "draft_report", "draft_act", "draft_supplier_message"],
    defaultRisk: "draft_only",
    requiresApproval: false,
    canBeAnsweredWithoutTool: true,
    requiresEvidence: true,
    professionalAnswerSections: ["draft summary", "missing data", "approval requirement"],
    executionBoundary: "draft_only",
  },
  {
    intent: "prepare_report",
    mapsToActionTypes: ["draft_report"],
    defaultRisk: "draft_only",
    requiresApproval: false,
    canBeAnsweredWithoutTool: true,
    requiresEvidence: true,
    professionalAnswerSections: ["object or scope", "work done", "open items", "risk"],
    executionBoundary: "draft_only",
  },
  {
    intent: "prepare_act",
    mapsToActionTypes: ["draft_act"],
    defaultRisk: "draft_only",
    requiresApproval: false,
    canBeAnsweredWithoutTool: true,
    requiresEvidence: true,
    professionalAnswerSections: ["own work", "document data", "missing evidence", "approval requirement"],
    executionBoundary: "draft_only",
  },
  {
    intent: "prepare_request",
    mapsToActionTypes: ["draft_request"],
    defaultRisk: "draft_only",
    requiresApproval: false,
    canBeAnsweredWithoutTool: true,
    requiresEvidence: true,
    professionalAnswerSections: ["materials", "quantity", "object", "approval next step"],
    executionBoundary: "draft_only",
  },
  {
    intent: "check_status",
    mapsToActionTypes: ["explain_status"],
    defaultRisk: "safe_read",
    requiresApproval: false,
    canBeAnsweredWithoutTool: true,
    requiresEvidence: true,
    professionalAnswerSections: ["status", "reason", "next action", "hidden data"],
    executionBoundary: "none",
  },
  {
    intent: "find_risk",
    mapsToActionTypes: ["summarize_project", "summarize_finance", "summarize_warehouse", "compare_suppliers"],
    defaultRisk: "safe_read",
    requiresApproval: false,
    canBeAnsweredWithoutTool: true,
    requiresEvidence: true,
    professionalAnswerSections: ["risk", "evidence refs", "next action", "approval boundary"],
    executionBoundary: "none",
  },
  {
    intent: "submit_for_approval",
    mapsToActionTypes: ["submit_request", "confirm_supplier", "create_order", "send_document", "change_payment_status", "change_warehouse_status"],
    defaultRisk: "approval_required",
    requiresApproval: true,
    canBeAnsweredWithoutTool: true,
    requiresEvidence: true,
    professionalAnswerSections: ["approval summary", "redacted payload", "risk", "approver required"],
    executionBoundary: "aiApprovalGate",
  },
  {
    intent: "approve",
    mapsToActionTypes: ["confirm_supplier", "create_order", "change_payment_status", "send_document"],
    defaultRisk: "approval_required",
    requiresApproval: true,
    canBeAnsweredWithoutTool: false,
    requiresEvidence: true,
    professionalAnswerSections: ["approval target", "risk", "audit", "explicit confirmation"],
    executionBoundary: "aiApprovalGate",
  },
  {
    intent: "execute_approved",
    mapsToActionTypes: ["submit_request", "confirm_supplier", "create_order", "change_warehouse_status", "send_document", "change_payment_status"],
    defaultRisk: "approval_required",
    requiresApproval: true,
    canBeAnsweredWithoutTool: false,
    requiresEvidence: true,
    professionalAnswerSections: ["approved action", "idempotency key", "audit event", "execution gate"],
    executionBoundary: "aiApprovalGate",
  },
];

export function getAiIntentKnowledge(intent: AiIntent): AiIntentKnowledgeEntry | null {
  return AI_INTENT_REGISTRY.find((entry) => entry.intent === intent) ?? null;
}

export function listAiIntentKnowledge(): AiIntentKnowledgeEntry[] {
  return [...AI_INTENT_REGISTRY];
}
