import type { AiScreenKnowledgeEntry } from "./aiKnowledgeTypes";

export const REQUIRED_AI_SCREEN_IDS: readonly string[] = [
  "director.dashboard",
  "director.reports_modal",
  "buyer.main",
  "buyer.subcontracts",
  "market.home",
  "accountant.main",
  "foreman.main",
  "foreman.ai.quick_modal",
  "foreman.subcontract",
  "contractor.main",
  "office.hub",
  "map.main",
  "chat.main",
  "reports.modal",
  "warehouse.main",
];

export const AI_SCREEN_KNOWLEDGE_REGISTRY: readonly AiScreenKnowledgeEntry[] = [
  {
    screenId: "director.dashboard",
    domain: "control",
    title: "Director dashboard",
    availableEntities: ["project", "request", "supplier", "warehouse_item", "payment", "company_debt", "report", "pdf_document", "subcontract"],
    allowedIntents: ["find", "summarize", "compare", "explain", "check_status", "find_risk", "draft", "prepare_report", "submit_for_approval", "approve", "execute_approved"],
    documentSources: ["director_reports", "finance_documents", "request_documents", "pdf_exports"],
    reportSources: ["director_reports", "ai_reports"],
    pdfSources: ["pdf_exports", "finance_documents"],
    defaultQuestions: ["What needs attention across finance, requests, warehouse, suppliers, and reports?", "Which high-risk action needs approval?"],
    roleNotes: { director: "Full-domain knowledge; high-risk execution still requires explicit approval and audit.", control: "Full-domain knowledge; high-risk execution still requires explicit approval and audit." },
    contextPolicy: "director_full",
  },
  {
    screenId: "director.reports_modal",
    domain: "reports",
    title: "Director reports modal",
    availableEntities: ["report", "pdf_document", "project", "request", "payment", "warehouse_item"],
    allowedIntents: ["find", "summarize", "explain", "prepare_report", "find_risk"],
    documentSources: ["director_reports", "pdf_exports"],
    reportSources: ["director_reports"],
    pdfSources: ["pdf_exports"],
    defaultQuestions: ["Which report should I open for this management question?"],
    roleNotes: { director: "Can summarize cross-domain reports with evidence references." },
    contextPolicy: "director_full",
  },
  {
    screenId: "buyer.main",
    domain: "procurement",
    title: "Buyer main",
    availableEntities: ["request", "supplier", "material", "pdf_document"],
    allowedIntents: ["find", "summarize", "compare", "explain", "draft", "prepare_request", "check_status", "find_risk", "submit_for_approval"],
    documentSources: ["request_documents", "pdf_exports", "ai_reports"],
    reportSources: ["ai_reports"],
    pdfSources: ["pdf_exports"],
    defaultQuestions: ["Find suppliers and prepare a request draft.", "Compare supplier risk before approval."],
    roleNotes: { buyer: "Procurement and marketplace context only; no accounting postings or raw finance." },
    contextPolicy: "role_scoped",
  },
  {
    screenId: "buyer.subcontracts",
    domain: "subcontracts",
    title: "Buyer subcontracts",
    availableEntities: ["subcontract", "contractor", "act", "pdf_document"],
    allowedIntents: ["find", "summarize", "compare", "explain", "draft", "prepare_act", "check_status", "find_risk", "submit_for_approval"],
    documentSources: ["subcontract_documents", "acts", "pdf_exports"],
    reportSources: ["ai_reports"],
    pdfSources: ["pdf_exports"],
    defaultQuestions: ["Which subcontract document or act is relevant to procurement?"],
    roleNotes: { buyer: "Can compare procurement-facing subcontract data, not internal finance final decisions." },
    contextPolicy: "role_scoped",
  },
  {
    screenId: "market.home",
    domain: "marketplace",
    title: "Market home",
    availableEntities: ["supplier", "material", "map_object"],
    allowedIntents: ["find", "summarize", "compare", "explain", "find_risk"],
    documentSources: ["ai_reports"],
    reportSources: ["ai_reports"],
    pdfSources: [],
    defaultQuestions: ["Find suppliers and compare price, schedule, availability, and risk."],
    roleNotes: { buyer: "Marketplace evidence is redacted and cannot confirm a supplier without approval." },
    contextPolicy: "redacted_marketplace",
  },
  {
    screenId: "accountant.main",
    domain: "finance",
    title: "Accountant main",
    availableEntities: ["payment", "company_debt", "accounting_posting", "act", "pdf_document", "report"],
    allowedIntents: ["find", "summarize", "explain", "draft", "check_status", "find_risk", "submit_for_approval"],
    documentSources: ["finance_documents", "acts", "pdf_exports", "ai_reports"],
    reportSources: ["director_reports", "ai_reports"],
    pdfSources: ["finance_documents", "pdf_exports"],
    defaultQuestions: ["Show debts, payment status, documents, and risk without changing payment state."],
    roleNotes: { accountant: "Finance/document/report context; payment or status mutation requires approval." },
    contextPolicy: "redacted_finance",
  },
  {
    screenId: "foreman.main",
    domain: "projects",
    title: "Foreman main",
    availableEntities: ["project", "request", "material", "report", "act", "subcontract"],
    allowedIntents: ["find", "summarize", "explain", "draft", "prepare_report", "prepare_act", "prepare_request", "check_status", "find_risk", "submit_for_approval"],
    documentSources: ["foreman_daily_reports", "request_documents", "acts", "pdf_exports"],
    reportSources: ["foreman_daily_reports"],
    pdfSources: ["pdf_exports"],
    defaultQuestions: ["What needs to be closed on my object?", "Prepare a daily report, act, or material request draft."],
    roleNotes: { foreman: "Project-scoped reports, acts, requests, and materials only; no full company finance." },
    contextPolicy: "role_scoped",
  },
  {
    screenId: "foreman.ai.quick_modal",
    domain: "procurement",
    title: "Foreman AI quick modal",
    availableEntities: ["project", "request", "material", "supplier"],
    allowedIntents: ["find", "explain", "draft", "prepare_request", "check_status", "submit_for_approval"],
    documentSources: ["request_documents", "ai_reports"],
    reportSources: ["ai_reports"],
    pdfSources: [],
    defaultQuestions: ["Prepare a material request draft for my object."],
    roleNotes: { foreman: "Draft request only; final submit goes through approval." },
    contextPolicy: "role_scoped",
  },
  {
    screenId: "foreman.subcontract",
    domain: "subcontracts",
    title: "Foreman subcontract",
    availableEntities: ["subcontract", "contractor", "act", "report", "pdf_document"],
    allowedIntents: ["find", "summarize", "explain", "draft", "prepare_act", "prepare_report", "check_status", "find_risk", "submit_for_approval"],
    documentSources: ["subcontract_documents", "acts", "pdf_exports"],
    reportSources: ["foreman_daily_reports"],
    pdfSources: ["pdf_exports"],
    defaultQuestions: ["Which subcontract acts or reports need to be closed?"],
    roleNotes: { foreman: "Own project/subcontract scope; approval required for sending documents." },
    contextPolicy: "role_scoped",
  },
  {
    screenId: "contractor.main",
    domain: "contractors",
    title: "Contractor main",
    availableEntities: ["subcontract", "contractor", "act", "report", "pdf_document"],
    allowedIntents: ["find", "summarize", "explain", "draft", "prepare_act", "prepare_report", "check_status", "submit_for_approval"],
    documentSources: ["subcontract_documents", "acts", "pdf_exports"],
    reportSources: ["foreman_daily_reports"],
    pdfSources: ["pdf_exports"],
    defaultQuestions: ["What do I need to close in my own tasks, acts, and documents?"],
    roleNotes: { contractor: "Own records only; no internal finance, procurement, or other contractor data." },
    contextPolicy: "own_records_only",
  },
  {
    screenId: "office.hub",
    domain: "office",
    title: "Office hub",
    availableEntities: ["office_member", "invite", "pdf_document"],
    allowedIntents: ["find", "summarize", "explain", "draft", "submit_for_approval"],
    documentSources: ["request_documents", "pdf_exports"],
    reportSources: [],
    pdfSources: ["pdf_exports"],
    defaultQuestions: ["Which office member, invite, or document route applies?"],
    roleNotes: { office: "Office member and invite context only unless another role grants more." },
    contextPolicy: "role_scoped",
  },
  {
    screenId: "map.main",
    domain: "map",
    title: "Map",
    availableEntities: ["map_object", "supplier", "project", "material"],
    allowedIntents: ["find", "summarize", "compare", "explain", "find_risk"],
    documentSources: ["ai_reports"],
    reportSources: ["ai_reports"],
    pdfSources: [],
    defaultQuestions: ["What should I inspect on the supplier or object map?"],
    roleNotes: { buyer: "Map context is redacted; no final supplier decision without approval." },
    contextPolicy: "redacted_marketplace",
  },
  {
    screenId: "chat.main",
    domain: "chat",
    title: "Chat",
    availableEntities: ["chat_thread", "request", "supplier", "pdf_document"],
    allowedIntents: ["find", "summarize", "explain", "draft", "submit_for_approval"],
    documentSources: ["chat_attachments", "ai_reports"],
    reportSources: ["ai_reports"],
    pdfSources: [],
    defaultQuestions: ["Draft a safe message or explain next steps without executing them."],
    roleNotes: { contractor: "Chat still follows own-records-only restrictions." },
    contextPolicy: "role_scoped",
  },
  {
    screenId: "reports.modal",
    domain: "reports",
    title: "Reports modal",
    availableEntities: ["report", "pdf_document", "project", "request", "warehouse_item", "payment"],
    allowedIntents: ["find", "summarize", "explain", "prepare_report", "find_risk"],
    documentSources: ["director_reports", "foreman_daily_reports", "warehouse_documents", "finance_documents", "pdf_exports"],
    reportSources: ["director_reports", "foreman_daily_reports", "ai_reports"],
    pdfSources: ["pdf_exports"],
    defaultQuestions: ["Which report source answers this role-scoped question?"],
    roleNotes: { accountant: "Finance reports are available only to finance roles or director/control." },
    contextPolicy: "role_scoped",
  },
  {
    screenId: "warehouse.main",
    domain: "warehouse",
    title: "Warehouse main",
    availableEntities: ["warehouse_item", "stock_movement", "request", "material", "report", "pdf_document"],
    allowedIntents: ["find", "summarize", "explain", "draft", "prepare_request", "check_status", "find_risk", "submit_for_approval"],
    documentSources: ["warehouse_documents", "request_documents", "pdf_exports"],
    reportSources: ["ai_reports"],
    pdfSources: ["warehouse_documents", "pdf_exports"],
    defaultQuestions: ["What stock is low, what moved, and what request draft is needed?"],
    roleNotes: { warehouse: "Inventory and stock operations only; final stock mutation requires approval." },
    contextPolicy: "role_scoped",
    futureOrExistingRoute: false,
    actualSurface: "warehouse tab under the existing office/app route",
  },
];

export function getAiScreenKnowledge(screenId: string): AiScreenKnowledgeEntry | null {
  const normalized = String(screenId || "").trim();
  return AI_SCREEN_KNOWLEDGE_REGISTRY.find((entry) => entry.screenId === normalized) ?? null;
}

export function listAiScreenKnowledge(): AiScreenKnowledgeEntry[] {
  return [...AI_SCREEN_KNOWLEDGE_REGISTRY];
}
