import type { AiUserRole } from "../policy/aiRolePolicy";
import type {
  AiScreenRuntimeIntent,
  AiScreenRuntimeProducerName,
  AiScreenRuntimeRegistryEntry,
} from "./aiScreenRuntimeTypes";

const CONTROL_ROLES: readonly AiUserRole[] = ["director", "control"];
const OPERATIONS_ROLES: readonly AiUserRole[] = [
  "director",
  "control",
  "foreman",
  "buyer",
  "accountant",
  "warehouse",
  "contractor",
  "office",
  "admin",
];
const PROCUREMENT_ROLES: readonly AiUserRole[] = ["director", "control", "buyer"];
const MARKET_ROLES: readonly AiUserRole[] = ["director", "control", "buyer", "foreman"];
const FINANCE_ROLES: readonly AiUserRole[] = ["director", "control", "accountant"];
const FOREMAN_ROLES: readonly AiUserRole[] = ["director", "control", "foreman"];
const WAREHOUSE_ROLES: readonly AiUserRole[] = ["director", "control", "warehouse"];
const CONTRACTOR_ROLES: readonly AiUserRole[] = ["director", "control", "contractor"];
const OFFICE_ROLES: readonly AiUserRole[] = ["director", "control", "office", "admin"];

const READ_INTENTS: readonly AiScreenRuntimeIntent[] = ["read", "explain", "check_status", "navigate"];
const DRAFT_INTENTS: readonly AiScreenRuntimeIntent[] = [
  "read",
  "search",
  "compare",
  "explain",
  "draft",
  "prepare_request",
  "check_status",
  "find_risk",
  "submit_for_approval",
  "navigate",
];
const REPORT_INTENTS: readonly AiScreenRuntimeIntent[] = [
  "read",
  "search",
  "explain",
  "draft",
  "prepare_report",
  "prepare_act",
  "check_status",
  "find_risk",
  "submit_for_approval",
  "navigate",
];

export const AI_SCREEN_RUNTIME_REQUIRED_SCREEN_IDS = [
  "director.dashboard",
  "ai.command.center",
  "buyer.main",
  "market.home",
  "accountant.main",
  "foreman.main",
  "foreman.subcontract",
  "warehouse.main",
  "contractor.main",
  "office.hub",
  "map.main",
  "chat.main",
  "reports.modal",
  "documents.surface",
] as const;

function entry(params: Omit<AiScreenRuntimeRegistryEntry, "evidenceRequired" | "source">): AiScreenRuntimeRegistryEntry {
  return {
    ...params,
    evidenceRequired: true,
    source: "ai_cross_screen_runtime_registry_v1",
  };
}

export const AI_SCREEN_RUNTIME_REGISTRY: readonly AiScreenRuntimeRegistryEntry[] = [
  entry({
    screenId: "director.dashboard",
    domain: "control",
    mounted: "mounted",
    producerName: "directorControlProducer",
    allowedRoles: CONTROL_ROLES,
    entityTypes: ["finance", "request", "warehouse", "supplier", "report", "approval"],
    availableIntents: [...DRAFT_INTENTS, "approve"],
    blockedIntents: ["execute_approved"],
    cardType: "risk",
    cardTitle: "Director control runtime",
    cardSummary: "Cross-domain summary, risk analysis, reports, documents, and approval queue.",
    priority: "high",
    approvalRequired: true,
    maxCards: 2,
  }),
  entry({
    screenId: "ai.command.center",
    domain: "control",
    mounted: "mounted",
    producerName: "directorControlProducer",
    allowedRoles: OPERATIONS_ROLES,
    entityTypes: ["task", "evidence", "draft", "approval"],
    availableIntents: DRAFT_INTENTS,
    blockedIntents: ["approve", "execute_approved"],
    cardType: "task",
    cardTitle: "Command Center runtime",
    cardSummary: "Role-scoped AI cards, evidence, draft previews, and approval boundaries.",
    priority: "normal",
    approvalRequired: true,
    maxCards: 2,
  }),
  entry({
    screenId: "buyer.main",
    domain: "procurement",
    mounted: "mounted",
    producerName: "buyerProcurementProducer",
    allowedRoles: PROCUREMENT_ROLES,
    entityTypes: ["request", "material", "supplier", "marketplace"],
    availableIntents: DRAFT_INTENTS,
    blockedIntents: ["approve", "execute_approved"],
    cardType: "procurement",
    cardTitle: "Buyer procurement runtime",
    cardSummary: "Requests, materials, marketplace checks, supplier comparison, and draft request boundary.",
    priority: "normal",
    approvalRequired: true,
    maxCards: 2,
  }),
  entry({
    screenId: "market.home",
    domain: "marketplace",
    mounted: "mounted",
    producerName: "buyerProcurementProducer",
    allowedRoles: MARKET_ROLES,
    entityTypes: ["supplier", "material", "catalog", "map_object"],
    availableIntents: ["read", "search", "compare", "explain", "find_risk", "navigate"],
    blockedIntents: ["submit_for_approval", "approve", "execute_approved"],
    cardType: "procurement",
    cardTitle: "Marketplace runtime",
    cardSummary: "Internal marketplace search and supplier comparison; no supplier confirmation.",
    priority: "normal",
    approvalRequired: false,
    maxCards: 2,
  }),
  entry({
    screenId: "accountant.main",
    domain: "finance",
    mounted: "mounted",
    producerName: "accountantFinanceProducer",
    allowedRoles: FINANCE_ROLES,
    entityTypes: ["debt", "payment", "document", "act", "report"],
    availableIntents: REPORT_INTENTS,
    blockedIntents: ["approve", "execute_approved"],
    cardType: "finance",
    cardTitle: "Accountant finance runtime",
    cardSummary: "Debts, payments, closing documents, acts, and finance risk without payment mutation.",
    priority: "high",
    approvalRequired: true,
    maxCards: 2,
  }),
  entry({
    screenId: "foreman.main",
    domain: "projects",
    mounted: "mounted",
    producerName: "foremanObjectProducer",
    allowedRoles: FOREMAN_ROLES,
    entityTypes: ["project", "material", "request", "act", "daily_report"],
    availableIntents: REPORT_INTENTS,
    blockedIntents: ["approve", "execute_approved"],
    cardType: "task",
    cardTitle: "Foreman object runtime",
    cardSummary: "Object status, materials, requests, acts, subcontractors, and daily report draft.",
    priority: "normal",
    approvalRequired: true,
    maxCards: 2,
  }),
  entry({
    screenId: "foreman.subcontract",
    domain: "subcontracts",
    mounted: "mounted",
    producerName: "foremanObjectProducer",
    allowedRoles: FOREMAN_ROLES,
    entityTypes: ["subcontract", "contractor", "act", "report", "document"],
    availableIntents: REPORT_INTENTS,
    blockedIntents: ["approve", "execute_approved"],
    cardType: "contractor",
    cardTitle: "Foreman subcontract runtime",
    cardSummary: "Subcontract acts, reports, contractor status, and approval boundary.",
    priority: "normal",
    approvalRequired: true,
    maxCards: 2,
  }),
  entry({
    screenId: "warehouse.main",
    domain: "warehouse",
    mounted: "mounted",
    producerName: "warehouseStatusProducer",
    allowedRoles: WAREHOUSE_ROLES,
    entityTypes: ["stock", "movement", "incoming", "outgoing", "request"],
    availableIntents: ["read", "search", "explain", "draft", "prepare_request", "check_status", "find_risk", "submit_for_approval", "navigate"],
    blockedIntents: ["compare", "approve", "execute_approved"],
    cardType: "warehouse",
    cardTitle: "Warehouse runtime",
    cardSummary: "Stock, movements, low-stock analysis, and draft request suggestions without stock mutation.",
    priority: "high",
    approvalRequired: true,
    maxCards: 2,
  }),
  entry({
    screenId: "contractor.main",
    domain: "subcontracts",
    mounted: "mounted",
    producerName: "contractorOwnWorkProducer",
    allowedRoles: CONTRACTOR_ROLES,
    entityTypes: ["own_task", "own_act", "own_document", "own_report"],
    availableIntents: ["read", "explain", "draft", "prepare_report", "prepare_act", "check_status", "submit_for_approval", "navigate"],
    blockedIntents: ["search", "compare", "approve", "execute_approved"],
    cardType: "contractor",
    cardTitle: "Contractor own-work runtime",
    cardSummary: "Own tasks, own acts, own documents, and own report draft boundary.",
    priority: "normal",
    approvalRequired: true,
    maxCards: 1,
  }),
  entry({
    screenId: "office.hub",
    domain: "control",
    mounted: "mounted",
    producerName: "officeAccessProducer",
    allowedRoles: OFFICE_ROLES,
    entityTypes: ["member", "invite", "access", "document"],
    availableIntents: ["read", "explain", "draft", "submit_for_approval", "navigate"],
    blockedIntents: ["compare", "approve", "execute_approved"],
    cardType: "document",
    cardTitle: "Office access runtime",
    cardSummary: "Members, invites, access requests, and documents with no silent permission mutation.",
    priority: "normal",
    approvalRequired: true,
    maxCards: 1,
  }),
  entry({
    screenId: "map.main",
    domain: "map",
    mounted: "mounted",
    producerName: "mapObjectProducer",
    allowedRoles: MARKET_ROLES,
    entityTypes: ["object", "location", "supplier", "material", "risk"],
    availableIntents: READ_INTENTS,
    blockedIntents: ["compare", "draft", "submit_for_approval", "approve", "execute_approved"],
    cardType: "map",
    cardTitle: "Map object runtime",
    cardSummary: "Objects, locations, object risks, linked requests, and linked materials.",
    priority: "normal",
    approvalRequired: false,
    maxCards: 1,
  }),
  entry({
    screenId: "chat.main",
    domain: "chat",
    mounted: "mounted",
    producerName: "chatContextProducer",
    allowedRoles: OPERATIONS_ROLES,
    entityTypes: ["thread", "participant", "request", "document", "next_action"],
    availableIntents: ["read", "explain", "draft", "submit_for_approval", "navigate"],
    blockedIntents: ["compare", "approve", "execute_approved"],
    cardType: "chat",
    cardTitle: "Chat context runtime",
    cardSummary: "Conversation context, linked requests, documents, participants, and next actions.",
    priority: "normal",
    approvalRequired: true,
    maxCards: 1,
  }),
  entry({
    screenId: "reports.modal",
    domain: "reports",
    mounted: "mounted",
    producerName: "reportsDocumentsProducer",
    allowedRoles: OPERATIONS_ROLES,
    entityTypes: ["report", "document", "pdf", "project", "request"],
    availableIntents: ["read", "search", "explain", "draft", "prepare_report", "find_risk", "navigate"],
    blockedIntents: ["approve", "execute_approved"],
    cardType: "document",
    cardTitle: "Reports runtime",
    cardSummary: "Role-scoped reports, documents, PDFs, and report draft previews.",
    priority: "normal",
    approvalRequired: true,
    maxCards: 2,
  }),
  entry({
    screenId: "documents.surface",
    domain: "documents",
    mounted: "future_or_not_mounted",
    actualSurface: "documents are currently exposed through reports.modal and role-specific document surfaces",
    producerName: "reportsDocumentsProducer",
    allowedRoles: OPERATIONS_ROLES,
    entityTypes: ["document", "pdf", "act", "attachment"],
    availableIntents: ["read", "search", "explain", "draft", "submit_for_approval"],
    blockedIntents: ["approve", "execute_approved"],
    cardType: "document",
    cardTitle: "Documents runtime",
    cardSummary: "Standalone documents surface is not mounted; use role-scoped existing document surfaces.",
    priority: "low",
    approvalRequired: true,
    maxCards: 1,
  }),
] as const;

export const AI_SCREEN_RUNTIME_PRODUCER_NAMES: readonly AiScreenRuntimeProducerName[] = [
  "directorControlProducer",
  "accountantFinanceProducer",
  "buyerProcurementProducer",
  "foremanObjectProducer",
  "warehouseStatusProducer",
  "contractorOwnWorkProducer",
  "officeAccessProducer",
  "mapObjectProducer",
  "chatContextProducer",
  "reportsDocumentsProducer",
] as const;

export function getAiScreenRuntimeEntry(screenId: string): AiScreenRuntimeRegistryEntry | null {
  const normalized = String(screenId || "").trim();
  return AI_SCREEN_RUNTIME_REGISTRY.find((entry) => entry.screenId === normalized) ?? null;
}

export function listAiScreenRuntimeEntries(): AiScreenRuntimeRegistryEntry[] {
  return [...AI_SCREEN_RUNTIME_REGISTRY];
}
