import { Platform, StyleSheet } from "react-native";

const UI = {
  bg: "#F8FAFC",
  text: "#0F172A",
  sub: "#64748B",
  border: "#E2E8F0",
  accent: "#0EA5E9",
  btnTake: "#16A34A",
};

const WEB_SHADOW_SOFT = { boxShadow: "0px 3px 6px rgba(15,23,42,0.06)" } as const;
const WEB_SHADOW_CARD = { boxShadow: "0px 2px 6px rgba(15,23,42,0.06)" } as const;
const NATIVE_SHADOW_SOFT = {
  shadowColor: "#0f172a",
  shadowOpacity: 0.06,
  shadowRadius: 6,
  shadowOffset: { width: 0, height: 3 },
} as const;
const NATIVE_SHADOW_CARD = {
  shadowColor: "#0f172a",
  shadowOpacity: 0.06,
  shadowRadius: 6,
  shadowOffset: { width: 0, height: 2 },
} as const;
const MODAL_CARD_BG = "#fff";
const MODAL_BORDER = "#e2e8f0";
const DIVIDER = "#f1f5f9";

export const styles = StyleSheet.create({
  container: { flex: 1, paddingHorizontal: 16, paddingTop: 10, paddingBottom: 30, backgroundColor: UI.bg },
  homeContainer: {
    backgroundColor: "#071124",
  },
  homeGlow: {
    position: "absolute",
    left: -80,
    right: -80,
    top: -120,
    height: 260,
    backgroundColor: "rgba(34,197,94,0.10)",
    borderBottomLeftRadius: 260,
    borderBottomRightRadius: 260,
    opacity: 0.9,
  },
  center: { flex: 1, alignItems: "center", justifyContent: "center" },

  title: { fontSize: 20, fontWeight: "800", color: UI.text, marginBottom: 12 },

  input: {
    marginTop: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: UI.border,
    borderRadius: 10,
    backgroundColor: "#fff",
  },

  activateBtn: {
    marginTop: 20,
    backgroundColor: UI.accent,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: "center",
  },
  activateText: { color: "#fff", fontWeight: "700" },

  header: { paddingBottom: 6, borderBottomWidth: 1, borderColor: UI.border },
  headerTitle: { fontSize: 22, fontWeight: "600", color: UI.text },
  homeHeader: {
    marginHorizontal: -16,
    marginTop: -16,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    backgroundColor: "#0B1324",
  },
  homeHeaderTitle: {
    color: "#F8FAFC",
    fontSize: 22,
    fontWeight: "600",
    lineHeight: 28,
  },
  subcontractHeaderCard: {
    position: "relative",
    minHeight: 72,
    justifyContent: "center",
    paddingRight: 52,
  },
  subcontractHeaderTitle: {
    fontSize: 30,
    lineHeight: 34,
    paddingRight: 12,
  },
  subcontractHeaderSubtitle: {
    color: "#94A3B8",
    marginTop: 4,
    fontSize: 18,
    lineHeight: 22,
    paddingRight: 12,
  },
  subcontractHeaderClose: {
    position: "absolute",
    top: 10,
    right: 0,
    backgroundColor: "rgba(255,255,255,0.12)",
  },

  segmentWrapper: { marginTop: 14 },
  segmentTrack: {
    backgroundColor: "#E2E8F0",
    borderRadius: 999,
    padding: 3,
    overflow: "hidden",
  },
  segmentRow: { flexDirection: "row" },
  segmentTab: { flex: 1, paddingVertical: 10, alignItems: "center" },
  segmentText: { fontWeight: "700", color: "#64748B" },
  segmentActive: { color: "#000" },
  segmentThumb: {
    position: "absolute",
    top: 3,
    bottom: 3,
    borderRadius: 999,
    backgroundColor: "#fff",
    elevation: 2,
  },
  modeHomeWrap: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    gap: 14,
    paddingTop: 56,
  },
  modeBtn: {
    width: "100%",
    maxWidth: 370,
    height: 72,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#121A2A",
    ...(Platform.OS === "web" ? WEB_SHADOW_SOFT : NATIVE_SHADOW_SOFT),
    elevation: 2,
  },
  modeBtnText: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "600",
    color: "#F8FAFC",
  },
  modeHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  modeHeaderTitle: {
    fontSize: 22,
    fontWeight: "600",
    color: "#F8FAFC",
  },
  modeHeaderClose: {
    width: 38,
    height: 38,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  modeHeaderCloseText: {
    fontSize: 24,
    lineHeight: 24,
    fontWeight: "600",
    color: "#F8FAFC",
  },

  card: {
    marginTop: 10,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: "#fff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: UI.border,
  },
  cardSeparated: {
    marginBottom: 12,
    ...(Platform.OS === "web" ? WEB_SHADOW_CARD : NATIVE_SHADOW_CARD),
    elevation: 1,
  },
  cardDark: {
    backgroundColor: "#0F172A",
    borderColor: "rgba(255,255,255,0.14)",
  },
  cardTitle: { fontSize: 16, fontWeight: "600" },
  cardCompany: { fontSize: 20, fontWeight: "600", color: UI.text },
  cardWork: { fontSize: 13, color: "#0F172A", marginTop: 4 },
  cardObject: { fontSize: 13, color: UI.sub, marginTop: 4 },
  cardCompanyDark: { color: "#F8FAFC" },
  cardWorkDark: { color: "rgba(248,250,252,0.85)" },
  cardObjectDark: { color: "rgba(226,232,240,0.9)" },
  cardMetaDark: { fontSize: 13, color: "rgba(226,232,240,0.9)", marginTop: 4, opacity: 0.7 },
  cardStatsRow: { flexDirection: "row", justifyContent: "space-between", gap: 8, marginTop: 6 },
  cardProgressTrack: {
    height: 6,
    borderRadius: 999,
    backgroundColor: "#E2E8F0",
    overflow: "hidden",
    marginTop: 8,
  },
  cardProgressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#0EA5E9",
  },
  cardMeta: { fontSize: 13, color: UI.sub, marginTop: 4, opacity: 0.7 },
  workCardTap: {
    borderRadius: 10,
    padding: 2,
  },
  workCardTapPressed: {
    opacity: 0.72,
  },

  takeBtn: {
    marginTop: 10,
    backgroundColor: UI.btnTake,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
  },
  takeText: { color: "#fff", fontWeight: "700" },
  workModalInfoCard: {
    backgroundColor: MODAL_CARD_BG,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: MODAL_BORDER,
    marginTop: 8,
    marginBottom: 8,
  },
  workModalInfoText: { fontSize: 11, color: "#334155" },
  workModalWorkCard: {
    backgroundColor: MODAL_CARD_BG,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: MODAL_BORDER,
  },
  workModalWorkTitle: {
    fontWeight: "800",
    fontSize: 15,
    marginBottom: 4,
  },
  workModalObjectText: { color: "#475569", marginBottom: 4 },
  workModalObjectTextError: { color: "#dc2626" },
  workModalObjectLabel: { fontWeight: "600" },
  workModalActions: { marginTop: 8, marginBottom: 8, gap: 8 },
  workModalMainActionBtn: {
    width: "100%",
    borderRadius: 10,
    paddingVertical: 10,
    backgroundColor: "#16a34a",
    alignItems: "center",
  },
  workModalMainActionBtnDisabled: {
    backgroundColor: "#94a3b8",
  },
  workModalSecondaryActionBtn: {
    width: "100%",
    borderRadius: 10,
    paddingVertical: 10,
    backgroundColor: "#0ea5e9",
    alignItems: "center",
  },
  workModalActionText: { color: "#fff", fontWeight: "700" },
  workModalHintText: { color: "#0369a1", fontSize: 12, fontWeight: "600" },
  workModalSectionBtn: {
    marginTop: 8,
    marginBottom: 8,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: MODAL_BORDER,
    backgroundColor: MODAL_CARD_BG,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  workModalSectionBtnTop12: { marginTop: 12 },
  workModalSectionTitle: { fontWeight: "700", color: "#334155" },
  workModalListCard: {
    marginBottom: 8,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: MODAL_BORDER,
    backgroundColor: MODAL_CARD_BG,
    gap: 6,
  },
  workModalEmptyText: { color: "#94a3b8", fontSize: 12 },
  workModalRowDivider: {
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderColor: DIVIDER,
  },
  workModalLogDateText: { fontWeight: "600", color: "#0f172a" },
  workModalLogStageText: { color: "#64748b", fontSize: 12 },
  workModalLogCommentText: { color: "#94a3b8", fontSize: 12 },
  workModalInlineBtn: {
    alignSelf: "flex-start",
    marginTop: 4,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: MODAL_BORDER,
  },
  workModalInlineBtnText: { fontSize: 12 },
  workModalLinkedReqCard: {
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: MODAL_BORDER,
    borderRadius: 10,
    padding: 10,
    marginBottom: 6,
  },
  workModalLinkedReqTitle: { fontWeight: "700", color: "#0f172a" },
  workModalLinkedReqMeta: { marginTop: 2, fontSize: 12, color: "#64748b" },
  workModalHintMeta: { marginTop: 4 },
  workModalIssuedCard: {
    backgroundColor: MODAL_CARD_BG,
    borderWidth: 1,
    borderColor: MODAL_BORDER,
    borderRadius: 10,
    padding: 10,
    marginBottom: 6,
  },
  workModalIssuedTitle: { fontWeight: "700", color: "#0f172a" },
  workModalIssuedMeta: { fontSize: 12, color: "#64748b", marginTop: 2 },
  searchItemRow: {
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderColor: DIVIDER,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  flex1: { flex: 1 },
  searchItemName: { fontWeight: "600", color: "#0f172a" },
  searchItemUom: { color: "#64748b", marginTop: 2 },
  searchItemStockText: { fontSize: 12, fontWeight: "700" },
  stageItemRow: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderColor: DIVIDER,
  },
  stageItemName: { fontWeight: "600" },
  stageItemCode: { color: "#9ca3af", fontSize: 12 },
});
