import { Platform, StyleSheet } from "react-native";
import { PROFILE_UI } from "./profile.helpers";

export const profileStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: PROFILE_UI.bg,
  },
  scrollFill: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  flexOne: {
    flex: 1,
  },
  center: {
    flex: 1,
    backgroundColor: PROFILE_UI.bg,
    alignItems: "center",
    justifyContent: "center",
  },
  centerText: {
    marginTop: 8,
    color: PROFILE_UI.sub,
    fontSize: 13,
  },
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    color: PROFILE_UI.sub,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 6,
  },
  sectionCard: {
    backgroundColor: PROFILE_UI.card,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
  },
  profileHeaderCard: {
    backgroundColor: PROFILE_UI.card,
    borderRadius: 26,
    paddingHorizontal: 20,
    paddingVertical: 24,
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
    alignItems: "center",
    marginBottom: 16,
  },
  profileHeaderAvatarWrap: {
    position: "relative",
    marginBottom: 14,
  },
  profileHeaderAvatar: {
    width: 104,
    height: 104,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  profileHeaderAvatarImage: {
    width: "100%",
    height: "100%",
  },
  profileHeaderAvatarText: {
    color: PROFILE_UI.text,
    fontSize: 34,
    fontWeight: "800",
  },
  profileHeaderBadge: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 32,
    height: 32,
    borderRadius: 999,
    backgroundColor: PROFILE_UI.cardSoft,
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
    alignItems: "center",
    justifyContent: "center",
  },
  profileHeaderName: {
    color: PROFILE_UI.text,
    fontSize: 22,
    fontWeight: "800",
    textAlign: "center",
  },
  profileHeaderRoleBadge: {
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 999,
  },
  profileHeaderRoleText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
  },
  profileHeaderSubtitle: {
    marginTop: 10,
    color: PROFILE_UI.sub,
    fontSize: 13,
    textAlign: "center",
  },
  profileTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 16,
  },
  profileTitleMeta: {
    flex: 1,
  },
  profileTitle: {
    color: PROFILE_UI.text,
    fontSize: 28,
    fontWeight: "800",
  },
  profileTitleSubtitle: {
    marginTop: 4,
    color: PROFILE_UI.sub,
    fontSize: 12,
    lineHeight: 18,
  },
  completionCard: {
    backgroundColor: PROFILE_UI.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  completionHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  completionTitle: {
    color: PROFILE_UI.text,
    fontSize: 15,
    fontWeight: "700",
  },
  completionSubtitle: {
    marginTop: 4,
    color: PROFILE_UI.sub,
    fontSize: 12,
    lineHeight: 18,
  },
  completionPercent: {
    color: PROFILE_UI.accent,
    fontSize: 20,
    fontWeight: "800",
  },
  completionBarTrack: {
    marginTop: 12,
    height: 8,
    borderRadius: 999,
    backgroundColor: PROFILE_UI.cardSoft,
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
    overflow: "hidden",
  },
  completionBarFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: PROFILE_UI.accent,
  },
  completionList: {
    marginTop: 12,
    gap: 8,
  },
  completionItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  completionItemText: {
    color: PROFILE_UI.sub,
    fontSize: 12,
  },
  completionItemTextDone: {
    color: PROFILE_UI.text,
  },
  completionAction: {
    alignSelf: "flex-start",
    marginTop: 14,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: PROFILE_UI.accent,
  },
  completionActionText: {
    color: "#0B1120",
    fontSize: 13,
    fontWeight: "700",
  },
  profileEditButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: PROFILE_UI.card,
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
  },
  profileEditButtonText: {
    color: PROFILE_UI.text,
    fontSize: 13,
    fontWeight: "700",
  },
  profileSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  profileSectionHeaderText: {
    color: PROFILE_UI.text,
    fontSize: 16,
    fontWeight: "700",
  },
  profileActionCard: {
    backgroundColor: PROFILE_UI.card,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  profileActionTextWrap: {
    flex: 1,
  },
  profileActionTitle: {
    color: PROFILE_UI.text,
    fontSize: 14,
    fontWeight: "700",
  },
  profileActionSubtitle: {
    marginTop: 4,
    color: PROFILE_UI.sub,
    fontSize: 12,
    lineHeight: 18,
  },
  profileHintCard: {
    marginTop: 10,
    backgroundColor: PROFILE_UI.card,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
  },
  profileHintTitle: {
    color: PROFILE_UI.sub,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  profileHintValue: {
    marginTop: 6,
    color: PROFILE_UI.text,
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: 1,
  },
  profileHintSubtitle: {
    marginTop: 6,
    color: PROFILE_UI.sub,
    fontSize: 12,
    lineHeight: 18,
  },
  profileMenuRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: PROFILE_UI.border,
  },
  profileMenuRowLast: {
    borderBottomWidth: 0,
    paddingBottom: 0,
  },
  profileMenuIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 999,
    backgroundColor: PROFILE_UI.accentSoft,
    borderWidth: 1,
    borderColor: PROFILE_UI.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  profileMenuIconWrapDanger: {
    backgroundColor: "rgba(239,68,68,0.12)",
    borderColor: "#7F1D1D",
  },
  profileMenuTextWrap: {
    flex: 1,
  },
  profileMenuTitle: {
    color: PROFILE_UI.text,
    fontSize: 13,
    fontWeight: "700",
  },
  profileMenuTitleDanger: {
    color: "#FCA5A5",
  },
  profileMenuSubtitle: {
    marginTop: 3,
    color: PROFILE_UI.sub,
    fontSize: 11,
    lineHeight: 17,
  },
  modeCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
    padding: 10,
    marginBottom: 8,
    backgroundColor: PROFILE_UI.cardSoft,
  },
  modeCardActive: {
    borderColor: PROFILE_UI.accent,
    backgroundColor: PROFILE_UI.accentSoft,
  },
  modeHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
    gap: 8,
  },
  modeCheck: {
    width: 18,
    height: 18,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: PROFILE_UI.sub,
    alignItems: "center",
    justifyContent: "center",
  },
  modeCheckActive: {
    borderColor: PROFILE_UI.accent,
    backgroundColor: PROFILE_UI.accent,
  },
  modeTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: PROFILE_UI.text,
  },
  modeText: {
    fontSize: 12,
    color: PROFILE_UI.sub,
  },
  savingHint: {
    marginTop: 4,
    fontSize: 11,
    color: PROFILE_UI.sub,
  },
  companyTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: PROFILE_UI.text,
    marginBottom: 4,
  },
  companyText: {
    fontSize: 12,
    color: PROFILE_UI.sub,
    marginBottom: 10,
  },
  companyBtn: {
    alignSelf: "flex-start",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: PROFILE_UI.accent,
  },
  companyBtnSecondary: {
    backgroundColor: PROFILE_UI.cardSoft,
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
  },
  companyBtnText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#0B1120",
  },
  companyBtnTextSecondary: {
    fontSize: 13,
    fontWeight: "600",
    color: PROFILE_UI.text,
  },
  companyActionsRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
  companyActionsRowTop: {
    marginTop: 10,
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  companySuccessBanner: {
    marginBottom: 10,
    padding: 10,
    borderRadius: 12,
    backgroundColor: PROFILE_UI.accentSoft,
    borderWidth: 1,
    borderColor: PROFILE_UI.accent,
  },
  companySuccessTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: PROFILE_UI.accent,
    marginBottom: 2,
  },
  companySuccessText: {
    fontSize: 12,
    color: PROFILE_UI.text,
  },
  chipHint: {
    marginTop: 4,
    fontSize: 11,
    color: PROFILE_UI.sub,
  },
  chipHintSpaced: {
    marginTop: 8,
  },
  modeSwitchRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 16,
  },
  modeSwitchBtn: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
    backgroundColor: PROFILE_UI.cardSoft,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  modeSwitchBtnActive: {
    borderColor: PROFILE_UI.accent,
    backgroundColor: PROFILE_UI.accentSoft,
  },
  modeSwitchText: {
    fontSize: 13,
    fontWeight: "600",
    color: PROFILE_UI.sub,
  },
  modeSwitchTextActive: {
    color: PROFILE_UI.accent,
  },
  modeSwitchSub: {
    marginTop: 4,
    fontSize: 11,
    color: PROFILE_UI.sub,
  },
  rowItem: {
    borderBottomWidth: 1,
    borderBottomColor: PROFILE_UI.border,
    paddingVertical: 8,
  },
  rowItemLast: {
    borderBottomWidth: 0,
    paddingBottom: 0,
  },
  rowLabel: {
    fontSize: 11,
    color: PROFILE_UI.sub,
  },
  rowValue: {
    marginTop: 2,
    fontSize: 13,
    color: PROFILE_UI.text,
  },
  catalogItemRow: {
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: PROFILE_UI.border,
  },
  catalogItemTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: PROFILE_UI.text,
  },
  catalogItemMeta: {
    marginTop: 2,
    fontSize: 11,
    color: PROFILE_UI.sub,
  },
  filterChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: PROFILE_UI.cardSoft,
    marginRight: 8,
  },
  filterChipActive: {
    backgroundColor: PROFILE_UI.accentSoft,
    borderColor: PROFILE_UI.accent,
  },
  filterChipText: {
    fontSize: 12,
    color: PROFILE_UI.sub,
  },
  filterChipTextActive: {
    color: PROFILE_UI.accent,
    fontWeight: "600",
  },
  profileFooterText: {
    marginTop: 4,
    marginBottom: 8,
    color: PROFILE_UI.sub,
    fontSize: 12,
    textAlign: "center",
  },
  inviteCodeBox: {
    marginTop: 12,
    marginBottom: 12,
    paddingVertical: 16,
    paddingHorizontal: 14,
    borderRadius: 16,
    backgroundColor: PROFILE_UI.cardSoft,
    borderWidth: 1,
    borderColor: PROFILE_UI.accent,
    alignItems: "center",
  },
  inviteCodeLabel: {
    fontSize: 12,
    color: PROFILE_UI.sub,
    marginBottom: 4,
  },
  inviteCodeValue: {
    fontSize: 24,
    fontWeight: "800",
    letterSpacing: 2,
    color: PROFILE_UI.accent,
    marginBottom: 4,
  },
  inviteCodeHint: {
    fontSize: 11,
    color: PROFILE_UI.sub,
  },
  roleChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 8,
  },
  roleChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
    backgroundColor: PROFILE_UI.cardSoft,
  },
  roleChipActive: {
    borderColor: PROFILE_UI.accent,
    backgroundColor: PROFILE_UI.accentSoft,
  },
  roleChipText: {
    fontSize: 12,
    color: PROFILE_UI.sub,
  },
  roleChipTextActive: {
    fontSize: 12,
    color: PROFILE_UI.accent,
    fontWeight: "600",
  },
  tabsRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
    marginBottom: 6,
  },
  tabChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
    backgroundColor: "#020617",
  },
  tabChipActive: {
    backgroundColor: PROFILE_UI.accentSoft,
    borderColor: PROFILE_UI.accent,
  },
  tabChipText: {
    fontSize: 12,
    color: "#ffffff",
  },
  tabChipTextActive: {
    color: PROFILE_UI.accent,
    fontWeight: "600",
  },
  shareRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
    marginBottom: 4,
    justifyContent: "center",
  },
  shareBtn: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  shareBtnPrimary: {
    borderColor: PROFILE_UI.accent,
    backgroundColor: PROFILE_UI.accentSoft,
  },
  shareBtnSecondary: {
    borderColor: PROFILE_UI.border,
    backgroundColor: PROFILE_UI.cardSoft,
  },
  shareBtnPrimaryText: {
    fontSize: 12,
    fontWeight: "600",
    color: PROFILE_UI.accent,
  },
  shareBtnSecondaryText: {
    fontSize: 12,
    fontWeight: "500",
    color: PROFILE_UI.sub,
  },
  wizardProgressOuter: {
    width: "100%",
    height: 6,
    borderRadius: 999,
    backgroundColor: PROFILE_UI.cardSoft,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
  },
  wizardProgressInner: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: PROFILE_UI.accent,
  },
  wizardStepTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: PROFILE_UI.text,
    marginTop: 10,
    marginBottom: 4,
  },
  wizardStepHint: {
    fontSize: 12,
    color: PROFILE_UI.sub,
    marginBottom: 10,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.55)",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  modalCard: {
    width: 420,
    maxWidth: "100%",
    borderRadius: 18,
    backgroundColor: PROFILE_UI.card,
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
    padding: 16,
    overflow: "hidden",
  },
  listingModalHost: {
    margin: 0,
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  listingFullscreenHost: {
    margin: 0,
    alignItems: "stretch",
    justifyContent: "flex-start",
    padding: 0,
  },
  listingFullscreenShell: {
    flex: 1,
    backgroundColor: PROFILE_UI.bg,
  },
  listingHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 68,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: PROFILE_UI.border,
    backgroundColor: PROFILE_UI.card,
  },
  listingHeaderBackButton: {
    minWidth: 88,
    paddingVertical: 8,
    paddingRight: 8,
  },
  listingHeaderBackText: {
    color: PROFILE_UI.sub,
    fontSize: 15,
    fontWeight: "600",
  },
  listingHeaderTitle: {
    flex: 1,
    color: PROFILE_UI.text,
    fontSize: 20,
    fontWeight: "800",
    textAlign: "center",
  },
  listingHeaderSpacer: {
    width: 88,
  },
  listingFullscreenScroll: {
    flex: 1,
  },
  listingFullscreenScrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 28,
  },
  modalTallCard: {
    maxHeight: "90%",
    minHeight: 0,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: PROFILE_UI.text,
    marginBottom: 4,
  },
  modalSub: {
    fontSize: 12,
    color: PROFILE_UI.sub,
    marginBottom: 12,
  },
  modalLabel: {
    fontSize: 12,
    color: PROFILE_UI.sub,
    marginTop: 8,
    marginBottom: 4,
  },
  modalBodySection: {
    flexShrink: 1,
    minHeight: 0,
  },
  labeledInputWrap: {
    marginBottom: 8,
  },
  modalInput: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 14,
    color: PROFILE_UI.text,
    backgroundColor: PROFILE_UI.cardSoft,
  },
  modalInputBig: {
    height: 80,
    textAlignVertical: "top",
  },
  modalScrollTall: {
    maxHeight: 430,
    minHeight: 0,
    flexShrink: 1,
  },
  modalScrollCompany: {
    maxHeight: 420,
  },
  modalScrollInvite: {
    maxHeight: 260,
    marginTop: 4,
  },
  modalScrollItem: {
    maxHeight: 320,
    minHeight: 0,
    flexShrink: 1,
  },
  modalScrollContent: {
    paddingBottom: 10,
  },
  wizardScroll: {
    maxHeight: 420,
    marginTop: 10,
  },
  compactModalCard: {
    maxWidth: 420,
  },
  modalFieldRow: {
    flexDirection: "row",
    gap: 8,
  },
  modalFieldCell: {
    flex: 1,
  },
  listingKindRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  listingKindChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: PROFILE_UI.cardSoft,
  },
  listingKindChipActive: {
    backgroundColor: PROFILE_UI.accentSoft,
    borderColor: PROFILE_UI.accent,
  },
  listingKindChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: PROFILE_UI.sub,
  },
  listingKindChipTextActive: {
    color: PROFILE_UI.accent,
  },
  listingHelperText: {
    fontSize: 11,
    color: PROFILE_UI.sub,
  },
  listingHelperTextTight: {
    marginTop: 2,
    marginBottom: 4,
  },
  listingHelperTextBottom: {
    marginBottom: 4,
  },
  listingCartCard: {
    marginTop: 8,
    marginBottom: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
    backgroundColor: PROFILE_UI.cardSoft,
    padding: 8,
  },
  listingCartTitle: {
    fontSize: 12,
    color: PROFILE_UI.sub,
    marginBottom: 4,
  },
  listingCartItem: {
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: PROFILE_UI.border,
  },
  listingCartItemLast: {
    borderBottomWidth: 0,
  },
  listingCartItemTitle: {
    fontSize: 13,
    color: PROFILE_UI.text,
    fontWeight: "600",
  },
  listingCartItemMeta: {
    fontSize: 11,
    color: PROFILE_UI.sub,
  },
  modalButtonsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: "#22C55E",
    backgroundColor: "#020617",
    flexShrink: 0,
    zIndex: 2,
  },
  listingBottomBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderTopColor: PROFILE_UI.border,
    backgroundColor: PROFILE_UI.card,
    gap: 12,
  },
  modalBtn: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 14,
    minWidth: 110,
    alignItems: "center",
    justifyContent: "center",
  },
  modalBtnSecondary: {
    borderWidth: 0,
    backgroundColor: "transparent",
  },
  modalBtnPrimary: {
    backgroundColor: "#22C55E",
  },
  modalBtnSecondaryText: {
    color: "#9CA3AF",
    fontSize: 13,
    fontWeight: "500",
  },
  modalBtnPrimaryText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
  listingBusyRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  profileAvatarEditor: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    padding: 12,
    marginBottom: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
    backgroundColor: PROFILE_UI.cardSoft,
  },
  profileAvatarEditorPreview: {
    width: 72,
    height: 72,
    borderRadius: 999,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: PROFILE_UI.card,
    borderWidth: 1,
    borderColor: PROFILE_UI.border,
  },
  profileAvatarEditorImage: {
    width: "100%",
    height: "100%",
  },
  profileAvatarEditorInitial: {
    color: PROFILE_UI.text,
    fontSize: 28,
    fontWeight: "700",
  },
  profileAvatarEditorMeta: {
    flex: 1,
  },
  profileAvatarEditorTitle: {
    color: PROFILE_UI.text,
    fontSize: 15,
    fontWeight: "700",
  },
  profileAvatarEditorText: {
    color: PROFILE_UI.sub,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
  profileAvatarEditorButton: {
    alignSelf: "flex-start",
    marginTop: 8,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: PROFILE_UI.accentSoft,
    borderWidth: 1,
    borderColor: PROFILE_UI.accent,
  },
  profileAvatarEditorButtonText: {
    color: PROFILE_UI.accent,
    fontSize: 12,
    fontWeight: "700",
  },
});

export const profileInputFocusStyle = {
  borderColor: PROFILE_UI.accent,
  ...Platform.select({
    web: { boxShadow: "0px 0px 12px rgba(79, 70, 229, 0.35)" },
    default: {
      shadowColor: PROFILE_UI.accent,
      shadowOpacity: 0.4,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 0 },
    },
  }),
};
