import type { S2BDomainPack, S2BWave2Kind } from "../types";

export const S2B_WATER_SEWER_STORM_DOMAIN_PACKS: Pick<Record<S2BWave2Kind, S2BDomainPack>, "water" | "sewer" | "stormwater" | "hydraulic" | "external_networks"> = {
  water: {
    prefix: "s2b_water",
    workUnit: "m",
    components: [
      { code: "route_survey", titleRu: "трассировка водопровода", materialUnit: "set", materialKey: "water_route_survey" },
      { code: "trench_shoring", titleRu: "траншея и крепление стенок", materialUnit: "m3", materialKey: "water_trench_shoring" },
      { code: "sand_bedding", titleRu: "песчаная подготовка и обсыпка", materialUnit: "m3", materialKey: "water_sand_bedding" },
      { code: "pipe", titleRu: "трубы водоснабжения", materialUnit: "m", materialKey: "water_pipe" },
      { code: "fittings", titleRu: "фитинги и переходы", materialUnit: "pcs", materialKey: "water_fittings" },
      { code: "valves", titleRu: "запорная арматура", materialUnit: "pcs", materialKey: "water_valves" },
      { code: "manholes", titleRu: "водопроводные колодцы", materialUnit: "pcs", materialKey: "water_manholes" },
      { code: "sleeves_crossings", titleRu: "футляры и пересечения", materialUnit: "m", materialKey: "water_sleeves" },
      { code: "connections", titleRu: "вводы и подключения", materialUnit: "pcs", materialKey: "water_connections" },
      { code: "backfill", titleRu: "обратная засыпка и уплотнение", materialUnit: "m3", materialKey: "water_backfill" },
      { code: "flushing_disinfection", titleRu: "промывка и дезинфекция", materialUnit: "set", materialKey: "water_disinfection" },
      { code: "hydro_testing", titleRu: "гидравлические испытания", materialUnit: "set", materialKey: "water_hydro_testing" },
    ],
  },
  sewer: {
    prefix: "s2b_sewer",
    workUnit: "m",
    components: [
      { code: "profile_marks", titleRu: "продольный профиль, уклон и отметки", materialUnit: "set", materialKey: "sewer_profile_marks" },
      { code: "trench", titleRu: "траншея канализации", materialUnit: "m3", materialKey: "sewer_trench" },
      { code: "shoring", titleRu: "крепление траншеи", materialUnit: "m", materialKey: "sewer_shoring" },
      { code: "bedding", titleRu: "песчаная постель трубы", materialUnit: "m3", materialKey: "sewer_bedding" },
      { code: "pipe", titleRu: "канализационная труба", materialUnit: "m", materialKey: "sewer_pipe" },
      { code: "manholes", titleRu: "смотровые колодцы", materialUnit: "pcs", materialKey: "sewer_manholes" },
      { code: "drop_structures", titleRu: "перепадные участки и лотки", materialUnit: "pcs", materialKey: "sewer_drop_structures" },
      { code: "outfall", titleRu: "выпуск и подключение", materialUnit: "set", materialKey: "sewer_outfall" },
      { code: "pump_station", titleRu: "насосная станция при напорной схеме", materialUnit: "set", materialKey: "sewer_pump_station" },
      { code: "backfill", titleRu: "обратная засыпка", materialUnit: "m3", materialKey: "sewer_backfill" },
      { code: "hydraulic_testing", titleRu: "гидравлические испытания", materialUnit: "set", materialKey: "sewer_hydraulic_testing" },
      { code: "cctv_inspection", titleRu: "телеинспекция и исполнительная схема", materialUnit: "set", materialKey: "sewer_cctv" },
    ],
  },
  stormwater: {
    prefix: "s2b_stormwater",
    workUnit: "m",
    components: [
      { code: "catchment_profile", titleRu: "водосбор, уклоны и отметки", materialUnit: "set", materialKey: "stormwater_profile" },
      { code: "trench", titleRu: "траншея ливневой сети", materialUnit: "m3", materialKey: "stormwater_trench" },
      { code: "pipe", titleRu: "трубы ливневой канализации", materialUnit: "m", materialKey: "stormwater_pipe" },
      { code: "rain_inlets", titleRu: "дождеприёмники", materialUnit: "pcs", materialKey: "rain_inlets" },
      { code: "trays", titleRu: "лотки и каналы", materialUnit: "m", materialKey: "stormwater_trays" },
      { code: "silt_traps", titleRu: "пескоуловители", materialUnit: "pcs", materialKey: "silt_traps" },
      { code: "manholes", titleRu: "ливневые колодцы", materialUnit: "pcs", materialKey: "stormwater_manholes" },
      { code: "outlet", titleRu: "выпуск воды", materialUnit: "set", materialKey: "stormwater_outlet" },
      { code: "pumping", titleRu: "насосная станция при напорной схеме", materialUnit: "set", materialKey: "stormwater_pumping" },
      { code: "road_restoration", titleRu: "восстановление покрытия", materialUnit: "m2", materialKey: "stormwater_road_restoration" },
      { code: "water_test", titleRu: "проверка проливом", materialUnit: "set", materialKey: "stormwater_water_test" },
      { code: "maintenance_access", titleRu: "точки обслуживания", materialUnit: "pcs", materialKey: "stormwater_access" },
    ],
  },
  hydraulic: {
    prefix: "s2b_hydraulic",
    workUnit: "m3",
    components: [
      { code: "survey_hydrology", titleRu: "гидрология, топосъёмка и исходные уровни воды", materialUnit: "set", materialKey: "hydraulic_survey_hydrology" },
      { code: "earthworks", titleRu: "земляные работы гидротехнического сооружения", materialUnit: "m3", materialKey: "hydraulic_earthworks" },
      { code: "impervious_core", titleRu: "противофильтрационное ядро или экран", materialUnit: "m3", materialKey: "hydraulic_impervious_core" },
      { code: "filter_layers", titleRu: "фильтрующие и переходные слои", materialUnit: "m3", materialKey: "hydraulic_filter_layers" },
      { code: "slope_protection", titleRu: "крепление откосов и берм", materialUnit: "m2", materialKey: "hydraulic_slope_protection" },
      { code: "spillway", titleRu: "водосброс и лотки", materialUnit: "m3", materialKey: "hydraulic_spillway" },
      { code: "drainage", titleRu: "дренажная призма и водоотвод", materialUnit: "m", materialKey: "hydraulic_drainage" },
      { code: "geomembrane", titleRu: "геомембрана или геотекстиль", materialUnit: "m2", materialKey: "hydraulic_geomembrane" },
      { code: "gates_metalwork", titleRu: "затворы и гидромеханическое оборудование", materialUnit: "set", materialKey: "hydraulic_gates_metalwork" },
      { code: "instrumentation", titleRu: "контрольно-измерительная аппаратура", materialUnit: "set", materialKey: "hydraulic_instrumentation" },
      { code: "monitoring", titleRu: "наблюдения, пьезометры и деформационный контроль", materialUnit: "set", materialKey: "hydraulic_monitoring" },
      { code: "handover_safety", titleRu: "испытания, безопасность и исполнительная документация", materialUnit: "set", materialKey: "hydraulic_handover_safety" },
    ],
  },
  external_networks: {
    prefix: "s2b_external_networks",
    workUnit: "m",
    components: [
      { code: "utility_conditions", titleRu: "технические условия подключений", materialUnit: "set", materialKey: "external_tu" },
      { code: "combined_trench", titleRu: "совмещённая траншея", materialUnit: "m3", materialKey: "external_combined_trench" },
      { code: "water_branch", titleRu: "ветка водоснабжения", materialUnit: "m", materialKey: "external_water_branch" },
      { code: "sewer_branch", titleRu: "ветка канализации", materialUnit: "m", materialKey: "external_sewer_branch" },
      { code: "power_branch", titleRu: "ветка электроснабжения", materialUnit: "m", materialKey: "external_power_branch" },
      { code: "heat_branch", titleRu: "ветка теплоснабжения", materialUnit: "m", materialKey: "external_heat_branch" },
      { code: "crossings", titleRu: "пересечения и футляры", materialUnit: "m", materialKey: "external_crossings" },
      { code: "chambers", titleRu: "камеры и колодцы сетей", materialUnit: "pcs", materialKey: "external_chambers" },
      { code: "backfill", titleRu: "обратная засыпка и уплотнение", materialUnit: "m3", materialKey: "external_backfill" },
      { code: "road_restoration", titleRu: "восстановление покрытия", materialUnit: "m2", materialKey: "external_road_restoration" },
      { code: "testing", titleRu: "испытания сетей", materialUnit: "set", materialKey: "external_testing" },
      { code: "as_built", titleRu: "исполнительная съёмка сетей", materialUnit: "set", materialKey: "external_as_built" },
    ],
  },
};
