import type { AiRoleWorkflowManifest } from "./aiRoleWorkflowTypes";

const forbiddenFinalActions = [
  "approve",
  "reject",
  "final_submit",
  "create_purchase_order_final",
  "post_payment",
  "issue_stock",
  "close_work",
  "publish_product",
  "send_reminder_final",
];

const baseSections: AiRoleWorkflowManifest["requiredAnswerSections"] = [
  "short",
  "facts",
  "links",
  "chain",
  "missing",
  "next_step",
  "status",
];

export const AI_ROLE_WORKFLOW_MANIFESTS: AiRoleWorkflowManifest[] = [
  {
    workflowId: "director_daily_decision_queue",
    role: "director",
    titleRu: "Решения директора сегодня",
    userGoalRu: "Понять, что решить, какой риск и куда нажать.",
    triggerQuestionsRu: ["что мне решить сегодня", "дай срез по всем данным"],
    requiredSources: ["app_context_graph", "app_data", "pdf_document", "warehouse", "finance", "field", "documents"],
    requiredEntities: ["procurement_request", "warehouse_stock", "work", "payment", "pdf_document", "approval"],
    allowedActionModes: ["safe_read", "draft_only", "approval_required"],
    forbiddenFinalActions,
    requiredAnswerSections: [...baseSections, "risks"],
  },
  {
    workflowId: "director_object_blocker_review",
    role: "director",
    titleRu: "Блокеры объекта",
    userGoalRu: "Понять, что блокирует объект или этаж.",
    triggerQuestionsRu: ["что блокирует первый этаж", "что мешает закрыть объект"],
    requiredSources: ["app_context_graph", "app_data", "warehouse", "finance", "field", "documents"],
    requiredEntities: ["procurement_request", "warehouse_stock", "work", "payment", "pdf_document"],
    allowedActionModes: ["safe_read", "approval_required"],
    forbiddenFinalActions,
    requiredAnswerSections: [...baseSections, "risks"],
  },
  {
    workflowId: "foreman_today_closeout",
    role: "foreman",
    titleRu: "Закрытие работ прораба",
    userGoalRu: "Понять, что можно закрыть и что блокирует закрытие.",
    triggerQuestionsRu: ["что мне закрыть сегодня", "каких фото не хватает"],
    requiredSources: ["app_context_graph", "app_data", "warehouse", "field", "documents"],
    requiredEntities: ["work", "procurement_request", "warehouse_issue", "warehouse_stock", "act"],
    allowedActionModes: ["safe_read", "draft_only"],
    forbiddenFinalActions,
    requiredAnswerSections: [...baseSections, "draft"],
  },
  {
    workflowId: "foreman_material_evidence_check",
    role: "foreman",
    titleRu: "Материалы и evidence",
    userGoalRu: "Понять, какие материалы выданы и каких evidence не хватает.",
    triggerQuestionsRu: ["какие материалы выданы на мои работы", "что блокирует ГКЛ"],
    requiredSources: ["app_context_graph", "app_data", "warehouse", "field"],
    requiredEntities: ["work", "procurement_request", "warehouse_issue", "warehouse_stock"],
    allowedActionModes: ["safe_read", "draft_only"],
    forbiddenFinalActions,
    requiredAnswerSections: [...baseSections, "draft"],
  },
  {
    workflowId: "buyer_approved_request_to_purchase_draft",
    role: "buyer",
    titleRu: "Черновик закупки по заявке",
    userGoalRu: "Понять, что купить, сколько, у кого и что отправить на согласование.",
    triggerQuestionsRu: ["что купить по заявке №124", "подбери варианты по заявке"],
    requiredSources: ["app_context_graph", "app_data", "internal_marketplace", "supplier_history", "warehouse", "external_knowledge"],
    requiredEntities: ["procurement_request", "warehouse_stock", "marketplace_product", "supplier", "work"],
    allowedActionModes: ["safe_read", "draft_only", "approval_required"],
    forbiddenFinalActions,
    requiredAnswerSections: [...baseSections, "draft"],
  },
  {
    workflowId: "buyer_supplier_comparison",
    role: "buyer",
    titleRu: "Сравнение поставщиков",
    userGoalRu: "Сравнить внутренние варианты, историю и внешние источники.",
    triggerQuestionsRu: ["найди поставщиков ГКЛ", "сравни предложения"],
    requiredSources: ["app_context_graph", "internal_marketplace", "supplier_history", "external_knowledge"],
    requiredEntities: ["marketplace_product", "supplier", "procurement_request"],
    allowedActionModes: ["safe_read", "draft_only", "approval_required"],
    forbiddenFinalActions,
    requiredAnswerSections: [...baseSections, "draft"],
  },
  {
    workflowId: "accountant_payment_readiness",
    role: "accountant",
    titleRu: "Готовность оплаты",
    userGoalRu: "Понять, какие платежи нельзя проводить и почему.",
    triggerQuestionsRu: ["какие платежи без документов", "что мешает оплате"],
    requiredSources: ["app_context_graph", "app_data", "pdf_document", "finance", "documents"],
    requiredEntities: ["payment", "invoice", "act", "pdf_document", "procurement_request", "work"],
    allowedActionModes: ["safe_read", "draft_only", "approval_required"],
    forbiddenFinalActions,
    requiredAnswerSections: [...baseSections, "risks", "draft"],
  },
  {
    workflowId: "accountant_accounting_entry_reference",
    role: "accountant",
    titleRu: "Справка по проводке",
    userGoalRu: "Подготовить справочную рекомендацию, не финальное бухгалтерское решение.",
    triggerQuestionsRu: ["какая проводка по счету", "как учитывать аванс подрядчику"],
    requiredSources: ["app_context_graph", "pdf_document", "finance", "documents", "external_knowledge"],
    requiredEntities: ["payment", "invoice", "document"],
    allowedActionModes: ["safe_read", "draft_only", "approval_required"],
    forbiddenFinalActions,
    requiredAnswerSections: [...baseSections, "draft"],
  },
  {
    workflowId: "warehouse_item_trace",
    role: "warehouse",
    titleRu: "Движение товара",
    userGoalRu: "Понять, куда ушел товар и чего не хватает.",
    triggerQuestionsRu: ["куда ушёл ГКЛ", "кому выдали профиль"],
    requiredSources: ["app_context_graph", "app_data", "warehouse", "field"],
    requiredEntities: ["warehouse_issue", "warehouse_stock", "procurement_request", "work"],
    allowedActionModes: ["safe_read", "draft_only", "approval_required"],
    forbiddenFinalActions,
    requiredAnswerSections: [...baseSections, "draft"],
  },
  {
    workflowId: "warehouse_deficit_to_request_draft",
    role: "warehouse",
    titleRu: "Черновик заявки на дефицит",
    userGoalRu: "Подготовить черновик по дефициту без списаний и выдач.",
    triggerQuestionsRu: ["подготовь черновик заявки на дефицит", "какие материалы в дефиците"],
    requiredSources: ["app_context_graph", "app_data", "warehouse"],
    requiredEntities: ["warehouse_stock", "procurement_request", "work"],
    allowedActionModes: ["safe_read", "draft_only", "approval_required"],
    forbiddenFinalActions,
    requiredAnswerSections: [...baseSections, "draft"],
  },
  {
    workflowId: "contractor_acceptance_closeout",
    role: "contractor",
    titleRu: "Приемка подрядчика",
    userGoalRu: "Понять, что мешает закрытию моих работ.",
    triggerQuestionsRu: ["что мешает закрыть мои работы", "какие фото нужны"],
    requiredSources: ["app_context_graph", "field", "documents"],
    requiredEntities: ["contractor", "work", "act", "document"],
    allowedActionModes: ["safe_read", "draft_only", "permission_limited"],
    forbiddenFinalActions,
    requiredAnswerSections: [...baseSections, "draft"],
  },
  {
    workflowId: "contractor_remark_response_draft",
    role: "contractor",
    titleRu: "Ответ на замечание",
    userGoalRu: "Подготовить ответ прорабу без закрытия работ.",
    triggerQuestionsRu: ["какие замечания открыты", "подготовь ответ прорабу"],
    requiredSources: ["app_context_graph", "field", "documents"],
    requiredEntities: ["contractor", "work", "document"],
    allowedActionModes: ["safe_read", "draft_only", "permission_limited"],
    forbiddenFinalActions,
    requiredAnswerSections: [...baseSections, "draft"],
  },
  {
    workflowId: "document_pdf_evidence_linking",
    role: "documents",
    titleRu: "Связи PDF",
    userGoalRu: "Понять, что в PDF и с чем он связан.",
    triggerQuestionsRu: ["что в этом PDF", "с чем связан счет"],
    requiredSources: ["app_context_graph", "pdf_document", "documents", "finance", "field"],
    requiredEntities: ["pdf_document", "payment", "invoice", "procurement_request", "work", "act"],
    allowedActionModes: ["safe_read", "draft_only", "approval_required"],
    forbiddenFinalActions,
    requiredAnswerSections: [...baseSections, "risks"],
  },
  {
    workflowId: "document_payment_blocker_review",
    role: "documents",
    titleRu: "Документы, блокирующие оплату",
    userGoalRu: "Понять, какого документа нет для оплаты.",
    triggerQuestionsRu: ["какой документ блокирует оплату", "каких документов не хватает"],
    requiredSources: ["app_context_graph", "pdf_document", "documents", "finance"],
    requiredEntities: ["pdf_document", "payment", "invoice", "act", "document"],
    allowedActionModes: ["safe_read", "draft_only", "approval_required"],
    forbiddenFinalActions,
    requiredAnswerSections: [...baseSections, "risks"],
  },
  {
    workflowId: "marketplace_photo_product_draft",
    role: "marketplace_user",
    titleRu: "Черновик карточки товара",
    userGoalRu: "Подготовить карточку по фото без публикации.",
    triggerQuestionsRu: ["определи товар по фото", "подготовь карточку товара"],
    requiredSources: ["app_context_graph", "internal_marketplace", "external_knowledge"],
    requiredEntities: ["marketplace_product", "supplier"],
    allowedActionModes: ["safe_read", "draft_only"],
    forbiddenFinalActions,
    requiredAnswerSections: [...baseSections, "draft"],
  },
  {
    workflowId: "marketplace_request_product_match",
    role: "marketplace_user",
    titleRu: "Связь товара с заявкой",
    userGoalRu: "Понять, для каких работ и заявок подходит товар.",
    triggerQuestionsRu: ["для каких работ используется", "покажи похожие товары"],
    requiredSources: ["app_context_graph", "internal_marketplace", "field", "procurement"],
    requiredEntities: ["marketplace_product", "procurement_request", "work"],
    allowedActionModes: ["safe_read", "draft_only"],
    forbiddenFinalActions,
    requiredAnswerSections: [...baseSections, "draft"],
  },
  {
    workflowId: "office_stuck_work_review",
    role: "office",
    titleRu: "Зависшие задачи офиса",
    userGoalRu: "Понять, кто следующий и какой reminder подготовить.",
    triggerQuestionsRu: ["покажи зависшие документы", "кому напомнить"],
    requiredSources: ["app_context_graph", "documents", "finance", "field", "warehouse"],
    requiredEntities: ["payment", "pdf_document", "procurement_request", "work", "approval"],
    allowedActionModes: ["safe_read", "draft_only", "approval_required"],
    forbiddenFinalActions,
    requiredAnswerSections: [...baseSections, "draft"],
  },
  {
    workflowId: "client_progress_summary",
    role: "client",
    titleRu: "Клиентский прогресс",
    userGoalRu: "Показать понятный прогресс без внутренних финансов.",
    triggerQuestionsRu: ["показать прогресс", "что сделано за неделю"],
    requiredSources: ["app_context_graph", "field", "documents", "reports"],
    requiredEntities: ["work", "document", "report"],
    allowedActionModes: ["safe_read", "permission_limited"],
    forbiddenFinalActions,
    requiredAnswerSections: [...baseSections],
  },
];

export function getAiRoleWorkflowManifest(workflowId: string): AiRoleWorkflowManifest | undefined {
  return AI_ROLE_WORKFLOW_MANIFESTS.find((manifest) => manifest.workflowId === workflowId);
}
