import fs from "node:fs";
import path from "node:path";

import {
  buildWarehouseBuyerRpcScaleRankings,
  renderWarehouseBuyerRpcScaleProof,
  type WarehouseBuyerRpcDefinition,
  type WarehouseBuyerRpcMatrixEntry,
} from "./_shared/warehouseBuyerRpcScaleCore";

const projectRoot = process.cwd();

const INVENTORY_PATH = path.join(projectRoot, "artifacts/WAREHOUSE_BUYER_rpc_scale_inventory.json");
const MATRIX_PATH = path.join(projectRoot, "artifacts/WAREHOUSE_BUYER_rpc_scale_matrix.json");
const RANKINGS_PATH = path.join(projectRoot, "artifacts/WAREHOUSE_BUYER_rpc_scale_rankings.json");
const NOTES_PATH = path.join(projectRoot, "artifacts/WAREHOUSE_BUYER_rpc_scale_notes.md");
const PROOF_PATH = path.join(projectRoot, "artifacts/WAREHOUSE_BUYER_rpc_scale_proof.md");

const readJson = <T>(fullPath: string): T => JSON.parse(fs.readFileSync(fullPath, "utf8")) as T;

const writeJson = (fullPath: string, payload: unknown) => {
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, `${JSON.stringify(payload, null, 2)}\n`);
};

const writeText = (fullPath: string, payload: string) => {
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, payload);
};

type InventoryFile = {
  collectedAt: string;
  readOnly: true;
  inventory: WarehouseBuyerRpcDefinition[];
};

type MatrixFile = {
  collectedAt: string;
  readOnly: true;
  waveStatus: string;
  environmentBlockers: string[];
  collectedTierCount: number;
  blockedTierCount: number;
  matrix: WarehouseBuyerRpcMatrixEntry[];
};

function main() {
  const inventoryFile = readJson<InventoryFile>(INVENTORY_PATH);
  const matrixFile = readJson<MatrixFile>(MATRIX_PATH);
  const rankings = buildWarehouseBuyerRpcScaleRankings(matrixFile.matrix);

  writeJson(RANKINGS_PATH, {
    collectedAt: new Date().toISOString(),
    rankings,
  });

  if (!fs.existsSync(NOTES_PATH)) {
    const lines = [
      "# Warehouse Buyer RPC Scale Verification",
      "",
      "## Scope",
      "- Notes file is generated by the collector; compare keeps it intact when present.",
      "",
      "## Shortlist Count",
      `- ${inventoryFile.inventory.length} RPC paths`,
    ];
    writeText(NOTES_PATH, `${lines.join("\n")}\n`);
  }

  writeText(PROOF_PATH, renderWarehouseBuyerRpcScaleProof(matrixFile.matrix, rankings));
}

main();
