import type { GlobalWorkCategory } from "../globalEstimate";
import { normalizeDimensionText } from "../constructionFormulas";
import type { EstimatorKernelComplexity } from "./estimatorKernelTypes";

export type EstimatorDomainLexiconEntry = {
  domain: string;
  terms: readonly string[];
  casePhrases: readonly string[];
  category: GlobalWorkCategory;
  object: string;
  operation: string;
  method: string;
  materialSystem: string;
  complexity: EstimatorKernelComplexity;
  requiredMaterials: readonly string[];
  requiredLabor: readonly string[];
  requiredEquipmentOrWarnings: readonly string[];
  requiredLogisticsOrWarnings: readonly string[];
  exclusions: readonly string[];
  clarifyingQuestions: readonly string[];
  unitRules: readonly string[];
  regulatedSafetyRequired?: boolean;
};

const sharedExclusions = [
  "Проектирование, разрешения и скрытые работы уточняются отдельно.",
  "Демонтаж, доставка, подъем и вывоз мусора включаются только при подтверждении условий площадки.",
];

const sharedQuestions = [
  "Укажите город, адрес и доступ к объекту для локальной ставки.",
  "Подтвердите фактический объем, основание и требования к материалам.",
];

function e(input: EstimatorDomainLexiconEntry): EstimatorDomainLexiconEntry {
  return input;
}

export const ESTIMATOR_DOMAIN_LEXICON: readonly EstimatorDomainLexiconEntry[] = [
  e({ domain: "flooring", terms: ["линолеум", "ламинат", "паркет", "пвх покрытие", "рулонное покрытие"], casePhrases: ["укладка линолеума", "настил ламината", "монтаж ПВХ покрытия", "укладка паркета", "замена напольного покрытия"], category: "flooring", object: "floor_covering", operation: "installation", method: "floor_covering_installation", materialSystem: "floor_covering_system", complexity: "medium", requiredMaterials: ["напольное покрытие", "подложка / клей", "плинтус", "порожки"], requiredLabor: ["подготовка основания", "раскрой покрытия", "укладка покрытия", "подрезка примыканий"], requiredEquipmentOrWarnings: ["ручной инструмент", "строительный пылесос"], requiredLogisticsOrWarnings: ["доставка покрытия", "вынос отходов"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["floor_covering_rows_sq_m", "baseboard_linear_m"] }),
  e({ domain: "tiling", terms: ["плитк", "керамогранит", "кафель", "мозаик"], casePhrases: ["укладка плитки на пол", "облицовка стен керамогранитом", "кладка кафеля", "монтаж мозаики", "плитка в санузле"], category: "tile", object: "tile_surface", operation: "installation", method: "tile_adhesive_laying", materialSystem: "ceramic_tile_system", complexity: "medium", requiredMaterials: ["плитка / керамогранит", "плиточный клей", "затирка", "крестики / СВП"], requiredLabor: ["подготовка основания", "раскладка плитки", "укладка плитки", "затирка швов"], requiredEquipmentOrWarnings: ["плиткорез", "миксер для клея"], requiredLogisticsOrWarnings: ["доставка плитки", "резерв на бой и подрезку"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["tile_sq_m", "grout_kg", "trim_linear_m"] }),
  e({ domain: "drywall", terms: ["гкл", "гипсокартон", "сухое строительство", "перегородк"], casePhrases: ["монтаж перегородки ГКЛ", "обшивка стен гипсокартоном", "каркас под ГКЛ", "зашивка ниши гипсокартоном", "потолок из ГКЛ"], category: "drywall", object: "drywall_system", operation: "installation", method: "drywall_metal_frame", materialSystem: "drywall_system", complexity: "medium", requiredMaterials: ["листы ГКЛ", "направляющий профиль", "стоечный профиль", "подвесы и крепеж", "лента и шпаклевка швов"], requiredLabor: ["разметка каркаса", "монтаж каркаса", "обшивка листами ГКЛ", "заделка швов"], requiredEquipmentOrWarnings: ["шуруповерт", "лазерный уровень"], requiredLogisticsOrWarnings: ["доставка листов ГКЛ", "подъем листов"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["drywall_sq_m", "profile_linear_m", "fasteners_pcs"] }),
  e({ domain: "painting", terms: ["покраск", "окраск", "краск", "покрасить"], casePhrases: ["покраска стен", "окраска потолка", "покраска фасада", "нанесение грунта и краски", "перекраска помещений"], category: "painting", object: "painted_surface", operation: "finishing", method: "primer_paint_system", materialSystem: "paint_system", complexity: "simple", requiredMaterials: ["грунтовка", "краска", "малярная лента", "укрывная пленка"], requiredLabor: ["подготовка поверхности", "грунтование", "окраска в два слоя", "контроль укрывистости"], requiredEquipmentOrWarnings: ["валики и кисти", "краскопульт warning"], requiredLogisticsOrWarnings: ["доставка ЛКМ", "защита помещений"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["paint_sq_m", "primer_liters"] }),
  e({ domain: "plastering", terms: ["штукатур", "выравнивание стен", "машинная штукатурка"], casePhrases: ["штукатурка стен", "машинная штукатурка", "выравнивание стен гипсом", "цементная штукатурка фасада", "штукатурка откосов"], category: "plastering", object: "plastered_surface", operation: "finishing", method: "plaster_leveling", materialSystem: "plaster_system", complexity: "medium", requiredMaterials: ["штукатурная смесь", "маяки", "грунтовка", "уголки"], requiredLabor: ["грунтование", "установка маяков", "нанесение штукатурки", "затирка поверхности"], requiredEquipmentOrWarnings: ["штукатурная станция warning", "правило и уровень"], requiredLogisticsOrWarnings: ["доставка сухих смесей", "вывоз мешков"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["plaster_sq_m", "mix_kg"] }),
  e({ domain: "ceilings", terms: ["потол", "натяжной", "подвесной потолок", "армстронг"], casePhrases: ["монтаж натяжного потолка", "подвесной потолок Армстронг", "реечный потолок", "ГКЛ потолок", "покраска потолка"], category: "ceiling", object: "ceiling_system", operation: "installation", method: "ceiling_system_install", materialSystem: "ceiling_system", complexity: "medium", requiredMaterials: ["профиль потолка", "полотно / панели", "подвесы", "крепеж потолочной системы"], requiredLabor: ["разметка уровня", "монтаж каркаса", "монтаж покрытия потолка", "обход светильников"], requiredEquipmentOrWarnings: ["лазерный уровень", "стремянки / подмости"], requiredLogisticsOrWarnings: ["доставка потолочной системы", "подъем материалов"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["ceiling_sq_m", "perimeter_linear_m"] }),
  e({ domain: "doors", terms: ["двер", "дверной блок", "межкомнатная дверь", "входная дверь"], casePhrases: ["установка межкомнатных дверей", "монтаж входной двери", "замена дверных блоков", "установка дверей с доборами", "монтаж противопожарной двери"], category: "doors_windows", object: "door_block", operation: "installation", method: "door_block_install", materialSystem: "door_system", complexity: "simple", requiredMaterials: ["дверной блок", "коробка и наличники", "доборы", "петли и фурнитура"], requiredLabor: ["демонтаж старого блока warning", "подготовка проема", "монтаж коробки", "навеска полотна"], requiredEquipmentOrWarnings: ["перфоратор", "уровень"], requiredLogisticsOrWarnings: ["доставка дверей", "вынос упаковки"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["door_pcs", "foam_set"] }),
  e({ domain: "windows", terms: ["окн", "стеклопакет", "витраж", "оконный блок"], casePhrases: ["установка окон ПВХ", "замена стеклопакетов", "монтаж витражных окон", "установка оконных блоков", "остекление балкона"], category: "doors_windows", object: "window_block", operation: "installation", method: "window_block_install", materialSystem: "window_system", complexity: "medium", requiredMaterials: ["оконный блок", "подоконник", "отлив", "монтажная пена"], requiredLabor: ["обмер проемов", "демонтаж старого окна warning", "монтаж оконного блока", "герметизация примыканий"], requiredEquipmentOrWarnings: ["подъем стеклопакетов", "страховка на высоте warning"], requiredLogisticsOrWarnings: ["доставка окон", "вывоз старых рам"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["window_pcs", "sealant_linear_m"] }),
  e({ domain: "waterproofing", terms: ["гидроизоляц", "мембрана", "битумная мастика", "рулонная изоляция"], casePhrases: ["гидроизоляция крыши", "гидроизоляция ванной", "гидроизоляция фундамента", "мембрана на кровлю", "гидроизоляция подвала"], category: "waterproofing", object: "waterproofing_surface", operation: "waterproofing", method: "membrane_or_mastic_waterproofing", materialSystem: "waterproofing_system", complexity: "medium", requiredMaterials: ["гидроизоляционный материал", "праймер", "герметик примыканий", "армирующая лента"], requiredLabor: ["подготовка основания", "нанесение праймера", "монтаж гидроизоляции", "герметизация примыканий"], requiredEquipmentOrWarnings: ["газовая горелка warning", "ручной инструмент"], requiredLogisticsOrWarnings: ["доставка гидроизоляции", "утилизация отходов"], exclusions: sharedExclusions, clarifyingQuestions: ["Уточните объект: крыша, ванная, фундамент, подвал или балкон?", ...sharedQuestions], unitRules: ["waterproofing_sq_m", "joint_linear_m"] }),
  e({ domain: "roofing", terms: ["двускат", "двухскат", "кровл", "крыш", "стропил", "мауэрлат"], casePhrases: ["установка двухскатной крыши", "монтаж скатной кровли", "устройство стропильной системы", "замена кровельного покрытия", "монтаж мягкой кровли"], category: "roofing", object: "roof_system", operation: "installation", method: "roof_system_install", materialSystem: "roofing_system", complexity: "complex", requiredMaterials: ["мауэрлат", "стропила", "коньковый прогон", "гидроизоляционная мембрана", "кровельное покрытие"], requiredLabor: ["монтаж стропильной системы", "монтаж обрешетки", "монтаж кровли", "установка доборных элементов"], requiredEquipmentOrWarnings: ["леса / страховка", "подъемник warning"], requiredLogisticsOrWarnings: ["доставка леса и кровли", "подъем материалов"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["roof_covering_sq_m", "ridge_linear_m"] }),
  e({ domain: "facade", terms: ["фасад", "сайдинг", "вентилируемый фасад", "облицовка фасада"], casePhrases: ["монтаж вентилируемого фасада", "отделка фасада сайдингом", "штукатурный фасад", "облицовка фасада плитами", "ремонт фасада"], category: "facade", object: "facade_system", operation: "installation", method: "facade_cladding_system", materialSystem: "facade_system", complexity: "complex", requiredMaterials: ["фасадная подсистема", "утеплитель warning", "облицовка фасада", "крепеж фасада"], requiredLabor: ["разметка фасада", "монтаж подсистемы", "монтаж облицовки", "герметизация примыканий"], requiredEquipmentOrWarnings: ["леса / автовышка", "страховка"], requiredLogisticsOrWarnings: ["доставка фасадных материалов", "подъем на фасад"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["facade_sq_m", "anchors_pcs"] }),
  e({ domain: "insulation", terms: ["утеплен", "теплоизоляц", "минвата", "пеноплекс"], casePhrases: ["утепление фасада минватой", "теплоизоляция кровли", "утепление стен пеноплексом", "утепление пола", "монтаж теплоизоляции труб"], category: "insulation", object: "insulation_system", operation: "installation", method: "thermal_insulation_install", materialSystem: "insulation_system", complexity: "medium", requiredMaterials: ["утеплитель", "клей / крепеж утеплителя", "ветрозащитная мембрана", "армирующая сетка warning"], requiredLabor: ["подготовка основания", "монтаж утеплителя", "крепление тарельчатыми дюбелями", "контроль мостиков холода"], requiredEquipmentOrWarnings: ["нож для утеплителя", "леса warning"], requiredLogisticsOrWarnings: ["доставка утеплителя", "хранение сухим способом"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["insulation_sq_m", "anchors_pcs"] }),
  e({ domain: "masonry", terms: ["кирпич", "кладк", "газоблок", "пеноблок"], casePhrases: ["кладка кирпича", "кладка стены из газоблока", "кирпичная перегородка", "кладка пеноблока", "облицовочная кладка"], category: "masonry", object: "masonry_wall", operation: "masonry", method: "brick_or_block_masonry", materialSystem: "masonry_system", complexity: "medium", requiredMaterials: ["кирпич / блок", "кладочный раствор", "кладочная сетка", "перемычки warning"], requiredLabor: ["разметка кладки", "кладка рядов", "армирование кладки", "расшивка / контроль плоскости"], requiredEquipmentOrWarnings: ["подмости", "миксер"], requiredLogisticsOrWarnings: ["доставка кирпича", "подъем блоков"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["masonry_sq_m", "mortar_m3"] }),
  e({ domain: "concrete", terms: ["бетон", "заливк", "плита", "тумб", "колонн"], casePhrases: ["заливка бетонной плиты", "бетонные тумбы", "устройство бетонных колонн", "заливка стяжки", "бетонная подготовка"], category: "concrete", object: "concrete_element", operation: "concrete_pour", method: "concrete_rebar_formwork", materialSystem: "concrete_rebar_formwork", complexity: "medium", requiredMaterials: ["бетон", "арматура", "опалубка", "фиксаторы защитного слоя"], requiredLabor: ["разметка осей", "вязка арматуры", "монтаж опалубки", "заливка бетона"], requiredEquipmentOrWarnings: ["вибратор", "бетононасос warning"], requiredLogisticsOrWarnings: ["доставка материалов", "резерв материалов"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["concrete_m3", "rebar_kg", "formwork_sq_m"] }),
  e({ domain: "foundation", terms: ["фундамент", "ленточный", "свай", "ростверк"], casePhrases: ["ленточный фундамент", "свайный фундамент", "плита фундамента", "ростверк", "усиление фундамента"], category: "foundation", object: "foundation_system", operation: "installation", method: "foundation_concrete_system", materialSystem: "foundation_system", complexity: "complex", requiredMaterials: ["бетон фундамента", "арматурный каркас", "опалубка", "гидроизоляция фундамента"], requiredLabor: ["разметка осей", "земляные работы", "вязка арматуры", "заливка фундамента"], requiredEquipmentOrWarnings: ["экскаватор warning", "бетононасос"], requiredLogisticsOrWarnings: ["доставка материалов на участок", "вывоз грунта"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["foundation_m3", "linear_m"] }),
  e({ domain: "earthworks", terms: ["котлован", "транше", "грунт", "планировка участка"], casePhrases: ["разработка котлована", "рытье траншеи", "планировка участка", "обратная засыпка", "выемка грунта"], category: "foundation", object: "earthwork_scope", operation: "preparation", method: "earthmoving", materialSystem: "earthworks", complexity: "medium", requiredMaterials: ["песок warning", "щебень warning", "геотекстиль warning"], requiredLabor: ["разбивка площадки", "выемка грунта", "планировка основания", "обратная засыпка"], requiredEquipmentOrWarnings: ["экскаватор", "самосвал", "виброплита"], requiredLogisticsOrWarnings: ["вывоз грунта", "доставка инертных материалов"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["earthworks_m3", "haulage_trip"] }),
  e({ domain: "asphalt_roadworks", terms: ["асфальт", "дорог", "проезд", "парковк"], casePhrases: ["асфальтирование площадки", "ремонт дороги", "устройство парковки", "ямочный ремонт асфальта", "подготовка основания под асфальт"], category: "roadworks", object: "asphalt_area", operation: "paving", method: "asphalt_hot_mix", materialSystem: "asphalt_road_base", complexity: "infrastructure", requiredMaterials: ["асфальтобетон", "щебеночное основание", "битумная эмульсия", "песок"], requiredLabor: ["планировка основания", "укладка асфальта", "уплотнение катком", "контроль уклонов"], requiredEquipmentOrWarnings: ["дорожная техника", "асфальтоукладчик", "каток", "виброплита"], requiredLogisticsOrWarnings: ["доставка асфальта", "вывоз старого покрытия"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["asphalt_sq_m", "asphalt_ton"] }),
  e({ domain: "paving_landscaping", terms: ["брусчат", "тротуарн", "мощен", "поребрик"], casePhrases: ["укладка брусчатки", "мощение тротуарной плиткой", "установка поребрика", "устройство садовой дорожки", "площадка из брусчатки"], category: "landscaping", object: "paving_stone", operation: "laying", method: "paving_stone_base_layers", materialSystem: "paving_system", complexity: "infrastructure", requiredMaterials: ["брусчатка / тротуарная плитка", "геотекстиль", "щебень", "пескоцементная смесь"], requiredLabor: ["разметка", "планировка основания", "укладка брусчатки", "заполнение швов"], requiredEquipmentOrWarnings: ["виброплита", "резчик плитки"], requiredLogisticsOrWarnings: ["доставка брусчатки", "вывоз грунта"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["paving_sq_m", "curb_linear_m"] }),
  e({ domain: "metal_structures", terms: ["металлоконструк", "металлическ", "ферм", "балк"], casePhrases: ["монтаж металлоконструкций", "изготовление и монтаж ферм", "монтаж металлических балок", "сварной каркас", "усиление металлом"], category: "metalworks", object: "steel_structure", operation: "installation", method: "welded_or_bolted_steel", materialSystem: "steel_structure_system", complexity: "complex", requiredMaterials: ["сталь / металлопрокат", "болты / анкера", "сварочные материалы", "антикоррозионная грунтовка"], requiredLabor: ["обмер / схема", "сварка / сборка", "монтаж металлоконструкций", "окраска металла"], requiredEquipmentOrWarnings: ["кран / автовышка", "сварочный аппарат"], requiredLogisticsOrWarnings: ["доставка металла", "разгрузка краном"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["steel_kg", "anchors_pcs"] }),
  e({ domain: "canopies", terms: ["навес", "козырек"], casePhrases: ["металлический навес", "навес из профнастила", "козырек над входом", "навес для парковки", "сварной навес"], category: "metalworks", object: "metal_canopy", operation: "installation", method: "welded_metal_frame", materialSystem: "metal_canopy_system", complexity: "complex", requiredMaterials: ["стойки металлические", "фермы / балки", "прогоны", "кровельное покрытие"], requiredLabor: ["монтаж стоек", "монтаж ферм / балок", "монтаж прогонов", "монтаж кровельного покрытия"], requiredEquipmentOrWarnings: ["кран / автовышка", "сварочное оборудование"], requiredLogisticsOrWarnings: ["доставка металла", "доставка кровельного покрытия"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["steel_kg", "roof_sq_m", "equipment_shift"] }),
  e({ domain: "fencing", terms: ["забор", "огражден", "ворот", "калитк"], casePhrases: ["установка забора из профнастила", "монтаж сетчатого ограждения", "забор на металлических столбах", "установка ворот", "ограждение участка"], category: "landscaping", object: "fence_system", operation: "installation", method: "fence_post_panel_system", materialSystem: "fencing_system", complexity: "medium", requiredMaterials: ["столбы забора", "панели / профнастил", "бетон для столбов", "крепеж секций забора"], requiredLabor: ["разметка линии забора", "бурение лунок", "установка столбов", "монтаж секций"], requiredEquipmentOrWarnings: ["бур / мотобур", "сварка warning"], requiredLogisticsOrWarnings: ["доставка секций", "вывоз грунта"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["fence_linear_m", "posts_pcs"] }),
  e({ domain: "demolition", terms: ["демонтаж", "снос", "разборк"], casePhrases: ["демонтаж перегородок", "снос старой стяжки", "демонтаж плитки", "разборка кровли", "снос несущей стены warning"], category: "demolition", object: "demolition_scope", operation: "demolition", method: "controlled_demolition", materialSystem: "demolition_waste", complexity: "medium", requiredMaterials: ["мешки / контейнеры", "укрывные материалы", "расходники демонтажа"], requiredLabor: ["обследование зоны", "отключение коммуникаций warning", "демонтаж конструкций", "сортировка отходов"], requiredEquipmentOrWarnings: ["перфоратор", "контейнер", "пылезащита"], requiredLogisticsOrWarnings: ["вывоз мусора", "утилизация отходов"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["demolition_sq_m", "waste_trip"] }),
  e({ domain: "plumbing", terms: ["сантех", "водопровод", "канализац", "труб"], casePhrases: ["монтаж сантехники", "разводка водопровода", "замена труб", "монтаж канализации", "установка коллекторного узла"], category: "plumbing", object: "plumbing_system", operation: "installation", method: "plumbing_pipework", materialSystem: "plumbing_system", complexity: "complex", requiredMaterials: ["трубы", "фитинги", "запорная арматура", "крепеж труб"], requiredLabor: ["разметка трасс", "монтаж труб", "опрессовка", "подключение приборов"], requiredEquipmentOrWarnings: ["пресс-инструмент", "испытательный насос"], requiredLogisticsOrWarnings: ["доставка труб", "доступ к стоякам warning"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["pipe_linear_m", "fixtures_pcs"] }),
  e({ domain: "heating", terms: ["отоплен", "радиатор", "теплый пол", "котельная"], casePhrases: ["монтаж отопления", "установка радиаторов", "теплый водяной пол", "замена труб отопления", "монтаж котельной обвязки"], category: "heating_hvac", object: "heating_system", operation: "installation", method: "heating_pipework", materialSystem: "heating_system", complexity: "complex", requiredMaterials: ["трубы отопления", "радиаторы / контуры", "коллектор", "теплоизоляция труб"], requiredLabor: ["гидравлическая схема", "монтаж труб", "установка радиаторов", "опрессовка отопления"], requiredEquipmentOrWarnings: ["опрессовочный насос", "тепловизор warning"], requiredLogisticsOrWarnings: ["доставка радиаторов", "слив системы warning"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["heating_points_pcs", "pipe_linear_m"] }),
  e({ domain: "ventilation", terms: ["вентиляц", "воздуховод", "вытяжк", "приточ"], casePhrases: ["монтаж вентиляции кафе", "установка воздуховодов", "приточно-вытяжная вентиляция", "вытяжка кухни", "балансировка вентиляции"], category: "heating_hvac", object: "ventilation_network", operation: "installation", method: "area_based_ventilation_preliminary", materialSystem: "ventilation_system", complexity: "complex", requiredMaterials: ["воздуховоды", "фасонные элементы", "решетки и диффузоры", "вентиляционная установка"], requiredLabor: ["разметка трасс", "монтаж воздуховодов", "монтаж решеток", "пусконаладка"], requiredEquipmentOrWarnings: ["подъемник", "измерительный прибор"], requiredLogisticsOrWarnings: ["доставка воздуховодов", "подъем материалов"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["duct_linear_m", "terminals_pcs"] }),
  e({ domain: "air_conditioning", terms: ["кондиционер", "кондиционир", "сплит", "мультисплит", "чиллер", "фанкойл", "vrf", "vrv"], casePhrases: ["монтаж кондиционеров", "установка сплит-систем", "монтаж чиллера", "фанкойлы в офисе", "трассы кондиционирования", "система кондиционирования"], category: "heating_hvac", object: "air_conditioning_system", operation: "installation", method: "air_conditioning_system_installation", materialSystem: "air_conditioning_system", complexity: "complex", requiredMaterials: ["внутренние блоки кондиционирования", "медная фреоновая трасса", "дренаж конденсата", "кронштейны наружных блоков"], requiredLabor: ["разметка трасс кондиционирования", "монтаж внутренних блоков", "вакуумирование и запуск"], requiredEquipmentOrWarnings: ["вакуумный насос", "подъем наружных блоков warning"], requiredLogisticsOrWarnings: ["доставка блоков кондиционирования", "подъем наружных блоков"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["ac_units_pcs", "copper_linear_m"] }),
  e({ domain: "electrical", terms: ["электромонтаж", "электрик", "кабель", "щит"], casePhrases: ["электромонтаж квартиры", "разводка кабеля", "монтаж электрощита", "электрика дома", "установка розеток"], category: "electrical", object: "electrical_network", operation: "installation", method: "area_points_preliminary", materialSystem: "electrical_installation", complexity: "complex", requiredMaterials: ["кабельные линии", "щит и автоматика", "розеточные точки", "гофра и короб"], requiredLabor: ["разметка электрических трасс", "прокладка кабеля", "монтаж щита", "испытания электросети"], requiredEquipmentOrWarnings: ["штроборез", "тестер"], requiredLogisticsOrWarnings: ["доставка кабеля", "вывоз мусора"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["cable_linear_m", "points_pcs"] }),
  e({ domain: "low_voltage", terms: ["слаботоч", "интернет", "скс", "домофон"], casePhrases: ["монтаж СКС", "слаботочные сети офиса", "прокладка интернет кабеля", "домофонная система", "структурированная кабельная сеть"], category: "electrical", object: "low_voltage_system", operation: "installation", method: "low_voltage_cabling", materialSystem: "low_voltage_system", complexity: "medium", requiredMaterials: ["UTP кабель", "патч-панель", "розетки RJ45", "кабель-канал"], requiredLabor: ["разметка слаботочных трасс", "прокладка кабеля", "оконцевание линий", "тестирование сети"], requiredEquipmentOrWarnings: ["кабельный тестер", "обжимной инструмент"], requiredLogisticsOrWarnings: ["доставка кабеля", "маркировка линий"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["cable_linear_m", "ports_pcs"] }),
  e({ domain: "fire_alarm", terms: ["пожарн", "апс", "соуэ", "дымовой датчик"], casePhrases: ["монтаж пожарной сигнализации", "АПС в офисе", "система оповещения СОУЭ", "установка дымовых датчиков", "пожарная автоматика"], category: "electrical", object: "fire_alarm_system", operation: "installation", method: "regulated_fire_alarm_install", materialSystem: "fire_alarm_system", complexity: "complex", requiredMaterials: ["пожарные датчики", "прибор АПС", "кабель огнестойкий", "оповещатели"], requiredLabor: ["проектная привязка warning", "прокладка кабеля", "монтаж датчиков", "ПНР пожарной сигнализации"], requiredEquipmentOrWarnings: ["тестер линий", "лицензированный подрядчик"], requiredLogisticsOrWarnings: ["доставка оборудования", "исполнительная документация"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["detectors_pcs", "cable_linear_m"], regulatedSafetyRequired: true }),
  e({ domain: "security_systems", terms: ["охран", "видеонаблюд", "скуд", "сигнализац"], casePhrases: ["монтаж видеонаблюдения", "охранная сигнализация", "СКУД офиса", "установка камер", "контроль доступа"], category: "electrical", object: "security_system", operation: "installation", method: "security_system_install", materialSystem: "security_low_voltage_system", complexity: "medium", requiredMaterials: ["камеры / датчики", "регистратор / контроллер", "кабель", "блок питания"], requiredLabor: ["разметка точек", "прокладка линий", "монтаж устройств", "настройка системы"], requiredEquipmentOrWarnings: ["тестер", "лестницы / подъемник"], requiredLogisticsOrWarnings: ["доставка оборудования", "маркировка кабелей"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["devices_pcs", "cable_linear_m"] }),
  e({ domain: "solar", terms: ["солнеч", "фотоэлектр", "инвертор"], casePhrases: ["установка солнечных панелей", "солнечная станция 30 кВт", "монтаж инвертора", "фотоэлектрические панели", "СЭС на крыше"], category: "electrical", object: "solar_power_system", operation: "installation", method: "solar_pv_install", materialSystem: "solar_pv_system", complexity: "infrastructure", requiredMaterials: ["солнечные панели", "инвертор", "крепежная система", "DC/AC кабели"], requiredLabor: ["обследование крыши", "монтаж креплений", "монтаж панелей", "подключение инвертора"], requiredEquipmentOrWarnings: ["страховка на крыше", "электроизмерения"], requiredLogisticsOrWarnings: ["доставка панелей", "подъем на кровлю"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["solar_kw", "panels_pcs"] }),
  e({ domain: "hydropower", terms: ["гэс", "гидро", "турбин"], casePhrases: ["установка турбины ГЭС", "гидроагрегат", "мини ГЭС", "монтаж гидротурбины", "оборудование ГЭС"], category: "concrete", object: "hydropower_turbine", operation: "installation", method: "hydro_turbine_equipment_install", materialSystem: "hydro_turbine_system", complexity: "infrastructure", requiredMaterials: ["турбина ГЭС", "генератор", "шкаф управления", "запорная арматура"], requiredLabor: ["обследование машинного зала", "монтаж турбины", "ПНР гидроагрегата", "испытания"], requiredEquipmentOrWarnings: ["кран", "такелаж", "инспекция"], requiredLogisticsOrWarnings: ["доставка оборудования ГЭС", "такелажный план"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["power_kw", "equipment_set"], regulatedSafetyRequired: true }),
  e({ domain: "industrial_equipment", terms: ["промышленное оборудование", "станок", "линия", "насосная станция"], casePhrases: ["монтаж промышленного оборудования", "установка станка", "монтаж производственной линии", "насосная станция", "такелаж оборудования"], category: "delivery_equipment", object: "industrial_equipment", operation: "installation", method: "industrial_equipment_install", materialSystem: "industrial_equipment_system", complexity: "infrastructure", requiredMaterials: ["оборудование", "анкер", "кабельные подключения", "трубная обвязка warning"], requiredLabor: ["обследование основания", "такелаж", "выверка оборудования", "ПНР"], requiredEquipmentOrWarnings: ["кран / погрузчик", "такелажная оснастка"], requiredLogisticsOrWarnings: ["доставка оборудования", "разгрузка и хранение"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["equipment_set", "anchors_pcs"] }),
  e({ domain: "well_drilling", terms: ["скважин", "бурен", "водозабор"], casePhrases: ["бурение скважины", "скважина на воду", "обсадная труба", "водозаборная скважина", "промывка скважины"], category: "roadworks", object: "water_well", operation: "drilling", method: "well_drilling", materialSystem: "well_system", complexity: "infrastructure", requiredMaterials: ["обсадная труба", "фильтр", "гравийная обсыпка", "оголовок"], requiredLabor: ["разметка точки бурения", "бурение скважины", "обсадка", "прокачка и промывка"], requiredEquipmentOrWarnings: ["буровая установка", "насос для прокачки"], requiredLogisticsOrWarnings: ["мобилизация буровой", "доставка труб"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["drilling_linear_m", "casing_linear_m"] }),
  e({ domain: "sewerage", terms: ["канализац", "септик", "колодец", "ливневк"], casePhrases: ["наружная канализация", "монтаж септика", "канализационные колодцы", "ливневая канализация", "прокладка канализационной трубы"], category: "plumbing", object: "sewerage_system", operation: "installation", method: "sewer_pipework", materialSystem: "sewerage_system", complexity: "complex", requiredMaterials: ["канализационная труба", "колодцы", "песчаная подготовка", "фитинги"], requiredLabor: ["разметка трассы", "разработка траншеи", "укладка трубы", "проверка уклонов"], requiredEquipmentOrWarnings: ["экскаватор", "виброплита"], requiredLogisticsOrWarnings: ["доставка труб", "вывоз грунта"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["pipe_linear_m", "wells_pcs"] }),
  e({ domain: "drainage", terms: ["дренаж", "дренажные каналы", "лотк", "водоотвод"], casePhrases: ["дренажные каналы", "линейный водоотвод", "дренаж участка", "установка лотков", "водоотвод с решетками"], category: "roadworks", object: "drainage_channel", operation: "installation", method: "length_based_drainage_channel", materialSystem: "drainage_channel_system", complexity: "medium", requiredMaterials: ["дренажные лотки / каналы", "решетки", "геотекстиль", "щебеночное основание"], requiredLabor: ["разметка трассы", "выемка грунта", "стыковка лотков", "проверка проливом"], requiredEquipmentOrWarnings: ["мини-экскаватор", "виброплита"], requiredLogisticsOrWarnings: ["вывоз грунта", "доставка материалов"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["drainage_linear_m", "grates_linear_m"] }),
  e({ domain: "commercial_fit_out", terms: ["офис", "кафе", "магазин", "коммерческ"], casePhrases: ["ремонт офиса", "fit-out кафе", "отделка магазина", "коммерческая отделка", "ремонт салона"], category: "other", object: "commercial_fit_out", operation: "renovation", method: "commercial_fit_out", materialSystem: "fit_out_system", complexity: "complex", requiredMaterials: ["черновые материалы", "финишные покрытия", "инженерные комплектующие", "двери / перегородки warning"], requiredLabor: ["обмер и ведомость", "черновые работы", "чистовая отделка", "инженерная координация"], requiredEquipmentOrWarnings: ["малая механизация", "пылеудаление"], requiredLogisticsOrWarnings: ["доставка по этапам", "вывоз строительного мусора"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["fitout_sq_m", "systems_set"] }),
  e({ domain: "apartment_renovation", terms: ["квартира", "капремонт", "ремонт квартиры"], casePhrases: ["капитальный ремонт квартиры", "ремонт квартиры под ключ", "черновой ремонт квартиры", "косметический ремонт квартиры", "ремонт студии"], category: "other", object: "apartment_renovation", operation: "renovation", method: "apartment_renovation", materialSystem: "renovation_system", complexity: "complex", requiredMaterials: ["черновые смеси", "финишные покрытия", "электрика и сантехника warning", "расходники"], requiredLabor: ["обмер квартиры", "демонтаж warning", "черновая отделка", "чистовая отделка"], requiredEquipmentOrWarnings: ["перфоратор", "пылезащита"], requiredLogisticsOrWarnings: ["доставка материалов", "вывоз мусора"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["renovation_sq_m", "rooms_pcs"] }),
  e({ domain: "house_renovation", terms: ["дом", "коттедж", "ремонт дома"], casePhrases: ["ремонт частного дома", "реконструкция дома", "отделка коттеджа", "ремонт фасада и кровли дома", "инженерия дома"], category: "other", object: "house_renovation", operation: "renovation", method: "house_renovation", materialSystem: "house_renovation_system", complexity: "complex", requiredMaterials: ["строительные материалы дома", "инженерные комплектующие", "утеплитель warning", "финишные покрытия"], requiredLabor: ["обследование дома", "черновые работы", "инженерные работы", "чистовая отделка"], requiredEquipmentOrWarnings: ["леса warning", "малая механизация"], requiredLogisticsOrWarnings: ["доставка на участок", "контейнер для отходов"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["house_sq_m", "systems_set"] }),
  e({ domain: "bathroom_renovation", terms: ["ванн", "сануз", "душев"], casePhrases: ["ремонт ванной", "ремонт санузла", "душевая под ключ", "замена плитки в ванной", "гидроизоляция санузла"], category: "tile", object: "bathroom_renovation", operation: "renovation", method: "wet_room_renovation", materialSystem: "bathroom_system", complexity: "complex", requiredMaterials: ["гидроизоляция", "плитка", "сантехника", "клей и затирка"], requiredLabor: ["демонтаж warning", "гидроизоляция санузла", "укладка плитки", "монтаж сантехники"], requiredEquipmentOrWarnings: ["плиткорез", "испытание водоснабжения"], requiredLogisticsOrWarnings: ["доставка плитки", "вынос мусора"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["bathroom_sq_m", "fixtures_pcs"] }),
  e({ domain: "kitchen_renovation", terms: ["кухн", "кухонный", "фартук"], casePhrases: ["ремонт кухни", "кухонный фартук", "монтаж кухни и плитки", "замена коммуникаций кухни", "отделка кухни"], category: "tile", object: "kitchen_renovation", operation: "renovation", method: "kitchen_renovation", materialSystem: "kitchen_system", complexity: "complex", requiredMaterials: ["плитка фартука", "электрика кухни warning", "сантехнические подключения", "финишные покрытия"], requiredLabor: ["подготовка стен", "укладка фартука", "подключение коммуникаций", "чистовая отделка"], requiredEquipmentOrWarnings: ["плиткорез", "тестер"], requiredLogisticsOrWarnings: ["доставка материалов", "защита мебели warning"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["kitchen_sq_m", "backsplash_sq_m"] }),
  e({ domain: "staircases", terms: ["лестниц", "ступен", "перила"], casePhrases: ["монтаж лестницы", "бетонная лестница", "металлическая лестница", "облицовка ступеней", "установка перил"], category: "carpentry", object: "staircase", operation: "installation", method: "staircase_install", materialSystem: "staircase_system", complexity: "complex", requiredMaterials: ["ступени", "косоур / каркас", "перила", "крепеж лестницы"], requiredLabor: ["обмер проема", "монтаж каркаса", "монтаж ступеней", "установка перил"], requiredEquipmentOrWarnings: ["подъем и фиксация", "сварка warning"], requiredLogisticsOrWarnings: ["доставка лестницы", "подъем элементов"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["stairs_pcs", "railing_linear_m"] }),
  e({ domain: "retaining_walls", terms: ["подпорн", "габион", "стена удержания"], casePhrases: ["подпорная стена", "габионная подпорная стенка", "бетонная подпорная стена", "дренаж подпорной стены", "усиление откоса"], category: "roadworks", object: "retaining_wall", operation: "installation", method: "retaining_wall_system", materialSystem: "retaining_wall_system", complexity: "infrastructure", requiredMaterials: ["бетон / габионы", "арматура", "дренаж за стеной", "щебень"], requiredLabor: ["разметка стены", "земляные работы", "монтаж стены", "устройство дренажа"], requiredEquipmentOrWarnings: ["экскаватор", "бетононасос warning"], requiredLogisticsOrWarnings: ["доставка инертных", "вывоз грунта"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["wall_linear_m", "concrete_m3"] }),
  e({ domain: "site_preparation", terms: ["подготовка площадки", "расчистка", "планировка территории"], casePhrases: ["подготовка строительной площадки", "расчистка участка", "планировка территории", "снятие плодородного слоя", "временный подъезд"], category: "roadworks", object: "site_preparation", operation: "preparation", method: "site_preparation", materialSystem: "site_preparation_system", complexity: "medium", requiredMaterials: ["геотекстиль warning", "щебень warning", "временное ограждение", "расходники разметки"], requiredLabor: ["обследование участка", "расчистка", "планировка", "организация подъезда"], requiredEquipmentOrWarnings: ["экскаватор / погрузчик", "самосвал"], requiredLogisticsOrWarnings: ["вывоз мусора", "доставка инертных"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["site_sq_m", "haulage_trip"] }),
  e({ domain: "landscaping", terms: ["газон", "озеленен", "ландшафт", "посадк"], casePhrases: ["устройство газона", "озеленение участка", "посадка деревьев", "ландшафтные работы", "планировка грунта под газон"], category: "landscaping", object: "landscaping_scope", operation: "installation", method: "landscaping_install", materialSystem: "landscaping_system", complexity: "medium", requiredMaterials: ["растительный грунт", "семена / рулонный газон", "удобрения", "посадочный материал"], requiredLabor: ["планировка грунта", "посев / укладка газона", "посадка растений", "первичный полив"], requiredEquipmentOrWarnings: ["культиватор", "каток для газона"], requiredLogisticsOrWarnings: ["доставка грунта", "вывоз лишнего грунта"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["landscaping_sq_m", "plants_pcs"] }),
  e({ domain: "irrigation", terms: ["полив", "орошен", "ирригац", "автополив"], casePhrases: ["монтаж автополива", "система орошения газона", "капельный полив", "полив участка", "разводка спринклеров"], category: "landscaping", object: "irrigation_system", operation: "installation", method: "irrigation_pipework", materialSystem: "irrigation_system", complexity: "medium", requiredMaterials: ["трубы полива", "спринклеры / капельная линия", "клапаны", "контроллер полива"], requiredLabor: ["схема зон полива", "траншеи под трубы", "монтаж труб", "настройка контроллера"], requiredEquipmentOrWarnings: ["тестер давления", "мини-траншеекопатель warning"], requiredLogisticsOrWarnings: ["доставка труб", "обратная засыпка"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["irrigation_zones_pcs", "pipe_linear_m"] }),
  e({ domain: "sauna_lighting_system", terms: ["подсветка сауны", "подсветки сауны", "сауны хаммамы", "бани сауны хаммамы"], casePhrases: ["монтаж подсветки сауны", "подсветка сауны", "ремонт подсветки сауны", "пусконаладка подсветки сауны"], category: "electrical", object: "sauna_lighting_system", operation: "installation", method: "sauna_lighting_install", materialSystem: "sauna_lighting_system", complexity: "medium", requiredMaterials: ["термостойкая LED-подсветка сауны", "влагозащищенные блоки питания", "термостойкий кабель", "профили и крепления для подсветки"], requiredLabor: ["обследование парной и влажных зон", "монтаж термостойкой подсветки", "прокладка кабельных линий", "проверка сценариев и защиты"], requiredEquipmentOrWarnings: ["тестер изоляции", "ручной электромонтажный инструмент", "работа во влажной зоне warning"], requiredLogisticsOrWarnings: ["доставка комплектов подсветки", "защита отделки сауны при работах"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["fixture_pcs", "linear_m"] }),
  e({ domain: "theatrical_lighting_hanger_system", terms: ["световые подвесы", "световых подвесов", "сцены театральное оборудование", "театральное оборудование", "сценическое освещение"], casePhrases: ["монтаж световых подвесов", "световые подвесы сцены", "проектирование световых подвесов", "пусконаладка сценического освещения"], category: "electrical", object: "theatrical_lighting_hanger_system", operation: "installation", method: "theatrical_lighting_hanger_install", materialSystem: "theatrical_lighting_hanger_system", complexity: "complex", requiredMaterials: ["световые подвесы и фермы", "сценические светильники", "силовые и DMX-линии", "крепеж и страховочные тросы"], requiredLabor: ["разметка подвесов сцены", "монтаж несущих подвесов", "подключение светового оборудования", "ПНР сценических сценариев"], requiredEquipmentOrWarnings: ["подъемник warning", "тестер линий управления", "такелажный инструмент"], requiredLogisticsOrWarnings: ["доставка сценического оборудования", "исполнительная документация по подвесам"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["hanger_pcs", "fixture_pcs"] }),
  e({ domain: "salt_room_lighting_system", terms: ["подсветка соляной комнаты", "подсветки соляной комнаты", "соляной комнаты", "соляные комнаты оздоровительные"], casePhrases: ["монтаж подсветки соляной комнаты", "подсветка соляной комнаты", "ремонт подсветки соляной комнаты", "пусконаладка подсветки соляной комнаты"], category: "electrical", object: "salt_room_lighting_system", operation: "installation", method: "salt_room_lighting_install", materialSystem: "salt_room_lighting_system", complexity: "medium", requiredMaterials: ["влагозащищенная подсветка соляной комнаты", "антикоррозионный профиль", "блоки питания и диммеры", "кабельные линии в защитной оболочке"], requiredLabor: ["обследование соляной комнаты", "монтаж профиля и световых линий", "герметизация подключений", "проверка режимов подсветки"], requiredEquipmentOrWarnings: ["тестер изоляции", "ручной электромонтажный инструмент", "антикоррозионная защита warning"], requiredLogisticsOrWarnings: ["доставка комплектов подсветки", "защита соляной отделки при работах"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["linear_m", "fixture_pcs"] }),
  e({ domain: "automation_commissioning_system", terms: ["пусконаладка автоматики", "пусконаладки автоматики", "испытания и пусконаладка систем", "пусконаладка систем"], casePhrases: ["пусконаладка автоматики", "испытания и пусконаладка систем автоматики", "профессиональная смета на пусконаладку автоматики", "смета на пусконаладку автоматики"], category: "electrical", object: "automation_commissioning_system", operation: "commissioning", method: "automation_commissioning", materialSystem: "automation_commissioning_system", complexity: "complex", requiredMaterials: ["комплект маркировки и протоколов", "расходные материалы для проверок", "сервисные кабели и адаптеры", "резервные клеммы и предохранители"], requiredLabor: ["проверка цепей автоматики", "настройка контроллеров", "функциональные испытания", "оформление протоколов ПНР"], requiredEquipmentOrWarnings: ["мультиметр и токовые клещи", "ноутбук с ПО контроллеров", "имитаторы сигналов warning"], requiredLogisticsOrWarnings: ["выезд инженера ПНР", "исполнительная документация и протоколы"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["io_points_pcs", "commissioning_set"] }),
  e({ domain: "outdoor_lighting_system", terms: ["опоры освещения", "опор освещения", "наружное освещение", "архитектурная подсветка", "архитектурной подсветки", "парковое освещение", "паркового освещения", "фотореле", "заземление опор"], casePhrases: ["проектирование и монтаж опор освещения", "монтаж архитектурной подсветки", "монтаж паркового освещения", "монтаж фотореле освещения"], category: "electrical", object: "outdoor_lighting_system", operation: "installation", method: "outdoor_lighting_install", materialSystem: "outdoor_lighting_system", complexity: "complex", requiredMaterials: ["опоры освещения", "светильники наружного освещения", "кабельные линии освещения", "заземление и фотореле"], requiredLabor: ["разметка трасс и опор", "монтаж опор и светильников", "прокладка кабеля", "ПНР управления освещением"], requiredEquipmentOrWarnings: ["автовышка", "кабельный тестер", "измеритель заземления warning"], requiredLogisticsOrWarnings: ["доставка опор и светильников", "исполнительная документация"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["lighting_poles_pcs", "fixture_pcs"] }),
  e({ domain: "fountain_lighting_system", terms: ["подсветка фонтана", "подсветки фонтана", "фонтанная подсветка"], casePhrases: ["устройство подсветки фонтана", "монтаж подсветки фонтана", "ремонт подсветки фонтана", "пусконаладка подсветки фонтана"], category: "electrical", object: "fountain_lighting_system", operation: "installation", method: "fountain_lighting_install", materialSystem: "fountain_lighting_system", complexity: "complex", requiredMaterials: ["подводные светильники", "герметичные кабельные вводы", "блоки питания и защиты", "кабельные линии фонтана"], requiredLabor: ["обследование чаши и ниш", "монтаж светильников", "герметизация вводов", "ПНР сценариев подсветки"], requiredEquipmentOrWarnings: ["тестер изоляции", "герметизационный инструмент", "работа у воды warning"], requiredLogisticsOrWarnings: ["доставка светильников", "защита оборудования от влаги"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["fixture_pcs", "cable_linear_m"] }),
  e({ domain: "fire_pump_station", terms: ["пожарная насосная станция", "пожарной насосной станции", "насосная станция пожаротушения"], casePhrases: ["проектирование и монтаж пожарной насосной станции", "монтаж насосной станции пожаротушения"], category: "plumbing", object: "fire_pump_station", operation: "installation", method: "fire_pump_station_install", materialSystem: "fire_pump_station_system", complexity: "infrastructure", requiredMaterials: ["пожарные насосы", "шкаф управления насосами", "трубная обвязка", "запорная арматура и датчики давления"], requiredLabor: ["обследование насосной", "монтаж насосов", "обвязка трубопроводов", "ПНР пожарной насосной станции"], requiredEquipmentOrWarnings: ["такелаж насосов", "манометры и тестер", "лицензированный подрядчик warning"], requiredLogisticsOrWarnings: ["доставка насосов", "исполнительная документация"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["pump_pcs", "pipe_linear_m"] }),
  e({ domain: "boiler_automation_system", terms: ["автоматика котельной", "автоматики котельной", "котельная автоматика"], casePhrases: ["проектирование и монтаж автоматики котельной", "монтаж автоматики котельной", "ПНР автоматики котельной"], category: "electrical", object: "boiler_automation_system", operation: "installation", method: "boiler_automation_install", materialSystem: "boiler_automation_system", complexity: "complex", requiredMaterials: ["шкаф автоматики котельной", "контроллеры и датчики", "исполнительные клапаны", "кабельные линии управления"], requiredLabor: ["обследование котельной", "монтаж автоматики", "подключение датчиков и клапанов", "ПНР алгоритмов котельной"], requiredEquipmentOrWarnings: ["газоанализатор warning", "программатор контроллеров", "тестер цепей"], requiredLogisticsOrWarnings: ["доставка автоматики", "исполнительная документация"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["power_kw", "io_points_pcs"] }),
  e({ domain: "heat_point_automation_system", terms: ["автоматика итп", "автоматики итп", "автоматизация итп", "итп"], casePhrases: ["монтаж автоматики ИТП", "проектирование и монтаж автоматики ИТП", "пусконаладка автоматики ИТП", "ремонт автоматики ИТП", "замена автоматики ИТП"], category: "heating_hvac", object: "heat_point_automation_system", operation: "installation", method: "heat_point_automation_install", materialSystem: "heat_point_automation_system", complexity: "complex", requiredMaterials: ["шкаф автоматики ИТП", "контроллер теплового пункта", "датчики температуры и давления", "исполнительные клапаны"], requiredLabor: ["обследование ИТП", "монтаж автоматики", "подключение теплообменников", "ПНР погодозависимого регулирования"], requiredEquipmentOrWarnings: ["теплотехнические измерения", "программатор контроллеров", "проверка защит warning"], requiredLogisticsOrWarnings: ["доставка шкафа автоматики", "исполнительная документация"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["heat_exchanger_pcs", "power_kw"] }),
  e({ domain: "entrance_group_automation", terms: ["автоматика входной группы", "автоматики входной группы", "входная группа автоматика"], casePhrases: ["ремонт автоматики входной группы", "пусконаладка автоматики входной группы", "замена автоматики входной группы"], category: "doors_windows", object: "entrance_group_automation", operation: "installation", method: "entrance_group_automation_service", materialSystem: "entrance_group_automation_system", complexity: "medium", requiredMaterials: ["контроллер входной группы", "датчики створок", "приводы и блоки питания", "кабельные линии"], requiredLabor: ["диагностика автоматики", "замена датчиков и приводов", "настройка контроллера", "ПНР сценариев входной группы"], requiredEquipmentOrWarnings: ["тестер цепей", "набор для регулировки приводов"], requiredLogisticsOrWarnings: ["доставка комплектующих", "маркировка кабелей"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["leaf_pcs", "sensor_pcs"] }),
  e({ domain: "illuminated_signage", terms: ["световая вывеска", "световой вывески", "подсветка вывески", "подсветки вывески", "вывеска"], casePhrases: ["монтаж световой вывески", "изготовление и монтаж световой вывески", "ремонт световой вывески", "монтаж подсветки вывески"], category: "electrical", object: "illuminated_signage", operation: "installation", method: "illuminated_signage_install", materialSystem: "illuminated_signage_system", complexity: "medium", requiredMaterials: ["световые модули", "корпус и буквы вывески", "блоки питания", "кабель и крепеж"], requiredLabor: ["замер фасада", "изготовление элементов", "монтаж вывески", "подключение подсветки"], requiredEquipmentOrWarnings: ["автовышка warning", "тестер цепей", "ручной инструмент"], requiredLogisticsOrWarnings: ["доставка вывески", "подъем и крепление"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["sign_pcs", "letters_pcs"] }),
  e({ domain: "furniture_lighting_system", terms: ["мебельная подсветка", "мебельной подсветки", "подсветка мебели"], casePhrases: ["изготовление и монтаж мебельной подсветки", "монтаж мебельной подсветки", "ремонт мебельной подсветки", "комплексное изготовление мебельной подсветки"], category: "carpentry", object: "furniture_lighting_system", operation: "installation", method: "furniture_lighting_install", materialSystem: "furniture_lighting_system", complexity: "medium", requiredMaterials: ["LED-профиль и лента", "блоки питания", "датчики включения", "кабельные линии мебели"], requiredLabor: ["замер мебели", "монтаж LED-профиля", "подключение блоков питания", "проверка сценариев подсветки"], requiredEquipmentOrWarnings: ["паяльный инструмент", "тестер цепей", "ручной инструмент"], requiredLogisticsOrWarnings: ["доставка комплектующих", "защита мебели при работах"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["linear_m", "items_pcs"] }),
  e({ domain: "energy_efficiency_lighting_audit", terms: ["энергоаудит здания", "энергоаудита здания", "энергоэффективность светильников"], casePhrases: ["монтаж энергоаудита здания", "энергоаудит здания по светильникам", "модернизация освещения после энергоаудита"], category: "electrical", object: "energy_efficiency_lighting_scope", operation: "audit", method: "energy_efficiency_lighting_audit", materialSystem: "energy_efficiency_lighting_system", complexity: "medium", requiredMaterials: ["измерительные приборы", "реестр светильников", "датчики потребления", "отчетные материалы"], requiredLabor: ["инвентаризация светильников", "замеры освещенности", "анализ потребления", "подготовка рекомендаций"], requiredEquipmentOrWarnings: ["люксметр", "энергоанализатор warning", "ноутбук"], requiredLogisticsOrWarnings: ["выезд специалиста", "оформление отчета"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["fixture_pcs", "audit_set"] }),
  e({ domain: "fire_damper_system", terms: ["пожарный клапан", "пожарных клапанов", "противопожарный клапан", "клапаны пожаротушения"], casePhrases: ["проектирование и монтаж пожарных клапанов", "монтаж противопожарных клапанов", "пожарные клапаны системы дымоудаления"], category: "heating_hvac", object: "fire_damper_system", operation: "installation", method: "regulated_fire_damper_install", materialSystem: "fire_damper_system", complexity: "complex", requiredMaterials: ["противопожарные клапаны", "огнестойкий кабель управления", "крепеж и монтажные рамы", "блоки управления клапанами"], requiredLabor: ["обследование проектных отметок", "монтаж пожарных клапанов", "подключение цепей управления", "испытание сценариев пожарной автоматики"], requiredEquipmentOrWarnings: ["подъемник", "измерительные приборы", "лицензированный подрядчик warning"], requiredLogisticsOrWarnings: ["доставка клапанов", "исполнительная документация"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["damper_pcs", "control_cable_linear_m"], regulatedSafetyRequired: true }),
  e({ domain: "automation_control_cabinet", terms: ["шкаф автоматики", "шкафа автоматики", "шкаф управления автоматики", "программирование шкафа автоматики"], casePhrases: ["монтаж шкафа автоматики", "проектирование и монтаж шкафа автоматики", "пусконаладка шкафа автоматики", "программирование шкафа автоматики"], category: "electrical", object: "automation_control_cabinet", operation: "installation", method: "automation_control_cabinet_install", materialSystem: "automation_control_cabinet_system", complexity: "complex", requiredMaterials: ["шкаф автоматики", "контроллеры и модули ввода-вывода", "датчики и исполнительные цепи", "кабель управления и маркировка"], requiredLabor: ["обследование точек подключения", "сборка и монтаж шкафа автоматики", "прокладка цепей управления", "программирование и ПНР контроллеров"], requiredEquipmentOrWarnings: ["тестер цепей", "ноутбук и конфигуратор контроллеров", "пусконаладочная лаборатория warning"], requiredLogisticsOrWarnings: ["доставка шкафа и контроллеров", "исполнительная документация"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["io_points_pcs", "cabinet_set"] }),
  e({ domain: "pump_automation_control", terms: ["автоматика насосной", "насосной автоматики", "автоматики насосной", "шкаф насосной автоматики"], casePhrases: ["проектирование и монтаж автоматики насосной", "монтаж автоматики насосной", "ПНР насосной автоматики"], category: "electrical", object: "pump_automation_control_system", operation: "installation", method: "pump_automation_control_install", materialSystem: "pump_automation_control_system", complexity: "complex", requiredMaterials: ["шкаф автоматики насосной", "датчики давления и уровня", "частотные приводы / пускатели", "кабельные линии управления"], requiredLabor: ["обследование насосной группы", "монтаж шкафа автоматики", "подключение датчиков и приводов", "ПНР алгоритмов насосной"], requiredEquipmentOrWarnings: ["мультиметр и токовые клещи", "программатор контроллеров", "проверка защит warning"], requiredLogisticsOrWarnings: ["доставка шкафа и датчиков", "маркировка кабелей"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["io_points_pcs", "pump_group_set"] }),
  e({ domain: "construction_site_lighting_service", terms: ["строительный городок", "строительного городка", "временное освещение"], casePhrases: ["обслуживание освещения строительного городка", "обслуживание строительного городка", "сервис временных светильников строительной площадки"], category: "electrical", object: "temporary_site_lighting", operation: "service", method: "temporary_site_lighting_maintenance", materialSystem: "temporary_site_lighting_system", complexity: "complex", requiredMaterials: ["светильники временного освещения", "кабельные линии временного питания", "крепеж и подвесы светильников", "защитная коммутация"], requiredLabor: ["обследование временной сети", "замена и обслуживание светильников", "проверка кабельных трасс", "испытание защитного отключения"], requiredEquipmentOrWarnings: ["электротехнический инструмент", "измеритель изоляции warning"], requiredLogisticsOrWarnings: ["доставка светильников и кабеля", "доступ к бытовому городку"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["fixture_pcs", "cable_linear_m"] }),
  e({ domain: "greenhouse_climate_automation", terms: ["автоматика микроклимата", "теплицы агрокомплексы", "теплиц", "агрокомплекс"], casePhrases: ["автоматика микроклимата теплиц", "монтаж автоматики микроклимата агрокомплекса", "автоматизация микроклимата тепличного комплекса"], category: "electrical", object: "greenhouse_climate_control_system", operation: "installation", method: "greenhouse_microclimate_automation", materialSystem: "greenhouse_climate_automation_system", complexity: "infrastructure", requiredMaterials: ["контроллеры микроклимата", "датчики температуры и влажности", "исполнительные клапаны и приводы", "шкаф автоматики и кабельные линии"], requiredLabor: ["обследование тепличных зон", "монтаж датчиков и контроллеров", "подключение исполнительных механизмов", "пусконаладка сценариев микроклимата"], requiredEquipmentOrWarnings: ["тестер и программатор контроллеров", "подъем к фермам теплицы warning"], requiredLogisticsOrWarnings: ["доставка автоматики на объект", "поэтапный доступ к тепличным секциям"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["greenhouse_zones_pcs", "controller_set"] }),
  e({ domain: "water_supply", terms: ["водоснабжен", "водомер", "насос", "скважинный насос"], casePhrases: ["монтаж водоснабжения", "ввод воды в дом", "установка насоса", "водомерный узел", "разводка холодной воды"], category: "plumbing", object: "water_supply_system", operation: "installation", method: "water_supply_pipework", materialSystem: "water_supply_system", complexity: "complex", requiredMaterials: ["водопроводные трубы", "насос / узел учета", "фитинги", "запорная арматура"], requiredLabor: ["разметка трассы", "монтаж труб", "установка насоса", "опрессовка"], requiredEquipmentOrWarnings: ["пресс-инструмент", "насос для испытаний"], requiredLogisticsOrWarnings: ["доставка труб", "доступ к вводу"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["water_pipe_linear_m", "nodes_pcs"] }),
  e({ domain: "gas_regulated", terms: ["газ", "газопровод", "газовый"], casePhrases: ["монтаж газопровода", "перенос газовой трубы", "газовое оборудование", "подключение газовой плиты", "наружный газопровод"], category: "heating_hvac", object: "gas_system", operation: "installation", method: "regulated_gas_system", materialSystem: "gas_system", complexity: "complex", requiredMaterials: ["газовая труба", "запорная арматура", "крепления", "сигнализатор газа warning"], requiredLabor: ["обследование газовой сети", "монтаж газопровода", "испытание герметичности", "сдача газовой службе"], requiredEquipmentOrWarnings: ["лицензированный подрядчик", "газоанализатор"], requiredLogisticsOrWarnings: ["доставка труб", "исполнительная документация"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["gas_pipe_linear_m", "valves_pcs"], regulatedSafetyRequired: true }),
  e({ domain: "boilers_regulated", terms: ["котел", "котельн", "бойлер", "теплогенератор"], casePhrases: ["монтаж котла", "котельная частного дома", "установка бойлера", "обвязка котла", "замена теплогенератора"], category: "heating_hvac", object: "boiler_system", operation: "installation", method: "regulated_boiler_install", materialSystem: "boiler_system", complexity: "complex", requiredMaterials: ["котел / бойлер", "дымоход warning", "насосная группа", "запорная арматура"], requiredLabor: ["обследование котельной", "монтаж котла", "обвязка котла", "ПНР котельной"], requiredEquipmentOrWarnings: ["газоанализатор warning", "лицензированный подрядчик"], requiredLogisticsOrWarnings: ["доставка котла", "согласования warning"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["boiler_set", "pipe_linear_m"], regulatedSafetyRequired: true }),
  e({ domain: "elevators_regulated", terms: ["лифт", "подъемник пассажир"], casePhrases: ["установка лифта пассажирского", "пассажирский лифт", "замена лифтового оборудования", "лифт на этажи", "монтаж лифтовой шахты warning"], category: "delivery_equipment", object: "passenger_elevator", operation: "installation", method: "licensed_elevator_installation", materialSystem: "passenger_elevator_system", complexity: "complex", requiredMaterials: ["пассажирская кабина", "лебедка / привод", "двери шахты", "направляющие"], requiredLabor: ["обследование шахты", "монтаж направляющих", "ПНР", "инспекция / сдача"], requiredEquipmentOrWarnings: ["только лицензированная организация", "такелаж"], requiredLogisticsOrWarnings: ["доставка лифтового оборудования", "подъем оборудования"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["elevator_set", "stops_pcs"], regulatedSafetyRequired: true }),
  e({ domain: "cranes_regulated", terms: ["кран", "кран-балк", "тельфер", "грузоподъем"], casePhrases: ["монтаж промышленного крана", "установка кран-балки", "монтаж тельфера", "грузоподъемное оборудование", "рельсовый путь крана"], category: "metalworks", object: "industrial_crane", operation: "installation", method: "regulated_crane_install", materialSystem: "industrial_crane_system", complexity: "infrastructure", requiredMaterials: ["крановое оборудование", "рельсовый путь", "анкера", "электропитание крана"], requiredLabor: ["обследование пролетов", "монтаж рельсов", "монтаж крана", "испытания грузоподъемности"], requiredEquipmentOrWarnings: ["кран для монтажа", "лицензированный подрядчик"], requiredLogisticsOrWarnings: ["доставка оборудования", "такелажный план"], exclusions: sharedExclusions, clarifyingQuestions: sharedQuestions, unitRules: ["crane_set", "rail_linear_m"], regulatedSafetyRequired: true }),
];

export type EstimatorResolvedDomainSignature = {
  workKey: string;
  titleRu: string;
  category: GlobalWorkCategory;
  domain: string;
  object: string;
  operation: string;
  method: string;
  materialSystem: string;
  complexity: EstimatorKernelComplexity;
  requiredMaterials: string[];
  requiredLabor: string[];
  requiredEquipmentOrWarnings: string[];
  requiredLogisticsOrWarnings: string[];
  exclusions: string[];
  clarifyingQuestions: string[];
};

function workKeyForEstimatorDomain(entry: EstimatorDomainLexiconEntry): string {
  if (entry.domain === "well_drilling") return "well_drilling_professional";
  return `dynamic_${entry.domain}_estimate`;
}

export function resolveEstimatorDomainSignature(text: string): EstimatorResolvedDomainSignature | null {
  const normalized = normalizeDimensionText(text);
  const matches = ESTIMATOR_DOMAIN_LEXICON
    .flatMap((item) =>
      [...item.terms, ...item.casePhrases]
        .map((term) => ({ item, term: normalizeDimensionText(term) }))
        .filter(({ term }) => term.length > 0 && normalized.includes(term)),
    );
  const demolitionDominant = /^(?:смета\s+на\s+)?(?:демонтаж|снос|разборк)/.test(normalized);
  const primaryWorkMatches = demolitionDominant ? matches : matches.filter(({ item }) => item.domain !== "demolition");
  const match = (primaryWorkMatches.length > 0 ? primaryWorkMatches : matches)
    .sort((left, right) => right.term.length - left.term.length)[0];
  if (!match) return null;
  const entry = match.item;
  return {
    workKey: workKeyForEstimatorDomain(entry),
    titleRu: `Профессиональная предварительная смета: ${entry.casePhrases[0]}`,
    category: entry.category,
    domain: entry.domain,
    object: entry.object,
    operation: entry.operation,
    method: entry.method,
    materialSystem: entry.materialSystem,
    complexity: entry.complexity,
    requiredMaterials: [...entry.requiredMaterials],
    requiredLabor: [...entry.requiredLabor],
    requiredEquipmentOrWarnings: [...entry.requiredEquipmentOrWarnings],
    requiredLogisticsOrWarnings: [...entry.requiredLogisticsOrWarnings],
    exclusions: [...entry.exclusions],
    clarifyingQuestions: [...entry.clarifyingQuestions],
  };
}
