export const UI = {
  bg: "#0B0F14",
  cardBg: "#101826",
  text: "#F8FAFC",
  sub: "#9CA3AF",
  border: "#1F2A37",
  btnApprove: "#22C55E",
  btnReject: "#EF4444",
  btnNeutral: "rgba(255,255,255,0.08)",
  accent: "#22C55E",
} as const;

export const TYPO = {
  titleLg: { fontSize: 22, fontWeight: "600" as const },
  titleSm: { fontSize: 16, fontWeight: "600" as const },
  sectionTitle: { fontSize: 14, fontWeight: "600" as const },
  groupTitle: { fontSize: 16, fontWeight: "600" as const },
  bodyStrong: { fontSize: 14, fontWeight: "600" as const },
  body: { fontSize: 14, fontWeight: "500" as const },
  meta: { fontSize: 13, fontWeight: "400" as const, letterSpacing: 0 },
  kpiLabel: { fontSize: 12, fontWeight: "500" as const },
  kpiValue: { fontSize: 12, fontWeight: "600" as const },
  btn: { fontSize: 13, fontWeight: "600" as const, letterSpacing: 0 },
} as const;

export const REQUEST_STATUS_STYLES: Record<string, { label: string; bg: string; fg: string }> = {
  draft: { label: "Черновик", bg: "#E2E8F0", fg: "#0F172A" },
  pending: { label: "На утверждении", bg: "#FEF3C7", fg: "#92400E" },
  approved: { label: "Утверждена", bg: "#DCFCE7", fg: "#166534" },
  rejected: { label: "Отклонена", bg: "#FEE2E2", fg: "#991B1B" },
  cancelled: { label: "\u041e\u0442\u043c\u0435\u043d\u0435\u043d\u0430", bg: "#E5E7EB", fg: "#374151" },
};

export const FOREMAN_TEXT = {
  errorTitle: "Ошибка",
  fillHeaderTitle: "Заполни шапку",
  fillForeman: "Укажи ФИО прораба.",
  fillObject: "Выбери объект строительства.",
  fillLevel: "Выбери этаж/уровень.",
  readonlyTitle: "Просмотр заявки",
  readonlyHint: "Редактирование доступно только в текущем черновике.",
  historyTitle: "История",
  historyLoadError: "Не удалось загрузить историю заявок.",
  draftCreateError: "Не удалось создать черновик",
  calcAddError: "Не удалось добавить рассчитанные позиции",
  catalogAddError: "Не удалось добавить позиции",
  qtyTitle: "Количество",
  qtyPositiveHint: "Значение должно быть больше нуля.",
  qtyUpdateError: "Не удалось обновить количество.",
  submitEmptyTitle: "Пустая заявка",
  submitEmptyHint: "Сначала добавь хотя бы одну позицию.",
  submitSentTitle: "Отправлено",
  submitError: "Не удалось отправить на утверждение",
  deleteConfirmTitle: "Отменить позицию?",
  deleteConfirmFallback: "Позиция",
  deleteDone: "Позиция удалена",
  deleteDraftError: "Не удалось удалить черновик",
  sendToDirectorError: "Не удалось отправить директору",
  submitNeedDraftHint: "Чтобы отправить, вернись к текущему черновику.",
} as const;
