type ExpandedFamilySource = {
  work_family_id?: unknown;
  professionalNameRu?: unknown;
};

export type PublicRussianIdentityR555 = {
  titleRu: string;
  aliasesRu: string[];
  lexiconVersion: "PUBLIC_RUSSIAN_LEXICON_R555_V1";
};

const BASE_CATEGORY_TITLE_LABELS_R555: Readonly<Record<string, string>> = Object.freeze({
  earthworks: "земляные работы",
  insulation: "теплоизоляция",
  paving_roads_landscape: "дорожные покрытия и благоустройство",
  special_repair: "специальный ремонт",
  ventilation: "вентиляция",
  waterproofing: "гидроизоляция",
});

export function resolveBasePublicRussianTitleR555(input: {
  localizedNameRu: string;
  category: string;
  duplicateTitleCount: number;
}): string {
  if (input.duplicateTitleCount <= 1) return input.localizedNameRu;
  const categoryTitle = BASE_CATEGORY_TITLE_LABELS_R555[input.category];
  if (!categoryTitle) throw new Error(`R555_BASE_PUBLIC_CATEGORY_TITLE_MISSING:${input.category}`);
  return `${input.localizedNameRu} (раздел: ${categoryTitle})`;
}

const PREFIX = {
  facade: "Фасады, высотное остекление и доступ",
  roof: "Кровля, мансарды и кровельные окна",
  transport: "Дороги, транспорт и площадки",
  bridge: "Мосты, тоннели и инженерные сооружения",
  water: "Водоснабжение сёл и наружные сети воды",
  sewer: "Канализация, дренаж и очистные сооружения",
  hydraulic: "Дамбы, гидротехника и орошение",
  electric: "Электроснабжение, ЛЭП и подстанции",
  utility: "Подведение инженерных сетей",
  pipeline: "Газ, теплосети и промышленные трубопроводы",
  energy: "ТЭЦ, ГЭС, котельные и энергетика",
  industrial: "Промышленные здания, ангары и склады",
  storage: "Резервуары, силосы и хранилища",
  ecology: "Экология, отходы и очистка территории",
  mining: "Горные работы, карьеры и крупные земляные работы",
  building: "Инженерные системы зданий",
} as const;

function title(prefix: keyof typeof PREFIX, name: string): string {
  return `${PREFIX[prefix]}: ${name}`;
}

/**
 * Reviewed replacements for every expanded-complex title that contained
 * English prose in the R5.5.4 source. Internal family IDs stay stable, but
 * none of them are permitted to become a public title or public search alias.
 */
export const PUBLIC_RUSSIAN_TITLE_REPLACEMENTS_R555: Readonly<Record<string, string>> = Object.freeze({
  mast_climber_facade_work: title("facade", "фасадные работы с мачтового подъёмника"),
  rope_access_facade_work: title("facade", "фасадные работы методом промышленного альпинизма"),
  skylight_systems: title("facade", "системы зенитных фонарей"),
  atrium_glazing: title("facade", "остекление атриума"),
  roof_lanterns: title("facade", "кровельные световые фонари"),
  standing_seam_roof: title("roof", "фальцевая кровля"),
  underroof_membrane: title("roof", "подкровельная мембрана"),
  battens_counterbattens: title("roof", "обрешётка и контробрешётка"),
  flashings_around_roof_windows: title("roof", "монтаж окладов кровельных окон"),
  snow_guards: title("roof", "снегозадержатели"),
  roof_safety_systems: title("roof", "системы безопасности кровли"),
  roof_access_hatches: title("roof", "люки выхода на кровлю"),
  cement_concrete_pavement: title("transport", "цементобетонное покрытие"),
  road_lighting: title("transport", "дорожное освещение"),
  bridge_approach_roads: title("transport", "дороги на подходах к мосту"),
  railway_track_bed: title("transport", "основание железнодорожного пути"),
  retaining_walls_transport: title("transport", "подпорные стены транспортных сооружений"),
  box_culvert: title("bridge", "прямоугольная водопропускная труба"),
  pipe_culvert: title("bridge", "круглая водопропускная труба"),
  water_meter_chambers: title("water", "камеры водомерных узлов"),
  flushing_disinfection: title("water", "промывка и дезинфекция водопровода"),
  septic_treatment_facility: title("sewer", "септические очистные сооружения"),
  rainwater_inlets: title("sewer", "дождеприёмники"),
  geomembrane_lining: title("hydraulic", "противофильтрационная облицовка геомембраной"),
  geotextile_layers: title("hydraulic", "слои геотекстиля"),
  water_control_gates: title("hydraulic", "водорегулирующие затворы"),
  hydraulic_steel_structures: title("hydraulic", "стальные гидротехнические конструкции"),
  flood_protection_embankment: title("hydraulic", "противопаводковая насыпь"),
  package_transformer_substation: title("electric", "комплектная трансформаторная подстанция"),
  outdoor_switchgear: title("electric", "открытое распределительное устройство"),
  distribution_board_outdoor: title("electric", "наружный распределительный щит"),
  street_lighting_poles: title("electric", "опоры уличного освещения"),
  electrical_testing_commissioning: title("electric", "испытания и пусконаладка электрооборудования"),
  road_crossing_sleeves: title("utility", "футляры инженерных сетей под дорогой"),
  service_chambers: title("utility", "эксплуатационные камеры инженерных сетей"),
  inspection_wells: title("utility", "смотровые колодцы"),
  testing_commissioning: title("utility", "испытания и пусконаладка инженерных сетей"),
  temporary_utilities_construction: title("utility", "временные инженерные сети строительной площадки"),
  external_engineering_networks: title("utility", "наружные инженерные сети"),
  gas_pipeline_medium_pressure: title("pipeline", "газопровод среднего давления"),
  district_heating_pipeline: title("pipeline", "трубопровод централизованного теплоснабжения"),
  heat_chamber: title("pipeline", "тепловая камера"),
  process_piping_dn50_dn1200: title("pipeline", "технологический трубопровод номинальным диаметром 50–1200 мм"),
  chimney_stack: title("energy", "дымовая труба"),
  fuel_oil_facility: title("energy", "мазутное хозяйство"),
  coal_handling_system: title("energy", "система топливоподачи угля"),
  ash_handling_system: title("energy", "система золоудаления"),
  water_intake_hpp: title("energy", "водозабор гидроэлектростанции"),
  turbine_installation_hpp: title("energy", "монтаж турбины гидроэлектростанции"),
  cable_trench_energy: title("energy", "кабельная траншея энергетического объекта"),
  control_building_energy: title("energy", "здание управления энергетического объекта"),
  commissioning_energy_facility: title("energy", "пусконаладка энергетического объекта"),
  cable_tray_gallery: title("industrial", "галерея кабельных лотков"),
  industrial_earthworks: title("industrial", "земляные работы промышленного объекта"),
  chemical_resistant_floor: title("industrial", "химически стойкий пол"),
  refrigeration_equipment_foundation: title("industrial", "фундамент холодильного оборудования"),
  grain_silo: title("storage", "зерновой силос"),
  tank_foundation_ring: title("storage", "кольцевой фундамент резервуара"),
  leachate_collection: title("ecology", "сбор фильтрата"),
  composting_facility: title("ecology", "сооружение компостирования"),
  incineration_facility_civil: title("ecology", "строительная часть мусоросжигательного сооружения"),
  remediation_earthworks: title("ecology", "земляные работы при рекультивации"),
  dust_suppression_system: title("ecology", "система пылеподавления"),
  environmental_monitoring_wells: title("ecology", "скважины экологического мониторинга"),
  blasting_preparation: title("mining", "подготовка к буровзрывным работам"),
  slope_reinforcement: title("mining", "укрепление откоса"),
  ore_processing_foundations: title("mining", "фундаменты оборудования обогащения руды"),
  HVAC_plant_room: title("building", "машинное помещение систем отопления, вентиляции и кондиционирования"),
  ventilation_system: title("building", "система вентиляции"),
  smoke_exhaust_system: title("building", "система дымоудаления"),
  fire_fighting_pump_station: title("building", "насосная станция пожаротушения"),
  sprinkler_system: title("building", "спринклерная система пожаротушения"),
  fire_alarm_system: title("building", "система пожарной сигнализации"),
  low_voltage_system: title("building", "слаботочная система"),
  CCTV_system: title("building", "система видеонаблюдения"),
  access_control_system: title("building", "система контроля и управления доступом"),
  BMS_system: title("building", "система автоматизации здания"),
  elevators: title("building", "лифты"),
  escalators: title("building", "эскалаторы"),
  generator_backup_system: title("building", "резервная генераторная установка"),
  UPS_system: title("building", "система бесперебойного электропитания"),
  data_center_mep: title("building", "инженерные системы центра обработки данных"),
  server_room_cooling: title("building", "система охлаждения серверного помещения"),
});

const PUBLIC_RUSSIAN_REVIEWED_ADDITIONAL_TITLES_R555: Readonly<Record<string, string>> = Object.freeze({
  private_house_construction: title("building", "строительство частного дома").replace(PREFIX.building, "Здания и жилые комплексы"),
  cottage_construction: "Здания и жилые комплексы: строительство коттеджа",
  multi_storey_residential_building: "Здания и жилые комплексы: строительство многоэтажного жилого дома",
  high_rise_building: "Здания и жилые комплексы: строительство высотного здания",
  apartment_complex: "Здания и жилые комплексы: строительство жилого комплекса",
  administrative_building: "Здания и жилые комплексы: строительство административного здания",
  school_building: "Здания и жилые комплексы: строительство школы",
  hospital_building: "Здания и жилые комплексы: строительство больницы",
  shopping_center: "Здания и жилые комплексы: строительство торгового центра",
  hotel_building: "Здания и жилые комплексы: строительство гостиницы",
  parking_structure: "Здания и жилые комплексы: строительство многоуровневого паркинга",
  underground_parking: "Здания и жилые комплексы: строительство подземного паркинга",
  monolithic_frame: "Здания и жилые комплексы: устройство монолитного каркаса",
  precast_concrete_frame: "Здания и жилые комплексы: монтаж сборного железобетонного каркаса",
  steel_frame_building: "Здания и жилые комплексы: монтаж стального каркаса здания",
  composite_frame: "Здания и жилые комплексы: устройство комбинированного каркаса",
  slab_column_frame: "Здания и жилые комплексы: устройство безбалочного плитно-колонного каркаса",
  shear_walls: "Здания и жилые комплексы: устройство диафрагм жёсткости",
  elevator_core: "Здания и жилые комплексы: устройство лифтового ядра",
  stair_core: "Здания и жилые комплексы: устройство лестничного ядра",
  basement_construction: "Здания и жилые комплексы: устройство подвала",
  foundation_pile_field: "Здания и жилые комплексы: устройство свайного поля фундамента",
  foundation_slab: "Здания и жилые комплексы: устройство фундаментной плиты",
  strip_foundation: "Устройство монолитного железобетонного ленточного фундамента",
  raft_foundation: "Здания и жилые комплексы: устройство плитного фундамента",
  high_rise_glazing: title("facade", "высотное фасадное остекление"),
  curtain_wall_system: title("facade", "устройство навесной фасадной системы"),
  aluminum_window_wall: title("facade", "устройство алюминиевой оконно-фасадной системы"),
  stained_glass_facade: title("facade", "устройство витражного фасада"),
  unitized_facade: title("facade", "монтаж элементного фасада"),
  stick_facade: title("facade", "монтаж стоечно-ригельного фасада"),
  balcony_glazing: title("facade", "остекление балконов"),
  facade_insulation_high_rise: title("facade", "утепление фасада высотного здания"),
  ventilated_facade: title("facade", "монтаж вентилируемого фасада"),
  wet_facade_system: title("facade", "устройство фасадной теплоизоляционной системы с тонкослойной штукатуркой"),
  firebreaks_facade: title("facade", "устройство противопожарных рассечек фасада"),
  facade_scaffolding: title("facade", "монтаж фасадных лесов"),
  facade_lifting_equipment: title("facade", "применение подъёмного оборудования для фасадных работ"),
  mansard_roof: title("roof", "устройство мансардной кровли"),
  mansard_roof_with_windows: title("roof", "устройство мансардной кровли с окнами"),
  dormer_windows: title("roof", "монтаж слуховых окон"),
  roof_windows_installation: title("roof", "монтаж кровельных окон"),
  metal_tile_roof: title("roof", "устройство кровли из металлочерепицы"),
  membrane_roof: title("roof", "устройство мембранной кровли"),
  flat_roof: title("roof", "устройство плоской кровли"),
  pitched_roof: title("roof", "устройство скатной кровли"),
  roof_insulation: title("roof", "утепление кровли"),
  roof_vapor_barrier: title("roof", "устройство пароизоляции кровли"),
  rafters_mansard: title("roof", "монтаж стропильной системы мансарды"),
  gutters_downpipes: title("roof", "монтаж желобов и водосточных труб"),
  road_construction: title("transport", "строительство дороги"),
  village_road_construction: title("transport", "строительство сельской дороги"),
  highway_construction: title("transport", "строительство автомобильной дороги"),
  asphalt_concrete_pavement: title("transport", "устройство асфальтобетонного покрытия"),
  crushed_stone_base: title("transport", "устройство основания из щебня"),
  sand_gravel_base: title("transport", "устройство песчано-гравийного основания"),
  road_subgrade: title("transport", "устройство земляного полотна дороги"),
  road_shoulders: title("transport", "устройство обочин дороги"),
  curbs: title("transport", "установка бортового камня"),
  sidewalks: title("transport", "устройство тротуаров"),
  road_drainage: title("transport", "устройство дорожного водоотвода"),
  culverts: title("transport", "устройство водопропускных труб"),
  road_marking: title("transport", "нанесение дорожной разметки"),
  traffic_signs: title("transport", "установка дорожных знаков"),
  guardrails: title("transport", "монтаж дорожных ограждений"),
  railway_embankment: title("transport", "устройство железнодорожной насыпи"),
  airport_runway: title("transport", "строительство взлётно-посадочной полосы"),
  airport_apron: title("transport", "устройство аэродромного перрона"),
  port_quay: title("transport", "строительство портового причала"),
  slope_stabilization: title("transport", "укрепление откоса"),
  bridge_construction: title("bridge", "строительство моста"),
  overpass_construction: title("bridge", "строительство путепровода"),
  flyover_construction: title("bridge", "строительство эстакады"),
  pedestrian_bridge: title("bridge", "строительство пешеходного моста"),
  bridge_pile_foundations: title("bridge", "устройство свайных фундаментов моста"),
  bridge_piers: title("bridge", "устройство промежуточных опор моста"),
  bridge_abutments: title("bridge", "устройство устоев моста"),
  bridge_girders: title("bridge", "монтаж балок пролётного строения моста"),
  bridge_deck: title("bridge", "устройство плиты проезжей части моста"),
  bridge_expansion_joints: title("bridge", "монтаж деформационных швов моста"),
  bridge_bearings: title("bridge", "монтаж опорных частей моста"),
  bridge_waterproofing: title("bridge", "гидроизоляция моста"),
  bridge_asphalt: title("bridge", "устройство асфальтобетонного покрытия моста"),
  tunnel_construction: title("bridge", "строительство тоннеля"),
  tunnel_lining: title("bridge", "устройство обделки тоннеля"),
  tunnel_waterproofing: title("bridge", "гидроизоляция тоннеля"),
  tunnel_ventilation: title("bridge", "монтаж вентиляции тоннеля"),
  tunnel_drainage: title("bridge", "устройство водоотвода тоннеля"),
  underpass_construction: title("bridge", "строительство подземного перехода"),
  retaining_wall: title("bridge", "строительство подпорной стены"),
  gabion_wall: title("bridge", "устройство габионной стены"),
  village_water_supply: title("water", "строительство наружного водопровода села"),
  settlement_water_network: title("water", "устройство водопроводной сети посёлка"),
  water_intake: title("water", "строительство водозабора"),
  borehole_water_supply: title("water", "устройство водозаборной скважины"),
  well_construction: title("water", "строительство водозаборного колодца"),
  pumping_station: title("water", "строительство насосной станции"),
  booster_pumping_station: title("water", "строительство повысительной насосной станции"),
  reservoir_clean_water: title("water", "строительство резервуара чистой воды"),
  water_tower: title("water", "строительство водонапорной башни"),
  pressure_pipeline: title("water", "прокладка напорного водопровода"),
  distribution_pipeline: title("water", "прокладка распределительного водопровода"),
  house_connection_water: title("water", "устройство ввода водопровода в дом"),
  fire_hydrants: title("water", "установка пожарных гидрантов"),
  valves_chambers: title("water", "устройство камер с запорной арматурой"),
  water_meter_chambers: title("water", "устройство камер водомерных узлов"),
  water_treatment_plant: title("water", "строительство водоочистных сооружений"),
  filtration_station: title("water", "строительство фильтровальной станции"),
  chlorination_station: title("water", "строительство станции хлорирования"),
  pressure_testing_disinfection: title("water", "испытание и дезинфекция напорного водопровода"),
  flushing_disinfection: title("water", "промывка и дезинфекция водопровода"),
  village_sewer_network: title("sewer", "устройство наружной канализации села"),
  gravity_sewer_collector: title("sewer", "прокладка самотечного канализационного коллектора"),
  pressure_sewer_pipeline: title("sewer", "прокладка напорного канализационного трубопровода"),
  sewer_pumping_station: title("sewer", "строительство канализационной насосной станции"),
  wastewater_treatment_plant: title("sewer", "строительство очистных сооружений сточных вод"),
  septic_treatment_facility: title("sewer", "строительство септических очистных сооружений"),
  stormwater_drainage: title("sewer", "устройство ливневой канализации"),
  drainage_channel: title("sewer", "устройство водоотводного канала"),
  manholes: title("sewer", "устройство канализационных колодцев"),
  inspection_chambers: title("sewer", "устройство смотровых камер"),
  pipe_bedding_backfill: title("sewer", "подготовка трубного основания и обратная засыпка"),
  hydraulic_testing: title("sewer", "гидравлическое испытание трубопровода"),
  sewage_treatment_tanks: title("sewer", "строительство резервуаров очистных сооружений"),
  aeration_tanks: title("sewer", "устройство аэротенков"),
  sludge_dewatering: title("sewer", "обезвоживание осадка сточных вод"),
  outfall_structure: title("sewer", "строительство выпускного сооружения"),
  rainwater_inlets: title("sewer", "установка дождеприёмников"),
  earth_dam: title("hydraulic", "строительство земляной дамбы"),
  concrete_dam: title("hydraulic", "строительство бетонной плотины"),
  small_dam: title("hydraulic", "строительство малой дамбы"),
  embankment_dam: title("hydraulic", "строительство насыпной плотины"),
  dam_core: title("hydraulic", "устройство противофильтрационного ядра дамбы"),
  dam_slope_protection: title("hydraulic", "укрепление откосов дамбы"),
  spillway: title("hydraulic", "строительство водосбросного сооружения"),
  intake_structure: title("hydraulic", "строительство водоприёмного сооружения"),
  outlet_structure: title("hydraulic", "строительство водовыпускного сооружения"),
  irrigation_channel: title("hydraulic", "строительство оросительного канала"),
  canal: title("hydraulic", "строительство канала"),
  riverbank_protection: title("hydraulic", "берегоукрепительные работы"),
  gabion_protection: title("hydraulic", "устройство габионного берегоукрепления"),
  riprap: title("hydraulic", "устройство каменной наброски"),
  geomembrane_lining: title("hydraulic", "устройство противофильтрационной облицовки геомембраной"),
  geotextile_layers: title("hydraulic", "укладка слоёв геотекстиля"),
  drainage_prism: title("hydraulic", "устройство дренажной призмы"),
  anti_filtration_screen: title("hydraulic", "устройство противофильтрационного экрана"),
  water_control_gates: title("hydraulic", "монтаж водорегулирующих затворов"),
  hydraulic_steel_structures: title("hydraulic", "монтаж стальных гидротехнических конструкций"),
  flood_protection_embankment: title("hydraulic", "устройство противопаводковой насыпи"),
  electrical_poles_04kv: title("electric", "установка опор линии 0,4 кВ"),
  electrical_poles_10kv: title("electric", "установка опор линии 10 кВ"),
  electrical_poles_35kv: title("electric", "установка опор линии 35 кВ"),
  electrical_poles_110kv: title("electric", "установка опор линии 110 кВ"),
  overhead_power_line_04kv: title("electric", "строительство воздушной линии 0,4 кВ"),
  overhead_power_line_10kv: title("electric", "строительство воздушной линии 10 кВ"),
  overhead_power_line_35kv: title("electric", "строительство воздушной линии 35 кВ"),
  overhead_power_line_110kv: title("electric", "строительство воздушной линии 110 кВ"),
  underground_cable_line: title("electric", "прокладка подземной кабельной линии"),
  transformer_substation: title("electric", "строительство трансформаторной подстанции"),
  package_transformer_substation: title("electric", "строительство комплектной трансформаторной подстанции"),
  distribution_substation: title("electric", "строительство распределительной подстанции"),
  outdoor_switchgear: title("electric", "монтаж открытого распределительного устройства"),
  distribution_board_outdoor: title("electric", "монтаж наружного распределительного щита"),
  grounding_system: title("electric", "устройство системы заземления"),
  lightning_protection: title("electric", "устройство молниезащиты"),
  street_lighting_poles: title("electric", "установка опор уличного освещения"),
  cable_trench: title("electric", "устройство кабельной траншеи"),
  cable_ducts: title("electric", "прокладка кабельных каналов"),
  cable_pulling: title("electric", "протяжка кабеля"),
  electrical_testing_commissioning: title("electric", "испытания и пусконаладка электрооборудования"),
  relay_protection_automation: title("electric", "монтаж релейной защиты и автоматики"),
  site_water_connection: title("utility", "подключение участка к водопроводу"),
  site_sewer_connection: title("utility", "подключение участка к канализации"),
  site_power_connection: title("utility", "подключение участка к электросети"),
  site_gas_connection: title("utility", "подключение участка к газовой сети"),
  site_heat_connection: title("utility", "подключение участка к тепловой сети"),
  site_telecom_connection: title("utility", "подключение участка к сети связи"),
  fiber_optic_connection: title("utility", "подключение по волоконно-оптической линии связи"),
  utility_trench: title("utility", "устройство траншеи инженерных сетей"),
  multi_utility_trench: title("utility", "прокладка комплекса наружных инженерных сетей"),
  utility_crossings: title("utility", "устройство переходов инженерных сетей"),
  road_crossing_sleeves: title("utility", "устройство футляров инженерных сетей под дорогой"),
  service_chambers: title("utility", "устройство эксплуатационных камер инженерных сетей"),
  inspection_wells: title("utility", "устройство смотровых колодцев"),
  testing_commissioning: title("utility", "испытания и пусконаладка инженерных сетей"),
  temporary_utilities_construction: title("utility", "устройство временных инженерных сетей строительной площадки"),
  external_engineering_networks: title("utility", "прокладка наружных инженерных сетей"),
  gas_pipeline_low_pressure: title("pipeline", "прокладка газопровода низкого давления"),
  gas_pipeline_medium_pressure: title("pipeline", "прокладка газопровода среднего давления"),
  gas_regulator_station: title("pipeline", "строительство газорегуляторного пункта"),
  heat_network: title("pipeline", "строительство тепловой сети"),
  district_heating_pipeline: title("pipeline", "прокладка трубопровода централизованного теплоснабжения"),
  preinsulated_pipe_installation: title("pipeline", "монтаж предизолированных труб"),
  heat_chamber: title("pipeline", "строительство тепловой камеры"),
  pipeline_compensators: title("pipeline", "монтаж компенсаторов трубопровода"),
  pipeline_welding: title("pipeline", "сварка трубопровода"),
  pipeline_insulation: title("pipeline", "теплоизоляция трубопровода"),
  pipeline_pressure_testing: title("pipeline", "гидравлическое испытание трубопровода"),
  technological_pipeline: title("pipeline", "прокладка технологического трубопровода"),
  pressure_pipeline_industrial: title("pipeline", "прокладка промышленного напорного трубопровода"),
  process_piping_dn50_dn1200: title("pipeline", "прокладка технологического трубопровода номинальным диаметром 50–1200 мм"),
  thermal_power_plant: title("energy", "строительство тепловой электростанции"),
  combined_heat_power_plant: title("energy", "строительство теплоэлектроцентрали"),
  turbine_hall: title("energy", "строительство турбинного зала"),
  boiler_house: title("energy", "строительство котельной"),
  boiler_installation: title("energy", "монтаж котельного оборудования"),
  generator_foundation: title("energy", "устройство фундамента генератора"),
  turbine_foundation: title("energy", "устройство фундамента турбоагрегата"),
  cooling_tower: title("energy", "строительство градирни"),
  chimney_stack: title("energy", "строительство дымовой трубы"),
  fuel_oil_facility: title("energy", "строительство мазутного хозяйства"),
  coal_handling_system: title("energy", "монтаж системы топливоподачи угля"),
  ash_handling_system: title("energy", "монтаж системы золоудаления"),
  hydro_power_plant: title("energy", "строительство гидроэлектростанции"),
  small_hydro_power_plant: title("energy", "строительство малой гидроэлектростанции"),
  powerhouse: title("energy", "строительство здания гидроэлектростанции"),
  penstock: title("energy", "монтаж напорного водовода"),
  water_intake_hpp: title("energy", "устройство водозабора гидроэлектростанции"),
  surge_tank: title("energy", "строительство уравнительного резервуара"),
  turbine_installation_hpp: title("energy", "монтаж гидротурбины"),
  hydromechanical_equipment: title("energy", "монтаж гидромеханического оборудования"),
  substation_10kv: title("energy", "строительство подстанции 10 кВ"),
  substation_35kv: title("energy", "строительство подстанции 35 кВ"),
  substation_110kv: title("energy", "строительство подстанции 110 кВ"),
  transformer_foundation: title("energy", "устройство фундамента трансформатора"),
  cable_trench_energy: title("energy", "устройство кабельной траншеи энергетического объекта"),
  control_building_energy: title("energy", "строительство здания управления энергетического объекта"),
  commissioning_energy_facility: title("energy", "пусконаладка энергетического объекта"),
  solar_power_plant: title("energy", "строительство солнечной электростанции"),
  wind_power_plant: title("energy", "строительство ветровой электростанции"),
  battery_energy_storage: title("energy", "монтаж аккумуляторной системы накопления энергии"),
  factory_building: title("industrial", "строительство заводского корпуса"),
  industrial_shed: title("industrial", "строительство промышленного корпуса"),
  warehouse_building: title("industrial", "строительство складского здания"),
  logistics_terminal: title("industrial", "строительство логистического терминала"),
  production_workshop: title("industrial", "строительство производственного цеха"),
  crane_runway: title("industrial", "монтаж крановых путей"),
  overhead_crane_installation: title("industrial", "монтаж мостового крана"),
  equipment_foundation: title("industrial", "устройство фундамента под оборудование"),
  tank_foundation: title("industrial", "устройство фундамента резервуара"),
  silo_foundation: title("industrial", "устройство фундамента силоса"),
  conveyor_gallery: title("industrial", "строительство конвейерной галереи"),
  pipe_rack: title("industrial", "строительство трубопроводной и кабельной эстакады"),
  cable_tray_gallery: title("industrial", "строительство галереи кабельных лотков"),
  industrial_earthworks: title("industrial", "земляные работы промышленного объекта"),
  industrial_floor: title("industrial", "устройство промышленного пола"),
  chemical_resistant_floor: title("industrial", "устройство химически стойкого пола"),
  cleanroom_construction: title("industrial", "строительство чистого помещения"),
  cold_storage_building: title("industrial", "строительство холодильного склада"),
  refrigeration_equipment_foundation: title("industrial", "устройство фундамента холодильного оборудования"),
  loading_docks: title("industrial", "строительство погрузочных доков"),
  long_span_steel_structure: title("industrial", "монтаж большепролётной стальной конструкции"),
  steel_tank: title("storage", "строительство стального резервуара"),
  reinforced_concrete_tank: title("storage", "строительство железобетонного резервуара"),
  water_reservoir: title("storage", "строительство резервуара чистой воды"),
  fuel_tank: title("storage", "строительство топливного резервуара"),
  chemical_tank: title("storage", "строительство резервуара для химических веществ"),
  silo_construction: title("storage", "строительство силоса"),
  grain_silo: title("storage", "строительство зернового силоса"),
  tank_foundation_ring: title("storage", "устройство кольцевого фундамента резервуара"),
  tank_coating: title("storage", "нанесение защитного покрытия резервуара"),
  tank_insulation: title("storage", "теплоизоляция резервуара"),
  tank_testing: title("storage", "испытание резервуара"),
  bund_wall: title("storage", "устройство обвалования резервуара"),
  spill_containment: title("storage", "устройство локализующего сооружения для аварийного разлива"),
  landfill_cell: title("ecology", "устройство карты полигона отходов"),
  landfill_liner: title("ecology", "устройство противофильтрационного экрана полигона"),
  leachate_collection: title("ecology", "устройство системы сбора фильтрата"),
  waste_sorting_station: title("ecology", "строительство станции сортировки отходов"),
  composting_facility: title("ecology", "строительство сооружения компостирования"),
  incineration_facility_civil: title("ecology", "строительство гражданской части мусоросжигательного сооружения"),
  hazardous_waste_storage: title("ecology", "строительство хранилища опасных отходов"),
  remediation_earthworks: title("ecology", "земляные работы при рекультивации"),
  soil_stabilization: title("ecology", "укрепление грунта"),
  dust_suppression_system: title("ecology", "монтаж системы пылеподавления"),
  environmental_monitoring_wells: title("ecology", "устройство скважин экологического мониторинга"),
  quarry_road: title("mining", "строительство карьерной дороги"),
  mining_service_road: title("mining", "строительство карьерной технологической дороги"),
  large_scale_excavation: title("mining", "выполнение крупномасштабных земляных работ"),
  rock_excavation: title("mining", "разработка скального грунта"),
  blasting_preparation: title("mining", "подготовка к буровзрывным работам"),
  retaining_berms: title("mining", "устройство предохранительных берм"),
  slope_reinforcement: title("mining", "укрепление откоса"),
  dewatering_system: title("mining", "устройство системы водопонижения"),
  tailings_dam: title("mining", "строительство дамбы хвостохранилища"),
  ore_processing_foundations: title("mining", "устройство фундаментов оборудования обогащения руды"),
  conveyor_foundations: title("mining", "устройство фундаментов конвейера"),
  HVAC_plant_room: title("building", "строительство машинного помещения систем отопления, вентиляции и кондиционирования"),
  ventilation_system: title("building", "монтаж системы вентиляции"),
  smoke_exhaust_system: title("building", "монтаж системы дымоудаления"),
  fire_fighting_pump_station: title("building", "строительство насосной станции пожаротушения"),
  sprinkler_system: title("building", "монтаж спринклерной системы пожаротушения"),
  fire_alarm_system: title("building", "монтаж системы пожарной сигнализации"),
  low_voltage_system: title("building", "монтаж слаботочной системы"),
  CCTV_system: title("building", "монтаж системы видеонаблюдения"),
  access_control_system: title("building", "монтаж системы контроля и управления доступом"),
  BMS_system: title("building", "монтаж системы автоматизации здания"),
  elevators: title("building", "монтаж лифтов"),
  escalators: title("building", "монтаж эскалаторов"),
  generator_backup_system: title("building", "монтаж резервной генераторной установки"),
  UPS_system: title("building", "монтаж системы бесперебойного электропитания"),
  data_center_mep: title("building", "монтаж инженерных систем центра обработки данных"),
  server_room_cooling: title("building", "монтаж системы охлаждения серверного помещения"),
});

const APPROVED_PUBLIC_ALIASES_R555: Readonly<Record<string, readonly string[]>> = Object.freeze({
  asphalt_concrete_pavement: [
    "асфальт",
    "асфа",
    "асфальтобетон",
    "асфальтобетонное покрытие",
    "асфальтовые работы",
    "устройство асфальта",
  ],
  road_construction: ["строительство дороги", "дорожные работы"],
  village_road_construction: ["строительство сельской дороги", "сельская дорога"],
  bridge_asphalt: ["асфальтирование моста", "асфальтобетонное покрытие моста"],
  parking_structure: ["парковка", "строительство парковки", "многоуровневая парковка"],
  underground_parking: ["подземная парковка", "строительство подземной парковки"],
  strip_foundation: ["ленточный фундамент", "железобетонная лента", "монолитный ленточный фундамент"],
});

export const PUBLIC_RUSSIAN_LEXICON_VERSION_R555 = "PUBLIC_RUSSIAN_LEXICON_R555_V1" as const;

const PUBLIC_RUSSIAN_CATEGORY_TITLE_REPLACEMENTS_R555: Readonly<Record<string, string>> = Object.freeze({
  mep_building: "Инженерные системы зданий",
});

export function resolveExpandedPublicRussianCategoryTitleR555(
  categoryGroup: string,
  sourceTitleRu: string,
): string {
  return PUBLIC_RUSSIAN_CATEGORY_TITLE_REPLACEMENTS_R555[categoryGroup] ?? sourceTitleRu;
}

export function resolveExpandedPublicRussianIdentityR555(
  family: ExpandedFamilySource,
): PublicRussianIdentityR555 {
  const familyId = String(family.work_family_id ?? "").trim();
  const sourceTitle = String(family.professionalNameRu ?? "").trim();
  if (!familyId || !sourceTitle) throw new Error(`R555_PUBLIC_RUSSIAN_SOURCE_INVALID:${familyId || "missing_family_id"}`);
  const titleRu = PUBLIC_RUSSIAN_REVIEWED_ADDITIONAL_TITLES_R555[familyId]
    ?? PUBLIC_RUSSIAN_TITLE_REPLACEMENTS_R555[familyId]
    ?? sourceTitle;
  const aliasesRu = [...new Set([titleRu, ...(APPROVED_PUBLIC_ALIASES_R555[familyId] ?? [])])];
  return { titleRu, aliasesRu, lexiconVersion: PUBLIC_RUSSIAN_LEXICON_VERSION_R555 };
}

export function listReviewedExpandedPublicRussianFamilyIdsR555(): string[] {
  return [...new Set([
    ...Object.keys(PUBLIC_RUSSIAN_REVIEWED_ADDITIONAL_TITLES_R555),
    ...Object.keys(PUBLIC_RUSSIAN_TITLE_REPLACEMENTS_R555),
  ])].sort();
}
