import type { AiUserRole } from "../policy/aiRolePolicy";
import type {
  AiScreenAiOpportunity,
  AiScreenAuditPrimaryDomain,
  AiScreenAuditRecommendedWave,
  AiScreenButtonActionEntry,
  AiScreenButtonActionKind,
  AiScreenEmulatorTargetability,
  AiScreenMutationRisk,
  AiScreenPiiFinancialSupplierRisk,
  AiScreenRouteStatus,
} from "./aiScreenButtonRoleActionTypes";
import { classifyAiScreenBffCoverage } from "./aiScreenBffCoverageClassifier";

const CONTROL_ROLES = ["director", "control"] as const;
const OPS_ROLES = [
  "director",
  "control",
  "foreman",
  "buyer",
  "accountant",
  "warehouse",
  "contractor",
  "office",
  "admin",
] as const;
const PROCUREMENT_ROLES = ["director", "control", "buyer"] as const;
const MARKET_ROLES = ["director", "control", "buyer", "foreman"] as const;
const WAREHOUSE_ROLES = ["director", "control", "warehouse"] as const;
const FINANCE_ROLES = ["director", "control", "accountant"] as const;
const FOREMAN_ROLES = ["director", "control", "foreman"] as const;
const CONTRACTOR_ROLES = ["director", "control", "contractor"] as const;
const OFFICE_ROLES = ["director", "control", "office", "admin"] as const;
const MAP_ROLES = ["director", "control", "buyer", "foreman"] as const;
const SECURITY_ROLES = ["director", "control", "admin"] as const;

const COMMON_READ_BFF_ROUTES = [
  "GET /agent/screen-runtime/:screenId",
  "GET /agent/screen-actions/:screenId",
  "GET /agent/screen-assistant/:screenId/context",
  "GET /agent/app-graph/screen/:screenId",
] as const;

const COMMON_DRAFT_BFF_ROUTES = [
  "POST /agent/screen-actions/:screenId/action-plan",
  "POST /agent/screen-assistant/:screenId/draft-preview",
] as const;

const COMMON_APPROVAL_BFF_ROUTES = [
  "POST /agent/action/submit-for-approval",
  "POST /agent/screen-assistant/:screenId/submit-for-approval-preview",
] as const;

type ScreenDefinition = {
  screenId: string;
  route: string;
  routeStatus: AiScreenRouteStatus;
  roleScope: readonly AiUserRole[];
  primaryDomain: AiScreenAuditPrimaryDomain;
  visibleButtons: readonly string[];
  onPressHandlers: readonly string[];
  existingTestIds: readonly string[];
  currentDataSources: readonly string[];
  evidenceSources: readonly string[];
  readRoutes?: readonly string[];
  draftRoutes?: readonly string[];
  approvalRoutes?: readonly string[];
  missingReadRoutes?: readonly string[];
  missingDraftRoutes?: readonly string[];
  missingApprovalRoutes?: readonly string[];
  safeLabel: string;
  draftLabel: string;
  approvalLabel: string;
  forbiddenLabel: string;
  forbiddenReason: string;
  safeOpportunity?: AiScreenAiOpportunity;
  draftOpportunity?: AiScreenAiOpportunity;
  approvalOpportunity?: AiScreenAiOpportunity;
  crossScreenRisks: readonly string[];
  piiFinancialSupplierRisk: AiScreenPiiFinancialSupplierRisk;
  emulatorTargetability: AiScreenEmulatorTargetability;
  recommendedNextWave: AiScreenAuditRecommendedWave;
};

type ActionSeed = {
  suffix: string;
  label: string;
  actionKind: AiScreenButtonActionKind;
  mutationRisk: AiScreenMutationRisk;
  aiOpportunity: AiScreenAiOpportunity;
  existingBffRoutes: readonly string[];
  missingBffRoutes: readonly string[];
  forbiddenReason?: string;
};

export const AI_ALL_SCREEN_BUTTON_ROLE_ACTION_REQUIRED_SCREEN_IDS = [
  "director.dashboard",
  "director.finance",
  "director.reports",
  "ai.command_center",
  "approval.inbox",
  "buyer.main",
  "buyer.requests",
  "buyer.request.detail",
  "procurement.copilot",
  "market.home",
  "supplier.showcase",
  "warehouse.main",
  "warehouse.incoming",
  "warehouse.issue",
  "accountant.main",
  "accountant.payment",
  "accountant.history",
  "foreman.main",
  "foreman.ai.quick_modal",
  "foreman.subcontract",
  "contractor.main",
  "reports.modal",
  "documents.main",
  "chat.main",
  "map.main",
  "office.hub",
  "security.screen",
  "screen.runtime",
] as const;

const SCREEN_DEFINITIONS: readonly ScreenDefinition[] = [
  {
    screenId: "director.dashboard",
    route: "/office/director",
    routeStatus: "registered",
    roleScope: CONTROL_ROLES,
    primaryDomain: "control",
    visibleButtons: ["Finance", "Reports", "Open AI command center"],
    onPressHandlers: ["openFinancePanel", "openReportsPanel", "router.push('/ai-command-center')"],
    existingTestIds: ["director-finance-dashboard-debt-card", "director-reports-home-card"],
    currentDataSources: ["director finance summary RPC contracts", "approval ledger status", "screen state"],
    evidenceSources: ["screen_state", "finance_summary", "approval_policy", "ledger_status"],
    readRoutes: ["GET /agent/finance/summary", "GET /agent/task-stream"],
    draftRoutes: ["POST /agent/finance/draft-summary"],
    approvalRoutes: ["POST /agent/action/submit-for-approval"],
    safeLabel: "Explain cross-domain executive status",
    draftLabel: "Draft executive control summary",
    approvalLabel: "Submit director decision pack for approval",
    forbiddenLabel: "Execute final cross-domain mutation directly",
    forbiddenReason: "Director AI can prepare and submit evidence, but final mutation must go through the approval ledger.",
    crossScreenRisks: ["finance to procurement leakage", "approval execution boundary"],
    piiFinancialSupplierRisk: "high",
    emulatorTargetability: "targetable",
    recommendedNextWave: "director_control_center",
  },
  {
    screenId: "director.finance",
    route: "/office/director#finance",
    routeStatus: "registered",
    roleScope: CONTROL_ROLES,
    primaryDomain: "finance",
    visibleButtons: ["Open supplier debt", "View finance dashboard", "Prepare summary"],
    onPressHandlers: ["openFinanceDebtCard", "openFinanceDashboard", "draftDirectorFinanceSummary"],
    existingTestIds: ["director-finance-dashboard-debt-card"],
    currentDataSources: ["director_finance_* RPC contracts", "finance summary cache", "approval ledger status"],
    evidenceSources: ["finance_summary", "screen_state", "approval_policy"],
    readRoutes: ["GET /agent/finance/summary", "GET /agent/finance/debts"],
    draftRoutes: ["POST /agent/finance/draft-summary"],
    approvalRoutes: ["POST /agent/action/submit-for-approval"],
    safeLabel: "Explain finance dashboard deltas",
    draftLabel: "Draft finance summary with evidence",
    approvalLabel: "Submit finance decision for approval",
    forbiddenLabel: "Post finance transaction directly",
    forbiddenReason: "Finance posting is a final accounting mutation and cannot be performed by AI directly.",
    crossScreenRisks: ["supplier payment exposure", "finance posting boundary"],
    piiFinancialSupplierRisk: "high",
    emulatorTargetability: "not_targeted_yet",
    recommendedNextWave: "finance_copilot",
  },
  {
    screenId: "director.reports",
    route: "/office/director#reports",
    routeStatus: "registered",
    roleScope: CONTROL_ROLES,
    primaryDomain: "reports",
    visibleButtons: ["Open reports", "Review report status", "Prepare report"],
    onPressHandlers: ["openReportsHome", "openReportStatus", "draftDirectorReport"],
    existingTestIds: ["director-reports-home-card"],
    currentDataSources: ["reports dashboard state", "documents metadata", "approval ledger status"],
    evidenceSources: ["report_summary", "document_metadata", "approval_policy"],
    readRoutes: ["GET /agent/screen-assistant/:screenId/context", "GET /agent/documents/knowledge"],
    draftRoutes: ["POST /agent/documents/summarize-preview", "POST /agent/screen-assistant/:screenId/draft-preview"],
    approvalRoutes: ["POST /agent/action/submit-for-approval"],
    safeLabel: "Summarize director reports status",
    draftLabel: "Draft director report narrative",
    approvalLabel: "Submit report package for approval",
    forbiddenLabel: "Publish final report directly",
    forbiddenReason: "AI can draft reports, but publication is a final action requiring human approval.",
    crossScreenRisks: ["document scope leakage", "report publication boundary"],
    piiFinancialSupplierRisk: "medium",
    emulatorTargetability: "not_targeted_yet",
    recommendedNextWave: "director_control_center",
  },
  {
    screenId: "ai.command_center",
    route: "/ai-command-center",
    routeStatus: "registered",
    roleScope: OPS_ROLES,
    primaryDomain: "control",
    visibleButtons: ["Preview screen actions", "Draft action", "Submit for approval"],
    onPressHandlers: ["previewScreenActions", "draftActionPlan", "submitActionForApproval"],
    existingTestIds: [
      "ai.command.center.screen",
      "ai.screen.actions.preview",
      "ai.screen.actions.safe_read",
      "ai.screen.actions.draft",
      "ai.screen.actions.approval_required",
    ],
    currentDataSources: ["screen action registry", "task stream", "approval ledger status"],
    evidenceSources: ["screen_state", "role_policy", "tool_contract", "ledger_status"],
    readRoutes: ["GET /agent/task-stream", "GET /agent/action/:actionId/status"],
    draftRoutes: ["POST /agent/screen-actions/:screenId/action-plan"],
    approvalRoutes: ["POST /agent/action/submit-for-approval"],
    safeLabel: "Explain current command center task",
    draftLabel: "Draft a command center action plan",
    approvalLabel: "Submit command center action for approval",
    forbiddenLabel: "Execute command center action without ledger",
    forbiddenReason: "Command Center execution must use persisted approval ledger state.",
    crossScreenRisks: ["cross-role action leakage", "ledger execution boundary"],
    piiFinancialSupplierRisk: "medium",
    emulatorTargetability: "targetable",
    recommendedNextWave: "approval_ledger_hardening",
  },
  {
    screenId: "approval.inbox",
    route: "/ai-approval-inbox",
    routeStatus: "registered",
    roleScope: CONTROL_ROLES,
    primaryDomain: "control",
    visibleButtons: ["Approve", "Reject", "Edit preview", "Execute approved"],
    onPressHandlers: ["approveAction", "rejectAction", "previewActionEdit", "executeApprovedAction"],
    existingTestIds: ["ai.approval_inbox.screen"],
    currentDataSources: ["approval inbox BFF", "approval ledger RPC", "action status"],
    evidenceSources: ["ledger_status", "approval_policy", "screen_state"],
    readRoutes: ["GET /agent/approval-inbox", "GET /agent/approval-inbox/:actionId"],
    draftRoutes: ["POST /agent/approval-inbox/:actionId/edit-preview"],
    approvalRoutes: [
      "POST /agent/approval-inbox/:actionId/approve",
      "POST /agent/approval-inbox/:actionId/reject",
      "POST /agent/approval-inbox/:actionId/execute-approved",
    ],
    safeLabel: "Explain approval inbox evidence",
    draftLabel: "Draft revision note for approver",
    approvalLabel: "Approve or reject through ledger RPC",
    forbiddenLabel: "Execute preview without approval ledger",
    forbiddenReason: "Approval Inbox can execute only through approved ledger RPC and never through UI-only mutation.",
    crossScreenRisks: ["approver role leakage", "point-of-no-return execution"],
    piiFinancialSupplierRisk: "high",
    emulatorTargetability: "targetable",
    recommendedNextWave: "approval_ledger_hardening",
  },
  {
    screenId: "buyer.main",
    route: "/office/buyer",
    routeStatus: "registered",
    roleScope: PROCUREMENT_ROLES,
    primaryDomain: "procurement",
    visibleButtons: ["Inbox", "Approved", "Create proposal", "Publish RFQ"],
    onPressHandlers: ["setBuyerTab('inbox')", "setBuyerTab('approved')", "handleCreateProposal", "handlePublishRfq"],
    existingTestIds: ["buyer-tab-inbox", "buyer-tab-approved", "buyer-rfq-publish"],
    currentDataSources: ["procurement request context", "market listings", "supplier quotes"],
    evidenceSources: ["procurement_context", "screen_state", "approval_policy"],
    readRoutes: ["GET /agent/procurement/request-context/:requestId"],
    draftRoutes: ["POST /agent/procurement/draft-request/preview"],
    approvalRoutes: ["POST /agent/procurement/submit-for-approval"],
    safeLabel: "Explain buyer workload",
    draftLabel: "Draft procurement request",
    approvalLabel: "Submit buyer request for approval",
    forbiddenLabel: "Confirm supplier directly",
    forbiddenReason: "Supplier confirmation requires approval-backed decision and cannot be direct AI output.",
    crossScreenRisks: ["supplier decision without evidence", "market to procurement mutation"],
    piiFinancialSupplierRisk: "high",
    emulatorTargetability: "targetable",
    recommendedNextWave: "procurement_execution",
  },
  {
    screenId: "buyer.requests",
    route: "/office/buyer#requests",
    routeStatus: "registered",
    roleScope: PROCUREMENT_ROLES,
    primaryDomain: "procurement",
    visibleButtons: ["Open request", "Send proposals", "Send to accounting", "Rework"],
    onPressHandlers: ["openBuyerRequest", "sendBuyerProposal", "sendProposalToAccounting", "markProposalRework"],
    existingTestIds: [
      "buyer-rfq-open",
      "buyer-create-proposals-send",
      "buyer-proposal-accounting",
      "buyer-proposal-rework",
    ],
    currentDataSources: ["buyer request list", "supplier quote state", "approval status"],
    evidenceSources: ["procurement_context", "document_metadata", "approval_policy"],
    readRoutes: ["GET /agent/procurement/request-understanding/:requestId"],
    draftRoutes: ["POST /agent/procurement/decision-card", "POST /agent/procurement/draft-request/preview"],
    approvalRoutes: ["POST /agent/procurement/submit-for-approval"],
    safeLabel: "Compare request options",
    draftLabel: "Draft buyer proposal rationale",
    approvalLabel: "Submit buyer proposal pack",
    forbiddenLabel: "Create purchase order directly",
    forbiddenReason: "Purchase order creation is a final procurement mutation and requires the approved execution path.",
    crossScreenRisks: ["proposal to accounting handoff", "supplier decision boundary"],
    piiFinancialSupplierRisk: "high",
    emulatorTargetability: "not_targeted_yet",
    recommendedNextWave: "procurement_execution",
  },
  {
    screenId: "buyer.request.detail",
    route: "/office/buyer#request-detail",
    routeStatus: "registered",
    roleScope: PROCUREMENT_ROLES,
    primaryDomain: "procurement",
    visibleButtons: ["Open PDF", "Add supplier", "Send to accounting", "Request rework"],
    onPressHandlers: ["openProposalPdf", "addSupplierCandidate", "sendProposalToAccounting", "requestProposalRework"],
    existingTestIds: ["buyer-proposal-pdf", "buyer-proposal-accounting", "buyer-proposal-rework"],
    currentDataSources: ["single request detail", "proposal documents", "supplier candidates"],
    evidenceSources: ["procurement_context", "document_metadata", "approval_policy"],
    readRoutes: ["GET /agent/procurement/request-context/:requestId"],
    draftRoutes: ["POST /agent/procurement/decision-card", "POST /agent/procurement/supplier-match/preview"],
    approvalRoutes: ["POST /agent/procurement/submit-for-approval"],
    safeLabel: "Explain request detail evidence",
    draftLabel: "Draft request decision card",
    approvalLabel: "Submit detailed supplier decision",
    forbiddenLabel: "Finalize supplier from detail view",
    forbiddenReason: "AI recommendation must remain evidence-backed and approval-gated before final supplier selection.",
    crossScreenRisks: ["supplier selection", "financial handoff"],
    piiFinancialSupplierRisk: "high",
    emulatorTargetability: "not_targeted_yet",
    recommendedNextWave: "procurement_execution",
  },
  {
    screenId: "procurement.copilot",
    route: "/ai-procurement-copilot",
    routeStatus: "registered",
    roleScope: PROCUREMENT_ROLES,
    primaryDomain: "procurement",
    visibleButtons: ["Plan", "Draft preview", "Submit preview", "Supplier chain"],
    onPressHandlers: ["planProcurementCopilot", "previewCopilotDraft", "previewCopilotSubmit", "previewLiveSupplierChain"],
    existingTestIds: ["ai.procurement.copilot.screen"],
    currentDataSources: ["procurement copilot context", "internal supplier rank", "external cited search preview"],
    evidenceSources: ["procurement_context", "tool_contract", "approval_policy"],
    readRoutes: ["GET /agent/procurement/copilot/context"],
    draftRoutes: ["POST /agent/procurement/copilot/draft-preview", "POST /agent/procurement/copilot/plan"],
    approvalRoutes: ["POST /agent/procurement/copilot/submit-for-approval-preview"],
    safeLabel: "Explain procurement copilot plan",
    draftLabel: "Draft copilot request preview",
    approvalLabel: "Prepare copilot submit-for-approval preview",
    forbiddenLabel: "Create order from copilot",
    forbiddenReason: "Copilot output is evidence and draft only until approval ledger execution.",
    crossScreenRisks: ["external supplier citation", "approval bypass"],
    piiFinancialSupplierRisk: "high",
    emulatorTargetability: "targetable",
    recommendedNextWave: "procurement_execution",
  },
  {
    screenId: "market.home",
    route: "/market",
    routeStatus: "registered",
    roleScope: MARKET_ROLES,
    primaryDomain: "marketplace",
    visibleButtons: ["Search", "Contact supplier", "Add to request", "Create proposal"],
    onPressHandlers: ["handleResetFeedFilters", "onContactSupplierPress", "onAddToRequestPress", "onCreateProposalPress"],
    existingTestIds: ["market-home-title", "market_search_input", "market_add_to_request_${listing.id}"],
    currentDataSources: ["market listings", "supplier contact metadata", "request draft state"],
    evidenceSources: ["screen_state", "procurement_context", "tool_contract"],
    readRoutes: ["GET /agent/external-intel/sources"],
    draftRoutes: ["POST /agent/procurement/draft-request-preview"],
    approvalRoutes: ["POST /agent/procurement/submit-for-approval"],
    missingReadRoutes: ["GET /agent/market/listing-context/:listingId"],
    safeLabel: "Compare marketplace supplier options",
    draftLabel: "Draft request from marketplace item",
    approvalLabel: "Submit marketplace-backed request",
    forbiddenLabel: "Create external supplier without citation",
    forbiddenReason: "External supplier creation requires citation/evidence and cannot be invented by AI.",
    crossScreenRisks: ["supplier contact PII", "external source trust"],
    piiFinancialSupplierRisk: "high",
    emulatorTargetability: "targetable",
    recommendedNextWave: "market_supplier_intel",
  },
  {
    screenId: "supplier.showcase",
    route: "/supplierShowcase",
    routeStatus: "registered",
    roleScope: MARKET_ROLES,
    primaryDomain: "marketplace",
    visibleButtons: ["Back", "Open assistant", "Call", "WhatsApp", "Open map"],
    onPressHandlers: ["safeBack", "openAssistant", "openExternal('tel:')", "openExternal('whatsapp:')", "router.push(map)"],
    existingTestIds: [],
    currentDataSources: ["supplier profile route params", "market listing metadata", "external contact links"],
    evidenceSources: ["screen_state", "procurement_context", "tool_contract"],
    readRoutes: ["GET /agent/external-intel/sources"],
    draftRoutes: ["POST /agent/procurement/external-supplier-preview"],
    approvalRoutes: ["POST /agent/procurement/submit-for-approval"],
    missingReadRoutes: ["GET /agent/supplier-showcase/:supplierId/context"],
    safeLabel: "Summarize supplier showcase evidence",
    draftLabel: "Draft supplier comparison note",
    approvalLabel: "Submit supplier recommendation",
    forbiddenLabel: "Confirm supplier directly from showcase",
    forbiddenReason: "Supplier choice requires approval and must cite evidence; showcase contact buttons are not AI execution paths.",
    crossScreenRisks: ["external contact leakage", "supplier recommendation without citation"],
    piiFinancialSupplierRisk: "high",
    emulatorTargetability: "not_targeted_yet",
    recommendedNextWave: "market_supplier_intel",
  },
  {
    screenId: "warehouse.main",
    route: "/office/warehouse",
    routeStatus: "registered",
    roleScope: WAREHOUSE_ROLES,
    primaryDomain: "warehouse",
    visibleButtons: ["Stock", "Incoming", "Issue", "Reports"],
    onPressHandlers: ["setWarehouseTab('stock')", "setWarehouseTab('incoming')", "setWarehouseTab('issue')", "setWarehouseReportsMode"],
    existingTestIds: ["warehouse-tab-stock"],
    currentDataSources: ["warehouse status", "warehouse movements", "local recovery queue"],
    evidenceSources: ["warehouse_status", "screen_state", "approval_policy"],
    readRoutes: ["GET /agent/warehouse/status", "GET /agent/warehouse/movements"],
    draftRoutes: ["POST /agent/warehouse/draft-action"],
    approvalRoutes: ["POST /agent/action/submit-for-approval"],
    safeLabel: "Explain warehouse stock status",
    draftLabel: "Draft warehouse restock action",
    approvalLabel: "Submit warehouse action for approval",
    forbiddenLabel: "Mutate stock balance directly",
    forbiddenReason: "Warehouse stock mutations must use approved warehouse flows and are forbidden to AI direct actions.",
    crossScreenRisks: ["stock mutation", "offline recovery queue"],
    piiFinancialSupplierRisk: "medium",
    emulatorTargetability: "targetable",
    recommendedNextWave: "warehouse_copilot",
  },
  {
    screenId: "warehouse.incoming",
    route: "/office/warehouse#incoming",
    routeStatus: "registered",
    roleScope: WAREHOUSE_ROLES,
    primaryDomain: "warehouse",
    visibleButtons: ["Open incoming", "Receive", "Sync draft", "Clear recovery"],
    onPressHandlers: ["setIncomingDetailsId", "enqueueWarehouseReceive", "syncWarehouseReceiveDraft", "clearWarehouseReceiveLocalRecovery"],
    existingTestIds: [],
    currentDataSources: ["wh_incoming_items", "v_wh_incoming_items_ui", "warehouse receive recovery drafts"],
    evidenceSources: ["warehouse_status", "screen_state", "approval_policy"],
    readRoutes: ["GET /agent/warehouse/status", "GET /agent/warehouse/movements"],
    draftRoutes: ["POST /agent/warehouse/draft-action"],
    approvalRoutes: ["POST /agent/action/submit-for-approval"],
    safeLabel: "Explain incoming receipt status",
    draftLabel: "Draft incoming receipt note",
    approvalLabel: "Submit incoming exception for approval",
    forbiddenLabel: "Receive incoming stock directly",
    forbiddenReason: "Receiving stock is a warehouse mutation and cannot be executed by AI screen audit.",
    crossScreenRisks: ["inventory mutation", "offline sync recovery"],
    piiFinancialSupplierRisk: "medium",
    emulatorTargetability: "not_targeted_yet",
    recommendedNextWave: "warehouse_copilot",
  },
  {
    screenId: "warehouse.issue",
    route: "/office/warehouse#issue",
    routeStatus: "registered",
    roleScope: WAREHOUSE_ROLES,
    primaryDomain: "warehouse",
    visibleButtons: ["Issue request", "Issue free", "Open issue details"],
    onPressHandlers: ["wh_issue_request_atomic_v1", "wh_issue_free_atomic_v5", "setIssueDetailsId"],
    existingTestIds: [],
    currentDataSources: ["warehouse issue queue", "warehouse issue RPC contracts", "issue local state"],
    evidenceSources: ["warehouse_status", "screen_state", "approval_policy"],
    readRoutes: ["GET /agent/warehouse/status", "GET /agent/warehouse/movements"],
    draftRoutes: ["POST /agent/warehouse/draft-action"],
    approvalRoutes: ["POST /agent/action/submit-for-approval"],
    safeLabel: "Explain warehouse issue queue",
    draftLabel: "Draft issue request rationale",
    approvalLabel: "Submit warehouse issue request",
    forbiddenLabel: "Issue stock directly",
    forbiddenReason: "Warehouse issue flows are mutating RPCs and cannot be executed by AI directly.",
    crossScreenRisks: ["stock issue mutation", "foreman request boundary"],
    piiFinancialSupplierRisk: "medium",
    emulatorTargetability: "not_targeted_yet",
    recommendedNextWave: "warehouse_copilot",
  },
  {
    screenId: "accountant.main",
    route: "/office/accountant",
    routeStatus: "registered",
    roleScope: FINANCE_ROLES,
    primaryDomain: "finance",
    visibleButtons: ["Open supplier card", "Open invoice", "Apply payment", "History"],
    onPressHandlers: ["openSupplierCard", "openInvoiceCard", "applyPayment", "openPaymentHistory"],
    existingTestIds: ["accountant-card-supplier", "accountant-card-invoice", "accountant-card-amount", "accountant-card-status"],
    currentDataSources: ["accountant invoice list", "payment queue", "finance summary"],
    evidenceSources: ["finance_summary", "document_metadata", "approval_policy"],
    readRoutes: ["GET /agent/finance/summary", "GET /agent/finance/debts"],
    draftRoutes: ["POST /agent/finance/draft-summary"],
    approvalRoutes: ["POST /agent/action/submit-for-approval"],
    safeLabel: "Explain accountant workload",
    draftLabel: "Draft finance document note",
    approvalLabel: "Submit finance document for approval",
    forbiddenLabel: "Create payment directly",
    forbiddenReason: "Payments require human-controlled approval and finance posting boundaries.",
    crossScreenRisks: ["payment execution", "supplier finance data"],
    piiFinancialSupplierRisk: "high",
    emulatorTargetability: "targetable",
    recommendedNextWave: "finance_copilot",
  },
  {
    screenId: "accountant.payment",
    route: "/office/accountant#payment",
    routeStatus: "registered",
    roleScope: FINANCE_ROLES,
    primaryDomain: "finance",
    visibleButtons: ["Select supplier", "Select invoice", "Apply payment"],
    onPressHandlers: ["selectPaymentSupplier", "selectPaymentInvoice", "applyPayment"],
    existingTestIds: ["payment-form-supplier", "payment-form-invoice"],
    currentDataSources: ["accountant.payment.apply flow", "payment idempotency key", "invoice update queue"],
    evidenceSources: ["finance_summary", "document_metadata", "approval_policy"],
    readRoutes: ["GET /agent/finance/summary", "GET /agent/finance/debts"],
    draftRoutes: ["POST /agent/finance/draft-summary"],
    approvalRoutes: ["POST /agent/action/submit-for-approval"],
    missingApprovalRoutes: ["POST /agent/finance/payment/submit-for-approval"],
    safeLabel: "Explain payment form status",
    draftLabel: "Draft payment approval rationale",
    approvalLabel: "Submit payment for approval",
    forbiddenLabel: "Apply payment directly",
    forbiddenReason: "Direct payment application is forbidden for AI and must remain a human/approval flow.",
    crossScreenRisks: ["finance posting", "idempotency conflicts"],
    piiFinancialSupplierRisk: "high",
    emulatorTargetability: "not_targeted_yet",
    recommendedNextWave: "finance_copilot",
  },
  {
    screenId: "accountant.history",
    route: "/office/accountant#history",
    routeStatus: "registered",
    roleScope: FINANCE_ROLES,
    primaryDomain: "finance",
    visibleButtons: ["Open payment history", "Open proposal row", "Export evidence"],
    onPressHandlers: ["openPaymentHistory", "openProposalRow", "exportAccountingEvidence"],
    existingTestIds: ["accountant-proposal-row-${proposalId}"],
    currentDataSources: ["accounting proposal history", "payment ledger", "document metadata"],
    evidenceSources: ["finance_summary", "document_metadata", "ledger_status"],
    readRoutes: ["GET /agent/finance/summary", "GET /agent/action/:actionId/status"],
    draftRoutes: ["POST /agent/finance/draft-summary"],
    approvalRoutes: ["POST /agent/action/submit-for-approval"],
    safeLabel: "Summarize accountant history",
    draftLabel: "Draft accounting history note",
    approvalLabel: "Submit accounting correction request",
    forbiddenLabel: "Rewrite payment history directly",
    forbiddenReason: "Accounting history is immutable evidence; AI cannot alter ledger history.",
    crossScreenRisks: ["audit trail tampering", "finance PII"],
    piiFinancialSupplierRisk: "high",
    emulatorTargetability: "not_targeted_yet",
    recommendedNextWave: "finance_copilot",
  },
  {
    screenId: "foreman.main",
    route: "/office/foreman",
    routeStatus: "registered",
    roleScope: FOREMAN_ROLES,
    primaryDomain: "projects",
    visibleButtons: ["Open AI", "Send draft", "Search catalog", "Add material"],
    onPressHandlers: ["openForemanAi", "sendForemanDraft", "searchCatalog", "addCatalogItem"],
    existingTestIds: ["foreman-ai-apply", "foreman-draft-send", "foreman-catalog-search-input"],
    currentDataSources: ["object context", "material request draft", "warehouse status"],
    evidenceSources: ["screen_state", "warehouse_status", "procurement_context"],
    readRoutes: ["GET /agent/field/context", "GET /agent/warehouse/status"],
    draftRoutes: ["POST /agent/field/draft-report", "POST /agent/field/draft-act"],
    approvalRoutes: ["POST /agent/action/submit-for-approval"],
    safeLabel: "Explain foreman object status",
    draftLabel: "Draft material request",
    approvalLabel: "Submit foreman request for approval",
    forbiddenLabel: "Approve own field request",
    forbiddenReason: "Foreman can draft and submit, but cannot self-approve or execute.",
    crossScreenRisks: ["self-approval", "warehouse request mutation"],
    piiFinancialSupplierRisk: "medium",
    emulatorTargetability: "targetable",
    recommendedNextWave: "foreman_closeout",
  },
  {
    screenId: "foreman.ai.quick_modal",
    route: "/office/foreman#ai-quick-modal",
    routeStatus: "registered",
    roleScope: FOREMAN_ROLES,
    primaryDomain: "procurement",
    visibleButtons: ["Apply AI", "Add material", "Send draft"],
    onPressHandlers: ["applyForemanAiSuggestion", "addCatalogItem", "sendForemanDraft"],
    existingTestIds: ["foreman-ai-apply", "foreman-catalog-add-${token}", "foreman-draft-send"],
    currentDataSources: ["foreman quick modal state", "catalog search results", "request draft"],
    evidenceSources: ["screen_state", "procurement_context", "approval_policy"],
    readRoutes: ["GET /agent/field/context", "GET /agent/procurement/request-context/:requestId"],
    draftRoutes: ["POST /agent/field/draft-report", "POST /agent/procurement/draft-request/preview"],
    approvalRoutes: ["POST /agent/action/submit-for-approval"],
    safeLabel: "Explain quick modal suggestion",
    draftLabel: "Draft quick material request",
    approvalLabel: "Submit quick request for approval",
    forbiddenLabel: "Execute quick modal request directly",
    forbiddenReason: "Quick modal AI cannot bypass approval ledger or write procurement records.",
    crossScreenRisks: ["catalog to procurement mutation", "approval bypass"],
    piiFinancialSupplierRisk: "medium",
    emulatorTargetability: "not_targeted_yet",
    recommendedNextWave: "foreman_closeout",
  },
  {
    screenId: "foreman.subcontract",
    route: "/office/foreman#subcontract",
    routeStatus: "registered",
    roleScope: FOREMAN_ROLES,
    primaryDomain: "subcontracts",
    visibleButtons: ["Open subcontract", "Draft act", "Submit progress"],
    onPressHandlers: ["openSubcontract", "draftSubcontractAct", "submitSubcontractProgress"],
    existingTestIds: [],
    currentDataSources: ["subcontract progress state", "document metadata", "field context"],
    evidenceSources: ["screen_state", "document_metadata", "approval_policy"],
    readRoutes: ["GET /agent/field/context"],
    draftRoutes: ["POST /agent/field/draft-act", "POST /agent/field/draft-report"],
    approvalRoutes: ["POST /agent/action/submit-for-approval"],
    safeLabel: "Explain subcontract progress",
    draftLabel: "Draft subcontract act",
    approvalLabel: "Submit subcontract progress",
    forbiddenLabel: "Sign subcontract directly",
    forbiddenReason: "Contract signing is a forbidden final action for AI.",
    crossScreenRisks: ["contract signing", "document evidence scope"],
    piiFinancialSupplierRisk: "medium",
    emulatorTargetability: "not_targeted_yet",
    recommendedNextWave: "foreman_closeout",
  },
  {
    screenId: "contractor.main",
    route: "/office/contractor",
    routeStatus: "registered",
    roleScope: CONTRACTOR_ROLES,
    primaryDomain: "subcontracts",
    visibleButtons: ["Open work", "Sync progress", "Submit progress"],
    onPressHandlers: ["openContractorWork", "syncContractorProgress", "submitContractorProgress"],
    existingTestIds: ["contractor-work-modal", "contractor-progress-sync-label", "contractor-progress-submit"],
    currentDataSources: ["contractor own work", "progress drafts", "document metadata"],
    evidenceSources: ["screen_state", "document_metadata", "approval_policy"],
    readRoutes: ["GET /agent/field/context"],
    draftRoutes: ["POST /agent/field/draft-report", "POST /agent/field/draft-act"],
    approvalRoutes: ["POST /agent/action/submit-for-approval"],
    safeLabel: "Explain contractor own-work status",
    draftLabel: "Draft contractor progress report",
    approvalLabel: "Submit contractor progress for approval",
    forbiddenLabel: "Read cross-role finance data",
    forbiddenReason: "Contractor scope is own-records only and cannot expose finance or other contractor rows.",
    crossScreenRisks: ["own-record boundary", "cross-role finance leakage"],
    piiFinancialSupplierRisk: "medium",
    emulatorTargetability: "targetable",
    recommendedNextWave: "foreman_closeout",
  },
  {
    screenId: "reports.modal",
    route: "/office/reports#modal",
    routeStatus: "registered",
    roleScope: OPS_ROLES,
    primaryDomain: "reports",
    visibleButtons: ["Open report", "Draft report", "Submit report"],
    onPressHandlers: ["openReportModal", "draftReport", "submitReport"],
    existingTestIds: [],
    currentDataSources: ["reports hub state", "report summary", "documents metadata"],
    evidenceSources: ["report_summary", "document_metadata", "approval_policy"],
    readRoutes: ["GET /agent/documents/knowledge"],
    draftRoutes: ["POST /agent/documents/summarize-preview"],
    approvalRoutes: ["POST /agent/action/submit-for-approval"],
    safeLabel: "Explain report modal status",
    draftLabel: "Draft report from visible evidence",
    approvalLabel: "Submit report for approval",
    forbiddenLabel: "Publish report directly",
    forbiddenReason: "Report publication requires explicit human approval.",
    crossScreenRisks: ["document access scope", "final publication"],
    piiFinancialSupplierRisk: "medium",
    emulatorTargetability: "not_targeted_yet",
    recommendedNextWave: "director_control_center",
  },
  {
    screenId: "documents.main",
    route: "/documents",
    routeStatus: "route_missing_or_not_registered",
    roleScope: OPS_ROLES,
    primaryDomain: "documents",
    visibleButtons: ["Search documents", "Summarize", "Draft document"],
    onPressHandlers: ["searchDocuments", "summarizeDocumentPreview", "draftDocument"],
    existingTestIds: [],
    currentDataSources: ["documents knowledge BFF", "document metadata"],
    evidenceSources: ["document_metadata", "screen_state", "approval_policy"],
    readRoutes: ["GET /agent/documents/knowledge"],
    draftRoutes: ["POST /agent/documents/search", "POST /agent/documents/summarize-preview"],
    approvalRoutes: ["POST /agent/action/submit-for-approval"],
    missingReadRoutes: ["GET /agent/documents/:documentId/context"],
    safeLabel: "Summarize document evidence",
    draftLabel: "Draft document note",
    approvalLabel: "Submit document change for approval",
    forbiddenLabel: "Send final document directly",
    forbiddenReason: "AI can draft and summarize documents but cannot send final documents directly.",
    crossScreenRisks: ["route missing", "document scope leakage"],
    piiFinancialSupplierRisk: "medium",
    emulatorTargetability: "route_missing",
    recommendedNextWave: "screen_runtime_bff_coverage",
  },
  {
    screenId: "chat.main",
    route: "/chat",
    routeStatus: "registered",
    roleScope: OPS_ROLES,
    primaryDomain: "chat",
    visibleButtons: ["Open assistant", "Send message", "Open product", "Open market"],
    onPressHandlers: ["openAssistant", "handleSend", "router.push(product)", "router.push(market)"],
    existingTestIds: ["chat-thread-list", "chat-composer-input", "chat-send-button"],
    currentDataSources: ["chat thread", "market listing references", "message composer"],
    evidenceSources: ["chat_thread", "screen_state", "document_metadata"],
    readRoutes: ["GET /agent/screen-assistant/:screenId/context"],
    draftRoutes: ["POST /agent/screen-assistant/:screenId/draft-preview"],
    approvalRoutes: ["POST /agent/action/submit-for-approval"],
    missingReadRoutes: ["GET /agent/chat/thread-context/:threadId"],
    safeLabel: "Explain chat context",
    draftLabel: "Draft chat reply",
    approvalLabel: "Submit chat evidence for approval",
    forbiddenLabel: "Send chat message directly",
    forbiddenReason: "AI may draft chat content, but sending is a user action.",
    crossScreenRisks: ["private message leakage", "market product cross-link"],
    piiFinancialSupplierRisk: "medium",
    emulatorTargetability: "targetable",
    recommendedNextWave: "screen_runtime_bff_coverage",
  },
  {
    screenId: "map.main",
    route: "/map",
    routeStatus: "registered",
    roleScope: MAP_ROLES,
    primaryDomain: "map",
    visibleButtons: ["Open supplier", "Open object", "Open route"],
    onPressHandlers: ["router.push('/supplierShowcase')", "openMapObject", "openExternalMap"],
    existingTestIds: [],
    currentDataSources: ["map controller state", "supplier showcase route", "object context"],
    evidenceSources: ["map_context", "screen_state", "role_policy"],
    readRoutes: ["GET /agent/screen-runtime/:screenId"],
    draftRoutes: ["POST /agent/field/draft-report"],
    approvalRoutes: ["POST /agent/action/submit-for-approval"],
    missingReadRoutes: ["GET /agent/map/object-context/:objectId"],
    safeLabel: "Explain map object context",
    draftLabel: "Draft site context note",
    approvalLabel: "Submit site context for approval",
    forbiddenLabel: "Create real estate record directly",
    forbiddenReason: "Map AI cannot create map or real-estate records without approval and evidence.",
    crossScreenRisks: ["location privacy", "supplier route cross-link"],
    piiFinancialSupplierRisk: "medium",
    emulatorTargetability: "targetable",
    recommendedNextWave: "screen_runtime_bff_coverage",
  },
  {
    screenId: "office.hub",
    route: "/office",
    routeStatus: "registered",
    roleScope: OFFICE_ROLES,
    primaryDomain: "control",
    visibleButtons: ["Open office role", "Back", "Open security"],
    onPressHandlers: ["router.push('/office/*')", "officeSafeBack", "router.push('/office/security')"],
    existingTestIds: ["office-safe-back"],
    currentDataSources: ["office route layout", "role navigation", "office directory"],
    evidenceSources: ["office_directory", "role_policy", "screen_state"],
    readRoutes: ["GET /agent/screen-runtime/:screenId"],
    draftRoutes: ["POST /agent/screen-assistant/:screenId/draft-preview"],
    approvalRoutes: ["POST /agent/action/submit-for-approval"],
    missingApprovalRoutes: ["POST /agent/office/access-change/submit-for-approval"],
    safeLabel: "Explain office role context",
    draftLabel: "Draft office collaboration note",
    approvalLabel: "Submit office access change",
    forbiddenLabel: "Change user role directly",
    forbiddenReason: "Role and permission changes are explicitly forbidden to AI direct actions.",
    crossScreenRisks: ["role permission mutation", "cross-role navigation"],
    piiFinancialSupplierRisk: "low",
    emulatorTargetability: "targetable",
    recommendedNextWave: "security_admin_review",
  },
  {
    screenId: "security.screen",
    route: "/office/security",
    routeStatus: "registered",
    roleScope: SECURITY_ROLES,
    primaryDomain: "security",
    visibleButtons: ["Enroll TOTP", "Verify TOTP", "Unenroll TOTP"],
    onPressHandlers: ["enrollTotp", "verifyTotp", "unenrollTotp"],
    existingTestIds: [],
    currentDataSources: ["TOTP enrollment state", "security screen local status", "auth session"],
    evidenceSources: ["screen_state", "role_policy", "approval_policy"],
    readRoutes: ["GET /agent/screen-runtime/:screenId"],
    draftRoutes: ["POST /agent/screen-assistant/:screenId/draft-preview"],
    approvalRoutes: ["POST /agent/action/submit-for-approval"],
    missingReadRoutes: ["GET /agent/security/context"],
    missingDraftRoutes: ["POST /agent/security/draft-review"],
    missingApprovalRoutes: ["POST /agent/security/submit-for-approval"],
    safeLabel: "Explain security screen status",
    draftLabel: "Draft security review note",
    approvalLabel: "Submit security change request",
    forbiddenLabel: "Enroll or unenroll factor directly",
    forbiddenReason: "Auth/security factor changes must remain explicit user actions and are forbidden to AI direct execution.",
    crossScreenRisks: ["auth factor mutation", "permission boundary"],
    piiFinancialSupplierRisk: "high",
    emulatorTargetability: "not_targeted_yet",
    recommendedNextWave: "security_admin_review",
  },
  {
    screenId: "screen.runtime",
    route: "BFF:/agent/screen-runtime/:screenId",
    routeStatus: "registered",
    roleScope: OPS_ROLES,
    primaryDomain: "screen_runtime",
    visibleButtons: ["Read context", "Intent preview", "Action plan"],
    onPressHandlers: ["getAgentScreenRuntime", "previewAgentScreenRuntimeIntent", "planAgentScreenRuntimeAction"],
    existingTestIds: ["ai.knowledge.preview"],
    currentDataSources: ["screen runtime registry", "screen runtime producers", "role policy"],
    evidenceSources: ["screen_state", "role_policy", "tool_contract"],
    readRoutes: ["GET /agent/screen-runtime/:screenId"],
    draftRoutes: ["POST /agent/screen-runtime/:screenId/intent-preview"],
    approvalRoutes: ["POST /agent/screen-runtime/:screenId/action-plan"],
    safeLabel: "Read screen runtime context",
    draftLabel: "Draft screen runtime action plan",
    approvalLabel: "Prepare approval-gated runtime action",
    forbiddenLabel: "Write screen state directly",
    forbiddenReason: "Screen runtime is read-only and plan-only; no UI or DB mutation is allowed.",
    crossScreenRisks: ["runtime producer boundary", "unknown screen fallback"],
    piiFinancialSupplierRisk: "medium",
    emulatorTargetability: "targetable",
    recommendedNextWave: "screen_runtime_bff_coverage",
  },
] as const;

function combine<T>(first: readonly T[], second?: readonly T[]): readonly T[] {
  return Object.freeze([...(first ?? []), ...(second ?? [])]);
}

function actionSeeds(screen: ScreenDefinition): readonly ActionSeed[] {
  return [
    {
      suffix: "safe_read",
      label: screen.safeLabel,
      actionKind: "safe_read",
      mutationRisk: "none",
      aiOpportunity: screen.safeOpportunity ?? "explain",
      existingBffRoutes: combine(COMMON_READ_BFF_ROUTES, screen.readRoutes),
      missingBffRoutes: screen.missingReadRoutes ?? [],
    },
    {
      suffix: "draft",
      label: screen.draftLabel,
      actionKind: "draft_only",
      mutationRisk: "draft",
      aiOpportunity: screen.draftOpportunity ?? "draft",
      existingBffRoutes: combine(COMMON_DRAFT_BFF_ROUTES, screen.draftRoutes),
      missingBffRoutes: screen.missingDraftRoutes ?? [],
    },
    {
      suffix: "approval",
      label: screen.approvalLabel,
      actionKind: "approval_required",
      mutationRisk: "approval_required",
      aiOpportunity: screen.approvalOpportunity ?? "submit_for_approval",
      existingBffRoutes: combine(COMMON_APPROVAL_BFF_ROUTES, screen.approvalRoutes),
      missingBffRoutes: screen.missingApprovalRoutes ?? [],
    },
    {
      suffix: "forbidden",
      label: screen.forbiddenLabel,
      actionKind: "forbidden",
      mutationRisk: "forbidden_direct_mutation",
      aiOpportunity: "none",
      existingBffRoutes: COMMON_READ_BFF_ROUTES,
      missingBffRoutes: [`NO_ROUTE_ALLOWED:${screen.screenId}:direct-final-mutation`],
      forbiddenReason: screen.forbiddenReason,
    },
  ] as const;
}

function buildAction(screen: ScreenDefinition, seed: ActionSeed): AiScreenButtonActionEntry {
  const entryWithoutCoverage = {
    screenId: screen.screenId,
    route: screen.route,
    routeStatus: screen.routeStatus,
    roleScope: screen.roleScope,
    primaryDomain: screen.primaryDomain,
    actionId: `${screen.screenId}.${seed.suffix}`,
    label: seed.label,
    actionKind: seed.actionKind,
    visibleButtons: screen.visibleButtons,
    onPressHandlers: screen.onPressHandlers,
    existingTestIds: screen.existingTestIds,
    currentDataSources: screen.currentDataSources,
    evidenceSources: screen.evidenceSources,
    existingBffRoutes: seed.existingBffRoutes,
    missingBffRoutes: seed.missingBffRoutes,
    bffCoverage: [],
    crossScreenRisks: screen.crossScreenRisks,
    mutationRisk: seed.mutationRisk,
    aiOpportunity: seed.aiOpportunity,
    forbiddenReason: seed.forbiddenReason,
    piiFinancialSupplierRisk: screen.piiFinancialSupplierRisk,
    emulatorTargetability: screen.emulatorTargetability,
    recommendedNextWave: screen.recommendedNextWave,
    source: "ai_all_screen_button_role_action_audit_v1",
  } satisfies AiScreenButtonActionEntry;

  return Object.freeze({
    ...entryWithoutCoverage,
    bffCoverage: classifyAiScreenBffCoverage(entryWithoutCoverage),
  });
}

export const AI_SCREEN_BUTTON_ROLE_ACTION_REGISTRY: readonly AiScreenButtonActionEntry[] = Object.freeze(
  SCREEN_DEFINITIONS.flatMap((screen) => actionSeeds(screen).map((seed) => buildAction(screen, seed))),
);

export function listAiScreenButtonRoleActionEntries(): AiScreenButtonActionEntry[] {
  return [...AI_SCREEN_BUTTON_ROLE_ACTION_REGISTRY];
}

export function listAiScreenButtonRoleActionScreenIds(): string[] {
  return [...new Set(AI_SCREEN_BUTTON_ROLE_ACTION_REGISTRY.map((entry) => entry.screenId))].sort();
}

export function listAiScreenButtonRoleActionEntriesForScreen(screenId: string): AiScreenButtonActionEntry[] {
  const normalized = String(screenId || "").trim();
  return AI_SCREEN_BUTTON_ROLE_ACTION_REGISTRY.filter((entry) => entry.screenId === normalized);
}

export function getAiScreenButtonRoleActionEntry(
  screenId: string,
  actionId: string,
): AiScreenButtonActionEntry | null {
  const normalizedScreenId = String(screenId || "").trim();
  const normalizedActionId = String(actionId || "").trim();
  return (
    AI_SCREEN_BUTTON_ROLE_ACTION_REGISTRY.find(
      (entry) => entry.screenId === normalizedScreenId && entry.actionId === normalizedActionId,
    ) ?? null
  );
}
