import type { MarketplaceIntakeActionQuestion, MarketplaceIntakeScreenId } from "./marketplaceIntakeTypes";

export const MARKETPLACE_INTAKE_ACTION_QUESTION_MAP: readonly MarketplaceIntakeActionQuestion[] = [
  {
    screenId: "market.home",
    actionId: "add_product_draft",
    labelRu: "+ Добавить товар",
    concreteQuestionRu: "Подготовь черновик карточки товара: категория, спецификация, единица, цена, наличие, регион, срок, документы, missing data и модерация.",
    allowedRoles: ["supplier"],
    requiredContext: ["offer_draft"],
    allowedSources: ["supplier_profile", "marketplace_draft", "price_list", "certificate", "specification"],
    answerMode: "draft",
  },
  {
    screenId: "market.home",
    actionId: "add_service_draft",
    labelRu: "+ Добавить услугу",
    concreteQuestionRu: "Подготовь черновик карточки услуги: тип работ, дисциплина, единица, цена, регион, доступность, документы, missing data и модерация.",
    allowedRoles: ["supplier", "contractor"],
    requiredContext: ["offer_draft"],
    allowedSources: ["contractor_profile", "marketplace_draft", "license", "portfolio", "specification"],
    answerMode: "draft",
  },
  {
    screenId: "market.home",
    actionId: "check_cards",
    labelRu: "Проверить карточки",
    concreteQuestionRu: "Проверь карточки marketplace: цена, единицы, наличие, документы, source trace, риски и готовность к модерации.",
    allowedRoles: ["supplier", "contractor", "buyer"],
    requiredContext: ["offer_draft"],
    allowedSources: ["marketplace_draft", "price_list", "certificate", "license", "specification"],
    answerMode: "read",
  },
  {
    screenId: "market.home",
    actionId: "show_request_matches",
    labelRu: "Показать подходящие к заявкам",
    concreteQuestionRu: "Покажи, какие approved карточки marketplace подходят к активным заявкам снабжения и почему.",
    allowedRoles: ["supplier", "contractor", "buyer"],
    requiredContext: ["buyer_request"],
    allowedSources: ["approved_marketplace_offer", "buyer_request", "specification"],
    answerMode: "read",
  },
  {
    screenId: "market.home",
    actionId: "send_to_moderation",
    labelRu: "Отправить на модерацию",
    concreteQuestionRu: "Подготовь безопасный маршрут модерации карточки без публикации, заказа или auto approval.",
    allowedRoles: ["supplier", "contractor"],
    requiredContext: ["offer_draft"],
    allowedSources: ["marketplace_draft", "price_list", "certificate", "license", "approval"],
    answerMode: "approval_route",
  },
  {
    screenId: "supplier.showcase",
    actionId: "add_product_draft",
    labelRu: "+ Добавить товар",
    concreteQuestionRu: "Подготовь черновик карточки товара поставщика с source trace, missing data и модерацией.",
    allowedRoles: ["supplier"],
    requiredContext: ["offer_draft"],
    allowedSources: ["supplier_profile", "marketplace_draft", "price_list", "certificate", "specification"],
    answerMode: "draft",
  },
  {
    screenId: "supplier.showcase",
    actionId: "add_service_draft",
    labelRu: "+ Добавить услугу",
    concreteQuestionRu: "Подготовь черновик карточки услуги поставщика/подрядчика с документами и модерацией.",
    allowedRoles: ["supplier", "contractor"],
    requiredContext: ["offer_draft"],
    allowedSources: ["contractor_profile", "marketplace_draft", "license", "portfolio"],
    answerMode: "draft",
  },
  {
    screenId: "supplier.showcase",
    actionId: "compare_with_request",
    labelRu: "Сравнить с заявкой",
    concreteQuestionRu: "Сравни карточку marketplace с активной заявкой: спецификация, цена, наличие, срок, риск и source trace.",
    allowedRoles: ["supplier", "buyer"],
    requiredContext: ["buyer_request"],
    allowedSources: ["approved_marketplace_offer", "buyer_request", "specification"],
    answerMode: "read",
  },
  {
    screenId: "supplier.showcase",
    actionId: "request_rfq_draft",
    labelRu: "Запросить КП",
    concreteQuestionRu: "Подготовь черновик запроса КП без финальной отправки и без заказа.",
    allowedRoles: ["buyer", "supplier"],
    requiredContext: ["approved_offer"],
    allowedSources: ["approved_marketplace_offer", "buyer_request", "document"],
    answerMode: "draft",
  },
  {
    screenId: "supplier.showcase",
    actionId: "add_to_shortlist_draft",
    labelRu: "Добавить в shortlist",
    concreteQuestionRu: "Подготовь черновик добавления approved карточки в shortlist без заказа и без auto approval.",
    allowedRoles: ["buyer"],
    requiredContext: ["approved_offer"],
    allowedSources: ["approved_marketplace_offer", "buyer_request", "approval"],
    answerMode: "draft",
  },
  {
    screenId: "supplier.showcase",
    actionId: "show_risks",
    labelRu: "Показать риски",
    concreteQuestionRu: "Покажи риски карточки marketplace: документы, срок, цена, наличие, соответствие заявке и модерация.",
    allowedRoles: ["supplier", "contractor", "buyer"],
    requiredContext: ["offer_draft"],
    allowedSources: ["marketplace_draft", "price_list", "certificate", "license", "buyer_request"],
    answerMode: "read",
  },
  {
    screenId: "contractor.main",
    actionId: "contractor_acceptance_blockers",
    labelRu: "Что мешает приёмке",
    concreteQuestionRu: "Покажи, что мешает приёмке работ подрядчика: фото, документы, замечания и безопасный следующий шаг.",
    allowedRoles: ["contractor"],
    requiredContext: ["contractor_work"],
    allowedSources: ["work", "document", "pdf_chunk"],
    answerMode: "read",
  },
  {
    screenId: "contractor.main",
    actionId: "contractor_response_draft",
    labelRu: "Подготовить ответ",
    concreteQuestionRu: "Подготовь черновик ответа прорабу по missing фото, документам и замечаниям без изменения статуса работы.",
    allowedRoles: ["contractor"],
    requiredContext: ["contractor_work"],
    allowedSources: ["work", "document", "contractor_profile"],
    answerMode: "draft",
  },
  {
    screenId: "contractor.main",
    actionId: "add_service_draft",
    labelRu: "+ Добавить услугу",
    concreteQuestionRu: "Если роль разрешает marketplace, подготовь черновик услуги подрядчика с документами и модерацией.",
    allowedRoles: ["contractor"],
    requiredContext: ["offer_draft"],
    allowedSources: ["contractor_profile", "marketplace_draft", "license", "portfolio"],
    answerMode: "draft",
  },
  {
    screenId: "contractor.main",
    actionId: "add_product_draft",
    labelRu: "+ Добавить товар",
    concreteQuestionRu: "Если роль разрешает supplier catalog, подготовь черновик товара подрядчика с документами и модерацией.",
    allowedRoles: ["contractor"],
    requiredContext: ["offer_draft"],
    allowedSources: ["contractor_profile", "marketplace_draft", "price_list", "certificate"],
    answerMode: "draft",
  },
  {
    screenId: "buyer.request.detail",
    actionId: "marketplace_source_check",
    labelRu: "Проверить marketplace source",
    concreteQuestionRu: "Проверь, какие approved marketplace карточки стали source для buyer sourcing по заявке.",
    allowedRoles: ["buyer"],
    requiredContext: ["approved_offer"],
    allowedSources: ["approved_marketplace_offer", "buyer_request", "approval"],
    answerMode: "read",
  },
] as const;

export function getMarketplaceActionQuestion(
  actionId: string,
  screenId: MarketplaceIntakeScreenId,
): MarketplaceIntakeActionQuestion | undefined {
  return MARKETPLACE_INTAKE_ACTION_QUESTION_MAP.find(
    (action) => action.actionId === actionId && action.screenId === screenId,
  ) ?? MARKETPLACE_INTAKE_ACTION_QUESTION_MAP.find((action) => action.actionId === actionId);
}
