begin;

create table if not exists public.scale_idempotency_records (
  key text not null,
  operation text not null,
  status text not null,
  attempts integer not null default 1,
  created_at_ms bigint not null,
  updated_at_ms bigint not null,
  expires_at_ms bigint not null,
  raw_payload_stored boolean not null default false,
  pii_stored boolean not null default false,
  result_status text not null default 'missing',
  primary key (key, operation),
  constraint scale_idempotency_records_status_check check (
    status in ('reserved', 'committed', 'failed_retryable', 'failed_final', 'expired')
  ),
  constraint scale_idempotency_records_attempts_check check (attempts >= 1),
  constraint scale_idempotency_records_payload_privacy_check check (
    raw_payload_stored = false and pii_stored = false
  ),
  constraint scale_idempotency_records_result_status_check check (
    result_status in ('missing', 'present_redacted')
  ),
  constraint scale_idempotency_records_time_order_check check (
    updated_at_ms >= created_at_ms and expires_at_ms >= created_at_ms
  )
);

create index if not exists scale_idempotency_records_expiry_idx
  on public.scale_idempotency_records(status, expires_at_ms);

create index if not exists scale_idempotency_records_operation_idx
  on public.scale_idempotency_records(operation);

alter table public.scale_idempotency_records enable row level security;
revoke all on table public.scale_idempotency_records from anon, authenticated;

comment on table public.scale_idempotency_records is
  'Synthetic staging idempotency provider ledger for scale smoke validation. Stores only opaque keys and redacted outcomes; no raw payload or PII.';

comment on column public.scale_idempotency_records.key is
  'Opaque bounded idempotency key generated by the server-side scale idempotency boundary.';

comment on column public.scale_idempotency_records.result_status is
  'Redacted result marker only. Raw response payloads are not stored in this provider ledger.';

commit;
