export const AGENT_DOCUMENT_KNOWLEDGE_BFF_CONTRACT = Object.freeze({
  contractId: "agent_document_knowledge_bff_v1",
  documentType: "agent_document_knowledge",
  endpoints: [
    "GET /agent/documents/knowledge",
    "POST /agent/documents/search",
    "POST /agent/documents/summarize-preview",
  ],
  backendFirst: true,
  roleScoped: true,
  evidenceBacked: true,
  readOnly: true,
  mutationCount: 0,
  dbWrites: 0,
  directDatabaseAccess: 0,
  directSupabaseFromUi: false,
  externalLiveFetchEnabled: false,
  mobileExternalFetch: false,
  modelProviderImports: 0,
  rawContentReturned: false,
  rawRowsReturned: false,
  secretsReturned: false,
  executionEnabled: false,
  finalExecution: 0,
  fakeDocuments: false,
  hardcodedAiAnswer: false,
} as const);
