export const AGENT_FIELD_WORK_COPILOT_BFF_CONTRACT = Object.freeze({
  contractId: "agent_field_work_copilot_bff_v1",
  documentType: "agent_field_work_copilot",
  endpoints: [
    "GET /agent/field/context",
    "POST /agent/field/draft-report",
    "POST /agent/field/draft-act",
    "POST /agent/field/action-plan",
  ],
  backendFirst: true,
  roleScoped: true,
  contractorOwnScopeEnforced: true,
  evidenceBacked: true,
  readOnly: true,
  draftOnly: true,
  mutationCount: 0,
  dbWrites: 0,
  directDatabaseAccess: 0,
  directSupabaseFromUi: false,
  mobileExternalFetch: false,
  externalLiveFetchEnabled: false,
  modelProviderImports: 0,
  rawRowsReturned: false,
  rawPromptReturned: false,
  rawProviderPayloadReturned: false,
  executionEnabled: false,
  finalExecution: 0,
  reportPublished: false,
  actSigned: false,
  contractorConfirmation: false,
  paymentMutation: false,
  warehouseMutation: false,
  fakeFieldCards: false,
  hardcodedAiAnswer: false,
} as const);
