export const AGENT_FINANCE_COPILOT_BFF_CONTRACT = Object.freeze({
  contractId: "agent_finance_copilot_bff_v1",
  documentType: "agent_finance_copilot",
  endpoints: [
    "GET /agent/finance/summary",
    "GET /agent/finance/debts",
    "POST /agent/finance/risk-preview",
    "POST /agent/finance/draft-summary",
  ],
  backendFirst: true,
  roleScoped: true,
  evidenceBacked: true,
  readOnly: true,
  mutationCount: 0,
  dbWrites: 0,
  directDatabaseAccess: 0,
  directSupabaseFromUi: false,
  mobileExternalFetch: false,
  externalLiveFetchEnabled: false,
  modelProviderImports: 0,
  rawRowsReturned: false,
  rawPromptReturned: false,
  rawProviderPayloadReturned: false,
  executionEnabled: false,
  finalExecution: 0,
  paymentCreated: false,
  postingCreated: false,
  invoiceMutated: false,
  fakeFinanceCards: false,
  hardcodedAiAnswer: false,
} as const);
