export const AGENT_WORKDAY_LIVE_EVIDENCE_BFF_CONTRACT = Object.freeze({
  contractId: "agent_workday_live_evidence_bff_v1",
  documentType: "agent_workday_live_evidence_tasks",
  endpoint: "GET /agent/workday/live-evidence-tasks",
  backendFirst: true,
  roleScoped: true,
  evidenceBacked: true,
  safeReadOnly: true,
  mutationCount: 0,
  dbWrites: 0,
  directDatabaseAccess: 0,
  directSupabaseFromUi: false,
  externalLiveFetchEnabled: false,
  uncontrolledExternalFetch: false,
  mobileExternalFetch: false,
  modelProviderImports: 0,
  executionEnabled: false,
  finalExecution: 0,
  fakeCards: false,
  hardcodedAiAnswer: false,
} as const);
