export const AGENT_WORKDAY_TASK_BFF_CONTRACT = Object.freeze({
  contractId: "agent_workday_task_bff_v1",
  documentType: "agent_workday_tasks",
  endpoints: [
    "GET /agent/workday/tasks",
    "POST /agent/workday/tasks/:taskId/preview",
    "POST /agent/workday/tasks/:taskId/action-plan",
  ],
  backendFirst: true,
  roleScoped: true,
  evidenceBacked: true,
  readOnly: true,
  mutationCount: 0,
  dbWrites: 0,
  directDatabaseAccess: 0,
  directSupabaseFromUi: false,
  externalLiveFetchEnabled: false,
  mobileExternalFetch: false,
  modelProviderImports: 0,
  executionEnabled: false,
  finalExecution: 0,
  fakeCards: false,
  hardcodedAiAnswer: false,
} as const);
