export const AGENT_WAREHOUSE_COPILOT_BFF_CONTRACT = Object.freeze({
  contractId: "agent_warehouse_copilot_bff_v1",
  documentType: "agent_warehouse_copilot",
  endpoints: [
    "GET /agent/warehouse/status",
    "GET /agent/warehouse/movements",
    "POST /agent/warehouse/risk-preview",
    "POST /agent/warehouse/draft-action",
  ],
  backendFirst: true,
  roleScoped: true,
  evidenceBacked: true,
  readOnly: true,
  mutationCount: 0,
  dbWrites: 0,
  directDatabaseAccess: 0,
  directSupabaseFromUi: false,
  mobileExternalFetch: false,
  externalLiveFetchEnabled: false,
  modelProviderImports: 0,
  rawRowsReturned: false,
  rawPromptReturned: false,
  rawProviderPayloadReturned: false,
  executionEnabled: false,
  finalExecution: 0,
  stockMutated: false,
  reservationCreated: false,
  movementCreated: false,
  fakeWarehouseCards: false,
  hardcodedAiAnswer: false,
} as const);
