import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  scroll: {
    flex: 1,
  },
  content: {
    padding: 16,
    paddingBottom: 36,
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingTop: 4,
  },
  headerIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: "#ECFDF5",
    alignItems: "center",
    justifyContent: "center",
  },
  headerText: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    color: "#0F172A",
    fontSize: 26,
    fontWeight: "900",
    lineHeight: 31,
  },
  subtitle: {
    color: "#475569",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 6,
  },
  stateBox: {
    marginTop: 18,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    padding: 14,
    gap: 6,
  },
  stateTitle: {
    color: "#0F172A",
    fontSize: 15,
    fontWeight: "900",
  },
  stateText: {
    color: "#475569",
    fontSize: 13,
    lineHeight: 18,
  },
  runtimeStatus: {
    marginTop: 14,
    borderRadius: 8,
    backgroundColor: "#E0F2FE",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  runtimeStatusText: {
    color: "#075985",
    fontSize: 12,
    fontWeight: "800",
  },
  runtimeMatrixSurface: {
    marginTop: 14,
    borderRadius: 8,
    backgroundColor: "#F1F5F9",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  runtimeMatrixText: {
    color: "#334155",
    fontSize: 12,
    fontWeight: "800",
  },
  screenActionSurface: {
    marginTop: 10,
    borderRadius: 8,
    backgroundColor: "#F7FEE7",
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 3,
  },
  screenActionText: {
    color: "#365314",
    fontSize: 12,
    fontWeight: "800",
  },
  constructionSurface: {
    marginTop: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 10,
    paddingVertical: 9,
    gap: 4,
  },
  constructionTitle: {
    color: "#0F172A",
    fontSize: 13,
    fontWeight: "900",
  },
  constructionMeta: {
    color: "#334155",
    fontSize: 11,
    fontWeight: "800",
  },
  workdaySurface: {
    marginTop: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#BFDBFE",
    backgroundColor: "#EFF6FF",
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 6,
  },
  workdayTitle: {
    color: "#1E3A8A",
    fontSize: 13,
    fontWeight: "900",
  },
  workdayMeta: {
    color: "#1D4ED8",
    fontSize: 11,
    fontWeight: "800",
  },
  workdayCard: {
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
    padding: 9,
    gap: 4,
  },
  workdayCardTitle: {
    color: "#0F172A",
    fontSize: 13,
    fontWeight: "900",
  },
  workdayCardSummary: {
    color: "#334155",
    fontSize: 12,
    lineHeight: 16,
  },
  workdayChip: {
    color: "#1E40AF",
    fontSize: 11,
    fontWeight: "800",
  },
  workdayEmpty: {
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
    padding: 9,
  },
  workdayEmptyText: {
    color: "#475569",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
  },
  runtimeInlineMarker: {
    width: 1,
    height: 1,
  },
  loadedBadge: {
    marginTop: 10,
    borderRadius: 8,
    backgroundColor: "#DCFCE7",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  loadedBadgeText: {
    color: "#166534",
    fontSize: 12,
    fontWeight: "800",
  },
  panel: {
    marginTop: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#99F6E4",
    backgroundColor: "#F0FDFA",
    padding: 12,
  },
  panelHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  panelTitle: {
    color: "#134E4A",
    fontSize: 14,
    fontWeight: "900",
    flex: 1,
  },
  panelClose: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  panelBody: {
    color: "#0F172A",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 8,
  },
  panelMeta: {
    color: "#0F766E",
    fontSize: 11,
    fontWeight: "800",
    marginTop: 8,
  },
});
