import type { BuiltInAi50000MacroDomain } from "./builtInAi50000CaseTypes";

export const BUILT_IN_AI_50000_PHASE1_MACRO_DOMAINS: readonly BuiltInAi50000MacroDomain[] = Object.freeze([
  {
    id: "01_site_preparation_earthworks",
    ordinal: 1,
    title: "site preparation and earthworks",
    category: "roadworks",
    workFamily: "earthworks_site_base",
    defaultWorkKey: "asphalt_paving",
    promptAnchor: "site preparation grading road base compaction asphalt paving",
    expectedRowsContain: ["base", "compaction", "equipment"],
    dangerousWork: true,
    productFamily: "geotextile and road base materials",
  },
  {
    id: "02_foundations_concrete_rebar",
    ordinal: 2,
    title: "foundations concrete and rebar",
    category: "foundation",
    workFamily: "concrete_rebar_foundations",
    defaultWorkKey: "foundation_concrete",
    promptAnchor: "concrete slab foundation formwork rebar pouring curing",
    expectedRowsContain: ["concrete", "rebar", "formwork"],
    dangerousWork: true,
    productFamily: "concrete and rebar",
  },
  {
    id: "03_masonry_blocks_stone",
    ordinal: 3,
    title: "masonry blocks and stone",
    category: "masonry",
    workFamily: "masonry_blocks_stone",
    defaultWorkKey: "brick_masonry",
    promptAnchor: "brick masonry block stone mortar laying jointing",
    expectedRowsContain: ["brick", "mortar", "laying"],
    dangerousWork: false,
    productFamily: "brick and masonry mixes",
  },
  {
    id: "04_roofing",
    ordinal: 4,
    title: "roofing",
    category: "roofing",
    workFamily: "roofing_repairs_and_installation",
    defaultWorkKey: "roof_repair",
    promptAnchor: "roof repair pitched roof membrane covering installation",
    expectedRowsContain: ["roof covering", "membrane", "installation"],
    dangerousWork: true,
    productFamily: "roofing materials",
  },
  {
    id: "05_facade_exterior",
    ordinal: 5,
    title: "facade and exterior",
    category: "facade",
    workFamily: "facade_exterior_systems",
    defaultWorkKey: "facade_insulation",
    promptAnchor: "facade insulation exterior cladding primer installation",
    expectedRowsContain: ["facade", "insulation", "installation"],
    dangerousWork: true,
    productFamily: "facade insulation",
  },
  {
    id: "06_windows_doors_glazing",
    ordinal: 6,
    title: "windows doors and glazing",
    category: "doors_windows",
    workFamily: "openings_glazing",
    defaultWorkKey: "window_installation",
    promptAnchor: "window door glazing installation sealing hardware",
    expectedRowsContain: ["unit block", "hardware", "installation"],
    dangerousWork: false,
    productFamily: "windows doors and hardware",
  },
  {
    id: "07_interior_floors_tile_walls_ceilings",
    ordinal: 7,
    title: "interior floors tile walls and ceilings",
    category: "flooring",
    workFamily: "interior_finish_surfaces",
    defaultWorkKey: "laminate_laying",
    promptAnchor: "laminate flooring installation",
    expectedRowsContain: ["covering material", "base preparation", "installation"],
    dangerousWork: false,
    productFamily: "interior finish materials",
  },
  {
    id: "08_drywall_partitions_fitout",
    ordinal: 8,
    title: "drywall partitions and fitout",
    category: "drywall",
    workFamily: "drywall_partitions_fitout",
    defaultWorkKey: "drywall_wall_cladding",
    promptAnchor: "drywall gkl partition profile frame gypsum board",
    expectedRowsContain: ["profile frame", "gypsum board", "joint finishing"],
    dangerousWork: false,
    productFamily: "drywall profiles and boards",
  },
  {
    id: "09_plumbing_water_sewer",
    ordinal: 9,
    title: "plumbing water and sewer",
    category: "plumbing",
    workFamily: "plumbing_water_sewer",
    defaultWorkKey: "pipe_replacement",
    promptAnchor: "plumbing pipe replacement water sewer pressure test",
    expectedRowsContain: ["pipes", "fittings", "pressure test"],
    dangerousWork: true,
    productFamily: "pipes and fittings",
  },
  {
    id: "10_electrical_low_voltage",
    ordinal: 10,
    title: "electrical and low voltage",
    category: "electrical",
    workFamily: "electrical_low_voltage",
    defaultWorkKey: "electrical_wiring",
    promptAnchor: "electrical wiring low voltage cable protection testing",
    expectedRowsContain: ["cable", "protection", "testing"],
    dangerousWork: true,
    productFamily: "electrical cable and protection",
  },
  {
    id: "11_hvac_heating_ventilation",
    ordinal: 11,
    title: "hvac heating and ventilation",
    category: "heating_hvac",
    workFamily: "hvac_heating_ventilation",
    defaultWorkKey: "boiler_room_piping",
    promptAnchor: "hvac heating boiler ventilation ducts commissioning",
    expectedRowsContain: ["equipment", "installation", "commissioning"],
    dangerousWork: true,
    productFamily: "hvac equipment",
  },
  {
    id: "12_waterproofing_insulation_fireproofing",
    ordinal: 12,
    title: "waterproofing insulation and fireproofing",
    category: "waterproofing",
    workFamily: "waterproofing_insulation_fireproofing",
    defaultWorkKey: "bathroom_waterproofing",
    promptAnchor: "waterproofing insulation fireproofing primer membrane mastic",
    expectedRowsContain: ["primer", "membrane", "application"],
    dangerousWork: false,
    productFamily: "waterproofing membranes",
  },
  {
    id: "13_demolition_waste_cleaning",
    ordinal: 13,
    title: "demolition waste and cleaning",
    category: "cleaning",
    workFamily: "demolition_waste_cleaning",
    defaultWorkKey: "construction_cleaning",
    promptAnchor: "demolition waste cleaning loading disposal protection",
    expectedRowsContain: ["protection", "demolition", "disposal"],
    dangerousWork: true,
    productFamily: "demolition consumables",
  },
  {
    id: "14_roadworks_landscape_drainage",
    ordinal: 14,
    title: "roadworks landscape and drainage",
    category: "roadworks",
    workFamily: "roadworks_landscape_drainage",
    defaultWorkKey: "asphalt_paving",
    promptAnchor: "asphalt roadworks landscape drainage compaction paving",
    expectedRowsContain: ["base", "asphalt", "compaction"],
    dangerousWork: true,
    productFamily: "asphalt and drainage materials",
  },
  {
    id: "15_metalworks_steel_welding",
    ordinal: 15,
    title: "metalworks steel and welding",
    category: "metalworks",
    workFamily: "metalworks_steel_welding",
    defaultWorkKey: "welded_frame",
    promptAnchor: "metal steel welding fabrication coating installation",
    expectedRowsContain: ["steel", "fabrication", "coating"],
    dangerousWork: true,
    productFamily: "steel profiles and welding consumables",
  },
  {
    id: "16_carpentry_furniture_furnishing",
    ordinal: 16,
    title: "carpentry furniture and furnishing",
    category: "carpentry",
    workFamily: "carpentry_furniture_furnishing",
    defaultWorkKey: "furniture_assembly",
    promptAnchor: "carpentry furniture cabinet furnishing timber installation",
    expectedRowsContain: ["timber", "fasteners", "installation"],
    dangerousWork: false,
    productFamily: "furniture and carpentry materials",
  },
  {
    id: "17_solar_storage_microgrids",
    ordinal: 17,
    title: "solar storage and microgrids",
    category: "electrical",
    workFamily: "solar_storage_microgrids",
    defaultWorkKey: "solar_panel_installation",
    promptAnchor: "solar panel battery storage inverter microgrid electrical installation",
    expectedRowsContain: ["cable", "equipment", "commissioning"],
    dangerousWork: true,
    productFamily: "solar and battery equipment",
  },
  {
    id: "18_thermal_energy_boiler_chp",
    ordinal: 18,
    title: "thermal energy boiler and chp",
    category: "heating_hvac",
    workFamily: "thermal_energy_boiler_chp",
    defaultWorkKey: "boiler_room_piping",
    promptAnchor: "boiler room thermal energy heating pipe commissioning",
    expectedRowsContain: ["equipment", "pipes", "commissioning"],
    dangerousWork: true,
    productFamily: "boiler room piping",
  },
  {
    id: "19_hydro_power_water_infrastructure",
    ordinal: 19,
    title: "hydro power and water infrastructure",
    category: "concrete",
    workFamily: "hydro_power_water_infrastructure",
    defaultWorkKey: "micro_hydro_preparation",
    promptAnchor: "micro hydro water intake concrete channel infrastructure",
    expectedRowsContain: ["concrete", "rebar", "installation"],
    dangerousWork: true,
    productFamily: "hydro civil materials",
  },
  {
    id: "20_power_grid_substations_lines",
    ordinal: 20,
    title: "power grid substations and lines",
    category: "electrical",
    workFamily: "power_grid_substations_lines",
    defaultWorkKey: "electrical_wiring",
    promptAnchor: "substation grounding power line electrical cable protection testing",
    expectedRowsContain: ["cable", "protection", "testing"],
    dangerousWork: true,
    productFamily: "substation grounding materials",
  },
  {
    id: "21_telecom_security_smart_home",
    ordinal: 21,
    title: "telecom security and smart home",
    category: "electrical",
    workFamily: "telecom_security_smart_home",
    defaultWorkKey: "smart_home_basic",
    promptAnchor: "electrical smart home telecom security low voltage automation installation",
    expectedRowsContain: ["cable", "devices", "testing"],
    dangerousWork: true,
    productFamily: "smart home devices",
  },
  {
    id: "22_agriculture_greenhouses_gardens",
    ordinal: 22,
    title: "agriculture greenhouses and gardens",
    category: "metalworks",
    workFamily: "agriculture_greenhouses_gardens",
    defaultWorkKey: "greenhouse_installation",
    promptAnchor: "greenhouse installation farm garden irrigation metal frame",
    expectedRowsContain: ["steel", "installation", "cleanup"],
    dangerousWork: false,
    productFamily: "greenhouse frames",
  },
  {
    id: "23_commercial_industrial_fitout",
    ordinal: 23,
    title: "commercial and industrial fitout",
    category: "metalworks",
    workFamily: "commercial_industrial_fitout",
    defaultWorkKey: "warehouse_steel_frame",
    promptAnchor: "commercial industrial fitout warehouse steel frame installation",
    expectedRowsContain: ["steel", "fabrication", "installation"],
    dangerousWork: true,
    productFamily: "industrial fitout materials",
  },
  {
    id: "24_documentation_design_inspection",
    ordinal: 24,
    title: "documentation design and inspection",
    category: "documents_design",
    workFamily: "documentation_design_inspection",
    defaultWorkKey: "design_project",
    promptAnchor: "design project documentation inspection estimate package drawings",
    expectedRowsContain: ["survey", "drawings", "delivery"],
    dangerousWork: false,
    productFamily: "documentation services",
  },
  {
    id: "25_procurement_logistics_maintenance_emergency",
    ordinal: 25,
    title: "procurement logistics maintenance and emergency",
    category: "delivery_equipment",
    workFamily: "procurement_logistics_maintenance_emergency",
    defaultWorkKey: "delivery_lifting",
    promptAnchor: "procurement logistics emergency maintenance delivery lifting supplier",
    expectedRowsContain: ["source", "quantity", "price status"],
    dangerousWork: false,
    productFamily: "logistics and maintenance services",
  },
]);

if (BUILT_IN_AI_50000_PHASE1_MACRO_DOMAINS.length !== 25) {
  throw new Error(`BUILT_IN_AI_50000_PHASE1_MACRO_DOMAIN_COUNT_INVALID:${BUILT_IN_AI_50000_PHASE1_MACRO_DOMAINS.length}`);
}
